import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import { query } from "./database";
const ttlDays=30;
function hashToken(token:string){return createHash("sha256").update(token).digest("hex");}
export function hashPassword(password:string,salt?:string){const s=salt??randomBytes(16).toString("hex");return `${s}:${scryptSync(password,s,64).toString("hex")}`;}
function verifyPassword(password:string,encoded:string){const [salt,hex]=encoded.split(":");if(!salt||!hex)return false;const expected=scryptSync(password,salt,64);const actual=Buffer.from(hex,"hex");return actual.length===expected.length&&timingSafeEqual(expected,actual);}
export async function createAccount(email:string,displayName:string,password:string){const learnerId=randomUUID(),userId=randomUUID();const passwordHash=hashPassword(password);await query("BEGIN");try{await query("INSERT INTO learners(id) VALUES($1)",[learnerId]);await query("INSERT INTO learner_profiles(learner_id,display_name) VALUES($1,$2)",[learnerId,displayName]);await query("INSERT INTO user_accounts(id,learner_id,email,display_name,password_hash) VALUES($1,$2,$3,$4,$5)",[userId,learnerId,email,displayName,passwordHash]);await query("COMMIT");return {id:userId,learnerId,email,displayName};}catch(e){await query("ROLLBACK");throw e;}}
export async function authenticate(email:string,password:string){const r=await query<{id:string;learner_id:string;email:string;display_name:string;password_hash:string}>("SELECT * FROM user_accounts WHERE email=$1",[email]);const u=r.rows[0];if(!u||!verifyPassword(password,u.password_hash))return null;return {id:u.id,learnerId:u.learner_id,email:u.email,displayName:u.display_name};}
export async function createSession(userId:string){const token=randomBytes(48).toString("base64url"),expires=new Date(Date.now()+ttlDays*86400000);await query("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,$4)",[randomUUID(),userId,hashToken(token),expires]);return {token,expiresAt:expires.toISOString()};}
export async function getSession(token:string){const r=await query<{user_id:string;email:string;display_name:string;learner_id:string;expires_at:string}>("SELECT s.user_id,u.email,u.display_name,u.learner_id,s.expires_at FROM sessions s JOIN user_accounts u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW()",[hashToken(token)]);if(!r.rows[0])return null;await query("UPDATE sessions SET last_seen_at=NOW() WHERE token_hash=$1",[hashToken(token)]);return {userId:r.rows[0].user_id,learnerId:r.rows[0].learner_id,email:r.rows[0].email,displayName:r.rows[0].display_name,expiresAt:r.rows[0].expires_at};}
export async function deleteSession(token:string){await query("DELETE FROM sessions WHERE token_hash=$1",[hashToken(token)]);}
