import type { CEFRLevel } from "./learner";
import type { EarActivity, ReadingActivity, SayItBetterExercise } from "./learning-systems";
import { rotate } from "./variety";
import { READING_ACTIVITIES_EXTRA } from "./reading-expansion";
import { EAR_ACTIVITIES_EXTRA } from "./ear-expansion";

const BASE_READING_ACTIVITIES: ReadingActivity[] = [
  // Pre-A1
  { id:"read-prea1-signs", level:"Pre-A1", title:"Read the Sign", passage:"EXIT. OPEN. CLOSED. BUS STOP.", wordRecognitionTargets:["EXIT","OPEN","CLOSED","BUS STOP"], comprehensionQuestions:[{id:"q1",question:"Which phrase tells you where the bus stops?",answer:"BUS STOP",skill:"detail"}], contentId:"original-read-prea1-signs" },
  { id:"read-prea1-airport", level:"Pre-A1", title:"At the Airport", passage:"GATE 5. PASSPORT CONTROL. ARRIVALS. DEPARTURES. BAGGAGE.", wordRecognitionTargets:["GATE","PASSPORT","ARRIVALS","DEPARTURES"], comprehensionQuestions:[{id:"q1",question:"Which word tells you where people leave from?",answer:"DEPARTURES",skill:"detail"},{id:"q2",question:"You need this document to travel. Which one?",answer:"PASSPORT",skill:"detail"}], contentId:"original-read-prea1-airport" },
  { id:"read-prea1-menu", level:"Pre-A1", title:"The Café Menu", passage:"COFFEE ..... 3. TEA ..... 2. WATER ..... 1. CAKE ..... 4.", wordRecognitionTargets:["COFFEE","TEA","WATER","CAKE"], comprehensionQuestions:[{id:"q1",question:"What costs the most?",answer:"CAKE",skill:"inference"},{id:"q2",question:"What can you drink for 1?",answer:"WATER",skill:"detail"}], contentId:"original-read-prea1-menu" },
  // A1
  { id:"read-a1-routine", level:"A1", title:"A Morning Routine", passage:"Omar wakes up at seven. He drinks coffee and walks to work. He starts work at eight.", wordRecognitionTargets:["wakes","drinks","walks"], comprehensionQuestions:[{id:"q1",question:"What time does Omar start work?",answer:"eight",skill:"detail"}], transferPrompt:"Write three sentences about your morning.", contentId:"original-read-a1-routine" },
  { id:"read-a1-weather", level:"A1", title:"Today's Weather", passage:"It is cold today. The sky is grey. Rain will come in the afternoon. Take an umbrella with you.", wordRecognitionTargets:["cold","grey","rain","umbrella"], comprehensionQuestions:[{id:"q1",question:"What will happen in the afternoon?",answer:"rain",skill:"detail"},{id:"q2",question:"What should you take?",answer:"an umbrella",skill:"detail"}], transferPrompt:"Write two sentences about today's weather where you live.", contentId:"original-read-a1-weather" },
  { id:"read-a1-messages", level:"A1", title:"Two Friends Text", passage:"Sara: Are you free tomorrow? Adam: Sorry, I am busy. Sara: OK. What about Friday? Adam: Yes! Friday is good.", wordRecognitionTargets:["free","busy","Friday"], comprehensionQuestions:[{id:"q1",question:"Why can't Adam meet tomorrow?",answer:"he is busy",skill:"detail"},{id:"q2",question:"When do they agree to meet?",answer:"Friday",skill:"inference"}], transferPrompt:"Write a short message inviting a friend to coffee.", contentId:"original-read-a1-messages" },
  // A2
  { id:"read-a2-travel", level:"A2", title:"A Travel Change", passage:"The train was delayed because of heavy rain. Passengers were asked to wait on platform three.", wordRecognitionTargets:["delayed","passengers","platform"], comprehensionQuestions:[{id:"q1",question:"Why was the train delayed?",answer:"heavy rain",skill:"main_idea"},{id:"q2",question:"Where should passengers wait?",answer:"platform three",skill:"detail"}], transferPrompt:"Explain what you would do if your train were delayed.", contentId:"original-read-a2-travel" },
  { id:"read-a2-job", level:"A2", title:"A Job Advertisement", passage:"Café Star needs a waiter. Experience is helpful but not necessary. You must be friendly and work weekends. Pay: 12 per hour. Free meals included.", wordRecognitionTargets:["experience","necessary","weekends"], comprehensionQuestions:[{id:"q1",question:"Do you need experience to apply?",answer:"no",skill:"detail"},{id:"q2",question:"When must you work?",answer:"weekends",skill:"detail"},{id:"q3",question:"What extra benefit do workers get?",answer:"free meals",skill:"detail"}], transferPrompt:"Write two sentences explaining why this job suits you — or why it does not.", contentId:"original-read-a2-job" },
  { id:"read-a2-hotel", level:"A2", title:"A Hotel Review", passage:"The room was clean and the staff were kind. However, the wifi did not work and breakfast finished very early. Good value for a short stay.", wordRecognitionTargets:["clean","staff","however","value"], comprehensionQuestions:[{id:"q1",question:"Name one good point about the hotel.",answer:"the room was clean / the staff were kind",skill:"detail"},{id:"q2",question:"Name one problem.",answer:"wifi did not work / breakfast finished early",skill:"detail"},{id:"q3",question:"Does the reviewer recommend it overall?",answer:"yes, good value for a short stay",skill:"main_idea"}], transferPrompt:"Write a two-line review of a place you know: one strength, one weakness.", contentId:"original-read-a2-hotel" },
  // B1
  { id:"read-b1-work", level:"B1", title:"Learning at Work", passage:"Many professionals develop new skills by working on challenging projects. The most effective learning often combines formal training with feedback and real-world practice.", wordRecognitionTargets:["professionals","effective","feedback"], comprehensionQuestions:[{id:"q1",question:"What combination is described as effective?",answer:"formal training, feedback and real-world practice",skill:"main_idea"}], transferPrompt:"Give one example from your own work or study.", contentId:"original-read-b1-work" },
  { id:"read-b1-sleep", level:"B1", title:"Why Sleep Matters", passage:"Research consistently links seven to eight hours of sleep with better memory and decision-making. People who regularly sleep less than six hours often believe they have adapted, yet tests show their reaction times slow significantly.", wordRecognitionTargets:["consistently","adapted","significantly"], comprehensionQuestions:[{id:"q1",question:"How much sleep is linked with better memory?",answer:"seven to eight hours",skill:"detail"},{id:"q2",question:"What do short sleepers wrongly believe?",answer:"that they have adapted",skill:"inference"},{id:"q3",question:"What do tests actually show?",answer:"slower reaction times",skill:"inference"}], transferPrompt:"Summarise the passage in one sentence, then say whether it matches your experience.", contentId:"original-read-b1-sleep" },
  { id:"read-b1-bikes", level:"B1", title:"The Bike-Share Experiment", passage:"When the city introduced free public bicycles, officials expected traffic to fall. Instead, most trips replaced short walks. Only after parking fees rose did car journeys begin to drop — a reminder that prices often change behaviour faster than good intentions.", wordRecognitionTargets:["introduced","expected","behaviour"], comprehensionQuestions:[{id:"q1",question:"What did officials expect to happen?",answer:"traffic would fall",skill:"detail"},{id:"q2",question:"What actually happened at first?",answer:"bikes replaced short walks instead of car trips",skill:"inference"},{id:"q3",question:"What finally reduced car journeys?",answer:"higher parking fees",skill:"detail"}], transferPrompt:"Describe a time a price or rule changed your behaviour more than advice did.", contentId:"original-read-b1-bikes" },
  // B2
  { id:"read-b2-policy", level:"B2", title:"A Policy Debate", passage:"Supporters argue that flexible work improves retention, while critics point to coordination costs. The evidence suggests the outcome depends heavily on job design and management practices.", wordRecognitionTargets:["retention","coordination","outcome"], comprehensionQuestions:[{id:"q1",question:"What do supporters argue?",answer:"flexible work improves retention",skill:"argument"},{id:"q2",question:"What does the final sentence imply?",answer:"the outcome depends on context",skill:"inference"}], transferPrompt:"State which side you find more convincing and why.", contentId:"original-read-b2-policy" },
  { id:"read-b2-hiring", level:"B2", title:"Algorithms in Hiring", passage:"Companies increasingly use software to screen applications, promising efficiency and consistency. Yet audits have found that systems trained on past decisions can quietly reproduce old biases at scale. Several jurisdictions now require human review of automated rejections — not to ban the tools, but to keep accountability somewhere recognisably human.", wordRecognitionTargets:["screening","biases","jurisdictions","accountability"], comprehensionQuestions:[{id:"q1",question:"What promise do screening systems offer?",answer:"efficiency and consistency",skill:"detail"},{id:"q2",question:"What risk have audits uncovered?",answer:"reproducing past biases at scale",skill:"inference"},{id:"q3",question:"What is the current regulatory approach?",answer:"require human review rather than ban the tools",skill:"argument"}], transferPrompt:"Argue for or against human review of automated decisions in 3–4 sentences.", contentId:"original-read-b2-hiring" },
  { id:"read-b2-climate", level:"B2", title:"Cities Adapting to Heat", passage:"Painting roofs white, planting street trees and adding shaded corridors can lower urban temperatures by several degrees. Critics note these measures cost money upfront; proponents reply that heatwaves already cost cities far more in lost productivity and healthcare. The debate is less about whether to adapt than who pays first.", wordRecognitionTargets:["urban","upfront","proponents","productivity"], comprehensionQuestions:[{id:"q1",question:"Give two cooling measures mentioned.",answer:"white roofs and street trees (or shaded corridors)",skill:"detail"},{id:"q2",question:"What is critics' main objection?",answer:"upfront cost",skill:"detail"},{id:"q3",question:"How do proponents reframe the cost argument?",answer:"heatwaves already cost more in lost productivity and healthcare",skill:"argument"}], transferPrompt:"Which public investment would you prioritise first, and why?", contentId:"original-read-b2-climate" },
  // C1
  { id:"read-c1-analysis", level:"C1", title:"Evidence and Inference", passage:"A convincing argument distinguishes observation from interpretation. When evidence is incomplete, the writer should qualify claims rather than convert uncertainty into confidence.", wordRecognitionTargets:["observation","interpretation","qualify"], comprehensionQuestions:[{id:"q1",question:"What should a writer do when evidence is incomplete?",answer:"qualify claims",skill:"main_idea"},{id:"q2",question:"What attitude does the passage promote?",answer:"careful reasoning under uncertainty",skill:"tone"}], transferPrompt:"Rewrite one strong claim from your own field with appropriate qualification.", contentId:"original-read-c1-analysis" },
  { id:"read-c1-teams", level:"C1", title:"The Ritual Economy of Remote Teams", passage:"Distributed teams rarely fail for lack of tools; they fail when informal coordination disappears. The corridor conversation, the overheard decision, the glance that says 'not now' — these micro-signals carry enormous bandwidth, and video calls transmit almost none of it. Successful remote organisations therefore manufacture ritual deliberately: predictable stand-ups, written decision logs, explicit office hours — replacing ambient awareness with architecture.", wordRecognitionTargets:["distributed","bandwidth","ambient","architecture"], comprehensionQuestions:[{id:"q1",question:"According to the passage, why do distributed teams fail?",answer:"informal coordination disappears, not lack of tools",skill:"main_idea"},{id:"q2",question:"What are examples of micro-signals given?",answer:"corridor conversation, overheard decision, a glance",skill:"detail"},{id:"q3",question:"What does the final metaphor suggest?",answer:"rituals deliberately replace spontaneous awareness",skill:"inference"},{id:"q4",question:"What is the author's tone toward video calls?",answer:"sceptical of their bandwidth",skill:"tone"}], transferPrompt:"Identify one ritual in your workplace and analyse what informal function it secretly performs.", contentId:"original-read-c1-teams" },
  { id:"read-c1-econ", level:"C1", title:"Automation and the Long View", passage:"Every wave of automation has retired some jobs mid-career while creating others nobody imagined. The honest summary of economic history is neither comfort nor catastrophe: transitions were net-positive in aggregate yet brutally uneven in distribution. Policy debates that conflate the average outcome with everyone's outcome mistake arithmetic for justice.", wordRecognitionTargets:["aggregate","uneven","conflate","arithmetic"], comprehensionQuestions:[{id:"q1",question:"What does the author call 'the honest summary'?",answer:"transitions were net-positive overall but unevenly distributed",skill:"main_idea"},{id:"q2",question:"What mistake do policy debates make, according to the writer?",answer:"treating the average outcome as everyone's outcome",skill:"inference"},{id:"q3",question:'What does "mistake arithmetic for justice" mean here?',answer:"statistical gain does not guarantee fair treatment of individuals",skill:"inference"}], transferPrompt:"Apply this distinction to a technology currently changing your industry.", contentId:"original-read-c1-econ" },
  // C2
  { id:"read-c2-rhetoric", level:"C2", title:"Rhetoric and Responsibility", passage:"Rhetorical precision is not merely decorative. It can expose hidden assumptions, constrain interpretation, or deliberately widen the space of plausible readings; responsible argument therefore requires attention not only to what is asserted, but to what the wording permits an audience to infer.", wordRecognitionTargets:["rhetorical","assumptions","plausible","infer"], comprehensionQuestions:[{id:"q1",question:"What can rhetorical precision affect?",answer:"interpretation and inference",skill:"inference"},{id:"q2",question:"Why must responsible argument attend to wording?",answer:"because wording shapes what audiences infer",skill:"argument"}], transferPrompt:"Give two ways wording can subtly change the interpretation of a claim.", contentId:"original-read-c2-rhetoric" },
  { id:"read-c2-accountability", level:"C2", title:"Accountability Without Actors", passage:"When harm emerges from a thousand optimised micro-decisions, liability finds no natural defendant. The law's imagination remains stubbornly personal: intent, negligence, a guilty hand. Systems that injure statistically — through accumulated thresholds, defaults and incentives — escape doctrine built for singular culprits. To govern them, we may need to legislate not against what systems intend, but against what they predictably do.", wordRecognitionTargets:["liability","doctrine","culprits","predictably"], comprehensionQuestions:[{id:"q1",question:"Why does liability find 'no natural defendant'?",answer:"harm emerges from many micro-decisions, not one actor",skill:"inference"},{id:"q2",question:"What is described as stubbornly personal?",answer:"the law's imagination — its focus on individual intent",skill:"detail"},{id:"q3",question:"What legislative shift does the author propose?",answer:"regulate predictable outcomes rather than intentions",skill:"argument"}], transferPrompt:"Rewrite the final sentence in plain language, then argue whether such legislation could work in practice.", contentId:"original-read-c2-accountability" },
  { id:"read-c2-literary", level:"C2", title:"On Unreliable Narration", passage:"The unreliable narrator does not lie to us so much as invite us to lie to ourselves alongside them. Our complicity is the point: we assemble the flattering version because we recognise the technique. Criticism that merely exposes the narrator's deception misses the deeper design — the text has been auditing the reader all along.", wordRecognitionTargets:["complicity","flattering","deception","auditing"], comprehensionQuestions:[{id:"q1",question:"What does the critic say readers do alongside unreliable narrators?",answer:"lie to themselves; build the flattering version together",skill:"inference"},{id:"q2",question:"Why does exposing the deception miss the point?",answer:"because the reader's willingness to be deceived is the true subject",skill:"inference"},{id:"q3",question:"What does 'auditing the reader' mean?",answer:"the text tests and reveals the reader's own self-serving interpretations",skill:"inference"}], transferPrompt:"Name a book or film that made you complicit in its narrator's self-deception, and explain how.", contentId:"original-read-c2-literary" },
];

const BASE_EAR_ACTIVITIES: EarActivity[] = [
  // Pre-A1
  { id:"ear-prea1-im", level:"Pre-A1", patternType:"contractions", spokenForm:"I'm", writtenForm:"I am", explanation:"In natural speech, I am commonly contracts to I'm.", replayCountTarget:3, discriminationQuestion:"Which written form matches what you hear?" },
  { id:"ear-prea1-dont", level:"Pre-A1", patternType:"contractions", spokenForm:"don't", writtenForm:"do not", explanation:"Don't is the spoken contraction of do not — the o disappears.", replayCountTarget:3, discriminationQuestion:"Which written form matches what you hear?" },
  { id:"ear-prea1-whats", level:"Pre-A1", patternType:"contractions", spokenForm:"what's", writtenForm:"what is", explanation:"What's contracts what is; the apostrophe marks the missing i.", replayCountTarget:3, discriminationQuestion:"Which written form matches what you hear?" },
  // A1
  { id:"ear-a1-gonna", level:"A1", patternType:"reduction", spokenForm:"gonna", writtenForm:"going to", explanation:"Informal spoken English often reduces going to to gonna.", replayCountTarget:3, discriminationQuestion:"Do you hear the full phrase or a reduced form?" },
  { id:"ear-a1-wanna", level:"A1", patternType:"reduction", spokenForm:"wanna", writtenForm:"want to", explanation:"Want to becomes wanna in relaxed speech.", replayCountTarget:3, discriminationQuestion:"Do you hear the full phrase or a reduced form?" },
  { id:"ear-a1-cause", level:"A1", patternType:"reduction", spokenForm:"'cause", writtenForm:"because", explanation:"Because is shortened to 'cause in casual speech — the be drops away.", replayCountTarget:3, discriminationQuestion:"Which longer word hides behind this reduction?" },
  // A2
  { id:"ear-a2-linking", level:"A2", patternType:"linking", spokenForm:"pick_it_up", writtenForm:"pick it up", explanation:"Final and initial sounds connect across word boundaries.", replayCountTarget:3, discriminationQuestion:"Which words blend together?" },
  { id:"ear-a2-anhour", level:"A2", patternType:"linking", spokenForm:"an_hour", writtenForm:"an hour", explanation:"The h in hour is silent, so the n links directly into the vowel: a-nower.", replayCountTarget:3, discriminationQuestion:"Which letter is silent, and how does it affect the link?" },
  { id:"ear-a2-nextstop", level:"A2", patternType:"linking", spokenForm:"next_stop", writtenForm:"next stop", explanation:"Next ends in t and stop begins with st — native speakers blend into neks-top.", replayCountTarget:3, discriminationQuestion:"How many t sounds do you actually hear?" },
  // B1
  { id:"ear-b1-can", level:"B1", patternType:"weak_forms", spokenForm:"kən", writtenForm:"can", explanation:"Function words like can are pronounced with a weak vowel (kən) unless stressed.", replayCountTarget:4, discriminationQuestion:"Is the modal strongly stressed or weak?" },
  { id:"ear-b1-him", level:"B1", patternType:"weak_forms", spokenForm:"tell_ɪm", writtenForm:"tell him", explanation:"The h of him disappears after tell, leaving tell'im in fast speech.", replayCountTarget:4, discriminationQuestion:"What happens to the h sound?" },
  { id:"ear-b1-alot", level:"B1", patternType:"linking", spokenForm:"a_lot_of", writtenForm:"a lot of", explanation:"Three small words fuse into one rhythm group: a-lot-of.", replayCountTarget:4, discriminationQuestion:"Where are the word boundaries in the sound stream?" },
  // B2
  { id:"ear-b2-dja", level:"B2", patternType:"fast_speech", spokenForm:"dja", writtenForm:"did you", explanation:"Did you compresses to dja — the d and y merge into a j sound.", replayCountTarget:4, discriminationQuestion:"What full phrase is represented?" },
  { id:"ear-b2-lemme", level:"B2", patternType:"fast_speech", spokenForm:"lemme", writtenForm:"let me", explanation:"Let me reduces to lemme in conversational speech.", replayCountTarget:4, discriminationQuestion:"What full phrase is represented?" },
  { id:"ear-b2-oughta", level:"B2", patternType:"fast_speech", spokenForm:"oughta", writtenForm:"ought to", explanation:"Ought to becomes oughta; the t of to attaches to ought.", replayCountTarget:4, discriminationQuestion:"What full form is hidden by the reduction?" },
  // C1
  { id:"ear-c1-coulda", level:"C1", patternType:"connected_speech", spokenForm:"coulda", writtenForm:"could have", explanation:"Could have may be heavily reduced to coulda in fast speech — the h vanishes entirely.", replayCountTarget:4, discriminationQuestion:"Identify the reduced auxiliary sequence." },
  { id:"ear-c1-kinda", level:"C1", patternType:"connected_speech", spokenForm:"kinda", writtenForm:"kind of", explanation:"Kind of reduces to kinda; register matters — avoid it in formal writing.", replayCountTarget:4, discriminationQuestion:"Which written form matches, and in which register is the reduced form acceptable?" },
  { id:"ear-c1-mighta", level:"C1", patternType:"connected_speech", spokenForm:"mighta", writtenForm:"might have", explanation:"Might have reduces to mighta; perfect modals are frequent reduction sites.", replayCountTarget:4, discriminationQuestion:"Reconstruct the full modal perfect phrase." },
  // C2
  { id:"ear-c2-wouldve", level:"C2", patternType:"fast_speech", spokenForm:"would've", writtenForm:"would have", explanation:"Advanced listeners recover reduced auxiliaries instantly from context, without needing the full form.", replayCountTarget:4, discriminationQuestion:"Which grammatical form is hidden by the reduction?" },
  { id:"ear-c2-suppose", level:"C2", patternType:"fast_speech", spokenForm:"s'pose", writtenForm:"suppose", explanation:"Suppose compresses to s'pose — the first syllable nearly disappears.", replayCountTarget:4, discriminationQuestion:"Which syllable survives the compression?" },
  { id:"ear-c2-innit", level:"C2", patternType:"connected_speech", spokenForm:"innit", writtenForm:"isn't it", explanation:"Innit fuses isn't it and extends far beyond its literal meaning as a universal tag question — recognising it signals sociolinguistic awareness.", replayCountTarget:4, discriminationQuestion:"What does innit literally contract from, and how is it used beyond that meaning?" },
];

export const SAY_IT_BETTER: SayItBetterExercise[] = [
  {id:"sib-prea1-greet",level:"Pre-A1",learnerVersion:"Hello.",correctedVersion:"Hello! Nice to meet you.",naturalVersion:"Hi there! Great to meet you.",advancedVersion:"Hello, it's really nice to meet you.",professionalVersion:"Good morning — pleased to meet you.",changeNotes:["add greeting formula","warmth","register"],retryPrompt:"Greet someone at a friend's party.",transferPrompt:"Greet someone at a job interview."},
  {id:"sib-prea1-thanks",level:"Pre-A1",learnerVersion:"Thanks you.",correctedVersion:"Thank you.",naturalVersion:"Thanks a lot!",advancedVersion:"Thank you so much — I really appreciate it.",professionalVersion:"I appreciate your assistance.",changeNotes:["verb form","natural intensifier","register"],retryPrompt:"Thank a friend for a gift.",transferPrompt:"Thank a colleague for their help on a report."},
  {id:"sib-prea1-name",level:"Pre-A1",learnerVersion:"My name Omar.",correctedVersion:"My name is Omar.",naturalVersion:"I'm Omar.",advancedVersion:"I'm Omar — lovely to meet you.",professionalVersion:"My name is Omar; I look forward to working with you.",changeNotes:["missing verb","shorter natural form","professional extension"],retryPrompt:"Introduce yourself to a new neighbour.",transferPrompt:"Introduce yourself in a job interview."},
  {id:"sib-a1-request",level:"A1",learnerVersion:"Give me water.",correctedVersion:"Give me some water, please.",naturalVersion:"Could I have some water, please?",advancedVersion:"Could I have a glass of water, please?",professionalVersion:"Could you please bring me a glass of water?",changeNotes:["politeness","article/quantifier","register"],retryPrompt:"Ask for something politely in a shop.",transferPrompt:"Ask for a different item without copying the sentence."},
  {id:"sib-a1-like",level:"A1",learnerVersion:"I very like pizza.",correctedVersion:"I really like pizza.",naturalVersion:"I love pizza!",advancedVersion:"I'm genuinely fond of pizza.",professionalVersion:"Pizza is something I particularly enjoy.",changeNotes:["adverb placement","stronger verb","register"],retryPrompt:"Say what food you dislike, correctly.",transferPrompt:"Recommend a restaurant to a visitor."},
  {id:"sib-a1-direction",level:"A1",learnerVersion:"Where is bank?",correctedVersion:"Where is the bank?",naturalVersion:"Excuse me, where's the nearest bank?",advancedVersion:"Sorry to bother you — could you point me towards the nearest bank?",professionalVersion:"Could you kindly direct me to the closest branch?",changeNotes:["definite article","softening opener","politeness escalation"],retryPrompt:"Ask for the train station politely.",transferPrompt:"Ask a stranger for directions in writing (chat)."},
  {id:"sib-a2-plan",level:"A2",learnerVersion:"Tomorrow I go to doctor.",correctedVersion:"Tomorrow I am going to the doctor.",naturalVersion:"I'm seeing the doctor tomorrow.",advancedVersion:"I have a doctor's appointment tomorrow.",professionalVersion:"I have a medical appointment scheduled for tomorrow.",changeNotes:["article","tense","natural chunk"],retryPrompt:"Describe another appointment.",transferPrompt:"Say it naturally for a friend."},
  {id:"sib-a2-invite",level:"A2",learnerVersion:"You want come party?",correctedVersion:"Do you want to come to the party?",naturalVersion:"Fancy coming to the party?",advancedVersion:"We'd love for you to join us at the party.",professionalVersion:"We would be delighted if you could attend.",changeNotes:["question structure","idiomatic invitation","formal invitation"],retryPrompt:"Invite a classmate to study together.",transferPrompt:"Write a formal event invitation in one sentence."},
  {id:"sib-a2-sorry",level:"A2",learnerVersion:"Sorry I late.",correctedVersion:"Sorry I'm late.",naturalVersion:"So sorry — got held up!",advancedVersion:"My apologies for the delay; I was unavoidably held up.",professionalVersion:"Please accept my apologies for arriving late to our meeting.",changeNotes:["missing verb","casual excuse formula","professional apology"],retryPrompt:"Apologise for forgetting a message.",transferPrompt:"Apologise by email for a late reply."},
  {id:"sib-b1-opinion",level:"B1",learnerVersion:"I think this idea is good because it saves time.",correctedVersion:"I think this idea is good because it saves time.",naturalVersion:"I think this idea makes sense because it saves us time.",advancedVersion:"I'd argue that this approach is worthwhile, largely because it saves time.",professionalVersion:"I would recommend this approach because it is likely to improve efficiency.",changeNotes:["lexical naturalness","register","argument framing"],retryPrompt:"Give an opinion about a work process.",transferPrompt:"State the same idea more diplomatically."},
  {id:"sib-b1-email-open",level:"B1",learnerVersion:"Send me report fast.",correctedVersion:"Could you send me the report by today?",naturalVersion:"Any chance you could send the report over today?",advancedVersion:"Would you mind sending the report through before end of day?",professionalVersion:"I would appreciate receiving the report by close of business today.",changeNotes:["imperative→request","deadline framing","formal register"],retryPrompt:"Ask a teammate for updated numbers.",transferPrompt:"Chase a late supplier by email — firm but polite."},
  {id:"sib-b1-suggest",level:"B1",learnerVersion:"We must go meeting.",correctedVersion:"We should attend the meeting.",naturalVersion:"We'd better get to the meeting.",advancedVersion:"It would be wise for us to attend the meeting.",professionalVersion:"I recommend that we attend the meeting.",changeNotes:["modal choice","natural contraction","hedged recommendation"],retryPrompt:"Suggest postponing a deadline.",transferPrompt:"Advise a client in writing."},
  {id:"sib-b2-disagreement",level:"B2",learnerVersion:"You are wrong about this.",correctedVersion:"I don't think that is quite right.",naturalVersion:"I'm not sure I see it that way.",advancedVersion:"I understand the point, but I would interpret the evidence differently.",professionalVersion:"I see the rationale, although the available evidence leads me to a different conclusion.",changeNotes:["tone","softening","evidence-based disagreement"],retryPrompt:"Disagree with a colleague without sounding confrontational.",transferPrompt:"Disagree with the same idea in an email."},
  {id:"sib-b2-raise",level:"B2",learnerVersion:"I want more salary.",correctedVersion:"I would like to discuss my compensation.",naturalVersion:"Can we talk about my pay? I feel it's due a review.",advancedVersion:"Given my results this year, I'd welcome a conversation about adjusting my compensation.",professionalVersion:"I would like to request a meeting to review my remuneration in light of my contributions.",changeNotes:["direct→diplomatic","justification frame","HR vocabulary"],retryPrompt:"Ask for a promotion opportunity.",transferPrompt:"Write the opening line of that salary email."},
  {id:"sib-c1-hedging",level:"C1",learnerVersion:"This plan will fail.",correctedVersion:"This plan may fail.",naturalVersion:"There is a risk that this plan may not work as intended.",advancedVersion:"The available evidence suggests that the plan may be vulnerable under these conditions.",professionalVersion:"Given the current evidence, I would treat the plan as high-risk unless these assumptions are validated.",changeNotes:["hedging","register","precision"],retryPrompt:"Make a strong claim more appropriately cautious.",transferPrompt:"Adapt the same claim for a senior executive audience."},
  {id:"sib-c1-pushback",level:"C1",learnerVersion:"Your data is wrong.",correctedVersion:"I think the data may need another look.",naturalVersion:"These figures don't quite add up to me.",advancedVersion:"I wonder whether we might be reading these figures too hastily.",professionalVersion:"Before we proceed, I would recommend validating the underlying data set.",changeNotes:["blunt→diplomatic","epistemic softening","process-oriented fix"],retryPrompt:"Challenge a methodology in a meeting.",transferPrompt:"Raise the same concern in a project channel, in writing."},
  {id:"sib-c2-nuance",level:"C2",learnerVersion:"This is a simple problem.",correctedVersion:"This is not a simple problem.",naturalVersion:"The situation is more complicated than it first appears.",advancedVersion:"The issue is deceptively complex, particularly once the competing constraints are considered.",professionalVersion:"The issue warrants a more nuanced assessment because the apparent simplicity conceals significant trade-offs.",changeNotes:["nuance","rhetorical control","register"],retryPrompt:"Reframe an oversimplified statement from your field.",transferPrompt:"Produce a version suitable for a public policy memo."},
  {id:"sib-c2-reframe",level:"C2",learnerVersion:"Nobody will accept this change.",correctedVersion:"This change may face resistance.",naturalVersion:"There'll be pushback on this.",advancedVersion:"Anticipating the response, I expect measured scepticism rather than outright rejection.",professionalVersion:"Stakeholder analysis suggests resistance concentrated in two areas, which we can pre-empt.",changeNotes:["absolute→calibrated","precision about resistance","strategic framing"],retryPrompt:"Soften a pessimistic forecast without losing force.",transferPrompt:"Deliver the same assessment to a board in one sentence."},
];

export function levelContentPool(level: CEFRLevel) {
  return {
    reading: READING_ACTIVITIES.filter((x) => x.level === level),
    ear: EAR_ACTIVITIES.filter((x) => x.level === level),
    sayItBetter: SAY_IT_BETTER.filter((x) => x.level === level),
  };
}

/** Same shape as before, but the pick rotates daily so learners meet fresh material on every visit. */
export function levelContent(level: CEFRLevel) {
  const pool = levelContentPool(level);
  return {
    reading: rotate(pool.reading, level, "reading"),
    ear: rotate(pool.ear, level, "ear"),
    sayItBetter: rotate(pool.sayItBetter, level, "sib"),
  };
}

/** Part 100: English Ear 20 / Reading 6 per CEFR band (base bank + expansion wave). */
export const READING_ACTIVITIES: ReadingActivity[] = [...BASE_READING_ACTIVITIES, ...READING_ACTIVITIES_EXTRA];
export const EAR_ACTIVITIES: EarActivity[] = [...BASE_EAR_ACTIVITIES, ...EAR_ACTIVITIES_EXTRA];