import type { CEFRLevel } from "./learner";
import type { EarActivity, ReadingActivity, SayItBetterExercise } from "./learning-systems";

export const READING_ACTIVITIES: ReadingActivity[] = [
  { id:"read-prea1-signs", level:"Pre-A1", title:"Read the Sign", passage:"EXIT. OPEN. CLOSED. BUS STOP.", wordRecognitionTargets:["EXIT","OPEN","CLOSED","BUS STOP"], comprehensionQuestions:[{id:"q1",question:"Which phrase tells you where the bus stops?",answer:"BUS STOP",skill:"detail"}], contentId:"original-read-prea1-signs" },
  { id:"read-a1-routine", level:"A1", title:"A Morning Routine", passage:"Omar wakes up at seven. He drinks coffee and walks to work. He starts work at eight.", wordRecognitionTargets:["wakes","drinks","walks"], comprehensionQuestions:[{id:"q1",question:"What time does Omar start work?",answer:"eight",skill:"detail"}], transferPrompt:"Write three sentences about your morning.", contentId:"original-read-a1-routine" },
  { id:"read-a2-travel", level:"A2", title:"A Travel Change", passage:"The train was delayed because of heavy rain. Passengers were asked to wait on platform three.", wordRecognitionTargets:["delayed","passengers","platform"], comprehensionQuestions:[{id:"q1",question:"Why was the train delayed?",answer:"heavy rain",skill:"main_idea"},{id:"q2",question:"Where should passengers wait?",answer:"platform three",skill:"detail"}], transferPrompt:"Explain what you would do if your train were delayed.", contentId:"original-read-a2-travel" },
  { id:"read-b1-work", level:"B1", title:"Learning at Work", passage:"Many professionals develop new skills by working on challenging projects. The most effective learning often combines formal training with feedback and real-world practice.", wordRecognitionTargets:["professionals","effective","feedback"], comprehensionQuestions:[{id:"q1",question:"What combination is described as effective?",answer:"formal training, feedback and real-world practice",skill:"main_idea"}], transferPrompt:"Give one example from your own work or study.", contentId:"original-read-b1-work" },
  { id:"read-b2-policy", level:"B2", title:"A Policy Debate", passage:"Supporters argue that flexible work improves retention, while critics point to coordination costs. The evidence suggests the outcome depends heavily on job design and management practices.", wordRecognitionTargets:["retention","coordination","outcome"], comprehensionQuestions:[{id:"q1",question:"What do supporters argue?",answer:"flexible work improves retention",skill:"argument"},{id:"q2",question:"What does the final sentence imply?",answer:"the outcome depends on context",skill:"inference"}], transferPrompt:"State which side you find more convincing and why.", contentId:"original-read-b2-policy" },
  { id:"read-c1-analysis", level:"C1", title:"Evidence and Inference", passage:"A convincing argument distinguishes observation from interpretation. When evidence is incomplete, the writer should qualify claims rather than convert uncertainty into confidence.", wordRecognitionTargets:["observation","interpretation","qualify"], comprehensionQuestions:[{id:"q1",question:"What should a writer do when evidence is incomplete?",answer:"qualify claims",skill:"main_idea"},{id:"q2",question:"What attitude does the passage promote?",answer:"careful reasoning under uncertainty",skill:"tone"}], transferPrompt:"Rewrite one strong claim from your own field with appropriate qualification.", contentId:"original-read-c1-analysis" },
  { id:"read-c2-rhetoric", level:"C2", title:"Rhetoric and Responsibility", passage:"Rhetorical precision is not merely decorative. It can expose hidden assumptions, constrain interpretation, or deliberately widen the space of plausible readings; responsible argument therefore requires attention not only to what is asserted, but to what the wording permits an audience to infer.", wordRecognitionTargets:["rhetorical","assumptions","plausible","infer"], comprehensionQuestions:[{id:"q1",question:"What can rhetorical precision affect?",answer:"interpretation and inference",skill:"inference"},{id:"q2",question:"Why must responsible argument attend to wording?",answer:"because wording shapes what audiences infer",skill:"argument"}], transferPrompt:"Give two ways wording can subtly change the interpretation of a claim.", contentId:"original-read-c2-rhetoric" },
];

export const EAR_ACTIVITIES: EarActivity[] = [
  { id:"ear-prea1-hello", level:"Pre-A1", patternType:"contractions", spokenForm:"I'm", writtenForm:"I am", explanation:"In natural speech, I am commonly contracts to I'm.", replayCountTarget:3, discriminationQuestion:"Which written form matches what you hear?" },
  { id:"ear-a1-gonna", level:"A1", patternType:"reduction", spokenForm:"gonna", writtenForm:"going to", explanation:"Informal spoken English often reduces going to to gonna.", replayCountTarget:3, discriminationQuestion:"Do you hear the full phrase or a reduced form?" },
  { id:"ear-a2-linking", level:"A2", patternType:"linking", spokenForm:"pick_it_up", writtenForm:"pick it up", explanation:"Final and initial sounds connect across word boundaries.", replayCountTarget:3, discriminationQuestion:"Which words blend together?" },
  { id:"ear-b1-weak", level:"B1", patternType:"weak_forms", spokenForm:"can", writtenForm:"can", explanation:"Function words are often pronounced with a weak vowel in connected speech.", replayCountTarget:4, discriminationQuestion:"Is the modal strongly stressed or weak?" },
  { id:"ear-b2-fast", level:"B2", patternType:"fast_speech", spokenForm:"dja wanna", writtenForm:"do you want to", explanation:"Fast speech can compress several sounds while the meaning stays recoverable.", replayCountTarget:4, discriminationQuestion:"What full phrase is represented?" },
  { id:"ear-c1-reduction", level:"C1", patternType:"connected_speech", spokenForm:"coulda", writtenForm:"could have", explanation:"Could have may be heavily reduced in fast conversational speech.", replayCountTarget:4, discriminationQuestion:"Identify the reduced auxiliary sequence." },
  { id:"ear-c2-register", level:"C2", patternType:"fast_speech", spokenForm:"would've", writtenForm:"would have", explanation:"Advanced learners should recover reduced auxiliaries without relying on formal spelling.", replayCountTarget:4, discriminationQuestion:"Which grammatical form is hidden by the reduction?" },
];

export const SAY_IT_BETTER: SayItBetterExercise[] = [
  {id:"sib-a1-request",level:"A1",learnerVersion:"Give me water.",correctedVersion:"Give me some water, please.",naturalVersion:"Could I have some water, please?",advancedVersion:"Could I have a glass of water, please?",professionalVersion:"Could you please bring me a glass of water?",changeNotes:["politeness","article/quantifier","register"],retryPrompt:"Ask for something politely in a shop.",transferPrompt:"Ask for a different item without copying the sentence."},
  {id:"sib-a2-plan",level:"A2",learnerVersion:"Tomorrow I go to doctor.",correctedVersion:"Tomorrow I am going to the doctor.",naturalVersion:"I'm seeing the doctor tomorrow.",advancedVersion:"I have a doctor's appointment tomorrow.",professionalVersion:"I have a medical appointment scheduled for tomorrow.",changeNotes:["article","tense","natural chunk"],retryPrompt:"Describe another appointment.",transferPrompt:"Say it naturally for a friend."},
  {id:"sib-b1-opinion",level:"B1",learnerVersion:"I think this idea is good because it saves time.",correctedVersion:"I think this idea is good because it saves time.",naturalVersion:"I think this idea makes sense because it saves us time.",advancedVersion:"I'd argue that this approach is worthwhile, largely because it saves time.",professionalVersion:"I would recommend this approach because it is likely to improve efficiency.",changeNotes:["lexical naturalness","register","argument framing"],retryPrompt:"Give an opinion about a work process.",transferPrompt:"State the same idea more diplomatically."},
  {id:"sib-b2-disagreement",level:"B2",learnerVersion:"You are wrong about this.",correctedVersion:"I don't think that is quite right.",naturalVersion:"I'm not sure I see it that way.",advancedVersion:"I understand the point, but I would interpret the evidence differently.",professionalVersion:"I see the rationale, although the available evidence leads me to a different conclusion.",changeNotes:["tone","softening","evidence-based disagreement"],retryPrompt:"Disagree with a colleague without sounding confrontational.",transferPrompt:"Disagree with the same idea in an email."},
  {id:"sib-c1-hedging",level:"C1",learnerVersion:"This plan will fail.",correctedVersion:"This plan may fail.",naturalVersion:"There is a risk that this plan may not work as intended.",advancedVersion:"The available evidence suggests that the plan may be vulnerable under these conditions.",professionalVersion:"Given the current evidence, I would treat the plan as high-risk unless these assumptions are validated.",changeNotes:["hedging","register","precision"],retryPrompt:"Make a strong claim more appropriately cautious.",transferPrompt:"Adapt the same claim for a senior executive audience."},
  {id:"sib-c2-nuance",level:"C2",learnerVersion:"This is a simple problem.",correctedVersion:"This is not a simple problem.",naturalVersion:"The situation is more complicated than it first appears.",advancedVersion:"The issue is deceptively complex, particularly once the competing constraints are considered.",professionalVersion:"The issue warrants a more nuanced assessment because the apparent simplicity conceals significant trade-offs.",changeNotes:["nuance","rhetorical control","register"],retryPrompt:"Reframe an oversimplified statement from your field.",transferPrompt:"Produce a version suitable for a public policy memo."},
];

export function levelContent(level: CEFRLevel) {
  return {
    reading: READING_ACTIVITIES.find(x=>x.level===level) ?? READING_ACTIVITIES[1],
    ear: EAR_ACTIVITIES.find(x=>x.level===level) ?? EAR_ACTIVITIES[1],
    sayItBetter: SAY_IT_BETTER.find(x=>x.level===level) ?? SAY_IT_BETTER[0],
  };
}
