/** Human-curated English → Arabic glossary, part 1: survival, people, time, places, food. */
export interface GlossEntry { ar: string; pos?: string; en?: string }

export const GLOSSARY_AR_1: Record<string, GlossEntry> = {
  hello: { ar: "مرحبًا", pos: "interjection", en: "a greeting" },
  hi: { ar: "أهلًا", pos: "interjection", en: "informal greeting" },
  goodbye: { ar: "وداعًا", pos: "interjection", en: "said when leaving" },
  please: { ar: "من فضلك", pos: "adverb", en: "polite word when asking" },
  thanks: { ar: "شكرًا", pos: "noun", en: "gratitude" },
  sorry: { ar: "آسف", pos: "adjective", en: "feeling regret" },
  yes: { ar: "نعم", pos: "adverb" },
  no: { ar: "لا", pos: "adverb" },
  welcome: { ar: "أهلًا بك", pos: "interjection" },
  excuse: { ar: "يسمح / يعتذر", pos: "verb", en: "excuse me = polite attention" },

  family: { ar: "عائلة", pos: "noun", en: "parents and relatives" },
  friend: { ar: "صديق", pos: "noun", en: "a person you know well and like" },
  mother: { ar: "أم", pos: "noun" },
  father: { ar: "أب", pos: "noun" },
  brother: { ar: "أخ", pos: "noun" },
  sister: { ar: "أخت", pos: "noun" },
  neighbour: { ar: "جار", pos: "noun", en: "a person living near you" },
  colleague: { ar: "زميل عمل", pos: "noun", en: "someone you work with" },
  people: { ar: "الناس", pos: "noun" },
  person: { ar: "شخص", pos: "noun" },
  name: { ar: "اسم", pos: "noun" },

  time: { ar: "وقت", pos: "noun" },
  today: { ar: "اليوم", pos: "adverb" },
  tomorrow: { ar: "غدًا", pos: "adverb" },
  yesterday: { ar: "أمس", pos: "adverb" },
  morning: { ar: "صباح", pos: "noun" },
  afternoon: { ar: "بعد الظهر", pos: "noun" },
  evening: { ar: "مساء", pos: "noun" },
  week: { ar: "أسبوع", pos: "noun" },
  month: { ar: "شهر", pos: "noun" },
  year: { ar: "سنة", pos: "noun" },
  monday: { ar: "الاثنين", pos: "noun" },
  friday: { ar: "الجمعة", pos: "noun" },
  sunday: { ar: "الأحد", pos: "noun" },
  saturday: { ar: "السبت", pos: "noun" },
  deadline: { ar: "موعد نهائي", pos: "noun", en: "latest time to finish" },
  minute: { ar: "دقيقة", pos: "noun" },
  hour: { ar: "ساعة", pos: "noun" },
  day: { ar: "يوم", pos: "noun" },
  night: { ar: "ليل", pos: "noun" },

  home: { ar: "منزل", pos: "noun" },
  house: { ar: "بيت", pos: "noun" },
  office: { ar: "مكتب", pos: "noun" },
  school: { ar: "مدرسة", pos: "noun" },
  station: { ar: "محطة", pos: "noun", en: "where trains or buses stop" },
  airport: { ar: "مطار", pos: "noun" },
  hospital: { ar: "مستشفى", pos: "noun" },
  shop: { ar: "متجر", pos: "noun" },
  cafe: { ar: "مقهى", pos: "noun" },
  city: { ar: "مدينة", pos: "noun" },
  country: { ar: "بلد", pos: "noun" },
  street: { ar: "شارع", pos: "noun" },
  market: { ar: "سوق", pos: "noun" },
  restaurant: { ar: "مطعم", pos: "noun" },
  hotel: { ar: "فندق", pos: "noun" },
  room: { ar: "غرفة", pos: "noun" },

  water: { ar: "ماء", pos: "noun" },
  coffee: { ar: "قهوة", pos: "noun" },
  tea: { ar: "شاي", pos: "noun" },
  bread: { ar: "خبز", pos: "noun" },
  rice: { ar: "أرز", pos: "noun" },
  meat: { ar: "لحم", pos: "noun" },
  chicken: { ar: "دجاج", pos: "noun" },
  fruit: { ar: "فاكهة", pos: "noun" },
  cake: { ar: "كيك", pos: "noun" },
  breakfast: { ar: "فطور", pos: "noun" },
  lunch: { ar: "غداء", pos: "noun" },
  dinner: { ar: "عشاء", pos: "noun" },
  food: { ar: "طعام", pos: "noun" },
  menu: { ar: "قائمة الطعام", pos: "noun" },
};
