/** Human-curated English → Arabic glossary, part 2: work, study, verbs, adjectives. */
import type { GlossEntry } from "./glossary-ar-1";

export const GLOSSARY_AR_2: Record<string, GlossEntry> = {
  meeting: { ar: "اجتماع", pos: "noun" },
  report: { ar: "تقرير", pos: "noun" },
  email: { ar: "بريد إلكتروني", pos: "noun" },
  project: { ar: "مشروع", pos: "noun" },
  team: { ar: "فريق", pos: "noun" },
  manager: { ar: "مدير", pos: "noun" },
  job: { ar: "وظيفة", pos: "noun" },
  salary: { ar: "راتب", pos: "noun" },
  interview: { ar: "مقابلة", pos: "noun" },
  appointment: { ar: "موعد", pos: "noun", en: "an arranged meeting at a fixed time" },
  schedule: { ar: "جدول", pos: "noun", en: "a plan showing times of events" },
  lesson: { ar: "درس", pos: "noun" },
  teacher: { ar: "معلم", pos: "noun" },
  student: { ar: "طالب", pos: "noun" },
  question: { ar: "سؤال", pos: "noun" },
  answer: { ar: "إجابة", pos: "noun" },
  book: { ar: "كتاب", pos: "noun" },
  english: { ar: "الإنجليزية", pos: "noun" },
  practice: { ar: "ممارسة", pos: "noun" },
  mistake: { ar: "خطأ", pos: "noun" },
  example: { ar: "مثال", pos: "noun" },
  evidence: { ar: "دليل", pos: "noun" },
  certificate: { ar: "شهادة", pos: "noun" },
  level: { ar: "مستوى", pos: "noun" },
  progress: { ar: "تقدم", pos: "noun" },
  goal: { ar: "هدف", pos: "noun" },
  plan: { ar: "خطة", pos: "noun" },
  idea: { ar: "فكرة", pos: "noun" },
  problem: { ar: "مشكلة", pos: "noun" },
  reason: { ar: "سبب", pos: "noun" },
  opinion: { ar: "رأي", pos: "noun" },

  have: { ar: "يملك", pos: "verb" },
  want: { ar: "يريد", pos: "verb" },
  need: { ar: "يحتاج", pos: "verb" },
  like: { ar: "يحب", pos: "verb" },
  love: { ar: "يعشق", pos: "verb" },
  eat: { ar: "يأكل", pos: "verb" },
  drink: { ar: "يشرب", pos: "verb" },
  sleep: { ar: "ينام", pos: "verb" },
  wake: { ar: "يستيقظ", pos: "verb" },
  speak: { ar: "يتحدث", pos: "verb" },
  talk: { ar: "يتحدث", pos: "verb" },
  listen: { ar: "يستمع", pos: "verb" },
  read: { ar: "يقرأ", pos: "verb" },
  write: { ar: "يكتب", pos: "verb" },
  learn: { ar: "يتعلم", pos: "verb" },
  teach: { ar: "يعلّم", pos: "verb" },
  help: { ar: "يساعد", pos: "verb" },
  play: { ar: "يلعب", pos: "verb" },
  buy: { ar: "يشتري", pos: "verb" },
  pay: { ar: "يدفع", pos: "verb" },
  borrow: { ar: "يستعير", pos: "verb", en: "to take and return later" },
  arrive: { ar: "يصل", pos: "verb", en: "to reach a place" },
  start: { ar: "يبدأ", pos: "verb" },
  finish: { ar: "ينتهي", pos: "verb" },
  understand: { ar: "يفهم", pos: "verb" },
  know: { ar: "يعرف", pos: "verb" },
  think: { ar: "يفكر", pos: "verb" },
  decide: { ar: "يقرر", pos: "verb", en: "to choose after thinking" },
  improve: { ar: "يحسّن", pos: "verb", en: "to become better" },
  introduce: { ar: "يقدّم شخصًا", pos: "verb", en: "tell someone a person's name" },
  recommend: { ar: "يوصي بـ", pos: "verb", en: "say something is good to try" },
  invite: { ar: "يدعو", pos: "verb" },
  complain: { ar: "يشتكي", pos: "verb", en: "say you are not satisfied" },
  apologise: { ar: "يعتذر", pos: "verb" },
  apologize: { ar: "يعتذر", pos: "verb" },
  explain: { ar: "يشرح", pos: "verb" },
  remember: { ar: "يتذكر", pos: "verb" },
  forget: { ar: "ينسى", pos: "verb" },
  send: { ar: "يرسل", pos: "verb" },
  call: { ar: "يتصل", pos: "verb" },
  meet: { ar: "يقابل", pos: "verb" },
  wait: { ar: "ينتظر", pos: "verb" },
  change: { ar: "يغيّر", pos: "verb" },
  choose: { ar: "يختار", pos: "verb" },

  good: { ar: "جيد", pos: "adjective" },
  bad: { ar: "سيئ", pos: "adjective" },
  big: { ar: "كبير", pos: "adjective" },
  small: { ar: "صغير", pos: "adjective" },
  new: { ar: "جديد", pos: "adjective" },
  old: { ar: "قديم", pos: "adjective" },
  happy: { ar: "سعيد", pos: "adjective" },
  sad: { ar: "حزين", pos: "adjective" },
  easy: { ar: "سهل", pos: "adjective" },
  difficult: { ar: "صعب", pos: "adjective" },
  important: { ar: "مهم", pos: "adjective" },
  free: { ar: "متفرغ / مجاني", pos: "adjective" },
  busy: { ar: "مشغول", pos: "adjective" },
  late: { ar: "متأخر", pos: "adjective" },
  early: { ar: "مبكر", pos: "adjective" },
  fast: { ar: "سريع", pos: "adjective" },
  slow: { ar: "بطيء", pos: "adjective" },
  delicious: { ar: "لذيذ", pos: "adjective", en: "tasting very good" },
  confident: { ar: "واثق", pos: "adjective", en: "sure you can do it" },
  reliable: { ar: "موثوق", pos: "adjective", en: "can be trusted" },
  generous: { ar: "كريم", pos: "adjective", en: "happy to give" },
  convenient: { ar: "ملائم", pos: "adjective", en: "easy and useful for you" },
};
