import type { CEFRLevel, CapabilitySkill } from "./curriculum";

export interface ProfessionalLesson {
  id: string;
  objectiveId: string;
  title: string;
  level: CEFRLevel;
  skill: CapabilitySkill;
  sequence: number;
  mission: string;
  category: string;
  description: string;
}

export const PROFESSIONAL_CURRICULUM: ProfessionalLesson[] = [
  // ── B1: Foundation (Lessons 1–7) ─────────────────────────────────────
  {
    id: "pro-lesson-01-professional-emails",
    objectiveId: "pro-obj-01",
    title: "Professional Email Writing",
    level: "B1",
    skill: "writing",
    sequence: 10,
    mission: "Write clear, professional emails for requests, updates, and follow-ups in a business context.",
    category: "Written Communication",
    description: "Master the structure and tone of professional emails. Learn to write subject lines, greetings, body paragraphs, and sign-offs that match business expectations.",
  },
  {
    id: "pro-lesson-02-business-meetings",
    objectiveId: "pro-obj-02",
    title: "Participating in Business Meetings",
    level: "B1",
    skill: "listening",
    sequence: 20,
    mission: "Understand meeting structure, follow agendas, and contribute ideas during team discussions.",
    category: "Spoken Communication",
    description: "Learn meeting vocabulary, how to agree and disagree politely, how to ask for clarification, and how to summarise action points.",
  },
  {
    id: "pro-lesson-03-telephone-calls",
    objectiveId: "pro-obj-03",
    title: "Telephone and Video Calls",
    level: "B1",
    skill: "listening",
    sequence: 30,
    mission: "Handle professional phone and video calls with confidence, including greetings, messages, and closing.",
    category: "Spoken Communication",
    description: "Practice answering calls, taking messages, confirming details, and managing video call etiquette in a professional setting.",
  },
  {
    id: "pro-lesson-04-describing-your-job",
    objectiveId: "pro-obj-04",
    title: "Describing Your Job and Company",
    level: "B1",
    skill: "speaking",
    sequence: 40,
    mission: "Introduce your role, responsibilities, and company clearly in professional conversations.",
    category: "Spoken Communication",
    description: "Learn to describe your job title, daily tasks, team structure, and company products or services in a natural, confident way.",
  },
  {
    id: "pro-lesson-05-business-travel",
    objectiveId: "pro-obj-05",
    title: "Business Travel and Accommodation",
    level: "B1",
    skill: "reading",
    sequence: 50,
    mission: "Handle travel bookings, hotel reservations, and transport arrangements for business trips.",
    category: "Practical Communication",
    description: "Read and write booking confirmations, understand travel itineraries, and practise conversations at hotels and airports.",
  },
  {
    id: "pro-lesson-06-scheduling",
    objectiveId: "pro-obj-06",
    title: "Scheduling and Appointments",
    level: "B1",
    skill: "speaking",
    sequence: 60,
    mission: "Arrange meetings, confirm appointments, and manage calendars using professional language.",
    category: "Practical Communication",
    description: "Practise suggesting times, confirming availability, rescheduling, and declining invitations politely.",
  },
  {
    id: "pro-lesson-07-basic-documents",
    objectiveId: "pro-obj-07",
    title: "Understanding Business Documents",
    level: "B1",
    skill: "reading",
    sequence: 70,
    mission: "Read and comprehend common business documents including invoices, memos, and standard forms.",
    category: "Written Communication",
    description: "Learn to identify key information in invoices, purchase orders, internal memos, and standard business correspondence.",
  },

  // ── B2: Intermediate Professional (Lessons 8–14) ─────────────────────
  {
    id: "pro-lesson-08-report-writing",
    objectiveId: "pro-obj-08",
    title: "Writing Business Reports",
    level: "B2",
    skill: "writing",
    sequence: 80,
    mission: "Structure and write business reports with executive summaries, findings, and recommendations.",
    category: "Written Communication",
    description: "Master report structure: title page, table of contents, executive summary, introduction, findings, conclusions, and recommendations.",
  },
  {
    id: "pro-lesson-09-presentations",
    objectiveId: "pro-obj-09",
    title: "Giving Presentations",
    level: "B2",
    skill: "speaking",
    sequence: 90,
    mission: "Deliver structured presentations with clear introductions, transitions, visual references, and Q&A handling.",
    category: "Spoken Communication",
    description: "Learn to open a presentation, signpost sections, handle slides, manage audience questions, and close with impact.",
  },
  {
    id: "pro-lesson-10-negotiations",
    objectiveId: "pro-obj-10",
    title: "Business Negotiations",
    level: "B2",
    skill: "speaking",
    sequence: 100,
    mission: "Negotiate terms, prices, and deadlines using persuasive language and concession strategies.",
    category: "Spoken Communication",
    description: "Practise making offers, counter-offers, requesting concessions, and reaching agreement while maintaining professional relationships.",
  },
  {
    id: "pro-lesson-11-job-interviews",
    objectiveId: "pro-obj-11",
    title: "Job Interviews",
    level: "B2",
    skill: "speaking",
    sequence: 110,
    mission: "Answer common interview questions clearly and demonstrate your experience using the STAR method.",
    category: "Spoken Communication",
    description: "Prepare for behavioural and competency-based interview questions. Practise structuring answers with Situation, Task, Action, Result.",
  },
  {
    id: "pro-lesson-12-customer-service",
    objectiveId: "pro-obj-12",
    title: "Customer Service Communication",
    level: "B2",
    skill: "speaking",
    sequence: 120,
    mission: "Handle customer enquiries, complaints, and feedback with empathy and professional resolution.",
    category: "Spoken Communication",
    description: "Learn to acknowledge concerns, apologise appropriately, offer solutions, and follow up professionally.",
  },
  {
    id: "pro-lesson-13-marketing-sales",
    objectiveId: "pro-obj-13",
    title: "Marketing and Sales Language",
    level: "B2",
    skill: "reading",
    sequence: 130,
    mission: "Write marketing copy and understand sales terminology including value propositions and calls to action.",
    category: "Written Communication",
    description: "Analyse marketing emails, landing pages, and sales pitches. Learn to write persuasive product descriptions and promotional content.",
  },
  {
    id: "pro-lesson-14-project-communication",
    objectiveId: "pro-obj-14",
    title: "Project Management Communication",
    level: "B2",
    skill: "writing",
    sequence: 140,
    mission: "Write project updates, status reports, and stakeholder communications using standard project vocabulary.",
    category: "Written Communication",
    description: "Practise writing progress reports, risk escalations, scope change requests, and project closure summaries.",
  },

  // ── C1: Advanced Professional (Lessons 15–21) ────────────────────────
  {
    id: "pro-lesson-15-persuasion",
    objectiveId: "pro-obj-15",
    title: "Persuasion and Influence",
    level: "C1",
    skill: "speaking",
    sequence: 150,
    mission: "Use advanced rhetorical strategies to persuade stakeholders, build consensus, and drive decisions.",
    category: "Strategic Communication",
    description: "Master rhetorical questions, evidence-based arguments, emotional appeal, and framing techniques for professional influence.",
  },
  {
    id: "pro-lesson-16-conflict-resolution",
    objectiveId: "pro-obj-16",
    title: "Conflict Resolution in the Workplace",
    level: "C1",
    skill: "speaking",
    sequence: 160,
    mission: "Mediate workplace disagreements, de-escalate tensions, and find mutually acceptable solutions.",
    category: "Strategic Communication",
    description: "Practise active listening, neutral language, reframing positions, and facilitating productive dialogue between conflicting parties.",
  },
  {
    id: "pro-lesson-17-cross-cultural",
    objectiveId: "pro-obj-17",
    title: "Cross-Cultural Communication",
    level: "C1",
    skill: "reading",
    sequence: 170,
    mission: "Navigate cultural differences in international business communication and avoid misunderstandings.",
    category: "Intercultural Communication",
    description: "Understand high-context vs low-context communication, cultural attitudes to hierarchy, and adapting style for international audiences.",
  },
  {
    id: "pro-lesson-18-financial-legal",
    objectiveId: "pro-obj-18",
    title: "Financial and Legal English",
    level: "C1",
    skill: "reading",
    sequence: 180,
    mission: "Read and understand financial reports, contracts, and legal correspondence with precision.",
    category: "Specialist Communication",
    description: "Learn key financial terminology, understand balance sheets and P&L statements, and read contract clauses carefully.",
  },
  {
    id: "pro-lesson-19-technical-communication",
    objectiveId: "pro-obj-19",
    title: "Technical Communication",
    level: "C1",
    skill: "writing",
    sequence: 190,
    mission: "Write clear technical documentation, user guides, and process manuals for professional audiences.",
    category: "Written Communication",
    description: "Practise writing step-by-step instructions, API documentation style, technical specifications, and knowledge base articles.",
  },
  {
    id: "pro-lesson-20-media-pr",
    objectiveId: "pro-obj-20",
    title: "Media and Public Relations",
    level: "C1",
    skill: "speaking",
    sequence: 200,
    mission: "Deliver press statements, handle media enquiries, and manage public-facing communications professionally.",
    category: "Strategic Communication",
    description: "Practise writing press releases, preparing for interviews, delivering key messages, and managing difficult questions.",
  },
  {
    id: "pro-lesson-21-leadership",
    objectiveId: "pro-obj-21",
    title: "Leadership Communication",
    level: "C1",
    skill: "speaking",
    sequence: 210,
    mission: "Communicate vision, give constructive feedback, and lead team conversations with authority and empathy.",
    category: "Strategic Communication",
    description: "Learn to deliver town halls, run one-to-ones, give performance feedback, and communicate organisational change effectively.",
  },

  // ── C2: Executive Professional (Lessons 22–28) ───────────────────────
  {
    id: "pro-lesson-22-strategic-writing",
    objectiveId: "pro-obj-22",
    title: "Strategic Business Writing",
    level: "C2",
    skill: "writing",
    sequence: 220,
    mission: "Draft board-level documents, strategic proposals, and policy papers with precision and authority.",
    category: "Executive Communication",
    description: "Write executive briefs, strategic plans, policy documents, and white papers that shape organisational decisions.",
  },
  {
    id: "pro-lesson-23-executive-presentations",
    objectiveId: "pro-obj-23",
    title: "Executive Presentations",
    level: "C2",
    skill: "speaking",
    sequence: 230,
    mission: "Deliver boardroom presentations that drive strategic decisions with data, narrative, and confident delivery.",
    category: "Executive Communication",
    description: "Master the art of presenting to C-suite audiences, using data visualisation, executive storytelling, and handling tough questions.",
  },
  {
    id: "pro-lesson-24-crisis-communication",
    objectiveId: "pro-obj-24",
    title: "Crisis Communication",
    level: "C2",
    skill: "speaking",
    sequence: 240,
    mission: "Manage organisational crisis messaging with transparency, speed, and stakeholder trust.",
    category: "Strategic Communication",
    description: "Practise drafting crisis statements, media holding statements, internal communications during incidents, and post-crisis reviews.",
  },
  {
    id: "pro-lesson-25-change-management",
    objectiveId: "pro-obj-25",
    title: "Change Management Communication",
    level: "C2",
    skill: "speaking",
    sequence: 250,
    mission: "Communicate organisational changes, restructuring, and transformation initiatives with clarity and empathy.",
    category: "Strategic Communication",
    description: "Learn to frame change positively, address resistance, communicate restructuring, and maintain morale during transitions.",
  },
  {
    id: "pro-lesson-26-ma-language",
    objectiveId: "pro-obj-26",
    title: "Mergers and Acquisitions Language",
    level: "C2",
    skill: "reading",
    sequence: 260,
    mission: "Understand and produce M&A documentation including due diligence reports and integration plans.",
    category: "Specialist Communication",
    description: "Master M&A vocabulary, understand term sheets, due diligence checklists, and post-merger integration communications.",
  },
  {
    id: "pro-lesson-27-corporate-governance",
    objectiveId: "pro-obj-27",
    title: "Corporate Governance Communication",
    level: "C2",
    skill: "writing",
    sequence: 270,
    mission: "Draft board minutes, governance reports, and compliance documentation with legal precision.",
    category: "Executive Communication",
    description: "Practise writing board agendas, minutes, compliance reports, and regulatory filings with appropriate formal register.",
  },
  {
    id: "pro-lesson-28-thought-leadership",
    objectiveId: "pro-obj-28",
    title: "Thought Leadership and Industry Voice",
    level: "C2",
    skill: "writing",
    sequence: 280,
    mission: "Establish professional authority through articles, keynotes, and industry commentary.",
    category: "Executive Communication",
    description: "Write opinion articles, keynote speeches, industry analysis, and professional commentary that positions you as a thought leader.",
  },
];

export const PROFESSIONAL_LEVELS: CEFRLevel[] = ["B1", "B2", "C1", "C2"];

export function professionalLessonsByLevel(level: CEFRLevel): ProfessionalLesson[] {
  return PROFESSIONAL_CURRICULUM.filter((l) => l.level === level);
}

export function professionalLessonById(id: string): ProfessionalLesson | undefined {
  return PROFESSIONAL_CURRICULUM.find((l) => l.id === id);
}

export const PROFESSIONAL_ADMIN_UNLOCK_ALL = true;
