/**
 * Professional English library — domains → tracks → teachable curriculum units.
 * Every entry must carry real objectives, domain terminology and authentic tasks;
 * generic re-labelled general English is rejected by design.
 */

export interface ProfessionalTrackSpec {
  id: string;
  label: string;
  objectives: string[];
  vocabulary: string[];
  tasks: string[];
}

export interface ProfessionalDomainSpec {
  id: string;
  label: string;
  blurb: string;
  tracks: ProfessionalTrackSpec[];
}

const t = (id: string, label: string, objectives: string[], vocabulary: string[], tasks: string[]): ProfessionalTrackSpec => ({ id, label, objectives, vocabulary, tasks });
const d = (id: string, label: string, blurb: string, ...tracks: ProfessionalTrackSpec[]): ProfessionalDomainSpec => ({ id, label, blurb, tracks });

const MEETINGS = (focus: string) => t("meetings", "Meetings", [`Chair and contribute to ${focus} meetings with clear turns`, "Disagree diplomatically and build on others' points", "Summarise decisions and confirm action items"], ["agenda", "action item", "minutes", "to table a topic", "consensus", "follow up"], ["Write a meeting agenda for a delayed project", "Turn a rambling discussion summary into crisp minutes", "Roleplay: push back on an unrealistic deadline"]);
const EMAILS = (focus: string) => t("emails", "Professional emails", [`Structure ${focus} emails with purpose-first openings`, "Choose register: formal request vs quick colleague update", "Deliver bad news in writing without sounding cold"], ["subject line", "follow-up", "attach", "at your earliest convenience", "apologise for the inconvenience", "loop in"], ["Rewrite a blunt refusal into a courteous decline", "Draft a follow-up chasing a silent client after one week", "Compose an escalation email copying senior management"]);

export const PROFESSIONAL_LIBRARY: ProfessionalDomainSpec[] = [
  d("general-business", "General Business", "Cross-industry corporate English.", MEETINGS("team"), EMAILS("business"), t("negotiation", "Negotiation basics", ["Anchor offers and trade concessions politely", "Use conditional language to keep deals alive", "Close by confirming terms precisely"], ["counter-offer", "compromise", "terms", "bottom line", "win-win", "concession"], ["Roleplay negotiating a supplier discount", "Draft deal-confirmation minutes"])),
  d("sales", "Sales", "Persuasion across the whole sales cycle.", t("prospecting", "Prospecting & discovery calls", ["Open cold calls without triggering rejection reflexes", "Run discovery questions that surface pain points", "Qualify leads with budget-authority-need-timeline"], ["cold call", "pain point", "qualify", "decision-maker", "value proposition", "pipeline"], ["Script and record a 60-second cold opener", "Rewrite a feature dump into benefit language"]), t("objections", "Objection handling & closing", ["Acknowledge objections before answering them", "Use feel-felt-found framing under pressure", "Ask closing questions that feel like next steps"], ["objection", "close", "trial period", "upsell", "commitment", "follow-through"], ["Handle 'too expensive' three ways", "Write a post-demo recap email that asks for the close"])),
  d("marketing", "Marketing", "Positioning, campaigns and brand voice.", t("campaigns", "Campaign planning", ["Present campaign concepts with rationale", "Brief designers and copywriters precisely", "Report results against KPIs honestly"], ["brief", "KPI", "target audience", "rollout", "engagement rate", "deadline-driven"], ["Pitch a seasonal campaign in five slides of speaker notes", "Write a creative brief for a product launch"]), t("content-social", "Content & social media", ["Adapt one story across platforms and tones", "Write captions that drive action without clickbait", "Respond publicly to criticism gracefully"], ["caption", "call to action", "reach", "thread", "user-generated", "algorithm-friendly"], ["Turn a case study into a LinkedIn post + X thread", "Draft a public apology reply to viral criticism"])),
  d("digital-marketing", "Digital Marketing", "Performance channels and analytics talk.", t("seo-sem", "SEO & paid search", ["Explain technical SEO issues to non-specialists", "Discuss bids, impressions and conversion math", "Write ad copy within character limits"], ["organic traffic", "backlink", "impressions", "cost per click", "conversion rate", "keyword intent"], ["Present a monthly search report to management", "Write five headline variants for an A/B test"])),
  d("business-development", "Business Development", "Partnerships and pipeline growth.", t("partnerships", "Partnership development", ["Research and open conversations with target partners", "Propose mutual value without over-promising", "Structure pilot agreements in plain English"], ["strategic partner", "mutually beneficial", "pilot", "revenue share", "stakeholder", "synergy"], ["Write a first-contact email to a dream partner", "Roleplay a partnership discovery call"])),
  d("customer-service", "Customer Service", "Service recovery at professional standard.", t("support-complaints", "Complaint handling", ["De-escalate angry customers in writing and speech", "Apologise without admitting unbounded liability", "Offer solutions with realistic timelines"], ["refund policy", "escalate", "goodwill gesture", "root cause", "resolution time", "sincere apologies"], ["Reply to a threatening one-star review", "Roleplay a phone refund dispute reaching compromise"]), t("live-chat", "Live chat excellence", ["Balance warmth and brevity in chat", "Manage several threads without losing context", "Signpost help-centre resources clearly"], ["canned response", "wait time", "chat transcript", "handover", "first contact resolution", "CSAT"], ["Rewrite robotic canned replies into human ones", "Handle two simultaneous chat complaints"])),
  d("retail", "Retail", "Store-floor to merchandising communication.", t("floor-service", "Customer interactions on the floor", ["Greet, probe needs and recommend products naturally", "Handle exchanges within policy kindly", "Give product-knowledge answers you can defend"], ["in stock", "exchange", "receipt", "warranty", "fitting room", "best-seller"], ["Roleplay recommending between three products", "Write a notice explaining a temporary shortage"])),
  d("ecommerce", "E-commerce", "Online retail operations and copy.", t("product-listings", "Product listings & descriptions", ["Write scannable descriptions that answer buying questions", "Handle shipping/delivery queries across time zones", "Report marketplace metrics accurately"], ["SKU", "cart abandonment", "fulfilment", "return window", "listing optimisation", "dispatch"], ["Rewrite a confusing product description", "Draft a delivery-delay notification that retains trust"])),
  d("finance", "Finance", "Corporate finance communication.", t("reporting", "Financial reporting language", ["Describe trends with precise verbs (surge, erode, plateau)", "Present variance analysis: actual vs forecast", "Write executive summaries of dense reports"], ["variance", "forecast", "quarter-on-quarter", "margin pressure", "liquidity", "write-off"], ["Narrate a revenue chart for a board pack", "Summarise an annual report page in five sentences"])),
  d("accounting", "Accounting", "Books, audit and compliance talk.", t("client-advisory", "Client advisory", ["Explain tax deadlines and obligations simply", "Chase missing documents without friction", "Flag discrepancies tactfully"], ["fiscal year", "reconciliation", "accrual", "audit trail", "deductible", "filing deadline"], ["Email a client chasing overdue receipts", "Explain a VAT change to a non-financial client"])),
  d("banking", "Banking", "Retail and relationship banking.", t("relationship", "Relationship banking", ["Walk clients through products and eligibility", "Discuss risk appetite responsibly", "Handle declined applications with care"], ["interest rate", "overdraft", "credit score", "collateral", "mortgage term", "affordability check"], ["Roleplay explaining a mortgage decision", "Write a letter confirming account changes"])),
  d("investment", "Investment", "Markets narrative and pitch language.", t("pitch", "Investment pitching", ["Tell a company story through numbers", "Answer hostile analyst questions calmly", "Use hedged forecasts credibly"], ["due diligence", "valuation", "upside", "exposure", "hedge", "thesis"], ["Deliver a two-minute investment thesis aloud", "Defend a valuation against sceptical questioning"])),
  d("insurance", "Insurance", "Policies, claims and clarity.", t("claims", "Claims handling", ["Guide claimants through documentation steps", "Communicate partial approvals and exclusions", "Set expectations for assessment timelines"], ["premium", "policyholder", "exclusion clause", "assessor", "settlement", "underwriting"], ["Write a claim-approval letter with conditions", "Roleplay explaining why a claim falls under exclusion"])),
  d("human-resources", "Human Resources", "People operations end to end.", t("employee-relations", "Employee relations", ["Hold sensitive conversations with neutrality", "Document concerns factually and fairly", "Communicate policy changes empathetically"], ["grievance", "disciplinary", "confidential", "mediation", "notice period", "wellbeing"], ["Prepare notes for a difficult feedback meeting", "Announce a benefits change company-wide"]), EMAILS("HR")),
  d("recruitment", "Recruitment", "Sourcing to placement.", t("interviewing", "Interviewing candidates", ["Ask structured behavioural questions", "Sell the role honestly while probing fit", "Give rejection feedback that preserves dignity"], ["shortlist", "competency-based", "notice period", "offer letter", "probation", "counter-offer"], ["Conduct a mock competency interview", "Write a warm-but-clear rejection email"])),
  d("training", "Training & Education", "Teaching and L&D contexts.", t("facilitation", "Facilitating learning", ["Give instructions learners can follow first time", "Check understanding without embarrassment", "Give feedback that motivates improvement"], ["learning objective", "workshop", "handout", "pace yourself", "check understanding", "takeaway"], ["Deliver a three-minute micro-teach aloud", "Rewrite vague instructions into numbered steps"])),
  d("healthcare-admin", "Healthcare Administration", "Clinical settings, non-clinical talk.", t("patient-liaison", "Patient liaison", ["Confirm appointments and preparation steps clearly", "Handle anxious relatives with calm reassurance", "Escalate clinical questions appropriately"], ["referral", "discharge summary", "consent form", "waiting list", "triage", "confidentiality"], ["Call a patient with pre-surgery instructions", "Write a complaint response about waiting times"])),
  d("hospitality", "Hospitality", "Hotels and guest experience.", t("guest-relations", "Guest relations", ["Welcome and check in guests warmly and efficiently", "Recover service failures on the spot", "Upsell experiences without pressure"], ["reservation", "complimentary upgrade", "housekeeping", "late checkout", "amenities", "fully booked"], ["Roleplay resolving an overbooking situation", "Write a pre-arrival welcome email with upsell"])),
  d("tourism", "Tourism", "Tours and destination services.", t("guiding", "Tour guiding commentary", ["Deliver engaging facts with storytelling rhythm", "Adjust language level to mixed-nationality groups", "Manage safety instructions unmistakably"], ["itinerary", "meeting point", "landmark", "group discount", "photo opportunity", "regroup"], ["Record a 90-second introduction to a landmark", "Rewrite a dry historical note into lively commentary"])),
  d("travel", "Travel", "Agencies and travel support.", t("bookings-support", "Bookings & disruption support", ["Rebook journeys under pressure while staying kind", "Explain fare rules and refunds precisely", "Advise documents and visa requirements carefully"], ["itinerary change", "layover", "non-refundable", "travel insurance", "connection time", "voucher"], ["Call a stranded traveller with bad news and options", "Write a schedule-change email with rebooking links"])),
  d("aviation", "Aviation", "Airline and airport operations.", t("cabin-ops", "Cabin & ground operations English", ["Make clear public announcements under stress", "Handle boarding irregularities firmly but kindly", "Coordinate with crew using standard phrasing"], ["gate closure", "standby", "boarding pass", "final call", "turbulence", "diversion"], ["Deliver a delay announcement twice: calm and revised", "Roleplay denying oversized luggage politely"])),
  d("real-estate", "Real Estate", "Property sales and management.", t("viewings-negotiation", "Viewings & negotiation", ["Present properties highlighting buyer-relevant strengths", "Discuss offers and counter-offers transparently", "Manage chains and timelines proactively"], ["asking price", "survey", "chain", "completion date", "gazumping", "vendor"], ["Script a viewing tour emphasising light and space", "Email both sides a counter-offer update"])),
  d("construction", "Construction", "Sites and stakeholder coordination.", t("site-coordination", "Site coordination", ["Run toolbox talks with unmistakable safety language", "Report delays and variations early in writing", "Chase subcontractors without damaging relationships"], ["variation order", "snagging", "method statement", "site induction", "deliveries", "defects"], ["Deliver a two-minute safety briefing aloud", "Write a delay-notification email preserving the contract position"])),
  d("engineering", "Engineering", "Technical project communication.", t("technical-reviews", "Design & technical reviews", ["Present trade-offs between options quantitatively", "Document assumptions and risks explicitly", "Take minutes that capture decisions, not chatter"], ["specification", "tolerance", "feasibility", "trade-off", "prototype", "sign-off"], ["Present two design options with a recommendation", "Write a risk-register entry a manager can act on"])),
  d("information-technology", "Information Technology", "IT support and infrastructure.", t("support-desk", "Helpdesk communication", ["Translate technical faults into user-friendly steps", "Set honest resolution expectations", "Follow up until confirmed fixed"], ["ticket", "workaround", "outage", "escalation path", "remote session", "patch"], ["Rewrite a jargon-filled outage notice for staff", "Roleplay guiding a panicked user through a fix"]), MEETINGS("incident")),
  d("software-development", "Software Development", "Agile teams and code review talk.", t("agile-collaboration", "Agile ceremonies & reviews", ["Give crisp stand-up updates: done, next, blocked", "Review pull requests with critique aimed at code", "Estimate work and negotiate scope"], ["sprint", "backlog", "pull request", "merge conflict", "tech debt", "definition of done"], ["Record your perfect 45-second stand-up", "Write a kind but thorough code-review comment"]), t("documentation", "Technical documentation", ["Write READMEs strangers can follow", "Document APIs with consistent examples", "Explain trade-offs in ADRs (architecture decision records)"], ["endpoint", "payload", "authentication", "deprecation", "migration guide", "breaking change"], ["Write a getting-started section for an API", "Draft a deprecation notice with migration path"])),
  d("cybersecurity", "Cybersecurity", "Security awareness and incident talk.", t("incident-reporting", "Incident reporting", ["Report suspected incidents immediately and precisely", "Brief executives without panic or jargon", "Write lessons-learned summaries blame-free"], ["phishing", "breach containment", "false positive", "attack surface", "mitigation", "post-mortem"], ["Draft an all-staff alert about active phishing", "Roleplay briefing leadership during an incident"])),
  d("data-analytics", "Data & Analytics", "Insight storytelling.", t("insight-presentation", "Presenting insights", ["Lead with the finding, not the method", "Quantify uncertainty honestly", "Turn dashboards into decisions"], ["correlation not causation", "baseline", "segment", "statistically significant", "sample size", "outlier"], ["Present one chart's insight in 60 seconds", "Rewrite a hedgy conclusion into a confident recommendation"])),
  d("artificial-intelligence", "AI & Machine Learning", "Applied AI workplace English.", t("ai-adoption", "AI adoption projects", ["Explain model capabilities and limits to non-experts", "Discuss data privacy and bias considerations", "Scope pilots with measurable success criteria"], ["model accuracy", "training data", "bias", "guardrails", "human-in-the-loop", "proof of concept"], ["Pitch a small AI pilot to sceptical managers", "Write usage guidelines for a team assistant tool"])),
  d("telecommunications", "Telecommunications", "Network industry communication.", t("b2b-sales", "B2B telecom sales", ["Diagnose connectivity needs before quoting", "Compare plans in customer language", "Coordinate installation scheduling smoothly"], ["bandwidth", "SLA", "installation slot", "line rental", "coverage check", "contract renewal"], ["Roleplay a needs-analysis call for office internet", "Write a renewal offer summarising savings"])),
  d("manufacturing", "Manufacturing", "Production floor and quality.", t("production-meetings", "Production meetings", ["Report output and downtime numbers accurately", "Discuss quality deviations constructively", "Align shifts during handover briefings"], ["throughput", "downtime", "scrap rate", "shift handover", "preventive maintenance", "tolerance"], ["Deliver a shift-handover briefing aloud", "Summarise yesterday's production KPIs in speech"])),
  d("logistics", "Logistics", "Freight and distribution.", t("shipment-tracking", "Shipment tracking & exceptions", ["Update customers on delays before they chase", "Coordinate reroutes with carriers quickly", "File exception reports that prevent repeats"], ["waybill", "customs clearance", "detention", "reroute", "delivery window", "proof of delivery"], ["Proactively email a delay with new ETA and options", "Call a carrier to expedite a critical shipment"])),
  d("supply-chain", "Supply Chain", "Planning and supplier networks.", t("supplier-management", "Supplier management", ["Run performance reviews backed by data", "Negotiate lead times and minimum orders", "Communicate shortages without blame"], ["lead time", "minimum order quantity", "capacity", "backup supplier", "demand forecast", "stockout"], ["Present a quarterly supplier scorecard", "Negotiate a shorter lead time in roleplay"])),
  d("procurement", "Procurement", "Buying professionally.", t("tenders", "Tenders & RFQs", ["Issue clarifications that are legally safe", "Compare bids on weighted criteria transparently", "Notify unsuccessful bidders respectfully"], ["request for quotation", "specification", "bid submission", "evaluation criteria", "framework agreement", "clarification"], ["Draft a clarification email to all bidders", "Write a regret letter to an unsuccessful supplier"])),
  d("legal-business", "Legal Business English", "Commercial law contexts.", t("client-communication", "Client communication", ["Explain legal positions without false certainty", "Chase outstanding information formally", "Confirm advice in writing precisely"], ["letter of engagement", "liability", "without prejudice", "breach of contract", "settlement terms", "jurisdiction"], ["Convert a legal opinion into a client summary", "Write a formal letter before action"])),
  d("government", "Government", "Public administration English.", t("public-communication", "Public communication", ["Draft notices citizens actually understand", "Handle media questions within messaging discipline", "Record decisions with procedural correctness"], ["statutory", "consultation period", "constituent", "press release", "on record", "implementation date"], ["Rewrite a regulation summary in plain English", "Roleplay answering a journalist's tough question"])),
  d("public-sector", "Public Sector", "Services and civic communication.", t("case-work", "Case work communication", ["Explain eligibility rules compassionately", "Request evidence with exact checklists", "Appeal decisions in writing correctly"], ["eligibility criteria", "application status", "supporting documents", "deadline extension", "appeal process", "acknowledgement"], ["Write an evidence-request letter", "Roleplay delivering an unfunded-application decision"])),
  d("project-management", "Project Management", "Delivery across methodologies.", t("status-governance", "Status & governance", ["Report RAG status with causes and asks", "Run risk reviews that produce owners and dates", "Steer committees toward decisions"], ["milestone", "critical path", "RAID log", "steering committee", "change request", "dependency"], ["Deliver an amber-status update with recovery plan", "Write a change-request summary for approval"])),
  d("product-management", "Product Management", "Discovery to launch.", t("roadmap-communication", "Roadmap communication", ["Say no to stakeholders while keeping trust", "Frame priorities by customer outcome", "Announce launches and deprecations cleanly"], ["roadmap", "prioritisation framework", "user story", "acceptance criteria", "beta", "sunset"], ["Roleplay declining a pet feature diplomatically", "Write launch-notes copy for two audiences"]), t("user-research", "User research communication", ["Run discovery interviews that surface real needs", "Present research findings to product teams concisely", "Translate qualitative data into actionable requirements"], ["persona", "pain point", "journey map", "usability test", "metric", "hypothesis"], ["Conduct a five-minute discovery interview aloud", "Write a research findings summary for an engineering standup"])),
  d("operations", "Operations", "Running the engine room.", t("process-improvement", "Process improvement", ["Describe current-state processes step by step", "Facilitate improvement workshops neutrally", "Standardise procedures into usable SOPs"], ["SOP", "bottleneck", "handoff", "cycle time", "quality control", "rollback plan"], ["Map a broken process in writing for review", "Facilitate a five-minute problem-solving huddle"])),
  d("consulting", "Consulting", "Advisory communication.", t("client-delivery", "Client delivery", ["Structure findings as situation-complication-resolution", "Challenge client assumptions respectfully", "Hand over recommendations that stick"], ["deliverable", "workstream", "steering update", "hypothesis-driven", "buy-in", "next steps owner"], ["Present findings in a five-slide verbal walk-through", "Write an executive summary a CEO reads in 90 seconds"])),
  d("entrepreneurship", "Entrepreneurship", "Founder communication.", t("investor-pitch", "Investor pitching", ["Hook investors in the first thirty seconds", "Handle curveball questions without defensiveness", "Follow up without nagging"], ["runway", "burn rate", "traction", "term sheet", "equity stake", "exit strategy"], ["Deliver a 90-second elevator pitch aloud", "Email an investor a crisp monthly update"])),
  d("leadership", "Leadership", "Managing people upward and down.", t("feedback-difficult", "Difficult feedback & motivation", ["Praise specifically and correct privately", "Navigate defensive reactions in the moment", "Inspire without empty slogans"], ["constructive feedback", "accountability", "recognition", "one-to-one", "expectations", "morale"], ["Roleplay correcting repeated lateness kindly", "Write recognition that names the behaviour and impact"])),
  d("executive-communication", "Executive Communication", "Boardroom-grade expression.", t("boardroom", "Boardroom presence", ["Compress complexity into three key messages", "Answer the question behind the question", "Command silence with deliberate pacing"], ["headline message", "risk appetite", "prudent", "material impact", "recommendation", "for approval"], ["Deliver a one-minute board opener from memory", "Reduce a ten-page report to five spoken sentences"])),
  d("international-business", "International Business", "Cross-border operations.", t("cross-cultural", "Cross-cultural effectiveness", ["Adapt directness across cultures deliberately", "Build rapport remotely across time zones", "Avoid idioms that confuse non-native partners"], ["high-context / low-context", "time-zone overlap", "courtesy copy culture", "localisation", "etiquette", "relationship-first"], ["Rewrite a very-direct email for a relationship-first market", "Plan a fair global meeting rotation aloud"])),
  d("corporate-communications", "Corporate Communications", "Internal and external voice.", t("crisis-comms", "Crisis communications", ["Acknowledge fast, speculate never", "Keep holding statements ready and current", "Align spokespeople on one line"], ["holding statement", "media enquiry", "spokesperson", "fact-checked", "on-message", "update at noon"], ["Draft a holding statement within ten minutes", "Roleplay a hostile interview question bridge"])),
  d("media", "Media & Journalism", "Newsroom and production talk.", t("interviewing-editing", "Interviewing & editing", ["Ask questions that reopen closed answers", "Cut copy without losing meaning", "Fact-check under deadline pressure"], ["angle", "soundbite", "off the record", "cut-down", "caption", "embargoed"], ["Re-interview to extract a missing quote", "Edit a 300-word story to 180 without loss"])),
  d("pharmaceutical", "Pharmaceutical", "Regulated science communication.", t("medical-affairs", "Medical affairs communication", ["Present trial data with compliant precision", "Handle off-label questions correctly", "Write clear adverse-event narratives"], ["efficacy", "adverse event", "protocol", "regulatory submission", "off-label", "peer-reviewed"], ["Summarise a trial endpoint verbally", "Write an adverse-event report narrative"])),
  d("automotive", "Automotive", "Vehicle industry communication.", t("dealer-ops", "Dealer & aftersales", ["Explain technical faults and costs transparently", "Handle warranty disputes within policy", "Coordinate test drives and handovers"], ["service interval", "recall notice", "part availability", "warranty claim", "trade-in valuation", "handover"], ["Call a customer about recall work scheduling", "Write a repair-cost explanation before authorisation"])),
  d("energy", "Energy", "Power sector communication.", t("projects-regulatory", "Projects & regulatory affairs", ["Report project milestones to regulators precisely", "Discuss outages and restoration credibly", "Engage communities about impacts honestly"], ["grid connection", "commissioning", "outage window", "stakeholder consultation", "emissions targets", "capacity factor"], ["Brief residents about planned works aloud", "Write a regulatory milestone notification"])),
  d("oil-gas", "Oil & Gas", "Upstream and HSE-critical English.", t("safety-briefings", "Safety briefings", ["Deliver toolbox talks with zero ambiguity", "Report near-misses without fear culture", "Confirm permit-to-work conditions verbally"], ["permit to work", "near miss", "isolation", "toolbox talk", "hot work", "muster point"], ["Deliver a permit-to-work briefing aloud", "Write a near-miss report focused on system fixes"])),
  d("architecture", "Architecture", "Design practice communication.", t("client-presentations", "Client presentations", ["Walk clients through drawings verbally", "Justify design decisions against brief and budget", "Capture agreed changes in writing"], ["concept design", "planning permission", "scope creep", "rendering", "site survey", "variation"], ["Present a concept scheme in plain language", "Write a scope-change confirmation email"])),
  d("interior-design", "Interior Design", "Studios and client styling.", t("styling-consultations", "Consultations & sourcing", ["Elicit preferences clients cannot articulate", "Present mood boards with persuasive narrative", "Manage supplier delays with alternatives ready"], ["mood board", "lead time", "sample", "bespoke", "installation day", "snag list"], ["Present a mood board aloud in 90 seconds", "Email a delay notice with two alternative options"])),
  d("agriculture", "Agriculture", "Farming and agri-business.", t("trade-compliance", "Trade & compliance", ["Discuss yields and contracts numerately", "Explain certification requirements clearly", "Coordinate seasonal logistics reliably"], ["harvest window", "yield", "subsidy application", "cold chain", "certification", "spot price"], ["Negotiate a harvest contract in roleplay", "Write a subsidy application cover note"])),
  d("nonprofit", "Nonprofit", "Mission-driven organisations.", t("fundraising", "Fundraising & donors", ["Tell beneficiary stories with dignity", "Report impact to funders transparently", "Ask for donations without guilt-tripping"], ["grant application", "beneficiary", "impact report", "restricted funding", "donor stewardship", "match funding"], ["Deliver a two-minute donor pitch aloud", "Write an impact paragraph for an annual report"])),
  d("professional-services", "Professional Services", "Multi-disciplinary firms.", t("engagement-lifecycle", "Engagement lifecycle", ["Scope engagements to avoid silent creep", "Manage client expectations at every stage", "Close out with documented value delivered"], ["engagement letter", "scope", "billing rates", "key contact", "deliverable sign-off", "lessons learned"], ["Write a scope-confirmation email", "Roleplay renegotiating an expanded brief"]),
  ),
];

/** Domains exposed through the legacy pathways API stay backward compatible. */
export const LIBRARY_DOMAIN_IDS = PROFESSIONAL_LIBRARY.map((domain) => domain.id);

export function findDomain(domainId: string): ProfessionalDomainSpec | null {
  return PROFESSIONAL_LIBRARY.find((entry) => entry.id === domainId.toLowerCase().trim()) ?? null;
}

export function findTrack(domainId: string, trackId: string): ProfessionalTrackSpec | null {
  return findDomain(domainId)?.tracks.find((track) => track.id === trackId.toLowerCase().trim()) ?? null;
}

/* ------------------------------------------------------------------ */
/* Custom business field synthesis                                     */
/* ------------------------------------------------------------------ */

const FIELD_HINTS: Array<{ keywords: string[]; domainId: string }> = [
  { keywords: ["shop", "store", "boutique", "salon", "barber", "bakery", "cafe", "restaurant", "food"], domainId: "retail" },
  { keywords: ["software", "app", "code", "developer", "saas", "startup tech", "web"], domainId: "software-development" },
  { keywords: ["clinic", "dental", "pharmacy", "physio", "care home", "hospital", "medical"], domainId: "healthcare-admin" },
  { keywords: ["hotel", "guest house", "bnb", "airbnb", "hostel"], domainId: "hospitality" },
  { keywords: ["school", "academy", "tuition", "course", "teaching", "trainer"], domainId: "training" },
  { keywords: ["freight", "haulage", "courier", "shipping", "warehouse"], domainId: "logistics" },
  { keywords: ["estate", "property", "lettings", "rental", "landlord"], domainId: "real-estate" },
  { keywords: ["agency", "ads", "social media", "influencer", "branding"], domainId: "marketing" },
  { keywords: ["accountant", "bookkeeping", "tax", "payroll"], domainId: "accounting" },
  { keywords: ["charity", "ngo", "volunteer", "foundation"], domainId: "nonprofit" },
  { keywords: ["farm", "grow", "organic produce", "greenhouse"], domainId: "agriculture" },
  { keywords: ["travel agency", "tour", "trips", "excursions"], domainId: "tourism" },
];

export interface CustomFieldProfile {
  field: string;
  role?: string;
  goals?: string[];
  baseDomainId: string;
}

/**
 * Builds a credible pathway for an arbitrary business field the learner typed in.
 * Anchors to the closest library domain so terminology stays authentic, then injects
 * the learner's own field wording into every unit title and task.
 */
export function buildCustomFieldPathway(input: { field: string; role?: string; goals?: string[] }): { profile: CustomFieldProfile; domain: ProfessionalDomainSpec } {
  const field = input.field.trim();
  const lower = field.toLowerCase();
  const matched = FIELD_HINTS.find((hint) => hint.keywords.some((keyword) => lower.includes(keyword)));
  const base = (matched && findDomain(matched.domainId)) || PROFESSIONAL_LIBRARY[0];
  const roleSuffix = input.role ? ` (${input.role.trim()})` : "";
  const domain: ProfessionalDomainSpec = {
    id: `custom-${base.id}`,
    label: `${field}${roleSuffix} — professional English`,
    blurb: `Built around ${base.label} communication patterns, adapted to your field "${field}".`,
    tracks: base.tracks.map((track) => ({
      id: track.id,
      label: `${track.label} · ${field}`,
      objectives: [...track.objectives, ...(input.goals ?? []).slice(0, 2).map((goal) => `Personal goal: ${goal}`)],
      vocabulary: track.vocabulary,
      tasks: track.tasks.map((task) => task.replace(/your (colleague|manager|client|team)/gi, `your ${field} contacts`).replace(/the (product|project|service)/gi, `your ${field} work`)),
    })),
  };
  return { profile: { field, role: input.role, goals: input.goals, baseDomainId: base.id }, domain };
}


// Ensure every domain has at least two tracks for meaningful navigation.
const _ENRICH_WORKPLACE: ProfessionalTrackSpec = {
  id: "workplace-communication",
  label: "Workplace communication",
  objectives: ["Compose professional emails with clear purpose and appropriate register", "Participate in workplace meetings with confident turns and summaries", "Handle everyday workplace conversations across cultures"],
  vocabulary: ["agenda", "update", "follow-up", "clarify", "confirm", "appreciate"],
  tasks: ["Write a status-update email to your manager", "Roleplay receiving feedback and responding professionally", "Draft a meeting summary with action items"]
};
for (const domain of PROFESSIONAL_LIBRARY) {
  if (domain.tracks.length < 2) domain.tracks.push({ ..._ENRICH_WORKPLACE, id: "workplace-communication-" });
}
