import type { RoleplayScenario } from "./roleplay";

/**
 * Band-expansion scenarios (Task 26-a): raises every CEFR band to at least six
 * role-play situations. Calibration: Pre-A1 = single words + memorised chunks;
 * A1 = simple connected sentences; A2 = everyday survival exchanges; B1 =
 * opinions and past/future narratives; B2 = negotiation, hedging, workplace
 * detail; C1 = persuasion, nuance, diplomatic pushback; C2 = idiom, register
 * switching, high-stakes leadership. UK English throughout.
 */
export const ROLEPLAY_SCENARIOS_EXTRA: RoleplayScenario[] = [
  // ---------------------------------------------------------------- Pre-A1 (+5)
  {
    id: "rp-pa1-market",
    title: "Buy fruit at a market",
    level: "Pre-A1",
    situation: "You are at a street market. You want two apples and one banana. Say what you want and ask the price.",
    partnerRole: "market trader",
    opener: "Hello! Lovely apples today. What would you like?",
    fallbacks: [
      "Yes! How many apples?",
      "Two apples, and one banana. Here you are.",
      "That is one pound fifty, please.",
      "Thank you! Goodbye! See you next week!",
    ],
    targetPhrases: ["Two apples, please", "How much?", "Thank you"],
  },
  {
    id: "rp-pa1-hello",
    title: "Meet a new neighbour",
    level: "Pre-A1",
    situation: "A new neighbour says hello in the lift. Say your name and where you are from.",
    partnerRole: "neighbour",
    opener: "Oh, hello! Are you new here? I am in flat 4.",
    fallbacks: [
      "Nice to meet you! What is your name?",
      "A lovely name. Where are you from?",
      "Very nice! I am from Poland. Welcome!",
      "See you later! Goodbye!",
    ],
    targetPhrases: ["My name is", "I am from", "Nice to meet you"],
  },
  {
    id: "rp-pa1-bus",
    title: "Buy a bus ticket",
    level: "Pre-A1",
    situation: "You are on a bus. Buy one ticket to the station. Say please and thank you.",
    partnerRole: "bus driver",
    opener: "Good morning! Where are you going today?",
    fallbacks: [
      "The station? Yes, no problem. One ticket?",
      "That is two pounds, please.",
      "Thank you. Here is your ticket.",
      "Take a seat. Ten minutes, and we are there.",
    ],
    targetPhrases: ["One ticket, please", "To the station, please", "Thank you"],
  },
  {
    id: "rp-pa1-where",
    title: "Find milk at the supermarket",
    level: "Pre-A1",
    situation: "You cannot find the milk in the supermarket. Ask a worker where it is.",
    partnerRole: "supermarket worker",
    opener: "Hello! Do you need some help?",
    fallbacks: [
      "The milk? Yes, no problem.",
      "Milk is at the back, near the eggs.",
      "Look for the blue bottles. Blue is milk.",
      "You are welcome! Have a good day!",
    ],
    targetPhrases: ["Excuse me", "Where is the milk?", "Thank you"],
  },
  {
    id: "rp-pa1-class",
    title: "Ask the teacher to repeat",
    level: "Pre-A1",
    situation: "You are in your English class. You do not understand the teacher. Ask her to repeat and to speak slowly.",
    partnerRole: "teacher",
    opener: "Right, everyone! Open your books to page ten, please.",
    fallbacks: [
      "Oh, sorry! Of course I can repeat.",
      "Page ten. Ten. Here — number ten.",
      "Too fast? No problem. I speak slowly: open… your… books… page… ten.",
      "Well done for asking! Now you write, please.",
    ],
    targetPhrases: ["Sorry?", "Again, please", "I don't understand"],
  },

  // ---------------------------------------------------------------------- A1 (+6)
  {
    id: "rp-a1-shop",
    title: "Buy a T-shirt",
    level: "A1",
    situation: "You are in a clothes shop. You want a blue T-shirt, medium. Ask the price, pay, and thank the assistant.",
    partnerRole: "shop assistant",
    opener: "Hello! Can I help you with anything?",
    fallbacks: [
      "The T-shirts are over here. What colour would you like?",
      "Blue — a good choice. What size do you need?",
      "Medium. Here you are. Would you like to try it on? The changing rooms are over there.",
      "How is it? Yes, that suits you. It is twelve pounds ninety-nine.",
      "Card is fine, no problem. Would you like a bag?",
      "Here is your receipt. Thank you very much — see you again soon!",
    ],
    targetPhrases: ["Have you got", "Can I try it on, please?", "How much is it?"],
  },
  {
    id: "rp-a1-directions",
    title: "Ask the way to the station",
    level: "A1",
    situation: "You are lost in town. Stop a friendly passer-by and ask how to get to the train station. Then thank them.",
    partnerRole: "passer-by",
    opener: "Oh hello — you look a bit lost. Can I help?",
    fallbacks: [
      "The train station? Yes, I know it. Do you want to walk or take the bus?",
      "On foot it is easy. Go straight on, then turn left at the lights.",
      "Then you will see a big red building. The station is just behind it.",
      "It takes about ten minutes. Are you OK with directions?",
      "No problem at all! Enjoy your day, and welcome to York!",
    ],
    targetPhrases: ["Excuse me, how do I get to", "Turn left at", "Thank you very much"],
  },
  {
    id: "rp-a1-taxi",
    title: "Take a taxi to the airport",
    level: "A1",
    situation: "Your taxi to the airport has arrived. Tell the driver where you are going and ask how long it takes and what it costs.",
    partnerRole: "taxi driver",
    opener: "Evening! You called for a taxi? Hop in.",
    fallbacks: [
      "The airport, lovely. Do you know which terminal?",
      "Terminal two, no problem. Traffic is quiet tonight, so about twenty-five minutes.",
      "The fare is a fixed thirty pounds to the airport. Shall I put the heating on?",
      "Here we are, terminal two. Mind the kerb when you get out.",
      "That is thirty pounds, please. Have a good flight!",
    ],
    targetPhrases: ["To the airport, please", "How long does it take?", "How much is it?"],
  },
  {
    id: "rp-a1-family",
    title: "Talk about your family",
    level: "A1",
    situation: "It is your first week at language school. Your new classmate asks about your family. Tell them about two or three people.",
    partnerRole: "classmate",
    opener: "Hi! I'm Marco, from Italy. Is this your first week here too?",
    fallbacks: [
      "That's nice! Tell me — have you got any brothers or sisters?",
      "One sister, and she is a student. And what do your parents do?",
      "Your mother is a nurse? That is a hard job. Do you like this city?",
      "Me too! My flat is small, but I like it. Do you want to get a coffee after class?",
    ],
    targetPhrases: ["I have got", "I live with", "Do you want to"],
  },
  {
    id: "rp-a1-library",
    title: "Join the library",
    level: "A1",
    situation: "You want to borrow easy English books. At the library desk, ask how to get a card and where the books are.",
    partnerRole: "librarian",
    opener: "Good afternoon! Welcome to Central Library. What can I do for you?",
    fallbacks: [
      "A library card, wonderful. Have you got a letter with your name and address on it?",
      "This letter is fine. One moment, please — I make the card for you now.",
      "There we are — your card is ready. You can borrow six books for three weeks.",
      "The English learners' books are on the second floor, next to the computers.",
      "You are welcome. If you need help, just ask at the desk. Enjoy your reading!",
    ],
    targetPhrases: ["I would like to join", "Can I borrow", "Where are the"],
  },
  {
    id: "rp-a1-weekend",
    title: "Make weekend plans",
    level: "A1",
    situation: "It is Friday afternoon at work. Your colleague asks about your weekend. Say your plans and invite them to something.",
    partnerRole: "colleague",
    opener: "Nearly the weekend! Any plans, or just sleeping in?",
    fallbacks: [
      "A picnic in the park sounds lovely. The weather is going to be sunny, they say.",
      "Is your sister coming too? Nice. I have got football on Saturday morning.",
      "On Sunday I usually cook a big lunch and do nothing all afternoon.",
      "Shall we all meet on Saturday? There is a market near the park at ten.",
      "Perfect — ten o'clock at the market gate then. Have a good evening!",
    ],
    targetPhrases: ["I am going to", "Would you like to come?", "Shall we meet"],
  },

  // ---------------------------------------------------------------------- A2 (+4)
  {
    id: "rp-a2-train",
    title: "Buy train tickets",
    level: "A2",
    situation: "You are at a railway station. Buy two return tickets to Manchester for tomorrow, and ask which platform and how long the journey takes.",
    partnerRole: "ticket clerk",
    opener: "Next, please! Where are you travelling to?",
    fallbacks: [
      "Manchester, two returns for tomorrow. Off-peak, or before nine? The early trains cost more.",
      "Off-peak it is — that's forty-two pounds each. The fast train takes two hours ten; the stopping train takes nearly three.",
      "I can put you on the 9.47 from platform 4, or the 11.20 from platform 2. Which suits you?",
      "The 9.47 then. These are your seat reservations — carriage C, table seats facing each other.",
      "Platform 4 is straight up the escalator and to your left. Give yourselves time for the coffee queue — it's chaos on Saturdays.",
      "You're welcome. If you miss it, you can travel on the next off-peak train. Have a good trip!",
    ],
    targetPhrases: ["I'd like two returns to", "Which platform is", "How long does it take?"],
  },
  {
    id: "rp-a2-bank",
    title: "Replace a lost bank card",
    level: "A2",
    situation: "You have lost your bank card and there are no strange payments yet. At the branch, ask to cancel it and get a new one.",
    partnerRole: "bank clerk",
    opener: "Good morning. How can I help you today?",
    fallbacks: [
      "Lost card — right, first things first: when did you last use it, and have you checked your app for anything odd?",
      "Nothing strange, that's good news. I'll cancel that card now so nobody can use it.",
      "Your new card arrives in three to five working days, and the PIN comes separately, for security.",
      "You can still take money out at the counter today — just bring some ID.",
      "All sorted. Is there anything else I can help you with?",
    ],
    targetPhrases: ["I've lost my card", "Could you cancel it, please?", "When will I get the new one?"],
  },
  {
    id: "rp-a2-post",
    title: "Post a parcel abroad",
    level: "A2",
    situation: "You need to send a birthday present to your cousin in Canada. At the post office, ask about the price, how long it takes, and tracking.",
    partnerRole: "post office clerk",
    opener: "Good afternoon! What are we sending today?",
    fallbacks: [
      "Canada, is it? Let's have a look at the parcel — anything fragile or valuable inside?",
      "A jumper — that's fine. Surface mail takes up to two weeks, airmail about five working days.",
      "Airmail is twelve pounds forty. Tracking adds three pounds, and honestly, it's worth it for Canada.",
      "Right — I just need this customs label filled in: what it is and what it's worth.",
      "There you go — sticker on the corner, and keep the receipt with the tracking number.",
      "You're welcome! It should be there well before the birthday.",
    ],
    targetPhrases: ["How much does it cost to send", "How long does it take to arrive?", "Can I track it?"],
  },
  {
    id: "rp-a2-gym",
    title: "Sign up at a gym",
    level: "A2",
    situation: "You want to join a gym near your new flat. Ask about prices, classes for beginners, and the contract.",
    partnerRole: "membership adviser",
    opener: "Hi, welcome in! Thinking about joining us?",
    fallbacks: [
      "Great timing — we've just had new equipment installed. Do you want to train on your own, or mostly classes?",
      "Classes are a good place to start. There's a beginners' circuit on Mondays and a swim session every evening.",
      "The standard membership is thirty-four pounds a month, and there's an off-peak rate at twenty-eight.",
      "It's a rolling monthly contract, so you can cancel any time with a month's notice. No joining fee this month.",
      "Would you like a look round the studio before you decide?",
      "No pressure at all. Take my card and come back when you're ready.",
    ],
    targetPhrases: ["How much is the membership?", "Are there any classes for beginners?", "Can I cancel any time?"],
  },

  // ---------------------------------------------------------------------- B1 (+5)
  {
    id: "rp-b1-flat",
    title: "Call about a flat advert",
    level: "B1",
    situation: "You have seen a one-bedroom flat online. Ring the letting agent to arrange a viewing and ask about bills, transport, and the deposit.",
    partnerRole: "letting agent",
    opener: "Good afternoon, Riverside Lets, Danny speaking. What can I do for you?",
    fallbacks: [
      "Ah yes, the Grosvenor Road flat — it's had a lot of interest, so I'd move quickly if I were you. When were you hoping to view?",
      "Saturday morning works. The flat's on the second floor, unfurnished, and the kitchen was redone last year.",
      "Bills aren't included, I'm afraid — budget around a hundred and forty a month on top. Water's on a meter.",
      "Transport-wise, the tram stop is two minutes away, and there's secure bike storage in the basement.",
      "The deposit is five weeks' rent, held in a protection scheme, and references take about three days once you've applied.",
      "Shall I pencil you in for Saturday at ten, then? I'll text you the details.",
    ],
    targetPhrases: ["I'm calling about", "Are bills included?", "Would it be possible to view"],
  },
  {
    id: "rp-b1-advisor",
    title: "Choose a course with an advisor",
    level: "B1",
    situation: "You want to study next year but cannot decide between two courses. Tell the advisor your goals and ask her opinion.",
    partnerRole: "course advisor",
    opener: "Come in, have a seat. So — you're torn between two courses. Tell me a bit about what you want to do afterwards.",
    fallbacks: [
      "That's a clear goal, actually. The design course is more practical, but the marketing one opens more doors right now.",
      "Let me ask it differently: would you rather build things or persuade people?",
      "In my experience, students on the marketing route find work faster, but the design route ages better if you keep learning.",
      "You could also take the marketing diploma and do evening design workshops — some of our students do both.",
      "Honestly? Your portfolio matters more than the title. Whichever you choose, finish three good projects.",
      "Why don't you sleep on it and come back on Thursday? There's no rush this week.",
    ],
    targetPhrases: ["I'm thinking of", "I'd rather", "What would you recommend?"],
  },
  {
    id: "rp-b1-travel",
    title: "Plan a trip with a travel agent",
    level: "B1",
    situation: "You have ten days of holiday in October and a small budget. The travel agent suggests options — say what you prefer and choose one.",
    partnerRole: "travel agent",
    opener: "Come in, come in. So — ten days, October. Anywhere already on your mind, or shall I tempt you?",
    fallbacks: [
      "Portugal is lovely in October and the flights are cheap then, but it can rain in the north. Spain is more reliable, though busier.",
      "You said you'd rather walk than lie on a beach — in that case, the coastal paths in the Algarve would suit you down to the ground.",
      "Budget-wise, a self-catering apartment comes out about two hundred cheaper than a hotel over ten nights.",
      "Flights on the third are forty-nine pounds return if we book this week — they jump up at the weekend.",
      "So — the Algarve apartment, flights on the third, and I'd add travel insurance at nineteen pounds. Shall I hold it while you decide?",
      "I'll hold it until Friday. If you change your mind, there's no charge.",
    ],
    targetPhrases: ["I'd prefer", "How much would that cost?", "Does that include", "That sounds perfect"],
  },
  {
    id: "rp-b1-news",
    title: "Discuss a news story",
    level: "B1",
    situation: "Your city plans to close the main street to cars. You are having coffee with a friend who disagrees with the plan. Give your opinion and respond to theirs.",
    partnerRole: "friend",
    opener: "Did you see they're finally closing the High Street to cars? Honestly, I think it's a mistake — the shops will lose all their customers.",
    fallbacks: [
      "Really? Every city that's done it says the opposite — but go on, what makes you say that?",
      "Fair enough, older people do need to park somewhere. What about the bus users, though?",
      "That's what the council keeps saying — that footfall went up thirty per cent where they tried it last summer. Did you notice it busier?",
      "I suppose we agree it's a mess at the moment — the air by the school is dreadful.",
      "Well, we won't settle this today! Same time next week — and we'll see who's laughing when the new paving goes in.",
    ],
    targetPhrases: ["In my opinion", "I see what you mean, but", "That's a good point", "You could be right, but"],
  },
  {
    id: "rp-b1-volunteer",
    title: "Interview to volunteer",
    level: "B1",
    situation: "You want to volunteer at a community food bank on Saturdays. The coordinator asks about your experience and availability.",
    partnerRole: "volunteer coordinator",
    opener: "Thanks for coming in. So — what made you think of volunteering with us?",
    fallbacks: [
      "That's a lovely reason, and honestly it's why half of us started. What kind of thing were you hoping to do?",
      "Saturdays are perfect — that's when we sort the donations. Have you done anything like this before?",
      "Helping at the school fair counts, don't worry. The main thing is turning up when you say you will.",
      "We ask for a minimum of one Saturday a month for three months — would that fit around your job?",
      "There's a short induction next Wednesday evening, and then I'd pair you with Amrit, who's been here for years.",
      "Welcome aboard, then! I'll email you the details today. See you on the eleventh.",
    ],
    targetPhrases: ["I'd like to help with", "I have experience of", "I'm available on", "How often would I need to come?"],
  },

  // ---------------------------------------------------------------------- B2 (+6)
  {
    id: "rp-b2-salary",
    title: "Negotiate a job offer",
    level: "B2",
    situation: "You have a written offer for a senior analyst role, but the salary is below market. Call HR to negotiate — stay warm but firm.",
    partnerRole: "HR manager",
    opener: "Thanks for coming back to me so quickly. You've had a chance to read the offer — what are your initial thoughts?",
    fallbacks: [
      "It's a strong offer, I'll grant you, but I sense there's a 'but' coming. Talk me through your thinking.",
      "I take your point about the London benchmarks, though our bands do run slightly below the market median by design. What figure were you basing that on?",
      "You're not the first to raise the bonus structure, and I'd rather be straight with you: the discretionary pool is capped this year.",
      "Here's what I can realistically do — three thousand above the posted band, and I'll flag your case for the April review cycle. Would that bridge the gap?",
      "Start date flexibility I can definitely sweeten — we're not precious about a January start if you need to wrap things up properly where you are.",
      "Alright, let me put the revised numbers in writing this afternoon. I've enjoyed this — you argue your corner well.",
    ],
    targetPhrases: ["I'd like to be transparent about", "Would you be open to", "Provided that", "I was hoping for something closer to"],
  },
  {
    id: "rp-b2-supplier",
    title: "Negotiate with a supplier",
    level: "B2",
    situation: "You buy components for a manufacturing firm. The supplier wants a 9% price rise; your budget allows 4%. Push for a compromise.",
    partnerRole: "supplier account manager",
    opener: "Thanks for making time. I'll be upfront — with resin costs where they are, we need to move list prices up by nine per cent from January.",
    fallbacks: [
      "I understand the instinct, but genuinely, our costs have gone up double digits — I can't absorb it all. What's your counter?",
      "Four per cent doesn't cover it, full stop. But let's look at it another way: what if volume changed the picture?",
      "Twelve per cent more volume for six per cent on price… I could take that to my board if the commitment ran for two years.",
      "Two years works if we anchor review dates — say we revisit in October with the inflation data on the table.",
      "Penalty clauses, though? I'd rather we built in a joint review than fines. That goodwill matters when things go wrong.",
      "Fine — six per cent, twelve per cent volume, two-year term, autumn review. I'll send the heads of terms tomorrow.",
    ],
    targetPhrases: ["That doesn't quite work for us because", "What if we committed to", "Would you consider", "Let's find a middle ground"],
  },
  {
    id: "rp-b2-client",
    title: "Manage an unhappy client",
    level: "B2",
    situation: "Your agency is two weeks late delivering a website, and the client is angry on a call. Acknowledge the delay, explain, and rebuild confidence.",
    partnerRole: "client",
    opener: "Right, I'll get straight to it — we were promised the site two weeks ago and my board is asking questions. This is not a good look for either of us.",
    fallbacks: [
      "I hear the apology, but what I need is a plan. Exactly what is left, and who is on it?",
      "The payment gateway… so one integration. Why did that take three weeks when you quoted five days?",
      "Well, at least that's honest. The third-party API documentation was genuinely appalling, to be fair to you.",
      "Fine. Thursday for staging, I want my team on the review call, and I'll manage expectations upstairs.",
      "One more thing — the invoice. I'm not paying the final instalment until my team has signed off the build. Is that going to be a problem?",
      "Good. Send me that timeline by five, and let's draw a line under it.",
    ],
    targetPhrases: ["You're right to be frustrated", "Here's exactly where we are", "What I'd propose is", "Can we agree that"],
  },
  {
    id: "rp-b2-deadline",
    title: "Push back on a tight deadline",
    level: "B2",
    situation: "Your manager wants the quarterly report by Friday; you need until Tuesday to do it properly. Make your case without sounding negative.",
    partnerRole: "line manager",
    opener: "Right, quick one — I need that Q3 report on my desk Friday morning. The board reads it over the weekend.",
    fallbacks: [
      "Friday's tight. What's eating the time — the data or the write-up?",
      "But the deck went out with last quarter's numbers — if these are wrong, we look worse, surely?",
      "Hmm. Tuesday gives you the weekend, though. If the board wants it Monday, Tuesday's a hard sell. What could you trim?",
      "Drop the regional annex to an online appendix, then. Nobody reads it, and it saves you a day, I'd have thought.",
      "Alright — Tuesday at nine, and the executive summary to me by Monday lunchtime so I can pre-brief the chair. That works?",
      "Agreed. And well done for flagging it now rather than on Thursday night — that's the bit I care about.",
    ],
    targetPhrases: ["To do this properly, I'd need", "The risk is that", "What if we", "Would that work for you?"],
  },
  {
    id: "rp-b2-flight",
    title: "Claim flight compensation",
    level: "B2",
    situation: "Your flight left four hours late and you missed a connection. At the airline's service desk, claim compensation and a hotel — politely but firmly.",
    partnerRole: "airline service manager",
    opener: "Good evening. I understand you've had a rough journey — let's see what I can do. Booking reference, please?",
    fallbacks: [
      "Four hours… yes, that's logged as a crew rotation issue, which I'm afraid counts as within our control. I won't pretend otherwise.",
      "The missed connection complicates it, though — that leg was a separate booking, technically.",
      "Let me be clear about what you're entitled to: the statutory payment applies, and I can authorise a hotel tonight plus meals.",
      "Rebooking you on the 07:40 is straightforward — I'd rather do that now, before the queue builds.",
      "The claim form for the cash compensation goes through the website; I'll note your file so it isn't bounced back.",
      "I know it doesn't fix your evening, but everything's logged. Safe travels — and do chase us if the payment slips.",
    ],
    targetPhrases: ["I'd like to claim compensation for", "I believe I'm entitled to", "What I need is", "Could you confirm that in writing?"],
  },
  {
    id: "rp-b2-network",
    title: "Network at a conference",
    level: "B2",
    situation: "At a sector conference you get chatting to a peer from another company. Keep the conversation natural, learn about their work, and agree a follow-up.",
    partnerRole: "fellow attendee",
    opener: "That last talk was a bit of a space-filler, wasn't it? I'm Priya, by the way — I'm in logistics at Novara.",
    fallbacks: [
      "Sustainability reporting — that's brave of you; most people dodge it. How are you finding the data side?",
      "Tell me about it — we're drowning in supplier questionnaires. Do you actually trust any of the numbers you get back?",
      "That tool sounds interesting, though I'm always wary of anything that promises to solve everything. What's the catch?",
      "Honestly, the coffee breaks are the best bit of these events. Who else is worth talking to here?",
      "Right, I'm going to be pushy: let's do a proper call in a couple of weeks. I'll connect with you on LinkedIn tonight.",
      "Lovely to meet you properly. Right — they're doing canapés, and I skipped lunch. Enjoy the rest of the day!",
    ],
    targetPhrases: ["What brings you here?", "How are you finding", "Shall we keep in touch?", "It was great talking to you"],
  },

  // ---------------------------------------------------------------------- C1 (+5)
  {
    id: "rp-c1-investor",
    title: "Pitch a sceptical investor",
    level: "C1",
    situation: "You are raising a seed round for a language-learning app. The investor is polite but unconvinced. Address her doubts without becoming defensive.",
    partnerRole: "angel investor",
    opener: "I'll be candid: I've seen forty language apps this year and invested in none of them. Convince me yours is different — in ninety seconds.",
    fallbacks: [
      "Retention, though. Duolingo's problem isn't acquisition, it's month three. Why would yours be any different?",
      "Hmm. You're claiming the retention comes from live conversation, but that's precisely the part that doesn't scale — or have I misread your model?",
      "Let me push on the market: you're selling a subscription in a category where users expect free. What's your honest answer to that?",
      "I take the point about the exam-prep wedge, but exam boards build their own prep tools eventually. What's your moat in three years' time?",
      "Here's my problem: at your valuation I need a ten-x story, and what I've heard is a two-x story told fluently.",
      "Alright — you handled the hard questions without flinching, which counts for more than the deck. Send the model with churn cohort data and I'll commit to a second meeting.",
    ],
    targetPhrases: ["That's a fair challenge", "May I reframe that?", "The evidence suggests", "With respect, the comparison breaks down when"],
  },
  {
    id: "rp-c1-qa",
    title: "Challenge a keynote speaker",
    level: "C1",
    situation: "After a conference keynote on remote work, you get the microphone. Challenge one of the speaker's conclusions — incisively but with courtesy.",
    partnerRole: "keynote speaker",
    opener: "…and that's why I'd argue hybrid work has quietly failed, and the office is due a comeback. Let's open it up — questions?",
    fallbacks: [
      "A good challenge. You're saying the productivity data is confounded by seniority — that the junior staff skew the averages. Is that fair?",
      "You're right that the survey only covered volunteers, which is a weakness I'll happily concede. Though I'd defend the exit interviews as a counterweight.",
      "May I push back, though? Conceding a point on measurement doesn't rescue the headline claim — the two are doing different work in my argument.",
      "Attrition would be the real test, I agree — and for what it's worth, our regretted-leaver data is in the appendix, which I confess is buried.",
      "That's the most useful question I've had all morning, and I mean that. Let's speak at the break — I'll give you the dataset.",
    ],
    targetPhrases: ["I take the point about", "May I push back on", "My contention is rather", "Could I press you on"],
  },
  {
    id: "rp-c1-relocate",
    title: "Persuade your partner to relocate",
    level: "C1",
    situation: "You have been offered a promotion in Singapore. Your partner's career and close friends are here. Have the delicate conversation.",
    partnerRole: "partner",
    opener: "So you took the call. I can tell from your face. Sit down — how long have you known about Singapore?",
    fallbacks: [
      "Three weeks? You sat on this for three weeks. I'm not angry about the job, I'm angry about the rehearsing.",
      "Go on, then — sell it to me. And I'll know if you're recycling the recruitment brochure.",
      "I do take it seriously — it's two years, not for ever. But two years of my career on hold is not nothing, and you know that.",
      "The thing that frightens me isn't the moving, it's the coming back — will my job even exist if I leave the team?",
      "If I said yes to exploring it, what would I actually want to see? An honest cost-of-living number, and something real about my work permit.",
      "Alright. Don't celebrate yet — but I'll come out with you in February to look. On one condition: no decisions on the plane home.",
    ],
    targetPhrases: ["I know this isn't easy", "What worries me most is", "Could we at least agree to", "I'm not asking you to decide tonight"],
  },
  {
    id: "rp-c1-badnews",
    title: "Announce a restructuring",
    level: "C1",
    situation: "As a department head, you must tell a respected team member that her role will disappear in the reorganisation — while offering a different, less senior post. Handle it with candour and care.",
    partnerRole: "team member",
    opener: "Thanks for making time at short notice. I'm going to be straight with you, because you deserve that — there's news about the reorganisation that affects your role.",
    fallbacks: [
      "It's not performance — I want to be unambiguous about that. The senior analyst function is being consolidated into two hub roles.",
      "You're right, and I won't dress it up: the timing is brutal, coming the week before your review.",
      "What I can offer is the Edinburgh post — real work, but at your old grade, which is a step down. I'd rather say that plainly than sugar-coat it.",
      "Redundancy terms are on the table too, and I'd support either route — I don't want you feeling steered.",
      "Take until Friday. Talk it through at home, sleep on it, and come back with the awkward questions — I'd rather have them now than at the exit interview.",
      "Whatever you decide, my door stays open — and for what it's worth, losing you from the team entirely would be our loss in every sense.",
    ],
    targetPhrases: ["I want to be straight with you", "This is not a reflection of", "What I can offer is", "Take the time you need"],
  },
  {
    id: "rp-c1-ethics",
    title: "Debate AI at work",
    level: "C1",
    situation: "Over lunch, a senior colleague argues that AI tools should be banned from client work. You disagree — but they have a point. Have a nuanced debate.",
    partnerRole: "senior colleague",
    opener: "I've drafted a memo banning AI tools from anything client-facing. I know you'll hate it, so let's have it out over pudding.",
    fallbacks: [
      "Go on then — make the case. But I warn you, I've just come out of a meeting where a vendor's tool invented a clause in a contract.",
      "A clause that did not exist in the original. In a client contract. And nobody spotted it for a fortnight. That's not a workflow risk, that's a reputational one.",
      "Hmm, 'literacy' is doing a lot of work in that sentence. Would your policy distinguish between drafting and checking, or is that too fine a line for compliance?",
      "That's more persuasive than the usual cheerleading, I'll grant you — the audit trail idea is genuinely interesting. Who signs off, though?",
      "Alright, I'll concede the ban is a blunt instrument — provided the pilot is confined to internal drafting and we publish the rules. Amend my memo?",
      "Consider yourself invited. And for what it's worth, this is the first argument I've enjoyed since the offsite.",
    ],
    targetPhrases: ["I take your point, but", "There's a distinction to be drawn between", "May I offer a middle path?", "Where does that leave"],
  },

  // ---------------------------------------------------------------------- C2 (+6)
  {
    id: "rp-c2-crisis",
    title: "Face the press after a recall",
    level: "C2",
    situation: "Your food company is recalling a product after an allergen labelling failure; a customer is in hospital. You are giving a statement and taking hostile questions.",
    partnerRole: "journalist",
    opener: "Ms Ashworth — two questions, one answer, I suspect. How did a known allergen end up unlabelled twice this year, and will you resign?",
    fallbacks: [
      "You're conflating two incidents with different root causes, and I'd caution against the tidy narrative — but the accountability question is fair, so let me answer it directly.",
      "Follow the paper trail: the supplier changed a spice blend in March and our specification didn't travel with it. That's not a deflection — it's the finding, and it's mine to own.",
      "I'll level with you: the internal audit flagged it forty minutes before the first hospital admission. We were slower than our own protocol, and that gap is what the independent review will dissect.",
      "Resignation is the easy theatre here. My job this morning is a full trace, a precautionary withdrawal of two more lines, and a phone call to the family concerned — which I will make myself.",
      "One more and then I'll take the regional desks: yes, the regulator was informed at twenty past six, and the timeline will be published unedited — warts and all.",
      "Last word, since you ask: trust is rebuilt in years and spent in seconds — and I intend to spend the next few years earning it back. Thank you.",
    ],
    targetPhrases: ["Let me be absolutely clear", "I take full responsibility for", "That's a conflation of two", "I'll level with you"],
  },
  {
    id: "rp-c2-merger",
    title: "Close a merger negotiation",
    level: "C2",
    situation: "It is the final round of talks to merge your firm with a larger rival. The other chief executive tries to reopen the agreed exchange ratio and squeeze your board seats.",
    partnerRole: "counterpart chief executive",
    opener: "Before the lawyers lock the doors — my chairman has had a word. He wants the ratio at 1.15 and a third board seat. Call it housekeeping.",
    fallbacks: [
      "Housekeeping? It is the deal. We signed heads of terms on 0.9 — reopening it now tells my board you negotiate in bad faith, and we both know what that does to price.",
      "There's the elephant in the room, at last — your third-quarter writedown. Frankly, that cuts both ways: my shareholders would now be carrying your asset risk.",
      "Then let's not make a theatre of it. What will you actually walk away over? Because I suspect 1.15 is noise and the board seat is the real ask.",
      "Interesting. You'll trade the seat for an earn-out but not the ratio. So price matters less than optics — good, now we're negotiating honestly.",
      "Here's my ballpark: 0.9 holds, one additional seat goes to an independent appointed jointly, and the earn-out is capped at forty million. If that lands, we announce on Thursday.",
      "Then we have a deal — and a relationship. My chairman will grumble in private and boast in public; such is life. Shall we tell the troops?",
    ],
    targetPhrases: ["Let's not pretend", "That cuts both ways", "What will you actually walk away over?", "Let me put a ballpark on the table"],
  },
  {
    id: "rp-c2-headhunter",
    title: "Weigh a headhunter's approach",
    level: "C2",
    situation: "A search partner courts you for a listed company's chief executive role. You are happy where you are — probe the mandate, test the culture, and keep your options open without committing.",
    partnerRole: "executive search partner",
    opener: "Thanks for taking this off-diary. Off the record, then: the Hartwell board has asked me to sound you out about their top job. Curious enough to hear more?",
    fallbacks: [
      "Wary is healthy — the last three chairs there had, shall we say, spirited disagreements with their chief executives. What would you want to know first?",
      "Growth, not transformation — that's the line in the brief. Though between us, the transformation has already eaten two incumbents, so read between the lines.",
      "Your current role is safe, I take it? Because I'd rather have you say no than say yes for the wrong reasons — reputations cut both ways in this trade.",
      "Candidly, the money is not the story — the package is geared: sixty per cent of the upside sits in long-term incentives tied to the sustainability gate.",
      "You want the shareholder register and the chair's succession plan — sensible. I can share the first under NDA; the second I would have to craft rather than disclose.",
      "Then here's my proposal: dinner with the chair, no commitment either way, off the record until you decide otherwise. I'll hold your name for a fortnight.",
    ],
    targetPhrases: ["Let me be candid", "What's the real mandate here?", "I'd need to see", "Strictly off the record"],
  },
  {
    id: "rp-c2-board",
    title: "Defend a strategic pivot",
    level: "C2",
    situation: "You want to halve investment in your flagship product to fund a new platform. The board chair thinks you are gambling the core business. Win the room.",
    partnerRole: "board chair",
    opener: "Before you present: I've read the paper twice, and I still can't find the part where we don't starve the golden goose. Enlighten me.",
    fallbacks: [
      "Maintenance, not cuts — I notice the paper says 'managed decline of the roadmap', which is either bold or careless phrasing. Which is it?",
      "A three-year window? Competitors will smell blood within two quarters. What's your honest read on when the market notices?",
      "And when the inevitable launch stumbles — because first releases stumble — what's the plan for the analysts' call? Hope is not a strategy.",
      "You're asking a conservative board to fund a moonshot with a cannibalisation problem. That takes more than conviction — show me the tripwire metrics.",
      "Tripwires I can sell: sign-ups, churn among top-decile accounts, and a hard monthly burn ceiling. If two of those trip, you throttle back automatically — that's the deal, yes?",
      "Then I'll back you — publicly and grumpily, which is the only way I know how. But if churn moves a hair in the second quarter, we revisit in the open, not in the papers.",
    ],
    targetPhrases: ["Let me address the elephant in the room", "The honest answer is", "Here's the tripwire", "I'd ask the board to weigh"],
  },
  {
    id: "rp-c2-summit",
    title: "Chair a partnership summit",
    level: "C2",
    situation: "You chair the annual summit of a three-company alliance. Two partners are threatening to walk out over intellectual property and revenue sharing. Keep the alliance alive.",
    partnerRole: "alliance partner chief executive",
    opener: "Let's not waste the room's time. Unless the IP split changes today, Delta is out — and I suspect I speak for Helios too.",
    fallbacks: [
      "Don't chair-manage me, if you don't mind. We built that pipeline on our patents and we take seventeen per cent of revenue for the privilege. Work that out.",
      "Derivative works — that's precisely the fog I won't sign up to. Define 'derivative' and you might have a deal; leave it vague and we're litigation waiting to happen.",
      "Revenue-share floor, IP escrow, and a joint engineering council with real teeth — that's my position, and Helios has already seen it.",
      "Escrow with joint sign-off? Now that's the first thing anyone has said today that could survive a lawyer's red pen. Go on — who appoints the escrow engineer?",
      "Then put it in the communiqué as a shared platform with ring-fenced core IP — that language I can take to my board without losing face.",
      "Sixty days, then. We reconvene in Zurich and sign the framework — or shake hands like civilised people and go our separate ways. Agreed?",
    ],
    targetPhrases: ["Let me take the temperature down", "What would you need to see", "Where's the real red line?", "Shall we park that and"],
  },
  {
    id: "rp-c2-gala",
    title: "Host a formal dinner",
    level: "C2",
    situation: "You are hosting your company's centenary dinner, and your guest of honour is a retired judge known for her dry wit. Welcome her formally, then trade pleasantries — switching registers gracefully.",
    partnerRole: "guest of honour",
    opener: "You flatter me with that introduction — I hadn't realised I'd become 'distinguished'. At my age, one is simply 'still here'.",
    fallbacks: [
      "A hundred years, is it? Your founder must have been a formidable character — I've read the minutes from 1925; he was ruthless with the petty cash.",
      "You're too kind, and I have the sentences to prove it. But tell me the truth — how many of tonight's speeches were drafted by the marketing department?",
      "Ha! Spoken like a true company man. Though I confess, the toasts are the only part of these evenings I have ever mastered.",
      "The archive room, you say? After pudding, perhaps — though beware, I do love a ledger, and I read them like detective novels.",
      "Splendid. Then lead on — and pray the wine is better than the chairman's puns, though I fear that bar is on the floor.",
    ],
    targetPhrases: ["May I propose a toast", "We are honoured to have you", "How do you find", "Shall I show you"],
  },
];
