/** Lesson-specific scenes: C2 speaking/writing/listening/reading. */
import type { LearningScene } from "./scenes-types";

export const SCENES_G: LearningScene[] = [
  {
    id: "c2-speaking-diplomacy",
    lessonIds: ["lesson-c2-speaking"],
    title: "Precision in delicate company",
    levels: ["C2"],
    topics: ["speaking", "precision", "nuance", "diplomacy", "negotiation"],
    setting: "A closed-door mediation between two founding partners",
    prop: "🤲",
    palette: ["#241f1c", "#5c5044"],
    characters: { a: { name: "Mediator Ines", emoji: "👩‍⚖️" }, b: { name: "Partner Elias", emoji: "🧔" } },
    lines: [
      { speaker: "a", text: "Before either of you restates a position, I want distinctions, not declarations.", ar: "قبل أن يعيد أي منكما صياغة موقفه، أريد تمايزات لا تصريحات." },
      { speaker: "b", text: "Then let me be exact about what I am not saying, since that seems to be the sticking point.", ar: "إذن دعني أدقق فيما لا أقوله، إذ يبدو أن هذه هي نقطة الخلاف." },
      { speaker: "b", text: "I am not disputing her authority to reorganise. I am questioning whether this reorganisation is reversible.", ar: "لا أنازع سلطتها في إعادة التنظيم. بل أسائل ما إذا كان هذا التنظيم قابلاً للعكس." },
      { speaker: "a", text: "A meaningful distinction. Reversibility, not authority. Would she accept that framing?", ar: "تمايز ذو معنى. قابلية العكس لا السلطة. هل تقبل هي تلك الصياغة؟" },
      { speaker: "b", text: "She will resist it — “reversible” quietly implies provisional, and she wants permanence.", ar: "ستقاومها — كلمة قابلة للعكس توحي ضمنياً بالأولية، وهي تريد الدوام." },
      { speaker: "a", text: "So the real contest is over connotation; we should negotiate the adjective, not the structure.", ar: "إذن الصراع الحقيقي على التضمين؛ وعلينا التفاوض على الصفة لا الهيكل." },
      { speaker: "b", text: "That is precisely the conversation worth having. Propose your wording.", ar: "هذه تحديداً هي المحادثة الجديرة بالوقت. اقترح صياغتك." },
    ],
    quiz: [
      { q: "Elias insists his objection concerns…", choices: ["her authority", "reversibility", "cost"], answer: 1 },
      { q: "Why would she resist “reversible”?", choices: ["It implies provisional", "It sounds expensive", "It is inaccurate"], answer: 0 },
      { q: "Ines reframes the dispute as being over…", choices: ["structure", "connotation", "timelines"], answer: 1 },
    ],
  },
  {
    id: "c2-writing-speech",
    lessonIds: ["lesson-c2-writing"],
    title: "Register, rhythm, rhetoric",
    levels: ["C2"],
    topics: ["writing", "register", "rhetoric", "speech", "style"],
    setting: "A speechwriter's studio, draft on the stand",
    prop: "🎤",
    palette: ["#2b2330", "#6d5a80"],
    characters: { a: { name: "Writer Omar", emoji: "✍️" }, b: { name: "Coach Vera", emoji: "🎭" } },
    lines: [
      { speaker: "b", text: "Read the closing line aloud as written.", ar: "اقرئي الخاتمة بصوت عالٍ كما هي." },
      { speaker: "a", text: "We must endeavour to strive towards the achievement of excellence.", ar: "يجب أن نسعى لاجتهادنا نحو بلوغ التميز." },
      { speaker: "b", text: "Four abstractions, zero images, and the rhythm dies mid-line. Cut to the bone.", ar: "أربع تجريدات، صفر صور، والإيقاع يموت في منتصف الجملة. اقطعي إلى العظم." },
      { speaker: "a", text: "We will be excellent. Too blunt for a funeral audience?", ar: "سنكون ممتازين. وقحة أكثر من اللازم لجمهور تأبين؟" },
      { speaker: "b", text: "For them, concrete memory beats abstract virtue: we will build what he sketched.", ar: "لهم، الذاكرة الملموسة تغلب الفضيلة المجردة: سنبنى ما رسمه." },
      { speaker: "a", text: "And register throughout — the board wanted gravitas without pomposity.", ar: "والسجل عبر النص — المجلس أراد وقاراً دون تبجح." },
      { speaker: "b", text: "Latinate only where precision demands it; Anglo-Saxon where feeling does.", ar: "اللاتينية حيث تتطلب الدقة؛ والإنجليزية الأصلية حيث يتطلب الشعور." },
      { speaker: "a", text: "Final pass tomorrow: read aloud, cut every syllable my breath trips on.", ar: "مرور أخير غداً: قراءة جهرية، وحذف كل مقطع يتعثر فيه نفَسي." },
    ],
    quiz: [
      { q: "The original closing fails because of…", choices: ["abstractions and dead rhythm", "bad grammar", "wrong tense"], answer: 0 },
      { q: "For a funeral audience Vera prefers…", choices: ["abstract virtue", "concrete memory", "humour"], answer: 1 },
      { q: "The register rule: Latinate for…", choices: ["feeling", "precision", "openings"], answer: 1 },
    ],
  },
  {
    id: "c2-listening-spin-room",
    lessonIds: ["lesson-c2-listening"],
    title: "Everything that matters, at speed",
    levels: ["C2"],
    topics: ["listening", "fast speech", "idiom", "register shifts", "inference"],
    setting: "A spin room minutes after a leaders' debate",
    prop: "⚡",
    palette: ["#1e2229", "#495364"],
    characters: { a: { name: "Ana", emoji: "👩‍💼" }, b: { name: "Rory", emoji: "🧑‍💼" } },
    lines: [
      { speaker: "a", text: "Three takeaways before the next feed goes live — talk fast.", ar: "ثلاث خلاصات قبل البث التالي — تحدث بسرعة." },
      { speaker: "b", text: "One: he front-loaded the economy then swerved housing the moment it got hairy.", ar: "أولاً: قدّم الاقتصاد ثم تفادى الإسكان لحظة ما عقدت العقدة." },
      { speaker: "a", text: "Swerved or strategically parked? The clip will be clipped either way.", ar: "تفادى أم أجّل استراتيجياً؟ سيُقتطع المقطع في الحالتين." },
      { speaker: "b", text: "Parked, I'd say — he flagged a white paper. That's an alibi, not an accident.", ar: "أجلها على ما أظن — أشار إلى ورقة سياسات. ذلك حجة غياب لا مصادفة." },
      { speaker: "a", text: "Two: her “frankly, with respect” count hit four. Each one preceded a rebuttal.", ar: "ثانياً: بلغت عبارة بصراحة وبكل احترام أربع مرات. كل واحدة سبقت ردّاً." },
      { speaker: "b", text: "Classic register shift as weapon — courtesy as a knife being unwrapped.", ar: "تحول سجلي كسلاح — المجاملة كسكين تُغلَّف." },
      { speaker: "a", text: "And three? Give me the one nobody else will run with.", ar: "وثالثاً؟ أعطني الخلاصة التي لن يتبناها غيرك." },
      { speaker: "b", text: "Neither mentioned social care once. The dog that didn't bark — that's tomorrow's story.", ar: "لم يذكر أي منهما الرعاية الاجتماعية. الكلب الذي لم ينبح — تلك قصة الغد." },
    ],
    quiz: [
      { q: "“Swerved… when it got hairy” means he…", choices: ["avoided it when difficult", "explained in detail", "changed his mind publicly"], answer: 0 },
      { q: "Her repeated “with respect” functions as…", choices: ["genuine politeness", "a pre-rebuttal weapon", "confusion filler"], answer: 1 },
      { q: "The dog that didn't bark refers to…", choices: ["an absent topic", "a loud attack", "a metaphor for loyalty"], answer: 0 },
    ],
  },
  {
    id: "c2-reading-subtext",
    lessonIds: ["lesson-c2-reading"],
    title: "Sophisticated texts, decoded",
    levels: ["C2"],
    topics: ["reading", "subtext", "rhetoric", "style", "interpretation"],
    setting: "Two critics comparing two obituaries of the same statesman",
    prop: "📜",
    palette: ["#26221d", "#635741"],
    characters: { a: { name: "Critique Nadia", emoji: "👩‍🎨" }, b: { name: "Critique Paul", emoji: "🧑‍🏫" } },
    lines: [
      { speaker: "b", text: "Same man, same week, two obituaries. Paper A calls his career “consequential”.", ar: "نفس الرجل، نفس الأسبوع، نعيان مختلفان. الصحيفة الأولى تصف مسيرته بأنها ذات نتائج." },
      { speaker: "a", text: "Consequential is doing somersaults there — consequences can be catastrophic. Faint praise with teeth.", ar: "كلمة ذات نتائج تقوم بالشقلبة هنا — فالنتائج قد تكون كارثية. مدح خفي بحوافّ." },
      { speaker: "b", text: "Paper B instead narrates a childhood anecdote about him returning a library book late.", ar: "الثانية بدل ذلك تسرد حكاية طفولة عن تأخره في إعادة كتاب للمكتبة." },
      { speaker: "a", text: "Which quietly files his whole career under personal virtue and avoids verdicts altogether.", ar: "ما يصنف ضمنياً مسيرته كلها تحت الفضيلة الشخصية ويتجنب الأحكام كلياً." },
      { speaker: "b", text: "Notice B's verbs: he helped, he served, he gave. Agentless where accountability would bite.", ar: "لاحظ أفعال الثانية: ساعد، خدم، أعطى. غائبة الفاعل حيث تنقر المساءلة." },
      { speaker: "a", text: "While A uses precise transitive verbs — he cut, he blocked, he signed — letting readers judge.", ar: "بينما تستخدم الأولى أفعالاً متعدية دقيقة — قطع، منع، وقّع — تاركة الحكم للقارئ." },
      { speaker: "b", text: "So the flattering text is the one that never judges, and the honest one hides judgement in verbs.", ar: "إذن النص المدحاء هو الذي لا يحكم أبداً، والصادق يخفي الحكم في الأفعال." },
      { speaker: "a", text: "Grammar as ideology. That's the whole seminar in one sentence.", ar: "القواعد كأيديولوجيا. هذا هو الندوة كلها في جملة." },
    ],
    quiz: [
      { q: "“Consequential” functions as…", choices: ["unambiguous praise", "faint praise allowing bad consequences", "neutral description"], answer: 1 },
      { q: "Paper B's anecdote strategy avoids…", choices: ["verdicts on the career", "personal warmth", "chronology"], answer: 0 },
      { q: "Agentless verbs appear where…", choices: ["accountability would bite", "rhythm demands", "space is short"], answer: 0 },
    ],
  },
];
