/** Lesson-specific scenes: B1 writing/listening/reading + B2 argument/writing/listening. */
import type { LearningScene } from "./scenes-types";

export const SCENES_E: LearningScene[] = [
  {
    id: "b1-writing-opinion",
    lessonIds: ["lesson-b1-writing"],
    title: "Drafting an opinion paragraph",
    levels: ["B1"],
    topics: ["writing", "opinion", "paragraphs", "linking words"],
    setting: "Study desk, tutor reviewing a draft on screen",
    prop: "📝",
    palette: ["#2f3e2e", "#5d7a52"],
    characters: { a: { name: "Salma", emoji: "👩‍🎓" }, b: { name: "Tutor Mark", emoji: "👨‍🏫" } },
    lines: [
      { speaker: "b", text: "Read me your topic sentence.", ar: "اقرئي لي جملة الموضوع." },
      { speaker: "a", text: "In my opinion, cities should have more green spaces.", ar: "برأيي، ينبغي أن تمتلك المدن مساحات خضراء أكثر." },
      { speaker: "b", text: "Clear position — good. Now one reason with a linker.", ar: "موقف واضح — جيد. الآن سبب واحد مع أداة ربط." },
      { speaker: "a", text: "Firstly, parks help people relax and exercise outdoors.", ar: "أولاً، تساعد الحدائق الناس على الاسترخاء والرياضة في الهواء الطلق." },
      { speaker: "b", text: "Add an example to make it concrete.", ar: "أضيفي مثالاً لجعله ملموساً." },
      { speaker: "a", text: "For example, after our park reopened, evening walks doubled.", ar: "على سبيل المثال، بعد إعادة افتتاح الحديقة تضاعفت المشي المسائي." },
      { speaker: "b", text: "Now close it by restating — not new information.", ar: "الآن اختمي بإعادة صياغة، لا بمعلومة جديدة." },
      { speaker: "a", text: "That is why investing in parks is worth every pound.", ar: "لهذا فإن الاستثمار في الحدائق يستحق كل جنيه." },
      { speaker: "b", text: "Position, reason, example, restatement. A solid B1 paragraph.", ar: "موقف، سبب، مثال، إعادة صياغة. فقرة B1 متينة." },
    ],
    quiz: [
      { q: "What is the paragraph's position?", choices: ["Cities need more green spaces", "Parks are expensive", "Walking is unhealthy"], answer: 0 },
      { q: "Which linker introduces the example?", choices: ["Firstly", "For example", "In conclusion"], answer: 1 },
      { q: "The closing sentence should…", choices: ["add new data", "restate the position", "ask a question"], answer: 1 },
    ],
  },
  {
    id: "b1-listening-training-change",
    lessonIds: ["lesson-b1-listening"],
    title: "Catching real points in fast chat",
    levels: ["B1"],
    topics: ["listening", "authentic speech", "main points", "details"],
    setting: "Two colleagues talking quickly over lunch",
    prop: "🎙️",
    palette: ["#312e25", "#6b6444"],
    characters: { a: { name: "Owen", emoji: "🧑" }, b: { name: "Priya", emoji: "👩" } },
    lines: [
      { speaker: "b", text: "So the training has moved to Thursday — did you catch that?", ar: "انتقل التدريب إلى الخميس — هل التقطت ذلك؟" },
      { speaker: "a", text: "Thursday? I thought it was Tuesday!", ar: "الخميس؟ ظننته الثلاثاء!" },
      { speaker: "b", text: "It was, but the trainer is ill. Same time though, eleven.", ar: "كان كذلك لكن المدربة مريضة. نفس الوقت، الحادية عشرة." },
      { speaker: "a", text: "Eleven works. Still in Room 4?", ar: "الحادية عشرة تناسبني. ما زالت في الغرفة الرابعة؟" },
      { speaker: "b", text: "No — everyone moves upstairs to Room 9.", ar: "لا — الجميع ينتقل إلى الأعلى، غرفة 9." },
      { speaker: "a", text: "OK: Thursday, eleven, Room 9. Prepare anything?", ar: "حسناً: الخميس، الحادية عشرة، غرفة 9. هل نجهز شيئاً؟" },
      { speaker: "b", text: "Just your laptop. And lunch isn't provided this time.", ar: "فقط حاسوبك. والغداء غير مقدّم هذه المرة." },
      { speaker: "a", text: "Good thing you mentioned that!", ar: "من حسن الحظ أنك ذكرت ذلك!" },
    ],
    quiz: [
      { q: "Why did the training move?", choices: ["Room booking failed", "The trainer is ill", "A time conflict"], answer: 1 },
      { q: "Final arrangements are…", choices: ["Tuesday 11, Room 4", "Thursday 11, Room 9", "Thursday 11, Room 4"], answer: 1 },
      { q: "What is NOT provided?", choices: ["Laptops", "Lunch", "Chairs"], answer: 1 },
    ],
  },
  {
    id: "b1-reading-article",
    lessonIds: ["lesson-b1-reading"],
    title: "Reading an article together",
    levels: ["B1"],
    topics: ["reading", "articles", "main idea", "details", "purpose"],
    setting: "Bookshop café, article open on a tablet",
    prop: "📰",
    palette: ["#37342c", "#77714f"],
    characters: { a: { name: "Hana", emoji: "👩‍🎓" }, b: { name: "Joe", emoji: "🧑‍🏫" } },
    lines: [
      { speaker: "b", text: "What is the headline telling us?", ar: "ماذا يقول لنا العنوان؟" },
      { speaker: "a", text: "Remote work saves commuters nine days a year. The main idea is time saved.", ar: "العمل عن بعد يوفر تسعة أيام سنوياً. الفكرة الرئيسية هي توفير الوقت." },
      { speaker: "b", text: "Good. Now scan for the number behind that claim.", ar: "جيد. الآن ابحثي عن الرقم وراء هذا الادعاء." },
      { speaker: "a", text: "Here: an average of fifty-four minutes per day.", ar: "هنا: بمعدل أربع وخمسون دقيقة يومياً." },
      { speaker: "b", text: "Why does the writer open with a bus driver's story?", ar: "لماذا يبدأ الكاتب بقصة سائق أتوبيس؟" },
      { speaker: "a", text: "To hook readers with a person before the statistics.", ar: "لجذب القراء بشخص قبل الإحصائيات." },
      { speaker: "b", text: "And the final paragraph warns about something. What?", ar: "والفقرة الأخيرة تحذر من شيء. ما هو؟" },
      { speaker: "a", text: "That city centres may lose trade if offices stay empty.", ar: "أن مراكز المدن قد تفقد تجارتها إن بقيت المكاتب فارغة." },
      { speaker: "b", text: "Main idea, detail, purpose, implication — you covered all four.", ar: "فكرة، تفصيلة، هدف، تضمين — غطيتِ الأربعة." },
    ],
    quiz: [
      { q: "The article's main idea is…", choices: ["time saved by remote work", "bus drivers' pay", "city cafés closing"], answer: 0 },
      { q: "The daily average saved is…", choices: ["54 minutes", "45 minutes", "9 hours"], answer: 0 },
      { q: "The bus driver appears first to…", choices: ["hook readers personally", "prove statistics wrong", "end the article warmly"], answer: 0 },
    ],
  },
  {
    id: "b2-argument-debate",
    lessonIds: ["lesson-b2-argument"],
    title: "Defending your position",
    levels: ["B2"],
    topics: ["argumentation", "debate", "counterpoints", "evidence"],
    setting: "A university debate society evening",
    prop: "⚖️",
    palette: ["#2c3639", "#5c7080"],
    characters: { a: { name: "Zaid", emoji: "🧑‍🎓" }, b: { name: "Marta", emoji: "👩‍💼" } },
    lines: [
      { speaker: "b", text: "Your motion says four-day weeks boost productivity. Prove it.", ar: "مقترحك يقول إن أسبوع العمل بأربعة أيام يرفع الإنتاجية. أثبت ذلك." },
      { speaker: "a", text: "Trials in Iceland and the UK showed output held steady or rose.", ar: "التجارب في آيسلندا وبريطانيا أظهرت ثبات الإنتاج أو ارتفاعه." },
      { speaker: "b", text: "Those were small pilots though. Doesn't scale change everything?", ar: "لكنها تجارب صغيرة. أليس التوسع يغيّر كل شيء؟" },
      { speaker: "a", text: "Fair challenge. But the mechanism — fewer meetings, sharper focus — scales with people.", ar: "اعتراض وجيه. لكن الآلية — اجتماعات أقل وتركيز أعلى — تتوسع مع عدد الناس." },
      { speaker: "b", text: "What about industries that need coverage seven days a week?", ar: "وماذا عن القطاعات التي تحتاج تغطية طوال الأسبوع؟" },
      { speaker: "a", text: "Rota deeper, not shorter: more staff per shift, same weekly cover.", ar: "توزيع أعمق لا أقصر: كوادر أكثر لكل وردية بنفس التغطية الأسبوعية." },
      { speaker: "b", text: "And if burnout just moves to managers?", ar: "وإذا انتقل الإرهاق إلى المديرين فقط؟" },
      { speaker: "a", text: "Then measure it — add manager workload metrics to any trial from day one.", ar: "إذاً قِسه — أضف مقاييس عبء المديرين لأي تجربة منذ اليوم الأول." },
      { speaker: "b", text: "Concede the motion is arguable — but you argued it properly today.", ar: "أعترف أن المقترح قابل للجدل — لكنك دافعت عنه كما يجب اليوم." },
    ],
    quiz: [
      { q: "Which evidence does Zaid cite?", choices: ["Iceland and UK trials", "A single company survey", "His own team only"], answer: 0 },
      { q: "How does he answer the scaling objection?", choices: ["Dismisses it", "Explains the mechanism scales", "Changes topic"], answer: 1 },
      { q: "His proposal for 24/7 industries is…", choices: ["shorter shifts only", "deeper rotas with same cover", "closing at weekends"], answer: 1 },
    ],
  },
  {
    id: "b2-writing-report",
    lessonIds: ["lesson-b2-writing"],
    title: "Structuring a professional report",
    levels: ["B2"],
    topics: ["writing", "report", "structure", "tone", "evidence"],
    setting: "Manager's desk, report draft between them",
    prop: "📊",
    palette: ["#232d3f", "#4e6e97"],
    characters: { a: { name: "Farah", emoji: "👩‍💼" }, b: { name: "James", emoji: "🧔‍♂️" } },
    lines: [
      { speaker: "b", text: "Your summary section first — what did you lead with?", ar: "قسم الملخص أولاً — بماذا بدأتِ؟" },
      { speaker: "a", text: "The recommendation: consolidate our three warehouses into two by Q3.", ar: "التوصية: دمج مستودعاتنا الثلاثة في اثنين بحلول الربع الثالث." },
      { speaker: "b", text: "Good — busy readers need the decision up front. Evidence next?", ar: "جيد — القارئ المشغول يحتاج القرار أولاً. ثم الأدلة؟" },
      { speaker: "a", text: "Costs fell twelve per cent in pilot regions; service levels held above target.", ar: "انخفضت التكاليف اثني عشر بالمئة في مناطق التجربة؛ وبقيت الخدمة فوق المستهدف." },
      { speaker: "b", text: "Tone check: read me sentence three of the risks part.", ar: "فحص النبرة: اقرئي الجملة الثالثة من قسم المخاطر." },
      { speaker: "a", text: "Staff concerns about relocation must be addressed through consultation.", ar: "ينبغي معالجة مخاوف الموظفين حول النقل عبر التشاور." },
      { speaker: "b", text: "Neutral and impersonal — right register for a board paper.", ar: "محايدة وغير شخصية — السجل المناسب لوثيقة مجلس الإدارة." },
      { speaker: "a", text: "I end each section with a mini-conclusion linking back to the goal.", ar: "أختم كل قسم بخلاصة صغيرة تعود إلى الهدف." },
      { speaker: "b", text: "Then it's ready. Send it before Thursday's meeting.", ar: "إذن هي جاهزة. أرسليها قبل اجتماع الخميس." },
    ],
    quiz: [
      { q: "What comes first in her report?", choices: ["Background history", "The recommendation", "Risk analysis"], answer: 1 },
      { q: "Pilot regions showed costs down by…", choices: ["12%", "20%", "2%"], answer: 0 },
      { q: "The tone of the risk section is…", choices: ["emotional", "neutral and impersonal", "humorous"], answer: 1 },
    ],
  },
  {
    id: "b2-listening-meeting-flow",
    lessonIds: ["lesson-b2-listening"],
    title: "Keeping up with the discussion",
    levels: ["B2"],
    topics: ["listening", "extended speech", "arguments", "implication"],
    setting: "A fast-moving project stand-up",
    prop: "🗂️",
    palette: ["#30271f", "#7a5c3f"],
    characters: { a: { name: "Dana", emoji: "👩‍💻" }, b: { name: "Marcus", emoji: "🧑‍🔧" } },
    lines: [
      { speaker: "b", text: "Quick update: supplier delays push delivery to the twelfth — which cascades.", ar: "تحديث سريع: تأخير المورد يدفع التسليم للثاني عشر — وهذا يترتب عليه تأثير متسلسل." },
      { speaker: "a", text: "Meaning testing slips too, unless we overlap phases. Correct?", ar: "أي أن الاختبار يتأخر أيضاً، ما لم نتراكب المراحل. صحيح؟" },
      { speaker: "b", text: "Exactly. If we start regression while build finishes, we claw back four days.", ar: "بالضبط. إذا بدأنا اختبار الانحدار قبل اكتمال البناء نستعيد أربعة أيام." },
      { speaker: "a", text: "Risky, but less risky than missing the client window. Who owns the overlap?", ar: "محفوف بمخاطرة، لكنه أقل من فقدان موعد العميل. من يملك التراكب؟" },
      { speaker: "b", text: "Priya volunteered, provided QA signs off by Friday.", ar: "بريا تطوعت بشرط موافقة ضمان الجودة بحلول الجمعة." },
      { speaker: "a", text: "Then the implicit ask this room owes her: protect her from scope creep next week.", ar: "إذن الطلب الضمني الذي على هذه الغرفة: حمايتها من زحف النطاق الأسبوع القادم." },
      { speaker: "b", text: "Agreed — freeze new requests during the overlap. I'll announce it.", ar: "اتفقنا — تجميد الطلبات الجديدة خلال التراكب. سأعلنه." },
      { speaker: "a", text: "Perfect. So: twelfth delivery, overlapped testing, frozen scope. Everyone aligned?", ar: "ممتاز. إذن: تسليم الثاني عشر، اختبار متراكب، نطاق مجمد. هل الجميع متوافقون؟" },
    ],
    quiz: [
      { q: "What causes the cascade?", choices: ["Supplier delay", "QA sign-off", "Scope creep"], answer: 0 },
      { q: "How do they recover four days?", choices: ["Overlapping test and build", "Adding staff", "Cutting tests"], answer: 0 },
      { q: "The “implicit ask” means…", choices: ["something said directly", "something understood but unstated", "an email follow-up"], answer: 1 },
    ],
  },
];
