/** Lesson-specific scenes: A1 listening + A2 (4) + B1 speaking. */
import type { LearningScene } from "./scenes-types";

export const SCENES_D: LearningScene[] = [
  {
    id: "a1-listening-needs",
    lessonIds: ["lesson-a1-listening"],
    title: "What do they need?",
    levels: ["A1"],
    topics: ["listening", "intent", "requests", "everyday exchanges"],
    setting: "Two short exchanges at a hotel desk and a pharmacy",
    prop: "🛎️",
    palette: ["#1b3a4b", "#3d7ea6"],
    characters: { a: { name: "Guest", emoji: "🧔" }, b: { name: "Reception", emoji: "💁‍♀️" } },
    lines: [
      { speaker: "a", text: "Excuse me, my room is very cold.", ar: "عفواً، غرفتي باردة جداً." },
      { speaker: "b", text: "I'm sorry. I'll send someone with a heater.", ar: "آسفة. سأرسل أحدهم بمدفأة." },
      { speaker: "a", text: "Thank you. And one more thing — a wake-up call at seven?", ar: "شكراً. وشيء آخر — مكالمة إيقاظ السابعة؟" },
      { speaker: "b", text: "Of course, seven o'clock.", ar: "بالطبع، الساعة السابعة." },
      { speaker: "a", text: "Perfect, good night.", ar: "ممتاز، تصبحين على خير." },
      { speaker: "b", text: "Good night, sleep well.", ar: "تصبح على خير." },
    ],
    quiz: [
      { q: "What is wrong with the room?", choices: ["Too noisy", "Too cold", "Too small"], answer: 1 },
      { q: "What does the guest ask for at seven?", choices: ["Breakfast", "A taxi", "A wake-up call"], answer: 2 },
      { q: "The receptionist will send…", choices: ["a heater", "new keys", "towels"], answer: 0 },
    ],
  },
  {
    id: "a2-interactions-pharmacy",
    lessonIds: ["lesson-a2-interactions"],
    title: "Everyday errand: the pharmacy",
    levels: ["A2"],
    topics: ["shopping", "services", "pharmacy", "transactions", "health"],
    setting: "A neighbourhood pharmacy on a Saturday",
    prop: "💊",
    palette: ["#144d3f", "#2e9e77"],
    characters: { a: { name: "Tariq", emoji: "🧑" }, b: { name: "Chemist Ada", emoji: "👩‍⚕️" } },
    lines: [
      { speaker: "a", text: "Hello, do you have anything for a cough?", ar: "مرحباً، هل لديكم شيء للكحة؟" },
      { speaker: "b", text: "We do. Is it dry, or with phlegm?", ar: "لدينا. هل هي جافة أم مع بلغم؟" },
      { speaker: "a", text: "Mostly at night, quite dry.", ar: "غالباً ليلاً، جافة تماماً." },
      { speaker: "b", text: "Then this syrup should help. Take it before bed.", ar: "إذن هذا الشراب سيساعد. تناوله قبل النوم." },
      { speaker: "a", text: "How much is it?", ar: "بكم هو؟" },
      { speaker: "b", text: "Five ninety-nine. Do you need anything else?", ar: "خمسة وتسعة وتسعين بنس. تحتاج شيئاً آخر؟" },
      { speaker: "a", text: "No, that's all. Thanks for your help.", ar: "لا، هذا كل شيء. شكراً على مساعدتك." },
      { speaker: "b", text: "You're welcome. Get better soon!", ar: "على الرحب والسعة. بالشفاء العاجل!" },
    ],
    quiz: [
      { q: "What kind of cough is it?", choices: ["Wet", "Dry", "With fever"], answer: 1 },
      { q: "When should he take the syrup?", choices: ["In the morning", "Before bed", "After meals"], answer: 1 },
      { q: "How much does he pay?", choices: ["£5.90", "£5.99", "£9.05"], answer: 1 },
    ],
  },
  {
    id: "a2-past-weekend",
    lessonIds: ["lesson-a2-past"],
    title: "So, what did you do?",
    levels: ["A2"],
    topics: ["past events", "weekend", "past simple", "time markers"],
    setting: "Monday morning, colleagues catching up",
    prop: "📅",
    palette: ["#3e2f4f", "#7e57c2"],
    characters: { a: { name: "Rami", emoji: "🧑‍💻" }, b: { name: "Chloe", emoji: "👩‍💻" } },
    lines: [
      { speaker: "b", text: "Morning! Did you have a good weekend?", ar: "صباح الخير! هل كانت نهاية أسبوعك جيدة؟" },
      { speaker: "a", text: "Really good, thanks. On Friday we visited my uncle.", ar: "جيدة جداً شكراً. يوم الجمعة زرنا عمي." },
      { speaker: "b", text: "Nice. What did you do on Saturday?", ar: "جميل. ماذا فعلت السبت؟" },
      { speaker: "a", text: "I played football in the park. We won 3–1!", ar: "لعبت كرة القدم في الحديقة. فزنا ثلاثة مقابل واحد!" },
      { speaker: "b", text: "Well done! And Sunday?", ar: "أحسنت! والأحد؟" },
      { speaker: "a", text: "Sunday was quiet. I cooked lunch and watched a film.", ar: "الأحد كان هادئاً. طبخت الغداء وشاهدت فيلماً." },
      { speaker: "b", text: "Sounds perfect. Mine wasn't so exciting — I studied all day!", ar: "يبدو مثالياً. يومي لم يكن ممتعاً — درست طوال اليوم!" },
    ],
    quiz: [
      { q: "What did Rami do on Friday?", choices: ["Played football", "Visited his uncle", "Watched a film"], answer: 1 },
      { q: "What was the football score?", choices: ["3–1 to them", "3–1 win", "1–1 draw"], answer: 1 },
      { q: "Who studied all day?", choices: ["Rami", "Chloe", "The uncle"], answer: 1 },
    ],
  },
  {
    id: "a2-messages-invite",
    lessonIds: ["lesson-a2-messages"],
    title: "Writing a short invitation",
    levels: ["A2"],
    topics: ["writing", "messages", "invitation", "notes"],
    setting: "Two flatmates planning a small dinner, phone between them",
    prop: "📱",
    palette: ["#334139", "#60806f"],
    characters: { a: { name: "Dana", emoji: "👩" }, b: { name: "Leo", emoji: "🧑" } },
    lines: [
      { speaker: "a", text: "I want to invite our neighbours for dinner. Help me write the message.", ar: "أريد دعوة الجيران للعشاء. ساعدني بكتابة الرسالة." },
      { speaker: "b", text: "Start with a greeting: “Dear Mr and Mrs Bell…”", ar: "ابدئي بتحية: عزيزي السيد والسيدة بل…" },
      { speaker: "a", text: "Then what? The date?", ar: "ثم ماذا؟ التاريخ؟" },
      { speaker: "b", text: "Say the day and time clearly: “We'd love you to join us on Friday at 7 pm.”", ar: "اذكري اليوم والوقت بوضوح: نحب أن تنضموا إلينا الجمعة السابعة مساءً." },
      { speaker: "a", text: "Should I mention food? They don't eat meat.", ar: "هل أذكر الطعام؟ هم لا يأكلون اللحم." },
      { speaker: "b", text: "Good thinking — add “There will be vegetarian food.”", ar: "تفكير جيد — أضيفي سيكون هناك طعام نباتي." },
      { speaker: "a", text: "And how do I finish?", ar: "كيف أختم؟" },
      { speaker: "b", text: "“Please let us know if you can come. See you soon, Dana.” Short and clear.", ar: "أخبرونا إن استطتم الحضور. أراكما قريباً، دانا. قصيرة وواضحة." },
    ],
    quiz: [
      { q: "When is the dinner?", choices: ["Friday at 7 pm", "Saturday at 6 pm", "Friday at 7 am"], answer: 0 },
      { q: "Why mention vegetarian food?", choices: ["They don't eat meat", "It's cheaper", "It cooks faster"], answer: 0 },
      { q: "How does the message end?", choices: ["With a request to reply", "With a joke", "With an address"], answer: 0 },
    ],
  },
  {
    id: "a2-listening-lost-bag",
    lessonIds: ["lesson-a2-listening"],
    title: "Following the details",
    levels: ["A2"],
    topics: ["listening", "main idea", "details", "lost property"],
    setting: "Reporting a lost bag at a train station office",
    prop: "👜",
    palette: ["#402d24", "#8a6547"],
    characters: { a: { name: "Nadia", emoji: "👩" }, b: { name: "Station Clerk", emoji: "🧑‍✈️" } },
    lines: [
      { speaker: "a", text: "Hello, I left my bag on the Manchester train.", ar: "مرحباً، نسيت حقيبتي على قطار مانشستر." },
      { speaker: "b", text: "Don't worry. Which train was it — the 10:15 or the 10:45?", ar: "لا تقلقي. أي قطار كان — العاشرة وخمسة عشر أم العاشرة وخمس وأربعون؟" },
      { speaker: "a", text: "The 10:15. It arrived twenty minutes ago.", ar: "العاشرة وخمسة عشر. وصل قبل عشرين دقيقة." },
      { speaker: "b", text: "Can you describe the bag?", ar: "هل تصفين الحقيبة؟" },
      { speaker: "a", text: "It's blue, quite big, with a white zip and a red key ring.", ar: "زرقاء، كبيرة قليلاً، بسحاب أبيض وميدالية مفاتيح حمراء." },
      { speaker: "b", text: "Blue bag, white zip, red key ring. Anything inside that matters?", ar: "حقيبة زرقاء، سحاب أبيض، ميدالية حمراء. هل فيها شيء مهم؟" },
      { speaker: "a", text: "My laptop charger and some books. Nothing dangerous!", ar: "شاحن الحاسوب وبعض الكتب. لا شيء خطير!" },
      { speaker: "b", text: "Good news — they've just found it. Collect it at lost property after twelve.", ar: "خبر جيد — وجدوها للتو. اجمعيها من مكتب المفقودات بعد الثانية عشرة." },
    ],
    quiz: [
      { q: "Which train was it?", choices: ["The 10:15", "The 10:45", "The 12:00"], answer: 0 },
      { q: "What colour is the key ring?", choices: ["White", "Blue", "Red"], answer: 2 },
      { q: "Where can she collect the bag?", choices: ["On the train", "Lost property office", "The café"], answer: 1 },
    ],
  },
  {
    id: "b1-conversation-networking",
    lessonIds: ["lesson-b1-conversation"],
    title: "An independent conversation",
    levels: ["B1"],
    topics: ["conversation", "follow-up questions", "work", "social", "fluency"],
    setting: "A networking break at a tech meetup",
    prop: "🥂",
    palette: ["#1f2937", "#4f6d9c"],
    characters: { a: { name: "Imad", emoji: "🧑‍💼" }, b: { name: "Becca", emoji: "👩‍🔬" } },
    lines: [
      { speaker: "b", text: "Interesting talk, wasn't it? Are you working in data too?", ar: "محاضرة شيقة، أليس كذلك؟ هل تعمل في مجال البيانات أيضاً؟" },
      { speaker: "a", text: "Sort of — I manage a small support team, but we deal with data daily. How about you?", ar: "نوعاً ما — أدير فريق دعم صغير، لكننا نتعامل مع البيانات يومياً. وأنتِ؟" },
      { speaker: "b", text: "I'm a data analyst at a hospital, actually. Mostly patient-flow dashboards.", ar: "أنا محللة بيانات في مستشفى. غالباً لوحات متابعة تدفق المرضى." },
      { speaker: "a", text: "That sounds meaningful. What's the hardest part of that job?", ar: "يبدو ذلك ذا معنى. ما أصعب جزء في هذه العملة؟", note: "Follow-up question keeps the conversation alive." },
      { speaker: "b", text: "Honestly? Explaining delays without blaming anyone. Numbers can sound cold.", ar: "بصراحة؟ شرح التأخير دون إلقاء اللوم على أحد. الأرقام قد تبدو باردة." },
      { speaker: "a", text: "I know that feeling — support tickets are the same. So how do you handle it?", ar: "أعرف الشعور — تذاكر الدعم مثلها. كيف تتعاملين مع ذلك؟" },
      { speaker: "b", text: "I pair every chart with a story from a real ward. Context changes everything.", ar: "أقترن كل رسم بقصة من قسم حقيقي. السياق يغيّر كل شيء." },
      { speaker: "a", text: "That's a great habit. Shall we swap contacts? I'd love to continue this.", ar: "هذه عادة رائعة. نتبادل التواصل؟ أود مواصلة الحديث." },
      { speaker: "b", text: "Definitely — here's my card. Great talking to you, Imad.", ar: "بالتأكيد — هذه بطاقتي. سعدت بالحديث معك يا عماد." },
    ],
    quiz: [
      { q: "What is Becca's job?", choices: ["Support manager", "Hospital data analyst", "Doctor"], answer: 1 },
      { q: "Which follow-up question does Imad ask?", choices: ["“How about you?”", "“What's the hardest part?”", "“Where are you from?”"], answer: 1 },
      { q: "Her trick for cold numbers is…", choices: ["hiding them", "pairing charts with real stories", "using fewer colours"], answer: 1 },
    ],
  },
];
