/** In-platform animated learning scenes, part A (Pre-A1 → B2): dialogues, voices, visuals, quizzes. */
import type { LearningScene } from "./scenes-types";

export const SCENES_A: LearningScene[] = [
  {
    id: "cafe-order",
    title: "Ordering at a café",
    levels: ["Pre-A1", "A1", "A2"],
    topics: ["food", "drink", "café", "coffee", "restaurant", "routine"],
    setting: "A small London café on a rainy morning",
    prop: "☕",
    palette: ["#3b2f2f", "#6f4e37"],
    characters: { a: { name: "Sam", emoji: "🧑" }, b: { name: "Layla", emoji: "👩‍🍳" } },
    lines: [
      { speaker: "b", text: "Good morning! What can I get you?", ar: "صباح الخير! ماذا أقدّم لك؟" },
      { speaker: "a", text: "Hi. Can I have a coffee, please?", ar: "مرحباً. ممكن قهوة، من فضلك؟", note: "\"Can I have…, please?\" = polite request." },
      { speaker: "b", text: "Of course. Anything to eat with that?", ar: "بالطبع. أي شيء تأكله معها؟" },
      { speaker: "a", text: "Just a croissant, thanks. How much is that?", ar: "كرواسون فقط، شكراً. كم المبلغ؟" },
      { speaker: "b", text: "That's four pounds fifty, please.", ar: "أربعة جنيهات ونصف، من فضلك.", note: "£4.50 = four pounds fifty." },
      { speaker: "a", text: "Here you are.", ar: "تفضل.", note: "\"Here you are.\" = giving money or objects." },
      { speaker: "b", text: "Perfect. Your coffee is just coming.", ar: "ممتاز. قهوتك في الطريق." },
      { speaker: "a", text: "Thanks a lot. Have a good day!", ar: "شكراً جزيلاً. نهارك سعيد!" },
      { speaker: "b", text: "You too! Enjoy.", ar: "وأنت كذلك! بالعافية." },
    ],
    quiz: [
      { q: "What does Sam order?", choices: ["Tea and cake", "A coffee and a croissant", "Two coffees"], answer: 1 },
      { q: "How much does he pay?", choices: ["£4.15", "£4.50", "£5.40"], answer: 1 },
      { q: "Which phrase means giving money?", choices: ["Here you are.", "How much?", "You too!"], answer: 0 },
    ],
  },
  {
    id: "meeting-new-people",
    title: "Meeting someone new",
    levels: ["Pre-A1", "A1", "A2"],
    topics: ["introduce", "introductions", "greetings", "small talk", "friends", "family"],
    setting: "A friendly welcome event at a language school",
    prop: "🤝",
    palette: ["#1f3a5f", "#3f6fae"],
    characters: { a: { name: "Omar", emoji: "👨" }, b: { name: "Emily", emoji: "👩" } },
    lines: [
      { speaker: "a", text: "Hello! Is this seat free?", ar: "مرحباً! هل هذا المقعد فارغ؟" },
      { speaker: "b", text: "Yes, of course. Please sit down.", ar: "نعم بالطبع. تفضل بالجلوس." },
      { speaker: "a", text: "Thanks. I'm Omar. Nice to meet you.", ar: "شكراً. أنا عمر. سُرت بلقائك.", note: "\"Nice to meet you.\" = first meeting." },
      { speaker: "b", text: "Nice to meet you too. I'm Emily. Where are you from?", ar: "سُرت بلقائك أيضاً. أنا إميلي. من أين أنت؟", note: "\"Where are you from?\" = classic opener." },
      { speaker: "a", text: "I'm from Cairo, but I live here now. And you?", ar: "من القاهرة، لكنني أعيش هنا الآن. وأنت؟" },
      { speaker: "b", text: "I'm from Manchester. What do you do?", ar: "أنا من مانشستر. ما عملك؟", note: "\"What do you do?\" = asking about a job." },
      { speaker: "a", text: "I'm an engineer. I work near the city centre.", ar: "أنا مهندس. أعمل قرب وسط المدينة." },
      { speaker: "b", text: "That's great. Well, see you around, Omar!", ar: "رائع. إلى اللقاء يا عمر!" },
      { speaker: "a", text: "See you! It was lovely talking to you.", ar: "إلى اللقاء! كان لطيفاً الحديث معك.", note: "\"It was lovely talking to you.\" = warm goodbye." },
    ],
    quiz: [
      { q: "Where is Omar from?", choices: ["Manchester", "Cairo", "London"], answer: 1 },
      { q: "Which question asks about a job?", choices: ["What do you do?", "Where are you from?", "Is this seat free?"], answer: 0 },
      { q: "Which phrase is a warm goodbye?", choices: ["Please sit down.", "It was lovely talking to you.", "I'm an engineer."], answer: 1 },
    ],
  },
  {
    id: "doctor-visit",
    title: "At the doctor's",
    levels: ["A1", "A2"],
    topics: ["health", "doctor", "illness", "body", "appointment", "medicine"],
    setting: "A GP surgery in Birmingham",
    prop: "🩺",
    palette: ["#14424f", "#2e7d8c"],
    characters: { a: { name: "Rana", emoji: "👩" }, b: { name: "Dr Patel", emoji: "👨‍⚕️" } },
    lines: [
      { speaker: "b", text: "Come in. What seems to be the problem?", ar: "تفضلي. ما المشكلة؟", note: "Standard doctor opener." },
      { speaker: "a", text: "I've had a sore throat and a headache since Monday.", ar: "عندي التهاب حلق وصداع منذ الاثنين.", note: "Present perfect + since = health timelines." },
      { speaker: "b", text: "I see. Do you have a temperature?", ar: "فهمت. هل لديك حرارة؟" },
      { speaker: "a", text: "A little, especially at night.", ar: "قليلاً، خاصةً ليلاً." },
      { speaker: "b", text: "Let me look at your throat… It's red, but nothing serious.", ar: "دعي أنظر إلى حلقك… إنه أحمر لكن لا شيء خطير." },
      { speaker: "a", text: "That's a relief. What should I do?", ar: "هذا مريح. ماذا أفعل؟", note: "\"That's a relief.\" = feeling less worried." },
      { speaker: "b", text: "Rest, drink warm fluids, and take this medicine twice a day.", ar: "اراحي، اشربي سوائل دافئة، وخذي هذا الدواء مرتين يومياً." },
      { speaker: "a", text: "Should I stay off work?", ar: "هل أبقى بعيداً عن العمل؟", note: "\"Stay off work\" = not go to work." },
      { speaker: "b", text: "Yes, for two days. If it gets worse, come straight back.", ar: "نعم ليومين. إذا ساء الأمر فعودي فوراً." },
    ],
    quiz: [
      { q: "How long has Rana been ill?", choices: ["Since Monday", "One night", "Two weeks"], answer: 0 },
      { q: "How often should she take the medicine?", choices: ["Once a day", "Twice a day", "Every hour"], answer: 1 },
      { q: "What does \"stay off work\" mean?", choices: ["Leave early", "Not go to work", "Work from home"], answer: 1 },
    ],
  },
  {
    id: "asking-directions",
    title: "Finding your way",
    levels: ["A1", "A2"],
    topics: ["directions", "city", "travel", "places", "transport", "street"],
    setting: "A busy street corner in central Manchester",
    prop: "🗺️",
    palette: ["#33322e", "#6b6a5c"],
    characters: { a: { name: "Yusuf", emoji: "🧑" }, b: { name: "Grace", emoji: "👵" } },
    lines: [
      { speaker: "a", text: "Excuse me, could you help me? I'm looking for the library.", ar: "عفواً، هل يمكنك المساعدة؟ أبحث عن المكتبة.", note: "\"Excuse me\" + \"I'm looking for…\" = safe opener." },
      { speaker: "b", text: "Of course. Go straight on, then turn left at the traffic lights.", ar: "بالطبع. امضِ مستقيماً ثم انعطف يساراً عند الإشارة." },
      { speaker: "a", text: "Left at the traffic lights. Is it far?", ar: "يساراً عند الإشارة. هل هو بعيد؟" },
      { speaker: "b", text: "About five minutes on foot. It's opposite the park.", ar: "نحو خمس دقائق سيراً. إنه مقابل الحديقة.", note: "\"Opposite\" = across from." },
      { speaker: "a", text: "Sorry, did you say opposite the bank or the park?", ar: "عفواً، قلت مقابل البنك أم الحديقة؟", note: "\"Sorry, did you say…?\" = checking details." },
      { speaker: "b", text: "The park — the big green one.", ar: "الحديقة — الكبيرة الخضراء." },
      { speaker: "a", text: "Got it. Thank you so much for your help.", ar: "فهمت. شكراً جزيلاً على مساعدتك." },
      { speaker: "b", text: "No problem at all. Have a lovely day!", ar: "لا مشكلة أبداً. نهارك سعيد!" },
    ],
    quiz: [
      { q: "Where should Yusuf turn left?", choices: ["At the park", "At the traffic lights", "At the bank"], answer: 1 },
      { q: "The library is ___ the park.", choices: ["next to", "behind", "opposite"], answer: 2 },
      { q: "Which phrase checks information?", choices: ["Got it.", "Did you say…?", "No problem."], answer: 1 },
    ],
  },
  {
    id: "hotel-checkin",
    title: "Checking in at a hotel",
    levels: ["A2", "B1"],
    topics: ["hotel", "travel", "holiday", "booking", "room", "airport"],
    setting: "Hotel reception at dusk, city view behind",
    prop: "🏨",
    palette: ["#2d1b4e", "#5b3f8f"],
    characters: { a: { name: "Khaled", emoji: "🧔" }, b: { name: "Sofia", emoji: "💁‍♀️" } },
    lines: [
      { speaker: "a", text: "Good evening. I have a reservation under the name Khaled.", ar: "مساء الخير. لدي حجز باسم خالد.", note: "\"Under the name…\" = booking vocabulary." },
      { speaker: "b", text: "Welcome, Mr Khaled. Let me find that… Yes, a double room for three nights.", ar: "أهلاً بك. لحظة من فضلك… نعم، غرفة مزدوجة ثلاث ليالٍ." },
      { speaker: "a", text: "That's right. Is breakfast included?", ar: "صحيح. هل الإفطار مشمول؟", note: "\"Included\" = part of the price." },
      { speaker: "b", text: "It is, from seven until ten in the restaurant downstairs.", ar: "نعم، من السابعة حتى العاشرة في المطعم بالأسفل." },
      { speaker: "a", text: "Great. Could I have a room away from the lift, if possible?", ar: "رائع. ممكن غرفة بعيدة عن المصعد إن أمكن؟", note: "\"If possible\" softens requests." },
      { speaker: "b", text: "Let me check… I can offer you room 512, quiet and overlooking the garden.", ar: "لأتأكد… أستطيع منحك الغرفة 512، هادئة ومطلة على الحديقة." },
      { speaker: "a", text: "Perfect. What time is check-out?", ar: "ممتاز. متى موعد تسليم الغرفة؟" },
      { speaker: "b", text: "Midday. Enjoy your stay — the lifts are just behind you.", ar: "الظهيرة. أتمنى لك إقامة طيبة — المصاعد خلفك." },
    ],
    quiz: [
      { q: "How many nights is Khaled staying?", choices: ["Two", "Three", "Five"], answer: 1 },
      { q: "Why does he ask about the room position?", choices: ["Cheaper price", "Away from the lift", "Bigger bed"], answer: 1 },
      { q: "\"Is breakfast included?\" asks whether…", choices: ["the price covers it", "it is fresh", "it is early"], answer: 0 },
    ],
  },
  {
    id: "shopping-complaint",
    title: "Returning a faulty item",
    levels: ["B1", "B2"],
    topics: ["shopping", "complaint", "return", "shop", "money", "problem"],
    setting: "Customer service desk in an electronics shop",
    prop: "🎧",
    palette: ["#4a1f1f", "#8c4a4a"],
    characters: { a: { name: "Nour", emoji: "👩" }, b: { name: "Dan", emoji: "🧑‍🔧" } },
    lines: [
      { speaker: "a", text: "Hello. I'd like to return these headphones — they stopped working after a week.", ar: "مرحباً. أريد إرجاع هذه السماعات — توقفت بعد أسبوع.", note: "\"I'd like to return…\" = complaint frame." },
      { speaker: "b", text: "I'm sorry to hear that. Do you have the receipt?", ar: "آسف لسماع ذلك. هل معك الفاتورة؟" },
      { speaker: "a", text: "Yes, here it is. I bought them on the twelfth.", ar: "نعم، تفضل. اشتريتها في الثاني عشر." },
      { speaker: "b", text: "Thanks. Would you like a replacement or a refund?", ar: "شكراً. تفضلين بديلاً أم استرداد المبلغ؟", note: "Replacement vs refund — the key choice." },
      { speaker: "a", text: "Honestly, I've lost confidence in the brand, so a refund please.", ar: "بصراحة فقدت الثقة بهذه العلامة، فالاسترداد من فضلك.", note: "\"I've lost confidence in…\" = firm but polite." },
      { speaker: "b", text: "Understood. The card you paid with, please… refunded. It may take three working days.", ar: "مفهوم. البطاقة التي دفعت بها من فضلك… تم الاسترداد. قد يستغرق ثلاثة أيام عمل." },
      { speaker: "a", text: "That's fine. Thanks for sorting it out quickly.", ar: "لا بأس. شكراً لحل الأمر سريعاً.", note: "\"Sort out\" = resolve a problem." },
      { speaker: "b", text: "My pleasure. Is there anything else I can help with?", ar: "هذا واجبي. هل من شيء آخر أستطيع مساعدتك به؟" },
    ],
    quiz: [
      { q: "What went wrong with the headphones?", choices: ["They were lost", "They stopped working", "They were too expensive"], answer: 1 },
      { q: "What does Nour choose?", choices: ["A replacement", "A refund", "Store credit"], answer: 1 },
      { q: "\"Sort out\" means…", choices: ["buy again", "resolve", "postpone"], answer: 1 },
    ],
  },
];
