/** Lesson-specific scenes: Pre-A1 (4) + A1 (3). Lines stay short and high-frequency. */
import type { LearningScene } from "./scenes-types";

export const SCENES_C: LearningScene[] = [
  {
    id: "prea1-survival-hello",
    lessonIds: ["lesson-prea1-survival"],
    title: "First words at school",
    levels: ["Pre-A1"],
    topics: ["greetings", "survival", "numbers", "classroom"],
    setting: "First morning at a small language school",
    prop: "🎒",
    palette: ["#2f3b52", "#5a7ba6"],
    characters: { a: { name: "Ali", emoji: "🧑" }, b: { name: "Miss Kate", emoji: "👩‍🏫" } },
    lines: [
      { speaker: "b", text: "Hello!", ar: "مرحباً!" },
      { speaker: "a", text: "Hello.", ar: "مرحباً." },
      { speaker: "b", text: "What is your name?", ar: "ما اسمك؟" },
      { speaker: "a", text: "Ali. My name is Ali.", ar: "اسمي علي." },
      { speaker: "b", text: "Nice to meet you, Ali.", ar: "سعدت بلقائك يا علي." },
      { speaker: "a", text: "Nice to meet you.", ar: "سعدت بلقائك." },
      { speaker: "b", text: "How are you?", ar: "كيف حالك؟" },
      { speaker: "a", text: "I am fine, thank you.", ar: "أنا بخير، شكراً." },
      { speaker: "b", text: "Good! Class starts at nine.", ar: "جيد! تبدأ الحصة التاسعة." },
    ],
    quiz: [
      { q: "What is the student's name?", choices: ["Kate", "Ali", "Nine"], answer: 1 },
      { q: "When does class start?", choices: ["At nine", "At ten", "Now"], answer: 0 },
      { q: "“I am fine” answers…", choices: ["How are you?", "What is your name?", "Hello!"], answer: 0 },
    ],
  },
  {
    id: "prea1-sounds-sounds",
    lessonIds: ["lesson-prea1-sounds"],
    title: "Listening for sounds",
    levels: ["Pre-A1"],
    topics: ["sounds", "pronunciation", "letters", "listening"],
    setting: "A quiet classroom with big letter cards",
    prop: "🔤",
    palette: ["#41324f", "#7c5cbf"],
    characters: { a: { name: "Mona", emoji: "👩" }, b: { name: "Mr Ben", emoji: "🧑‍🏫" } },
    lines: [
      { speaker: "b", text: "Listen. Ship.", ar: "اسمع. Ship (سفينة)." },
      { speaker: "a", text: "Ship.", ar: "Ship." },
      { speaker: "b", text: "Good. Now: sheep.", ar: "جيد. الآن: sheep (خروف)." },
      { speaker: "a", text: "Sheep. Long sound.", ar: "Sheep. صوت طويل." },
      { speaker: "b", text: "Yes! Ship — short. Sheep — long.", ar: "نعم! Ship قصيرة، Sheep طويلة." },
      { speaker: "a", text: "Ship. Sheep. I hear it.", ar: "Ship. Sheep. أسمع الفرق." },
      { speaker: "b", text: "One more: cat, then cut.", ar: "واحدة أخرى: cat ثم cut." },
      { speaker: "a", text: "Cat. Cut. Easy!", ar: "Cat. Cut. سهل!" },
    ],
    quiz: [
      { q: "Which word has the long sound?", choices: ["Ship", "Sheep", "Cat"], answer: 1 },
      { q: "What does Mr Ben do first?", choices: ["Writes", "Says “ship”", "Opens the door"], answer: 1 },
      { q: "The lesson practises…", choices: ["numbers", "similar sounds", "greetings"], answer: 1 },
    ],
  },
  {
    id: "prea1-reading-signs",
    lessonIds: ["lesson-prea1-reading"],
    title: "Reading the street",
    levels: ["Pre-A1"],
    topics: ["reading", "signs", "labels", "city"],
    setting: "Walking down a busy shopping street",
    prop: "🪧",
    palette: ["#37474f", "#78909c"],
    characters: { a: { name: "Omar", emoji: "🧑" }, b: { name: "Lily", emoji: "👩" } },
    lines: [
      { speaker: "a", text: "Look. That says OPEN.", ar: "انظر. مكتوب OPEN (مفتوح)." },
      { speaker: "b", text: "Yes. The shop is open.", ar: "نعم. المتجر مفتوح." },
      { speaker: "a", text: "And that one? EXIT?", ar: "وهذا؟ EXIT؟" },
      { speaker: "b", text: "EXIT is the way out.", ar: "EXIT يعني المخرج." },
      { speaker: "a", text: "Toilet? Where?", ar: "Toilet؟ أين؟" },
      { speaker: "b", text: "There — the sign says TOILET.", ar: "هناك — اللافتة مكتوب TOILET." },
      { speaker: "a", text: "Thank you! I can read English.", ar: "شكراً! أستطيع قراءة الإنجليزية." },
    ],
    quiz: [
      { q: "What does EXIT mean?", choices: ["Way out", "Way in", "Stop"], answer: 0 },
      { q: "Which sign do they look for second?", choices: ["OPEN", "TOILET", "STOP"], answer: 1 },
      { q: "OPEN means the shop is…", choices: ["closed", "open", "full"], answer: 1 },
    ],
  },
  {
    id: "prea1-listening-cafe-word",
    lessonIds: ["lesson-prea1-listening"],
    title: "Catch the key word",
    levels: ["Pre-A1"],
    topics: ["listening", "numbers", "requests", "café"],
    setting: "Ordering at a busy market stall",
    prop: "🥤",
    palette: ["#4e342e", "#8d6e63"],
    characters: { a: { name: "Sara", emoji: "👩" }, b: { name: "Seller", emoji: "🧔" } },
    lines: [
      { speaker: "b", text: "Yes please?", ar: "تفضلي؟" },
      { speaker: "a", text: "Two juices, please.", ar: "عصيرين، من فضلك." },
      { speaker: "b", text: "Two? Or three?", ar: "اثنان؟ أم ثلاثة؟" },
      { speaker: "a", text: "Two. Only two.", ar: "اثنان. اثنان فقط." },
      { speaker: "b", text: "OK. Six pounds, please.", ar: "حسناً. ستة جنيهات، من فضلك." },
      { speaker: "a", text: "Six pounds? Here you are.", ar: "ستة جنيهات؟ تفضل." },
      { speaker: "b", text: "Thank you! Enjoy your day.", ar: "شكراً! نهارك سعيد." },
    ],
    quiz: [
      { q: "How many juices?", choices: ["Three", "Two", "Six"], answer: 1 },
      { q: "How much does she pay?", choices: ["£2", "£6", "£3"], answer: 1 },
      { q: "Which number word do you hear twice?", choices: ["Six", "Two", "Ten"], answer: 1 },
    ],
  },
  {
    id: "a1-intro-first-day",
    lessonIds: ["lesson-a1-self-introduction"],
    title: "Your first introduction",
    levels: ["A1"],
    topics: ["introduce yourself", "name", "job", "origin", "interests"],
    setting: "A new colleague's first day at the office",
    prop: "🪪",
    palette: ["#22354d", "#4a76a8"],
    characters: { a: { name: "Hassan", emoji: "🧑‍💼" }, b: { name: "Anna", emoji: "👩‍💼" } },
    lines: [
      { speaker: "b", text: "Hi! You're new here, right? I'm Anna.", ar: "مرحباً! أنت جديد هنا، صحيح؟ أنا آنا." },
      { speaker: "a", text: "Yes, today is my first day. I'm Hassan.", ar: "نعم، اليوم أول يوم لي. أنا حسن." },
      { speaker: "b", text: "Welcome, Hassan! Where are you from?", ar: "أهلاً حسن! من أين أنت؟" },
      { speaker: "a", text: "I'm from Egypt, from Alexandria.", ar: "أنا من مصر، من الإسكندرية." },
      { speaker: "b", text: "Nice! And what's your job?", ar: "جميل! وما عملك؟" },
      { speaker: "a", text: "I'm a designer. I make phone apps.", ar: "أنا مصمم. أصمم تطبيقات الهاتف." },
      { speaker: "b", text: "Great! What do you like doing?", ar: "رائع! ماذا تحب أن تفعل في وقت فراغك؟" },
      { speaker: "a", text: "I like football and cooking. Not at the same time!", ar: "أحب كرة القدم والطبخ. ليس في نفس الوقت!" },
      { speaker: "b", text: "Ha! Welcome to the team.", ar: "هاها! أهلاً بك في الفريق." },
    ],
    quiz: [
      { q: "Where is Hassan from?", choices: ["Egypt", "England", "Spain"], answer: 0 },
      { q: "What is his job?", choices: ["Teacher", "Designer", "Doctor"], answer: 1 },
      { q: "He likes football and…", choices: ["swimming", "cooking", "shopping"], answer: 1 },
    ],
  },
  {
    id: "a1-routines-morning",
    lessonIds: ["lesson-a1-routines"],
    title: "Talking about your day",
    levels: ["A1"],
    topics: ["routine", "present simple", "every day", "times"],
    setting: "Coffee break, two friends chatting",
    prop: "⏰",
    palette: ["#3e2723", "#795548"],
    characters: { a: { name: "Yasmin", emoji: "👩" }, b: { name: "Jack", emoji: "🧑" } },
    lines: [
      { speaker: "b", text: "What time do you get up?", ar: "في أي وقت تستيقظين؟" },
      { speaker: "a", text: "I get up at six every day.", ar: "أستيقظ السادسة كل يوم." },
      { speaker: "b", text: "Six! Why so early?", ar: "السادسة! لماذا بهذا الوقت المبكر؟" },
      { speaker: "a", text: "I go running before work.", ar: "أذهب للجري قبل العمل." },
      { speaker: "b", text: "Every day? Wow.", ar: "كل يوم؟ واو." },
      { speaker: "a", text: "No, not Sunday. Sunday I sleep!", ar: "لا، ليس الأحد. الأحد أنام!" },
      { speaker: "b", text: "What time do you start work?", ar: "متى تبدئين العمل؟" },
      { speaker: "a", text: "At nine. I have breakfast at eight.", ar: "التاسعة. أتناول الإفطار الثامنة." },
      { speaker: "b", text: "Your morning is full!", ar: "صباحك مليء بالأنشطة!" },
    ],
    quiz: [
      { q: "When does Yasmin get up?", choices: ["At six", "At eight", "At nine"], answer: 0 },
      { q: "What does she do before work?", choices: ["Goes running", "Sleeps", "Watches TV"], answer: 0 },
      { q: "On Sunday she…", choices: ["runs", "works", "sleeps"], answer: 2 },
    ],
  },
  {
    id: "a1-questions-smalltalk",
    lessonIds: ["lesson-a1-questions"],
    title: "Keeping the chat going",
    levels: ["A1"],
    topics: ["questions", "small talk", "who what where", "conversation"],
    setting: "Waiting for a delayed bus",
    prop: "🚌",
    palette: ["#263238", "#546e7a"],
    characters: { a: { name: "Karim", emoji: "🧑" }, b: { name: "Megan", emoji: "👩‍🦰" } },
    lines: [
      { speaker: "a", text: "Is this bus late too?", ar: "هل هذا الحافلة متأخرة أيضاً؟" },
      { speaker: "b", text: "Yes! I wait twenty minutes now.", ar: "نعم! أنتظر عشرين دقيقة الآن." },
      { speaker: "a", text: "Where do you go?", ar: "إلى أين تذهبين؟" },
      { speaker: "b", text: "To the city centre. And you?", ar: "إلى وسط المدينة. وأنت؟" },
      { speaker: "a", text: "Me too. Do you work there?", ar: "أنا أيضاً. هل تعملين هناك؟" },
      { speaker: "b", text: "Yes, in a bookshop. What about you?", ar: "نعم، في مكتبة. وأنت؟" },
      { speaker: "a", text: "I'm a student. I study English!", ar: "أنا طالب. أدرس الإنجليزية!" },
      { speaker: "b", text: "You speak very well.", ar: "أنت تتحدث جيداً جداً." },
      { speaker: "a", text: "Thank you! Here comes the bus.", ar: "شكراً! ها قد وصلت الحافلة." },
    ],
    quiz: [
      { q: "Where is Megan going?", choices: ["To the city centre", "Home", "To school"], answer: 0 },
      { q: "Where does she work?", choices: ["In a café", "In a bookshop", "At a school"], answer: 1 },
      { q: "Karim studies…", choices: ["maths", "English", "art"], answer: 1 },
    ],
  },
];
