/** In-platform animated learning scenes, part B (B1 → C2). */
import type { LearningScene } from "./scenes-types";

export const SCENES_B: LearningScene[] = [
  {
    id: "phone-appointment",
    title: "Booking an appointment by phone",
    levels: ["A2", "B1"],
    topics: ["phone", "appointment", "work", "arrange", "schedule", "time"],
    setting: "A quiet kitchen table, phone in hand",
    prop: "📞",
    palette: ["#1e3d33", "#3f7d63"],
    characters: { a: { name: "Adam", emoji: "🧑‍💼" }, b: { name: "Priya", emoji: "👩‍💼" } },
    lines: [
      { speaker: "b", text: "Good afternoon, Riverside Dental, Priya speaking. How can I help?", ar: "مساء الخير، عيادة ريفرسايد، معك بريا. كيف أساعدك؟" },
      { speaker: "a", text: "Hello. I'd like to book a check-up, please.", ar: "مرحباً. أود حجز موعد فحص، من فضلك.", note: "\"I'd like to book…\" = arranging politely." },
      { speaker: "b", text: "Of course. Are you already registered with us?", ar: "بالطبع. هل أنت مسجل لدينا؟" },
      { speaker: "a", text: "Yes, I am — Adam Foster. Do you have anything on Thursday morning?", ar: "نعم، آدم فوستر. هل لديكم موعد صباح الخميس؟" },
      { speaker: "b", text: "Let me see… Thursday at half past nine, or eleven o'clock?", ar: "لأرى… الخميس التاسعة والنصف أو الحادية عشرة؟", note: "\"Half past nine\" = 9:30." },
      { speaker: "a", text: "Half past nine suits me perfectly.", ar: "التاسعة والنصف تناسبني تماماً." },
      { speaker: "b", text: "Lovely. You're booked in for Thursday at 9:30 with Dr Ellis. Could you arrive ten minutes early?", ar: "رائع. تم حجزك الخميس 9:30 مع د. إيليس. هل تحضر قبلها بعشر دقائق؟" },
      { speaker: "a", text: "No problem. And if something comes up, what's the best number to call?", ar: "لا مشكلة. وإذا طرأ شيء، ما أفضل رقم للاتصال؟", note: "\"If something comes up\" = if plans change." },
      { speaker: "b", text: "The number you're calling now. We'll send a reminder the day before. Thank you, Adam.", ar: "الرقم الذي تتصل به الآن. سنرسل تذكيراً في اليوم السابق. شكراً آدم." },
    ],
    quiz: [
      { q: "What time is the appointment?", choices: ["9:00", "9:30", "11:00"], answer: 1 },
      { q: "What does \"if something comes up\" mean?", choices: ["If it rains", "If plans change unexpectedly", "If the phone rings"], answer: 1 },
      { q: "When will he get a reminder?", choices: ["Ten minutes before", "The day before", "Never"], answer: 1 },
    ],
  },
  {
    id: "airport-delay",
    title: "A flight delay at the airport",
    levels: ["B1", "B2"],
    topics: ["airport", "travel", "flight", "delay", "complaint", "transport"],
    setting: "Departure gate, evening, rain on the windows",
    prop: "✈️",
    palette: ["#122a44", "#3c6ea5"],
    characters: { a: { name: "Lina", emoji: "👩‍🦱" }, b: { name: "Gate Agent Tom", emoji: "👨‍✈️" } },
    lines: [
      { speaker: "a", text: "Excuse me, the board says our flight is delayed. Do you know what's happening?", ar: "عفواً، الشاشة تقول أن رحلتنا متأخرة. هل تعرف ما يجري؟", note: "\"Do you know what's happening?\" = polite info-seeking." },
      { speaker: "b", text: "I'm afraid there's a knock-on effect from the storm earlier. We're looking at about ninety minutes.", ar: "للأسفل هناك تأثير متتابع من العاصفة سابقاً. نتحدث عن نحو تسعين دقيقة.", note: "\"Knock-on effect\" = chain reaction of delays." },
      { speaker: "a", text: "That's frustrating — I have a connection in Frankfurt at nine.", ar: "هذا محبط — لدي رحلة ترانزيت في فرانكفورت التاسعة." },
      { speaker: "b", text: "Understood. Let me check whether your connection is still showing as scheduled… It is, but it's tight.", ar: "مفهوم. لأتحقق إن كانت رحلة الترانزيت لا تزال في الموعد… نعم لكن الوقت ضيق." },
      { speaker: "a", text: "Is there any chance of rebooking me onto a later one, just in case?", ar: "هل من الممكن إعادة حجزي على رحلة لاحقة احتياطاً؟", note: "\"Is there any chance of…?\" = tentative request." },
      { speaker: "b", text: "I can note it on your booking now, so if you miss it they'll rebook you automatically.", ar: "أستطيع تدوين ذلك في حجزك الآن، فإذا فاتتك سيُعاد الحجز تلقائياً." },
      { speaker: "a", text: "That would put my mind at rest. Thank you.", ar: "هذا يريحني كثيراً. شكراً لك.", note: "\"Put my mind at rest\" = stop worrying." },
      { speaker: "b", text: "You're welcome. We'll keep you updated over the announcements.", ar: "عفواً. سنوافيك بالمستجدات عبر الإعلانات." },
    ],
    quiz: [
      { q: "Why is the flight delayed?", choices: ["A strike", "Storm-related knock-on effects", "Technical failure"], answer: 1 },
      { q: "What does Tom do about her connection?", choices: ["Cancels it", "Notes it so she'll be rebooked automatically", "Says nothing can be done"], answer: 1 },
      { q: "\"Put my mind at rest\" means…", choices: ["make me sleepy", "stop me worrying", "confuse me"], answer: 1 },
    ],
  },
  {
    id: "job-interview",
    title: "The job interview",
    levels: ["B2", "C1"],
    topics: ["job", "interview", "work", "career", "cv", "strengths"],
    setting: "A glass-walled meeting room, city skyline behind",
    prop: "💼",
    palette: ["#23272e", "#4e5866"],
    characters: { a: { name: "Maya", emoji: "👩‍💻" }, b: { name: "Mr Hughes", emoji: "🧔‍♂️" } },
    lines: [
      { speaker: "b", text: "Thanks for coming in, Maya. To start, could you tell me a little about yourself?", ar: "شكراً لحضورك يا مايا. للبداية، حدثيني قليلاً عن نفسك.", note: "\"Tell me about yourself\" = your opening pitch." },
      { speaker: "a", text: "Of course. I've spent four years in customer analytics, and I led a team of three last year.", ar: "بالتأكيد. أمضيت أربع سنوات في تحليلات العملاء، وترأست فريقاً من ثلاثة العام الماضي.", note: "Present perfect for experience up to now." },
      { speaker: "b", text: "And what would you say is your greatest strength?", ar: "وما التي تراها أكبر نقاط قوتك؟" },
      { speaker: "a", text: "I'd say turning messy data into clear stories that teams actually act on.", ar: "أقول إن تحويل البيانات الفوضوية إلى قصص واضحة تعمل بها الفرق فعلاً.", note: "\"I'd say…\" = hedged self-description." },
      { speaker: "b", text: "Can you give me an example?", ar: "هل يمكنك تقديم مثال؟" },
      { speaker: "a", text: "Certainly. Our churn reports were ignored, so I rebuilt them around decisions, not metrics — retention rose eight per cent.", ar: "بالتأكيد. كانت تقارير فقدان العملاء مهملة، فأعدت بناءها حول القرارات لا الأرقام — فارتفعت نسبة البقاء ثمانية بالمئة.", note: "STAR-style answer: situation → action → result." },
      { speaker: "b", text: "Impressive. And where do you see yourself in five years' time?", ar: "مؤثر. وأين ترين نفسك بعد خمس سنوات؟" },
      { speaker: "a", text: "Leading this function, ideally — and mentoring others the way good managers once mentored me.", ar: "قائدة لهذا القسم مثالياً — وأوجّه الآخرين كما وجّهني مديرون جيدون سابقاً." },
      { speaker: "b", text: "Thank you. We'll be in touch by Friday — do you have any questions for us?", ar: "شكراً لك. سنتواصل بحلول الجمعة — هل لديك أسئلة لنا؟", note: "Always have a question ready." },
      { speaker: "a", text: "Just one: how does success look for this role in the first six months?", ar: "سؤال واحد فقط: كيف يبدو النجاح في هذا الدور خلال أول ستة أشهر؟" },
    ],
    quiz: [
      { q: "How does Maya frame her experience?", choices: ["Simple past only", "Present perfect + a concrete result", "Future plans"], answer: 1 },
      { q: "Her rebuilt reports led to…", choices: ["eight per cent better retention", "three new clients", "no change"], answer: 0 },
      { q: "Why ask a question at the end?", choices: ["To fill time", "It signals genuine interest and preparation", "To negotiate salary"], answer: 1 },
    ],
  },
  {
    id: "meeting-disagree",
    title: "Disagreeing politely in a meeting",
    levels: ["B2", "C1"],
    topics: ["meeting", "opinion", "agree", "disagree", "team", "suggest"],
    setting: "A stand-up style meeting room, whiteboard full of notes",
    prop: "🧑‍🏫",
    palette: ["#3a2417", "#7a5230"],
    characters: { a: { name: "Tarek", emoji: "🧑‍💼" }, b: { name: "Hannah", emoji: "👩‍🦰" } },
    lines: [
      { speaker: "b", text: "So, proposal: we launch in all five cities at once. Thoughts?", ar: "إذن، الاقتراح: نطلق في المدن الخمس دفعة واحدة. آراؤكم؟" },
      { speaker: "a", text: "I see the appeal, but I'm slightly worried about spreading support too thin.", ar: "أرى الجاذبية، لكنني قلق قليلاً من تشتيت الدعم.", note: "\"I see the appeal, but…\" = respectful disagreement." },
      { speaker: "b", text: "Fair point. What would concern you most, specifically?", ar: "وجهة نظر عادلة. وما يقلقك أكثر بالتحديد؟" },
      { speaker: "a", text: "Response times. Last quarter, two cities doubled our ticket load overnight.", ar: "سرعة الاستجابة. الربع الماضي ضاعفت مدينتان أحمال التذاكر بين ليلة وضحاها." },
      { speaker: "b", text: "That's a fair concern. Would phasing help — say, three first, then the rest?", ar: "قلق منطقي. هل يساعد التقسيم المرحي — ثلاث أولاً ثم البقية؟", note: "\"Would … help?\" = inviting compromise." },
      { speaker: "a", text: "Phasing would work for us. Could we also agree a pause trigger if quality dips?", ar: "التصعيد المرحلي يناسبنا. هل نتفق أيضاً على مؤشر توقف إذا تراجعت الجودة؟", note: "\"Pause trigger\" = agreed safety switch." },
      { speaker: "b", text: "Agreed. If satisfaction drops below ninety per cent, we hold the next phase.", ar: "اتفقنا. إذا هبطت الرضا تحت تسعين بالمئة نجمّد المرحلة التالية." },
      { speaker: "a", text: "Perfect. That way we keep momentum without gambling on quality.", ar: "ممتاز. هكذا نحافظ على الزخم دون مقامرة بالجودة.", note: "\"Keep momentum without gambling on…\" = balanced close." },
    ],
    quiz: [
      { q: "How does Tarek open his disagreement?", choices: ["You're wrong", "I see the appeal, but…", "Absolutely not"], answer: 1 },
      { q: "What compromise emerges?", choices: ["Launch everywhere anyway", "Phase the launch with a pause rule", "Delay six months"], answer: 1 },
      { q: "\"Spreading too thin\" means…", choices: ["expanding resources", "overextending capacity", "losing money"], answer: 1 },
    ],
  },
  {
    id: "salary-conversation",
    title: "Discussing a pay rise",
    levels: ["C1", "C2"],
    topics: ["salary", "negotiate", "work", "raise", "career", "money"],
    setting: "Manager's office, door closed, calm atmosphere",
    prop: "📈",
    palette: ["#26221f", "#5c5044"],
    characters: { a: { name: "Salma", emoji: "👩‍💼" }, b: { name: "Richard", emoji: "👔" } },
    lines: [
      { speaker: "a", text: "Thanks for making time. I'd like to discuss my remuneration in light of this year's results.", ar: "شكراً لتخصيص الوقت. أود مناقشة تعويضي في ضوء نتائج هذا العام.", note: "\"In light of…\" = justifying with evidence." },
      { speaker: "b", text: "Go ahead. I agree the numbers were strong — walk me through your case.", ar: "تفضلي. أوافق أن الأرقام كانت قوية — اعرضي عليّ حجتك." },
      { speaker: "a", text: "Two points. Revenue per client is up twelve per cent since I took over the account portfolio.", ar: "نقطتان. ارتفع العائد لكل عميل اثني عشر بالمئة منذ توليت محفظة الحسابات." },
      { speaker: "a", text: "Second, I've absorbed the coordination role from operations without additional cover, which saved roughly one headcount.", ar: "ثانياً، استوعبت دور التنسيق من العمليات دون تغطية إضافية، مما وفّر تقريباً وظيفة كاملة.", note: "\"Without additional cover\" = no extra hire needed." },
      { speaker: "b", text: "Both verifiable, I'll grant you. What figure did you have in mind?", ar: "كلتاهما يمكن التحقق منهما، أمنحك ذلك. ما الرقم الذي في ذهنك؟" },
      { speaker: "a", text: "Benchmarked against similar roles, I'm thinking of a move to the upper quartile rather than a token adjustment.", ar: "بالمقارنة بأدوار مشابهة، أفكر بالانتقال إلى الربع الأعلى لا بتعديل رمزي.", note: "\"Upper quartile\" = top-quarter pay band." },
      { speaker: "b", text: "That's ambitious. I can commit to a staged review: a rise now, and a formal reassessment after Q2 targets are met.", ar: "هذا طموح. أستطيع الالتزام بمراجعة متدرجة: زيارة الآن، وإعادة تقييم رسمية بعد تحقيق مستهدفات الربع الثاني." },
      { speaker: "a", text: "Provided the reassessment criteria are written down, that feels like a fair path forward.", ar: "بشرط كتابة معايير إعادة التقييم، يبدو لي ذلك مساراً عادلاً.", note: "\"Provided (that)…\" = conditional acceptance." },
    ],
    quiz: [
      { q: "Which evidence does Salma NOT use?", choices: ["Revenue growth", "Absorbed extra duties", "Her long commute"], answer: 2 },
      { q: "\"Upper quartile\" refers to…", choices: ["top-quarter pay band", "four-week holiday", "quarterly bonus"], answer: 0 },
      { q: "Her final sentence shows…", choices: ["rejection", "conditional agreement", "uncertainty"], answer: 1 },
    ],
  },
  {
    id: "seminar-debate",
    title: "Summarising an academic debate",
    levels: ["C1", "C2"],
    topics: ["academic", "summarise", "debate", "research", "media", "technology"],
    setting: "University seminar room, projector glowing",
    prop: "🎓",
    palette: ["#191b2a", "#40456b"],
    characters: { a: { name: "Dr Chen", emoji: "🧑‍🏫" }, b: { name: "Fatima", emoji: "👩‍🎓" } },
    lines: [
      { speaker: "a", text: "Fatima, could you draw today's discussion together for us?", ar: "فتيمة، هل يمكنك تلخيص نقاش اليوم لنا؟", note: "\"Draw together\" = synthesise." },
      { speaker: "b", text: "Gladly. Broadly, we weighed two framings of algorithmic curation: empowerment versus manipulation.", ar: "بكل سرور. عموماً وزنّا تصورين للتنظيم الخوارزمي: التمكين مقابل التلاعب." },
      { speaker: "a", text: "And where did the weight of evidence seem to lie?", ar: "وأين بدت حجة الأدلة أرجح؟" },
      { speaker: "b", text: "Inconclusively. The empowerment camp cites user autonomy; the sceptics counter that choice architecture is rarely neutral.", ar: "بشكل غير حاسم. معسكر التمكين يستشهد باستقلالية المستخدم؛ والمتشككون يقابلون بأن بنية الاختيار نادراً ما تكون محايدة." },
      { speaker: "a", text: "Nicely put. Any methodological reservations worth flagging?", ar: "قالها بإتقان. أي تحفظات منهجية تستحق الإشارة؟" },
      { speaker: "b", text: "Mostly that the longitudinal studies skew towards Western platforms, which arguably limits generalisability.", ar: "غالباً أن الدراسات الطولية تنحاز نحو المنصات الغربية، مما قد يحد من قابلية التعميم.", note: "\"Arguably\" = calibrated hedging." },
      { speaker: "a", text: "An excellent caveat. How might we test that limitation?", ar: "تحفظ ممتاز. كيف قد نختبر هذا القيد؟" },
      { speaker: "b", text: "A cross-regional replication would be the natural next step — same instruments, contrasting media ecosystems.", ar: "التكرار عبر المناطق هو الخطوة الطبيعية التالية — نفس الأدوات، نظم إعلامية متباينة." },
    ],
    quiz: [
      { q: "The two framings debated are…", choices: ["cost versus speed", "empowerment versus manipulation", "privacy versus profit"], answer: 1 },
      { q: "\"Generalisability\" concerns…", choices: ["how widely findings apply", "data storage", "user interface design"], answer: 0 },
      { q: "Her proposed next step is…", choices: ["abandoning the topic", "cross-regional replication", "a literature review"], answer: 1 },
    ],
  },
];
