/** Lesson-specific scenes: B2 reading + C1 discussion/writing/listening/reading. */
import type { LearningScene } from "./scenes-types";

export const SCENES_F: LearningScene[] = [
  {
    id: "b2-reading-review",
    lessonIds: [],
    title: "Reading between the lines",
    levels: ["B2"],
    topics: ["reading", "attitude", "inference", "tone", "review"],
    setting: "Two friends debating a scathing restaurant review",
    prop: "🍽️",
    palette: ["#3a1f24", "#7d4048"],
    characters: { a: { name: "Lina", emoji: "👩" }, b: { name: "Tom", emoji: "🧑" } },
    lines: [
      { speaker: "b", text: "The reviewer calls the menu “ambitious, occasionally successfully so”. What's the real message?", ar: "يسمي الناقد القائمة طموحة، ناجحة أحياناً. ما الرسالة الحقيقية؟" },
      { speaker: "a", text: "Polite disappointment. The qualifier does all the work.", ar: "خيبة أمل مهذبة. التقييد يحمل كل المعنى." },
      { speaker: "b", text: "And this line: “the service had its own sense of time.”?", ar: "وهذه الجملة: الخدمة لديها إحساسها الخاص بالوقت؟" },
      { speaker: "a", text: "It means slow — but he's too elegant to say it outright.", ar: "تعني بطء — لكنه راقٍ أكثر من قولها صراحة." },
      { speaker: "b", text: "Why open with the chef's biography at all?", ar: "لماذا يفتتح بسيرة الشيف أصلاً؟" },
      { speaker: "a", text: "To raise expectations — so the criticism lands harder later. Deliberate contrast.", ar: "لرفع التوقعات — فتكون الانتقادات أقسى لاحقاً. تباين مقصود." },
      { speaker: "b", text: "Does he ever recommend it, though? I lost track of his verdict.", ar: "لكن هل يوصي بها؟ فقدتُ خيط حكمه." },
      { speaker: "a", text: "“Worth visiting once, perhaps twice if you order wisely.” That's three stars wearing a suit.", ar: "يستحق الزيارة مرة، وربما مرتين إن طلبت بحكمة. ثلاث نجوم ببدلة." },
      { speaker: "b", text: "You read reviews like X-rays. Book us a table anyway!", ar: "أنتِ تقرأين المراجعات كأشعة سينية. احجزي لنا طاولة على أي حال!" },
    ],
    quiz: [
      { q: "“Occasionally successfully so” signals…", choices: ["strong praise", "polite disappointment", "confusion"], answer: 1 },
      { q: "The service comment really means it was…", choices: ["fast", "slow", "friendly"], answer: 1 },
      { q: "Opening with the chef's bio is designed to…", choices: ["praise him", "raise then undercut expectations", "fill space"], answer: 1 },
    ],
  },
  {
    id: "c1-discussion-moderating",
    lessonIds: ["lesson-24-society-politics-global"],
    title: "Leading a complex discussion",
    levels: ["C1"],
    topics: ["discussion", "moderating", "nuance", "turn-taking"],
    setting: "A policy roundtable, five voices, one moderator",
    prop: "🏛️",
    palette: ["#20293a", "#4c6a92"],
    characters: { a: { name: "Dr Amal", emoji: "👩‍⚖️" }, b: { name: "Councillor Reid", emoji: "🧑‍🌾" } },
    lines: [
      { speaker: "a", text: "Before we diverge further, let me triangulate what I'm hearing.", ar: "قبل أن نتباعد أكثر، دعوني أجمّع ما أسمعه." },
      { speaker: "a", text: "Reid backs congestion charging; Okafor fears regressive effects. Have I framed that fairly?", ar: "ريد يدعم رسوم الازدحام؛ أوكافور يخشى آثارها التصحيحية على الفقراء. هل صغت الأمر بعدل؟" },
      { speaker: "b", text: "Fairly, yes — though I'd add rural commuters are the real losers here.", ar: "بعدل، نعم — لكن أضف أن سكان الريف هم الخاسرون الحقيقيون." },
      { speaker: "a", text: "Noted. So the crux isn't whether to charge, but whom the exemption should shield.", ar: "دُوّن. إذن الجوهر ليس هل نتقاضى رسوماً بل مَن يشملهم الإعفاء." },
      { speaker: "b", text: "Precisely. A flat charge punishes those with no alternative.", ar: "بالضبط. الرسوم الموحدة تعاقب من لا بديل لديه." },
      { speaker: "a", text: "Then let's stress-test an exemption for postcode areas lacking transport links.", ar: "إذن لنختبر تحت الضغط إعفاءً للمناطق التي تفتقر لروابط النقل." },
      { speaker: "b", text: "Workable in principle — the devil will be in the mapping criteria.", ar: "قابل للتطبيق مبدئياً — والشيطان سيكون في معايير الرسم." },
      { speaker: "a", text: "Which we delegate to data, not debate. Moving on — housing, anyone?", ar: "ونفوّض ذلك للبيانات لا للجدال. ننتقل — الإسكان، من يبدأ؟" },
    ],
    quiz: [
      { q: "What is Dr Amal's moderating move at the start?", choices: ["Picking a winner", "Triangulating both positions", "Closing the topic"], answer: 1 },
      { q: "The reframed crux concerns…", choices: ["whether to charge", "who exemptions protect", "rural roads funding"], answer: 1 },
      { q: "Her phrase “the devil will be in…” is completed by Reid as…", choices: ["mapping criteria", "public anger", "legal costs"], answer: 0 },
    ],
  },
  {
    id: "c1-writing-brief",
    lessonIds: ["lesson-23-leadership-personal-development"],
    title: "Precision writing under review",
    levels: ["C1"],
    topics: ["writing", "precision", "register", "editing"],
    setting: "Editor's office, one page of prose between them",
    prop: "🖋️",
    palette: ["#26202b", "#5f4b73"],
    characters: { a: { name: "Nadia", emoji: "👩‍💻" }, b: { name: "Editor Ruth", emoji: "👵" } },
    lines: [
      { speaker: "b", text: "Your opening sentence is doing three jobs. It should do one.", ar: "جملتك الافتتاحية تقوم بثلاث وظائف. ينبغي أن تقوم بواحدة." },
      { speaker: "a", text: "So cut the context clause and let the claim stand alone?", ar: "إذن أحذف جملة السياق وأترك الادعاء وحدته؟" },
      { speaker: "b", text: "Yes. Precision is subtraction with intent, not decoration with adjectives.", ar: "نعم. الدقة هي الطرح بقصد، لا الزخرفة بالصفات." },
      { speaker: "a", text: "What about register? The brief targets senior policymakers.", ar: "وماذا عن السجل؟ الموجّه يستهدف صناع قرار كبار." },
      { speaker: "b", text: "Formal, not frozen. Replace “utilise” with “use” and keep your contractions out.", ar: "رسمي لا متجمد. استبدلي utilise ب use واحذفي الصيغ المختصرة." },
      { speaker: "a", text: "One more pass on hedging — my claims read either absolute or timid.", ar: "مرور أخير على التحوط — ادعاءاتي إما مطلقة أو مترددة." },
      { speaker: "b", text: "Calibrate: “evidence suggests”, never “proves”; commit where data is firm.", ar: "معايرة: تشير الأدلة، أبداً يثبت؛ والتزم حيث البيانات راسخة." },
      { speaker: "a", text: "Rewrite by tomorrow morning, tighter by a third.", ar: "سأعيد الكتابة غداً صباحاً، أكثر إحكاماً بالثلث." },
      { speaker: "b", text: "I'll know within one paragraph whether you nailed it. Off you go.", ar: "سأعرف خلال فقرة واحدة إن كنتِ أتقنتِ. هيا." },
    ],
    quiz: [
      { q: "Ruth's core editing principle is…", choices: ["subtraction with intent", "richer vocabulary", "longer sentences"], answer: 0 },
      { q: "The right register for policymakers is described as…", choices: ["frozen formal", "formal, not frozen", "conversational"], answer: 1 },
      { q: "Correct calibrated hedging uses…", choices: ["“proves”", "“evidence suggests”", "no verbs of claim"], answer: 1 },
    ],
  },
  {
    id: "c1-listening-interview",
    lessonIds: ["lesson-22-psychology-human-mind"],
    title: "The meaning behind the words",
    levels: ["C1"],
    topics: ["listening", "inference", "attitude", "interview"],
    setting: "A radio interview with a retiring judge",
    prop: "📡",
    palette: ["#1d2521", "#486958"],
    characters: { a: { name: "Host Sam", emoji: "🎙️" }, b: { name: "Judge Ellis", emoji: "🧓" } },
    lines: [
      { speaker: "a", text: "Thirty years on the bench. Any regrets about how sentencing evolved?", ar: "ثلاثون عاماً في القضاء. أي ندمان على تطور الأحكام؟" },
      { speaker: "b", text: "Regret is a strong word. Let's say certain reforms tested my patience rather than my principles.", ar: "الندمة كلمة قوية. لنقل إن بعض الإصلاحات اختبرت صبري لا مبادئي." },
      { speaker: "a", text: "That's a carefully built sentence. Which reforms did you mean?", ar: "تلك جملة مصاغة بعناية. أي إصلاحات تقصد؟" },
      { speaker: "b", text: "If I answered that directly, tomorrow's headline would write itself — and it would be wrong.", ar: "لو أجبت مباشرة لكتبت عناوين الغد نفسها — وكانت خاطئة." },
      { speaker: "a", text: "So we infer rather than hear. Noted. Did shorter sentences reduce reoffending?", ar: "إذن نستنتج ولا نسمع. مفهوم. هل قصر مدد العقوبات خفض عودة الجريمة؟" },
      { speaker: "b", text: "The data says less than either side wishes. Reality resists tidy narratives.", ar: "البيانات تقول أقل مما يتمنى الطرفان. الواقع يقاوم السرديات المرتبة." },
      { speaker: "a", text: "A diplomatic non-answer, Judge — but a revealing one. Final thoughts?", ar: "إجابة دبلوماسية غائبة يا قاضٍ — لكنها كاشفة. كلمات أخيرة؟" },
      { speaker: "b", text: "Read judgments, not headlines. The gap between them is where truth lives.", ar: "اقرؤوا الأحكام لا العناوين. الفجوة بينهما هي موطن الحقيقة." },
    ],
    quiz: [
      { q: "“Tested my patience rather than my principles” implies…", choices: ["deep regret", "irritation without disagreement", "full approval"], answer: 1 },
      { q: "Why won't he name the reforms?", choices: ["He forgot", "Headlines would distort it", "Legal prohibition"], answer: 1 },
      { q: "His closing advice privileges…", choices: ["headlines", "judgments", "statistics"], answer: 1 },
    ],
  },
  {
    id: "c1-reading-critique",
    lessonIds: [],
    title: "Evaluating claims critically",
    levels: ["C1"],
    topics: ["reading", "critical", "rhetoric", "assumptions", "evaluation"],
    setting: "A postgraduate seminar dissecting an opinion piece",
    prop: "🔍",
    palette: ["#232733", "#576081"],
    characters: { a: { name: "Professor Hale", emoji: "🧑‍🏫" }, b: { name: "Fatima", emoji: "👩‍🎓" } },
    lines: [
      { speaker: "a", text: "The piece argues automation anxiety is cyclical. Where's the load-bearing assumption?", ar: "المقال يجادل بأن قلق الأتمتة دوري. أين الافتراض المحوري؟" },
      { speaker: "b", text: "That past adaptation predicts future adaptation — history as guarantee.", ar: "أن التكيف السابق يتنبأ بالتكيف القادم — التاريخ كضمانة." },
      { speaker: "a", text: "Good. And that assumption is doing rhetorical work beyond evidence. Why deploy it?", ar: "جيد. وهذا الافتراض يؤدي عملاً بلاغياً يتجاوز الدليل. لماذا يُستخدم؟" },
      { speaker: "b", text: "It flatters readers who already feel reassured — confirmation dressed as analysis.", ar: "يُدليل القراء المطمئنين أصلاً — تأكيد متنكر في صورة تحليل." },
      { speaker: "a", text: "Now the statistics: employment rates since 1990. What can't they show?", ar: "والآن الإحصاءات: معدلات التوظيف منذ 1990. ما الذي لا تستطيع إظهاره؟" },
      { speaker: "b", text: "Composition and precarity — aggregate employment can rise while quality collapses.", ar: "التركيبة والهشاشة — قد يرتفع التوظيف الكلي بين تنهار جودة الوظائف." },
      { speaker: "a", text: "So the strongest counter reads quality-adjusted employment into the same data?", ar: "إذن أقوى نقد يقرأ التوظيف المعدَّل بالجودة في نفس البيانات؟" },
      { speaker: "b", text: "Exactly — refute from within, using their own numbers, better interpreted.", ar: "بالضبط — نقضِ من الداخل، بأرقامهم نفسها، أفضل تفسيراً." },
    ],
    quiz: [
      { q: "The article's load-bearing assumption is…", choices: ["history guarantees future adaptation", "automation is new", "readers are anxious"], answer: 0 },
      { q: "Aggregate employment stats cannot reveal…", choices: ["job quality", "total jobs", "dates"], answer: 0 },
      { q: "Fatima's recommended rebuttal strategy is…", choices: ["rejecting the data entirely", "reinterpreting their own data", "changing the subject"], answer: 1 },
    ],
  },
];
