/** Lesson-specific scenes: new flagship bindings for lessons 08, 09, 11, 14, 16, 20, 21. */
import type { LearningScene } from "./scenes-types";

export const SCENES_H: LearningScene[] = [
  {
    id: "a2-future-roadmap",
    lessonIds: ["lesson-08-future-plans"],
    title: "Plans for next year",
    levels: ["A2"],
    topics: ["future", "plans", "going to", "ambitions", "arrangements"],
    setting: "Two friends with coffee, sketching plans on a napkin",
    prop: "🗓️",
    palette: ["#1b3a4b", "#4f8a8b"],
    characters: { a: { name: "Nour", emoji: "👩" }, b: { name: "Tom", emoji: "🧑" } },
    lines: [
      { speaker: "b", text: "So, what are you going to do next year?", ar: "إذن، ماذا ستفعلين العام القادم؟" },
      { speaker: "a", text: "I'm going to study design in Canada.", ar: "سأدرس التصميم في كندا." },
      { speaker: "b", text: "Wow! When are you leaving?", ar: "واو! متى ستسافرين؟" },
      { speaker: "a", text: "In September. I've already applied.", ar: "في سبتمبر. لقد قدّمت الطلب بالفعل." },
      { speaker: "b", text: "And after that?", ar: "وماذا بعد ذلك؟" },
      { speaker: "a", text: "I hope I'll work for a big studio.", ar: "آمل أن أعمل في استوديو كبير." },
      { speaker: "b", text: "You will — your work is great.", ar: "ستنجحين — أعمالك رائعة." },
      { speaker: "a", text: "Thanks! What about you? Any plans?", ar: "شكراً! وأنت؟ هل لديك خطط؟" },
      { speaker: "b", text: "I'm starting my own bakery. That's the dream.", ar: "سأفتح مخبزي الخاص. هذا هو الحلم." },
    ],
    quiz: [
      { q: "What is Nour going to study?", choices: ["Baking", "Design", "Medicine"], answer: 1 },
      { q: "When is she leaving?", choices: ["Next month", "In September", "Next week"], answer: 1 },
      { q: "Tom's dream is…", choices: ["a big studio", "his own bakery", "travelling"], answer: 1 },
    ],
  },
  {
    id: "a2-learning-study-group",
    lessonIds: ["lesson-09-education-learning"],
    title: "The study group",
    levels: ["A2"],
    topics: ["study", "exams", "learning", "online courses"],
    setting: "Library table covered with notes before exams",
    prop: "📚",
    palette: ["#3e2c23", "#8d6e63"],
    characters: { a: { name: "Lina", emoji: "👩‍🎓" }, b: { name: "Diego", emoji: "🧑‍🎓" } },
    lines: [
      { speaker: "a", text: "How's your studying going?", ar: "كيف تسير دراستك؟" },
      { speaker: "b", text: "Slowly! I have three exams next week.", ar: "ببطء! لدي ثلاثة امتحانات الأسبوع القادم." },
      { speaker: "a", text: "Me too. Do you want to study together?", ar: "وأنا أيضاً. هل تريد أن ندرس معاً؟" },
      { speaker: "b", text: "Good idea. Where do you study best?", ar: "فكرة جيدة. أين تدرسين أفضل؟" },
      { speaker: "a", text: "Here, or online with flashcards.", ar: "هنا، أو عبر الإنترنت ببطاقات المراجعة." },
      { speaker: "b", text: "I prefer practice questions.", ar: "أفضّل أسئلة التدريب." },
      { speaker: "a", text: "Let's do both. Half an hour each?", ar: "لنفعل الاثنين. نصف ساعة لكل واحد؟" },
      { speaker: "b", text: "Deal. Coffee first!", ar: "اتفاق. القهوة أولاً!" },
    ],
    quiz: [
      { q: "How many exams does Diego have?", choices: ["One", "Three", "Ten"], answer: 1 },
      { q: "What does Lina use online?", choices: ["Flashcards", "Videos of cats", "Practice exams"], answer: 0 },
      { q: "What do they do first?", choices: ["Study", "Get coffee", "Go home"], answer: 1 },
    ],
  },
  {
    id: "a2-phone-message-etiquette",
    lessonIds: ["lesson-11-communication-technology"],
    title: "Sorry, wrong message!",
    levels: ["A2"],
    topics: ["phones", "messages", "email", "online politeness"],
    setting: "A phone buzzes at the worst possible moment",
    prop: "📱",
    palette: ["#263238", "#607d8b"],
    characters: { a: { name: "Adam", emoji: "🧑" }, b: { name: "Salma", emoji: "👩" } },
    lines: [
      { speaker: "b", text: "You look worried. What's wrong?", ar: "تبدو قلقاً. ما المشكلة؟" },
      { speaker: "a", text: "I sent a complaint to my boss by mistake.", ar: "أرسلت شكوى لمديري بالخطأ." },
      { speaker: "b", text: "Oh no! What did you write?", ar: "يا للأسف! ماذا كتبت؟" },
      { speaker: "a", text: "That the meeting was too long.", ar: "أن الاجتماع كان طويلاً جداً." },
      { speaker: "b", text: "Send a quick apology email. Keep it short.", ar: "أرسل بريداً سريعاً للاعتذار. اجعله مختصراً." },
      { speaker: "a", text: "\"Dear Mr Lee, I'm sorry about my last message…\"", ar: "\u201cعزيزي السيد لي، أعتذر عن رسالتي الأخيرة...\u201d" },
      { speaker: "b", text: "Perfect. Next time, check the address first!", ar: "ممتاز. في المرة القادمة، تحقق من العنوان أولاً!" },
      { speaker: "a", text: "Lesson learned. He replied: \"No problem.\"", ar: "عبرتُ الدرس. ردّ: \u201cلا مشكلة.\u201d" },
    ],
    quiz: [
      { q: "Who got Adam's message by mistake?", choices: ["His friend", "His boss", "A customer"], answer: 1 },
      { q: "What did the message say?", choices: ["The meeting was too long", "He quit his job", "The wifi was broken"], answer: 0 },
      { q: "What advice does Salma give?", choices: ["Ignore it", "Write a long letter", "Send a short apology"], answer: 2 },
    ],
  },
  {
    id: "b1-money-budget-talk",
    lessonIds: ["lesson-14-money-personal-finance"],
    title: "Where does the money go?",
    levels: ["B1"],
    topics: ["budget", "saving", "banking", "spending habits"],
    setting: "Flatmates reviewing bills at the kitchen table",
    prop: "💰",
    palette: ["#1f3d2b", "#4e7a51"],
    characters: { a: { name: "Yusuf", emoji: "🧑" }, b: { name: "Emma", emoji: "👩" } },
    lines: [
      { speaker: "b", text: "We overspent again this month. Look at this.", ar: "أفرطنا في الإنفاق هذا الشهر. انظر إلى هذا." },
      { speaker: "a", text: "Ouch. Delivery food again — that's twice a week.", ar: "أوخ. طعام التوصيل مجدداً — مرتان أسبوعياً." },
      { speaker: "b", text: "Let's set a simple budget. Essentials first.", ar: "لنضع ميزانية بسيطة. الأساسيات أولاً." },
      { speaker: "a", text: "Rent, bills, transport… then savings?", ar: "الإيجار، الفواتير، المواصلات... ثم المدخرات؟" },
      { speaker: "b", text: "Exactly. Ten percent straight into savings on payday.", ar: "بالضبط. عشرة بالمئة مباشرة إلى المدخرات يوم الراتب." },
      { speaker: "a", text: "And a small fund for emergencies?", ar: "وصندوق صغير للطوارئ؟" },
      { speaker: "b", text: "Good thinking. Three months of expenses, ideally.", ar: "تفكير سليم. ثلاثة أشهر من المصاريف، في الأفضل." },
      { speaker: "a", text: "Agreed. Cooking at home starts tonight!", ar: "موافق. الطبخ في المنزل يبدأ الليلة!" },
    ],
    quiz: [
      { q: "What did they overspend on?", choices: ["Rent", "Delivery food", "Transport"], answer: 1 },
      { q: "How much goes into savings?", choices: ["Half", "Nothing", "Ten percent"], answer: 2 },
      { q: "An emergency fund should ideally cover…", choices: ["one day", "three months", "ten years"], answer: 1 },
    ],
  },
  {
    id: "b1-festival-neighbourhood",
    lessonIds: ["lesson-16-society-culture"],
    title: "Festival night on our street",
    levels: ["B1"],
    topics: ["festivals", "culture", "traditions", "community"],
    setting: "A street festival with food stalls from five countries",
    prop: "🏮",
    palette: ["#4a148c", "#ce93d8"],
    characters: { a: { name: "Rania", emoji: "👩🏽" }, b: { name: "Peter", emoji: "🧔" } },
    lines: [
      { speaker: "b", text: "I've never seen so many lanterns on one street!", ar: "لم أرَ قط عدداً من الفوانيس كهذا في شارع واحد!" },
      { speaker: "a", text: "Every community brought something. Try these dumplings.", ar: "كل مجتمع أحضر شيئاً. جرّب هذه الزلابية." },
      { speaker: "b", text: "Delicious! And the music earlier — was that a wedding?", ar: "لذيذة! والموسيقى قبل قليل — هل كان حفل زفاف؟" },
      { speaker: "a", text: "No, it's a traditional dance from my country. Come, I'll show you.", ar: "لا، إنها رقصة تقليدية من بلدي. تعال، سأريك إياها." },
      { speaker: "b", text: "Is everyone welcome to join?", ar: "هل يمكن للجميع المشاركة؟" },
      { speaker: "a", text: "Of course — that's the whole point of tonight.", ar: "بالطبع — هذه هي فكرة الليلة كلها." },
      { speaker: "b", text: "Honestly, festivals like this make the city feel smaller.", ar: "بصراحة، حفلات مثل هذه تجعل المدينة تبدو أصغر." },
      { speaker: "a", text: "Same traditions, different tables. That's our street.", ar: "تقاليد واحدة، موائد مختلفة. هذا هو شارعنا." },
    ],
    quiz: [
      { q: "What has every community brought?", choices: ["Lanterns only", "Something to share", "Wedding gifts"], answer: 1 },
      { q: "The music came from…", choices: ["a wedding", "a traditional dance", "a concert hall"], answer: 1 },
      { q: "According to Rania, the point of tonight is…", choices: ["selling food", "everyone joining in", "watching quietly"], answer: 1 },
    ],
  },
  {
    id: "b2-ai-panel-future",
    lessonIds: ["lesson-20-technology-digital-future"],
    title: "AI panel: threat or tool?",
    levels: ["B2"],
    topics: ["AI", "automation", "future of work", "privacy"],
    setting: "Panel discussion at a tech conference, audience mic live",
    prop: "🤖",
    palette: ["#102027", "#37474f"],
    characters: { a: { name: "Dr Chen", emoji: "👩‍🔬" }, b: { name: "Moderator", emoji: "🎙️" } },
    lines: [
      { speaker: "b", text: "Dr Chen, critics say AI will replace entire professions. Your response?", ar: "دكتورة تشين، يقول النقاد إن الذكاء الاصطناعي سيحل محل مهن كاملة. ما ردك؟" },
      { speaker: "a", text: "History suggests tools transform jobs rather than erase them — but the transition hurts.", ar: "التاريخ يشير إلى أن الأدوات تُحوّل الوظائف ولا تمحوها — لكن مرحلة الانتقال مؤلمة." },
      { speaker: "b", text: "So should workers be retraining now?", ar: "إذن هل يجب على العمال إعادة التأهيل الآن؟" },
      { speaker: "a", text: "Absolutely. The scarce skill is judgment — knowing what to ask the machine.", ar: "بالتأكيد. المهارة النادرة هي الحكم — معرفة ما نسأل الآلة عنه." },
      { speaker: "b", text: "And privacy concerns around training data?", ar: "وماذا عن مخاوف الخصوصية حول بيانات التدريب؟" },
      { speaker: "a", text: "Legitimate ones. Regulation is catching up, but slowly — citizens should demand better.", ar: "وهي مشروعة. التنظيم يلحق بالأمر ببطء — وعلى المواطنين المطالبة بالأفضل." },
      { speaker: "b", text: "A nuanced position: optimism plus pressure.", ar: "موقف متوازن: تفاؤل مع ضغط." },
      { speaker: "a", text: "Precisely. Neither panic nor complacency serves us.", ar: "بالضبط. لا الذعر ولا الاطمئنان يخدمان مصالحنا." },
    ],
    quiz: [
      { q: "According to Dr Chen, AI mostly…", choices: ["erases jobs", "transforms them", "changes nothing"], answer: 1 },
      { q: "What does she call the scarce skill?", choices: ["Coding", "Judgment", "Marketing"], answer: 1 },
      { q: "Her stance could be summarised as…", choices: ["pure optimism", "panic", "optimism plus pressure"], answer: 2 },
    ],
  },
  {
    id: "c1-climate-explainer",
    lessonIds: ["lesson-21-science-natural-world"],
    title: "Explaining the science calmly",
    levels: ["C1"],
    topics: ["climate", "science communication", "energy", "uncertainty"],
    setting: "Radio studio: scientist interviewed about a new climate report",
    prop: "🌡️",
    palette: ["#0d2b24", "#2e7d64"],
    characters: { a: { name: "Dr Okafor", emoji: "👩🏾‍🔬" }, b: { name: "Host", emoji: "🎧" } },
    lines: [
      { speaker: "b", text: "The report uses phrases like 'high confidence'. What does that actually mean?", ar: "يستخدم التقرير عبارات مثل \u201cثقة عالية\u201d. ماذا يعني ذلك فعلاً؟" },
      { speaker: "a", text: "It's calibrated language: we grade how strongly evidence supports each finding.", ar: "إنها لغة معايَرة: نرتّب مدى دعم الأدلة لكل استنتاج." },
      { speaker: "b", text: "So uncertainty means scientists disagree about whether warming happens?", ar: "إذن عدم اليقين يعني أن العلماء يختلفون حول حدوث الاحترار؟" },
      { speaker: "a", text: "Not at all. The core physics is settled; uncertainty lives in rates and regional detail.", ar: "إطلاقاً. الفيزياء الأساسية محسومة؛ وعدم اليقين يتعلق بالسرعات والتفاصيل الإقليمية." },
      { speaker: "b", text: "Which finding worries you most?", ar: "أي استنتاج يقلقك أكثر؟" },
      { speaker: "a", text: "The feedback loops — thawing permafrost releasing methane faster than models predicted.", ar: "حلقات التغذية الراجعة — ذوبان التربة الجليدية وإطلاق الميثان أسرع مما تنبأت به النماذج." },
      { speaker: "b", text: "And yet you sound cautiously hopeful.", ar: "ومع ذلك يبدو صوتك متفائلًا بحذر." },
      { speaker: "a", text: "Because every tenth of a degree avoided matters. Despair isn't data.", ar: "لأن كل عُشر درجة نتجنبها مهم. اليأس ليس بيانات." },
    ],
    quiz: [
      { q: "'High confidence' in the report refers to…", choices: ["scientists' mood", "strength of evidence", "temperature readings"], answer: 1 },
      { q: "Where does real uncertainty lie?", choices: ["Whether warming occurs", "Rates and regional detail", "Everything equally"], answer: 1 },
      { q: "Why does Dr Okafor remain hopeful?", choices: ["The report was wrong", "Every fraction of a degree matters", "Technology solved it"], answer: 1 },
    ],
  },
];
