import type { LabPhrase } from "./speaking-lab";

/** Expanded calibration phrases per level for the Speaking Coach (17 per band). */
export const LAB_PHRASES_EXTRA: LabPhrase[] = [
  // Pre-A1 — 1-3 word chunks
  { id: "sl-prea1-x1", level: "Pre-A1", focus: "clear 'th' sound at the start of 'thank'", text: "Thank you." },
  { id: "sl-prea1-x2", level: "Pre-A1", focus: "warm stress on 'good' in a greeting", text: "Good morning." },
  { id: "sl-prea1-x3", level: "Pre-A1", focus: "linking the final 's' of 'excuse' into 'me'", text: "Excuse me." },
  { id: "sl-prea1-x4", level: "Pre-A1", focus: "strong 'v' sound: top teeth on the bottom lip", text: "Very good." },
  { id: "sl-prea1-x5", level: "Pre-A1", focus: "friendly rise in tone on 'you'", text: "How are you?" },
  { id: "sl-prea1-x6", level: "Pre-A1", focus: "polite stress on 'thank you' after 'no'", text: "No, thank you." },
  { id: "sl-prea1-x7", level: "Pre-A1", focus: "long 'ee' at the end of 'please'", text: "One ticket, please." },
  { id: "sl-prea1-x8", level: "Pre-A1", focus: "the contraction 'don't' said as one syllable", text: "I don't know." },
  { id: "sl-prea1-x9", level: "Pre-A1", focus: "the hidden 's in 'it's'", text: "It's cold." },
  { id: "sl-prea1-x10", level: "Pre-A1", focus: "smooth link from 'come' straight into 'here'", text: "Come here." },
  { id: "sl-prea1-x11", level: "Pre-A1", focus: "the weak little 'a' before 'moment'", text: "Wait a moment." },
  { id: "sl-prea1-x12", level: "Pre-A1", focus: "clear stress on 'time' in a short question", text: "What time?" },
  { id: "sl-prea1-x13", level: "Pre-A1", focus: "falling tone on 'turn' to claim your go", text: "My turn." },
  { id: "sl-prea1-x14", level: "Pre-A1", focus: "the 'k' sound in the middle of 'careful'", text: "Be careful." },
  { id: "sl-prea1-x15", level: "Pre-A1", focus: "'of course' said as one smooth phrase", text: "Of course." },
  { id: "sl-prea1-x16", level: "Pre-A1", focus: "stress on the first syllable of 'tomorrow'", text: "See you tomorrow." },
  { id: "sl-prea1-x17", level: "Pre-A1", focus: "clear 'th' in 'there' with the tongue between the teeth", text: "Over there." },
  // A1 — short sentences
  { id: "sl-a1-x1", level: "A1", focus: "weak 'can' in a polite request", text: "Can I have some water, please?" },
  { id: "sl-a1-x2", level: "A1", focus: "'do you' said as one sound, 'd'you'", text: "Where do you live?" },
  { id: "sl-a1-x3", level: "A1", focus: "the contraction 'I'll' as one quick syllable", text: "I'll see you tomorrow." },
  { id: "sl-a1-x4", level: "A1", focus: "'she's' with the stress on 'sister'", text: "She's my sister." },
  { id: "sl-a1-x5", level: "A1", focus: "linking 'is' into 'it' so the words join", text: "How much is it?" },
  { id: "sl-a1-x6", level: "A1", focus: "the silent 'l' in 'half'", text: "It's half past nine." },
  { id: "sl-a1-x7", level: "A1", focus: "sentence stress on 'very much'", text: "Thank you very much." },
  { id: "sl-a1-x8", level: "A1", focus: "the 'ng' sound in 'English' made at the back of the mouth", text: "I'm learning English." },
  { id: "sl-a1-x9", level: "A1", focus: "a w-glide linking 'you' into 'on'", text: "See you on Monday." },
  { id: "sl-a1-x10", level: "A1", focus: "weak 'to' said as a quick 'tuh'", text: "I go to school by bus." },
  { id: "sl-a1-x11", level: "A1", focus: "'n' and 'y' melting together in 'can you'", text: "Can you help me?" },
  { id: "sl-a1-x12", level: "A1", focus: "the weak 'a' before 'coffee'", text: "I'd like a coffee, please." },
  { id: "sl-a1-x13", level: "A1", focus: "linking 's' into 'th' in 'what's the time'", text: "What's the time?" },
  { id: "sl-a1-x14", level: "A1", focus: "'t' of 'meet' linking into 'you'", text: "Nice to meet you." },
  { id: "sl-a1-x15", level: "A1", focus: "falling tone at the end of a flat statement", text: "I don't understand." },
  { id: "sl-a1-x16", level: "A1", focus: "strong 'like' against weak 'it' and 'a lot'", text: "I like it a lot." },
  { id: "sl-a1-x17", level: "A1", focus: "rising tone on 'open' in a question", text: "What time does the shop open?" },
  // A2 — everyday sentences with one tricky sound
  { id: "sl-a2-x1", level: "A2", focus: "the 'yoo' sound at the start of 'usually'", text: "I usually walk to the market on Saturdays." },
  { id: "sl-a2-x2", level: "A2", focus: "'s' pronounced as 'z' at the end of 'always'", text: "She always arrives ten minutes early." },
  { id: "sl-a2-x3", level: "A2", focus: "the long 'ar' vowel in 'rather'", text: "I'd rather stay at home this evening." },
  { id: "sl-a2-x4", level: "A2", focus: "'-ed' in 'watched' said as a single 't'", text: "We watched a film last night." },
  { id: "sl-a2-x5", level: "A2", focus: "the 'h' in 'him' disappearing after 'tell'", text: "Can you tell him I called?" },
  { id: "sl-a2-x6", level: "A2", focus: "'would you' spoken as 'wouldja'", text: "Would you mind closing the window?" },
  { id: "sl-a2-x7", level: "A2", focus: "the 't' of 'meet' linking into 'outside'", text: "Let's meet outside the cinema at seven." },
  { id: "sl-a2-x8", level: "A2", focus: "sentence stress on 'de-pends'", text: "It depends on the weather." },
  { id: "sl-a2-x9", level: "A2", focus: "'-ed' in 'enjoyed' said as a soft 'd'", text: "I really enjoyed the concert." },
  { id: "sl-a2-x10", level: "A2", focus: "'cup of' reduced to 'cuppa'", text: "Do you fancy a cup of tea?" },
  { id: "sl-a2-x11", level: "A2", focus: "the middle syllable of 'probably' nearly vanishing", text: "I'll probably stay in tonight." },
  { id: "sl-a2-x12", level: "A2", focus: "linking 'does' into 'it' as 'duzzit'", text: "How long does it take on foot?" },
  { id: "sl-a2-x13", level: "A2", focus: "weak 'than' — short, quiet, unstressed", text: "This one's cheaper than that one." },
  { id: "sl-a2-x14", level: "A2", focus: "the 't' in 'just' nearly vanishing before 'missed'", text: "I've just missed the bus." },
  { id: "sl-a2-x15", level: "A2", focus: "'m' of 'film' linking into 'on'", text: "There's a good film on later." },
  { id: "sl-a2-x16", level: "A2", focus: "'What are you' spoken as 'whaddaya'", text: "What are you doing tonight?" },
  { id: "sl-a2-x17", level: "A2", focus: "the 'th' in 'think' with the tongue lightly between the teeth", text: "I think it's a great idea." },
  // B1 — opinion sentences
  { id: "sl-b1-x1", level: "B1", focus: "sentence stress on 'reckon' to signal a personal view", text: "I reckon learning a language online actually works better for me." },
  { id: "sl-b1-x2", level: "B1", focus: "the 't' of 'don't' nearly vanishing before 'think'", text: "To be honest, I don't think cities need more car parks." },
  { id: "sl-b1-x3", level: "B1", focus: "fall-rise tone on 'weekend' to soften the opinion", text: "If you ask me, homework should be lighter at the weekend." },
  { id: "sl-b1-x4", level: "B1", focus: "extra stress on 'far' to sharpen the point", text: "The thing is, prices here are far too high." },
  { id: "sl-b1-x5", level: "B1", focus: "'I'd' spoken as one quick syllable", text: "I'd say the new timetable is a clear improvement." },
  { id: "sl-b1-x6", level: "B1", focus: "keeping the 't' audible in 'can't' so the meaning survives", text: "Personally, I can't stand loud advertising in the street." },
  { id: "sl-b1-x7", level: "B1", focus: "'as far as' run together in one breath group", text: "As far as I'm concerned, museums should be free." },
  { id: "sl-b1-x8", level: "B1", focus: "weak 'to me' — a quick 'tuh me'", text: "It seems to me that the bus service has got worse." },
  { id: "sl-b1-x9", level: "B1", focus: "linking 'best' into 'thing'", text: "The best thing about the city is the parks." },
  { id: "sl-b1-x10", level: "B1", focus: "fall-rise tone on 'agree' to keep disagreement polite", text: "I'm not sure I agree with that, actually." },
  { id: "sl-b1-x11", level: "B1", focus: "stressing 'really enjoy' in a cleft sentence", text: "What I really enjoy is cooking for friends." },
  { id: "sl-b1-x12", level: "B1", focus: "smooth link from 'point' into 'but'", text: "You've got a point, but I still think the plan is risky." },
  { id: "sl-b1-x13", level: "B1", focus: "weak 'to' between 'trains' and 'planes'", text: "Generally speaking, I prefer trains to planes." },
  { id: "sl-b1-x14", level: "B1", focus: "main stress landing on '-rated' in 'overrated'", text: "In my experience, early mornings are wildly overrated." },
  { id: "sl-b1-x15", level: "B1", focus: "the weak first vowel in 'doesn't'", text: "If I'm honest, that argument doesn't convince me." },
  { id: "sl-b1-x16", level: "B1", focus: "a quick, quiet 'I'd' between 'thing' and 'change'", text: "One thing I'd change is the booking system." },
  { id: "sl-b1-x17", level: "B1", focus: "fall-rise on 'Mind you' to mark a contrast", text: "Mind you, some of the old rules worked rather well." },
  // B2 — workplace sentences with connected speech
  { id: "sl-b2-x1", level: "B2", focus: "'come back to you' held in one smooth rhythm group", text: "I'll chase the design team and come back to you by Friday." },
  { id: "sl-b2-x2", level: "B2", focus: "'need to' spoken as 'needa'", text: "We need to finalise the figures before the board meets." },
  { id: "sl-b2-x3", level: "B2", focus: "a gentle rise on 'moment' to keep the request warm", text: "Could you walk me through the proposal when you have a moment?" },
  { id: "sl-b2-x4", level: "B2", focus: "weak 'can' between 'we' and 'start'", text: "Assuming the client signs, we can start production in May." },
  { id: "sl-b2-x5", level: "B2", focus: "'didn't' as one compact syllable with a clear 't'", text: "I'd rather we didn't commit until the scope is agreed." },
  { id: "sl-b2-x6", level: "B2", focus: "'been' linking straight into 'a'", text: "There's been a slight delay with the shipment, nothing serious." },
  { id: "sl-b2-x7", level: "B2", focus: "sentence stress on 'matters most'", text: "What matters most is that the deadline holds." },
  { id: "sl-b2-x8", level: "B2", focus: "the 't' of 'don't' fading before 'hear'", text: "If we don't hear back by Tuesday, I'll escalate." },
  { id: "sl-b2-x9", level: "B2", focus: "'we're' as a single weak syllable", text: "The figures suggest we're pacing ahead of last quarter." },
  { id: "sl-b2-x10", level: "B2", focus: "stress landing on 'now' and 'week' to frame the plan", text: "Let's park that for now and revisit it next week." },
  { id: "sl-b2-x11", level: "B2", focus: "'want to' spoken as 'wanna'", text: "You'll want to loop in legal before we announce anything." },
  { id: "sl-b2-x12", level: "B2", focus: "'I'll have' gliding into 'I'll've'", text: "Give me until Wednesday and I'll have the draft ready." },
  { id: "sl-b2-x13", level: "B2", focus: "'everyone's' contracted without losing the final 's'", text: "As long as everyone's clear on ownership, this should run smoothly." },
  { id: "sl-b2-x14", level: "B2", focus: "the attached 's in 'budget's' and 'timeline's'", text: "It's not that the budget's wrong; it's that the timeline's unrealistic." },
  { id: "sl-b2-x15", level: "B2", focus: "a fall-rise on 'uptake' to signal openness", text: "Perhaps we could revisit the terms once we've seen the uptake." },
  { id: "sl-b2-x16", level: "B2", focus: "'but' reduced and joined to 'they' in one beat", text: "The numbers don't lie, but they can mislead if you cherry-pick." },
  { id: "sl-b2-x17", level: "B2", focus: "a smooth w-glide from 'who' into 'owns'", text: "Right, let's take stock and decide who owns what." },
  // C1 — complex sentences, registers and weak forms
  { id: "sl-c1-x1", level: "C1", focus: "'would have' reduced to 'would've' inside formal speech", text: "Had we anticipated the disruption, we would have re-sequenced the rollout." },
  { id: "sl-c1-x2", level: "C1", focus: "'of' almost disappearing inside 'degree of'", text: "The findings, however preliminary, warrant a degree of caution." },
  { id: "sl-c1-x3", level: "C1", focus: "contrastive stress on 'struck' and 'conceded'", text: "What struck me most was how readily the committee conceded the point." },
  { id: "sl-c1-x4", level: "C1", focus: "a quick linked 't' between 'argument' and 'to'", text: "There's an argument to be made for phasing the transition gradually." },
  { id: "sl-c1-x5", level: "C1", focus: "reduced 'to' inside 'inclined to'", text: "I'm inclined to think the latter interpretation holds more water." },
  { id: "sl-c1-x6", level: "C1", focus: "'that as it' collapsing into two light syllables", text: "Be that as it may, the evidence base remains thin." },
  { id: "sl-c1-x7", level: "C1", focus: "parallel stress on 'scalable' and 'sustainable'", text: "To put it bluntly, the current approach is neither scalable nor sustainable." },
  { id: "sl-c1-x8", level: "C1", focus: "stress on '-states' in 'overstates' to sharpen the criticism", text: "The proposal, if I may say so, rather overstates its own novelty." },
  { id: "sl-c1-x9", level: "C1", focus: "the aside 'of course' delivered lower and faster", text: "One could argue, of course, that the distinction is largely academic." },
  { id: "sl-c1-x10", level: "C1", focus: "'up to' fusing into 'upto' before 'review'", text: "Unless the methodology is tightened, I struggle to see this standing up to review." },
  { id: "sl-c1-x11", level: "C1", focus: "the aside 'at best' dropping in pitch and speed", text: "It follows, then, that our earlier assumptions were, at best, optimistic." },
  { id: "sl-c1-x12", level: "C1", focus: "'I've ever' gliding together into two light syllables", text: "She's arguably the most formidable negotiator I've ever sat across from." },
  { id: "sl-c1-x13", level: "C1", focus: "both words of 'rather than' weakened to almost nothing", text: "There's a strong case for treating this as a pilot rather than a commitment." },
  { id: "sl-c1-x14", level: "C1", focus: "contrastive stress pairing 'urgent' with 'important'", text: "Frankly, the distinction between 'urgent' and 'important' has evaporated here." },
  { id: "sl-c1-x15", level: "C1", focus: "'I'd endorse' spoken as one smooth group", text: "Were it not for the timing, I'd endorse the recommendation without reservation." },
  { id: "sl-c1-x16", level: "C1", focus: "the 't' of 'yet' melting into 'the'", text: "Granted, the dataset is narrow, yet the pattern is too consistent to dismiss." },
  { id: "sl-c1-x17", level: "C1", focus: "'in light of' held as one rhythm group", text: "In light of what we now know, a more measured tone seems warranted." },
  // C2 — idiom and nuance challenges
  { id: "sl-c2-x1", level: "C2", focus: "fall-rise across 'subtle as it is' to flag the aside", text: "The distinction, subtle as it is, makes all the difference in negotiation." },
  { id: "sl-c2-x2", level: "C2", focus: "the idiom 'kicking the can down the road' in one phrase group", text: "Call it what you will, the strategy amounts to kicking the can down the road." },
  { id: "sl-c2-x3", level: "C2", focus: "a lighter, quicker 'as it were' to carry the irony", text: "One hesitates to say it, but the emperor, as it were, has few clothes." },
  { id: "sl-c2-x4", level: "C2", focus: "soft stress on 'touch' to land the understatement", text: "That's a generous reading, though perhaps a touch too generous." },
  { id: "sl-c2-x5", level: "C2", focus: "stress on 'quietly' to reveal the criticism", text: "The report reads well until you notice what it quietly declines to mention." },
  { id: "sl-c2-x6", level: "C2", focus: "light stress on 'faintly' to colour the irony", text: "There's something faintly absurd about debating process while the deadline burns." },
  { id: "sl-c2-x7", level: "C2", focus: "mirrored stress on the two 'to concede' phrases", text: "To concede the point now would be to concede the argument entirely." },
  { id: "sl-c2-x8", level: "C2", focus: "a pitch reset after 'nuance' at the semicolon", text: "I take your point about nuance; I simply doubt the audience shares it." },
  { id: "sl-c2-x9", level: "C2", focus: "'for want of a' running as one weak phrase", text: "The policy is, for want of a better word, aspirational." },
  { id: "sl-c2-x10", level: "C2", focus: "stress on 'admire', then lower pitch through 'I question'", text: "Much as I admire the ambition, I question the premise beneath it." },
  { id: "sl-c2-x11", level: "C2", focus: "a measured stress pattern across 'trouble', 'euphemism' and 'read'", text: "The trouble with euphemism is that everyone eventually learns to read it." },
  { id: "sl-c2-x12", level: "C2", focus: "flat delivery until the dry, ironic 'charming'", text: "Were the stakes lower, one might call the oversight charming." },
  { id: "sl-c2-x13", level: "C2", focus: "stress on 'did' for emphatic contrast", text: "In fairness, the committee did flag the risk — we simply chose not to hear it." },
  { id: "sl-c2-x14", level: "C2", focus: "the 'less... than' frame leaning on 'hope' and 'budget'", text: "It's less a strategy than a hope with a budget line." },
  { id: "sl-c2-x15", level: "C2", focus: "the parenthetical 'I suspect' tucked in at lower volume", text: "History will judge, I suspect, rather less kindly than the press has." },
  { id: "sl-c2-x16", level: "C2", focus: "'could be forgiven for' blurring together before the stress on 'ignored'", text: "You could be forgiven for thinking the review was designed to be ignored." },
  { id: "sl-c2-x17", level: "C2", focus: "a clipped, firm 'wouldn't' to land the irony", text: "A more charitable observer might call it ambition; a realistic one wouldn't." },
];
