/** 150-topic master library, part 3 of 6 (topics 51–75 · Lessons 11–15): technology, travel, relationships, money, media. */
import type { Topic150 } from "./topics150-a";

const t = (
  n: number, id: string, title: string, category: string, lessonId: string, purpose: string,
  vocab: string[], grammar: string[],
  skills: [string, string, string, string],
  scenario: string, pitfall: string,
  ladder: Array<[string, string]>,
): Topic150 => ({
  n, id, title, category, lessonId, purpose,
  vocab, grammar,
  skills: { speaking: skills[0], listening: skills[1], reading: skills[2], writing: skills[3] },
  scenario, pitfall,
  ladder: ladder.map(([level, example]) => ({ level, example })),
});

export const TOPICS_150_C: Topic150[] = [
  t(51, "phones-messaging", "Phones and Messaging", "technology", "lesson-11-communication-technology",
    "Manage calls and messages: signal problems, voicemail, texting conventions.",
    ["call / text / message", "voicemail", "The line is bad", "Can you hear me now?", "hang up / call back", "emoji", "voice note", "missed call"],
    ["will for promises on calls (I'll call you back)", "question tags (You got it, didn't you?)"],
    ["Handle a call where the signal keeps dropping.", "Catch callback numbers and names first time.", "Read a long group-chat thread fast.", "Write a polite chasing message."],
    "Important call on a train: two tunnels, one dropped connection — recover professionally.",
    "'Hang up' can mean end a call rudely — tone and context decide.",
    [["Pre-A1", "Hello? Can you hear me?"], ["A1", "Sorry, the line is bad. Call me later."], ["A2", "I'll call you back in five minutes — I'm losing you."], ["B1", "You're breaking up a bit — could you repeat the address?"], ["B2", "Voice notes have quietly replaced half of my actual calls."], ["C1", "Phone anxiety is generational; younger users treat calls as intrusive by default."]],

  ),
  t(52, "email-basics", "Email", "workplace", "lesson-11-communication-technology",
    "Write and understand emails: greetings, purpose, action, sign-off.",
    ["Dear Sir or Madam", "I'm writing to...", "attached / attached file", "Could you confirm...?", "Best regards", "subject line", "reply / forward", "CC"],
    ["formal vs informal register", "I would be grateful if + past"],
    ["Write a five-sentence formal request email.", "Extract actions from a long email thread.", "Scan inbox for urgent items.", "Rewrite a rude email politely."],
    "Email to a government office: request a document replacement without any ambiguity.",
    "Formal emails avoid contractions — 'I would' not 'I'd' in very formal registers.",
    [["Pre-A1", "Dear Mr Ali,"], ["A1", "Thank you for your email."], ["A2", "I'm writing to ask about the delivery date for order 4471."], ["B1", "Apologies for the delayed reply — I've been out of office this week."], ["B2", "As per my previous email, could you confirm receipt by Friday?"], ["C1", "Email tone is read colder than intended; write warm, edit cold."]],

  ),
  t(53, "social-media", "Social Media", "media", "lesson-11-communication-technology",
    "Discuss platforms, posting, privacy settings and social media habits.",
    ["post / share / like", "follower", "story / reel", "tag someone", "go viral", "privacy settings", "block / mute", "influencer"],
    ["present perfect frequency (I've posted twice today)", "comparatives of platforms"],
    ["Describe your platform habits honestly.", "Follow a debate about quitting social media.", "Read community guidelines briefly.", "Write a caption with a clear message."],
    "A friend's post went viral for the wrong reasons: advise them in real time.",
    "'Like' as verb/noun both exist — 'give it a like', 'I liked your photo'.",
    [["Pre-A1", "I like your photo!"], ["A1", "I use Instagram every day."], ["A2", "She posts cooking videos and has thousands of followers."], ["B1", "I muted the group chat — too many notifications during work."], ["B2", "Algorithms reward outrage because outrage is measurable."], ["C1", "Social media collapsed the distance between private thought and public record."]],

  ),
  t(54, "internet-online-services", "Internet and Online Services", "technology", "lesson-11-communication-technology",
    "Use online services: accounts, passwords, forms, deliveries, subscriptions.",
    ["website / app", "sign up / log in", "password / username", "subscription", "download / update", "checkout / cart", "tracking number", "terms and conditions"],
    ["imperatives in instructions", "present simple for processes"],
    ["Guide a friend through creating an account.", "Follow spoken troubleshooting steps.", "Read terms to find cancellation rules.", "Write step-by-step instructions for an app task."],
    "Grandfather wants video calls with family: set up his account patiently over one session.",
    "'Subscribe' often auto-renews — always find the cancellation path first.",
    [["Pre-A1", "What is your password?"], ["A1", "Click here and sign up with your email."], ["A2", "My subscription renewed automatically — how do I cancel it?"], ["B1", "Scroll down, accept the terms, then check your inbox to verify the account."], ["B2", "Dark patterns make cancelling deliberately harder than signing up."], ["C1", "Convenience is the currency platforms spend to acquire your data."]],

  ),
  t(55, "digital-habits-screen-time", "Digital Habits and Screen Time", "technology", "lesson-11-communication-technology",
    "Evaluate your screen habits and discuss digital balance strategies.",
    ["screen time", "doomscrolling", "notification", "digital detox", "focus mode", "addicted to", "cut down on", "mindless scrolling"],
    ["spend + time + -ing (I spend hours scrolling)", "too / enough with nouns"],
    ["Audit and report your weekly screen time.", "Follow two people comparing detox attempts.", "Read a digital-wellbeing study summary.", "Write three rules for healthier phone use."],
    "Your screen-time report says 7 hours daily. Design a realistic reduction plan with a friend.",
    "Spend time + -ing: 'I spend hours WATCHING videos'.",
    [["Pre-A1", "I use my phone a lot."], ["A1", "Too much screen time is bad for your eyes."], ["A2", "I spend about four hours a day on social apps."], ["B1", "Turning notifications off was the single most useful change I made."], ["B2", "Attention has become the scarcest resource in most households."], ["C1", "Screen time debates conflate tools with habits — the distinction matters."]],

  ),
  t(56, "airports-flights", "Airports and Flights", "travel", "lesson-12-travel-international",
    "Navigate airports: check-in, security, boarding, gates and announcements.",
    ["check-in desk", "boarding pass", "gate", "security", "hand luggage / checked bag", "boarding", "final call", "aisle / window seat"],
    ["passive voice basics (Flight BA201 has been delayed)", "modality at airports: you must / you can't"],
    ["Check in, pass security, board — full airport sequence.", "Decode gate-change announcements.", "Read baggage rules.", "Write a flight summary for a family member."],
    "Gate changed twice, boarding closing: navigate a busy airport against the clock.",
    "Announcements bury key info late: 'Passengers Smith, gate change, gate 22'.",
    [["Pre-A1", "Where is gate five?"], ["A1", "Here is my passport and boarding pass."], ["A2", "Excuse me, is this the queue for flight 208 to Cairo?"], ["B1", "They've announced a gate change — we should head over now rather than risk it."], ["B2", "Budget airlines monetise everything from bags to boarding order."], ["C1", "Airport design engineers compliance through fatigue more than signage."]],

  ),
  t(57, "hotels-accommodation", "Hotels and Accommodation", "travel", "lesson-12-travel-international",
    "Book and stay somewhere: reservations, facilities, problems, checkout.",
    ["reservation / booking reference", "double / twin room", "breakfast included?", "reception / front desk", "check-in / check-out", "safe / key card", "en-suite", "review"],
    ["would like for requests", "past modals for complaints (should have been cleaned)"],
    ["Check in, ask three facility questions, check out.", "Understand reception explaining a booking problem.", "Read hotel reviews critically.", "Write a fair review after a stay."],
    "Arriving at midnight, your booked room was given away — negotiate an upgrade calmly.",
    "Complaints land better with facts + desired fix, not volume.",
    [["Pre-A1", "I have a reservation."], ["A1", "Is breakfast included?"], ["A2", "The room wasn't cleaned today — could someone come up, please?"], ["B1", "We reserved a twin but were given a double; how will you resolve this?"], ["B2", "Location justified the price; soundproofing did not."], ["C1", "Hospitality is judged in failures — recovery quality defines brands."]],

  ),
  t(58, "planning-a-trip", "Planning a Trip", "travel", "lesson-12-travel-international",
    "Plan trips: compare options, budgets, itineraries and bookings.",
    ["itinerary", "book flights / accommodation", "budget", "sightseeing list", "off the beaten track", "day trip", "peak season", "exchange rate"],
    ["future plans mix (going to / will / might)", "conditionals: if we leave early..."],
    ["Propose and defend a weekend itinerary.", "Follow friends negotiating trip choices.", "Compare two tour descriptions.", "Write a day-by-day mini itinerary."],
    "Three friends, one budget, one weekend: build an itinerary everyone actually accepts.",
    "'Might' keeps options open; 'going to' closes them. Choose deliberately when planning.",
    [["Pre-A1", "Beach or mountains?"], ["A1", "Let's visit the old city on Saturday."], ["A2", "If we book tonight, the flights are forty percent cheaper."], ["B1", "Might be worth skipping the museum Monday — apparently it closes early."], ["B2", "Over-planning kills spontaneity; under-planning kills weekends."], ["C1", "Good itineraries protect energy, not just sights."]],

  ),
  t(59, "travel-problems", "Travel Problems", "travel", "lesson-12-travel-international",
    "Solve travel trouble: lost luggage, missed connections, wrong bookings.",
    ["lost luggage / lost property", "delayed / cancelled", "compensation", "claim form", "Is there a later train?", "wrong turn", "stuck in", "make it in time"],
    ["past modals for blame/repair (should have arrived)", "polite escalation phrases"],
    ["Explain a problem and negotiate a fix.", "Catch compensation rules in a fast reply.", "Read an airline delay-policy page.", "Write a short compensation claim."],
    "Connection missed due to delay: get rebooking plus meal voucher without losing composure.",
    "Escalation ladder: explain → request → insist politely → ask for a manager.",
    [["Pre-A1", "My bag is lost!"], ["A1", "The train is cancelled. What can I do?"], ["A2", "Our connecting flight left early — what are our options now?"], ["B1", "According to EU rules, we should be entitled to compensation for this."], ["B2", "Being calm and specific gets better outcomes than being loud and vague."], ["C1", "Travel disruption tests systems, not just patience."]],

  ),
  t(60, "cultural-differences-travelling", "Cultural Differences While Travelling", "culture", "lesson-12-travel-international",
    "Notice and respect cultural differences: tipping, dress, greetings, taboos.",
    ["custom / habit", "tipping", "appropriate dress", "taboo", "gesture", "It's normal to...", "In my country, we...", "respect"],
    ["habitual present for customs", "comparatives across cultures"],
    ["Explain one custom from your country.", "Follow travellers comparing culture shocks.", "Read local etiquette dos/don'ts.", "Write advice for a visitor to your country."],
    "Pre-trip briefing: colleagues who worked abroad share what surprised them culturally.",
    "Gestures flip meanings between countries — thumbs up isn't universal.",
    [["Pre-A1", "Here, we eat together."], ["A1", "In my country, we don't tip."], ["A2", "You should cover your shoulders when visiting temples there."], ["B1", "What's considered friendly eye contact here felt aggressive at first."], ["B2", "Culture shock arrives in waves — the second month is harder than the first week."], ["C1", "Etiquette guides describe averages; individuals always exceed their categories."]],

  ),
  t(61, "romantic-relationships", "Romantic Relationships", "social", "lesson-13-relationships-behaviour",
    "Talk about dating and partnership: meeting, commitment, breakups.",
    ["date / dating", "boyfriend / girlfriend", "get engaged / married", "propose", "break up", "long-distance", "propose / settle down", "the one"],
    ["present perfect duration (We've been together for...)", "future intentions in relationships"],
    ["Tell a meet-cute story briefly.", "Follow relationship advice radio call.", "Read a wedding announcement.", "Write an anniversary message."],
    "Coffee with a friend deciding whether to move abroad with their partner — help them think.",
    "Relationship stages differ culturally — 'dating' means different things elsewhere.",
    [["Pre-A1", "This is my wife."], ["A2", "They met at work and got engaged last spring."], ["B1", "We've been together six years, married for two."], ["B2", "Long-distance worked until it didn't — visits became logistics."], ["C1", "Commitment is less a feeling than a series of renewed decisions."]],

  ),
  t(62, "family-relationships", "Family Relationships", "personal", "lesson-13-relationships-behaviour",
    "Navigate family dynamics: expectations, support, distance, obligations.",
    ["get along with", "look after / take care of", "support each other", "family gathering", "the eldest / youngest", "in-laws", "fall out (with)", "make up"],
    ["modality of obligation within families", "narrative past for disputes"],
    ["Describe one close and one difficult family bond.", "Follow siblings resolving an inheritance disagreement.", "Read advice-column letters.", "Write a message mending a small rift."],
    "Family lunch where old tensions surface: keep peace while staying honest.",
    "'Fall out' = argue/stop speaking; 'make up' = reconcile. Opposites worth memorising.",
    [["Pre-A1", "I love my family."], ["A2", "I look after my grandmother at weekends."], ["B1", "My brother and I fell out for a year over money, stupidly."], ["B2", "Care responsibilities reverse eventually — that transition is brutal."], ["C1", "Families function less on fairness than on negotiated memory."]],

  ),
  t(63, "conflict-disagreement", "Conflict and Disagreement", "thinking", "lesson-13-relationships-behaviour",
    "Disagree productively: soften, listen, propose, repair.",
    ["I see your point, but...", "That's not quite right", "calm down", "let's not argue", "misunderstanding", "apologise", "move on", "agree to disagree"],
    ["hedging (perhaps, maybe, a bit)", "conditionals for de-escalation"],
    ["Disagree with someone respectfully and hold your ground.", "Hear implied anger beneath polite words.", "Read a tense exchange for subtext.", "Write an apology that takes responsibility."],
    "Flatmate conflict over noise and guests: confront kindly, agree rules, repair the mood.",
    "Softeners aren't weakness — 'I might be wrong, but...' keeps conversations alive.",
    [["Pre-A1", "No! That's wrong."], ["A2", "Sorry, but I see it differently."], ["B1", "I take your point about cost, but reliability matters more here."], ["B2", "Can we park this for now and revisit when everyone's less tired?"], ["C1", "Most arguments are proxy wars for unspoken needs."]],

  ),
  t(64, "trust-communication", "Trust and Communication", "thinking", "lesson-13-relationships-behaviour",
    "Build trust: honesty, keeping promises, admitting mistakes, listening.",
    ["trust", "keep a promise", "confide in", "be upfront about", "give someone the benefit of the doubt", "betray", "transparent", "count on"],
    ["promises with will/won't", "regret structures: I wish I had told you"],
    ["Rebuild trust in a role-play after breaking a promise.", "Detect sincerity vs deflection in tone.", "Read a trust-repair letter.", "Write a promise you intend to keep — specifically."],
    "You forgot something important to a friend: own it fully, rebuild credibility live.",
    "Trust language is specific: vague apologies ('sorry if...') erode it further.",
    [["Pre-A1", "You can trust me."], ["A2", "He promised to help, and he kept his word."], ["B1", "I should have told you sooner — hiding it made things worse."], ["B2", "Trust accrues in drops and drains in buckets."], ["C1", "Reliability is love expressed as scheduling."]],

  ),
  t(65, "understanding-behaviour", "Understanding Other People's Behaviour", "psychology", "lesson-13-relationships-behaviour",
    "Read behaviour charitably: motives, pressure, context before judgement.",
    ["Why would he...?", "maybe she's just...", "put yourself in their shoes", "under pressure", "overreact", "read between the lines", "give them space", "context"],
    ["speculation modals (he might be / she must feel)", "empathy conditionals"],
    ["Offer three interpretations of one odd behaviour.", "Follow a case discussed among friends.", "Read a psychology explainer paragraph.", "Write a charitable reading of a conflict."],
    "Colleague turned cold overnight: generate hypotheses before conclusions.",
    "'Must be' = strong guess; 'might be' = weak guess. Calibrate certainty.",
    [["Pre-A1", "Maybe he is tired."], ["A2", "She might be stressed about exams."], ["B1", "There's probably something going on at home we don't know about."], ["B2", "Behaviour makes sense from inside the person's constraints."], ["C1", "Charitable interpretation is epistemic humility applied socially."]],
  ),
  t(66, "personal-budgeting", "Personal Budgeting", "finance", "lesson-14-money-personal-finance",
    "Build a monthly budget: income, essentials, fun, savings buffer.",
    ["income / expenses", "rent / utilities", "fixed costs", "left over", "track spending", "blow the budget", "essentials", "buffer"],
    ["present simple money routines", "quantifiers: too much, hardly any"],
    ["Present your monthly budget aloud.", "Follow a budgeting-app walkthrough.", "Read a bank statement summary.", "Draft next month's realistic budget."],
    "Salary landed on the 1st, gone by the 20th: audit where it leaks and plug two holes.",
    "Track in categories — 'miscellaneous' is where budgets go to die.",
    [["Pre-A1", "Money for food, money for rent."], ["A2", "I spend too much on delivery apps every month."], ["B1", "Once I tracked every pound for a month, the leaks became obvious."], ["B2", "Budgets fail when they assume perfect future discipline."], ["C1", "A budget is a values document disguised as arithmetic."]],

  ),
  t(67, "saving-money", "Saving Money", "finance", "lesson-14-money-personal-finance",
    "Save systematically: goals, automation, emergency funds, trade-offs.",
    ["save up (for)", "emergency fund", "set aside", "interest rate", "impulse buy", "cut back on", "three months' expenses", "automatic transfer"],
    ["intend/plan + to-infinitive", "first conditional savings logic"],
    ["Design a savings plan for a named goal.", "Follow advice on emergency funds.", "Compare two savings accounts.", "Write your saving rule in two sentences."],
    "Payday ritual: automate transfers before spending begins — set yours up now, verbally.",
    "'Save' vs 'save up': saving is general; saving up targets a goal.",
    [["Pre-A1", "I save money every month."], ["A2", "I'm saving up for a new laptop."], ["B1", "Setting aside ten percent automatically means I never see it."], ["B2", "An emergency fund converts crises into inconveniences."], ["C1", "Savings buy optionality, which compounds faster than interest."]],

  ),
  t(68, "banking", "Banking", "finance", "lesson-14-money-personal-finance",
    "Use banks confidently: accounts, transfers, branches, problems, apps.",
    ["current account / savings account", "transfer", "standing order", "exchange rate", "PIN", "frozen card", "branch", "statement"],
    ["polite banking requests", "present perfect for account states (has been blocked)"],
    ["Open an account and set up one transfer.", "Follow security verification questions.", "Read fee schedules quickly.", "Write to the bank about a frozen card."],
    "Card declined abroad: call the bank, pass security, unfreeze, breathe.",
    "Never say your PIN aloud — even bank staff never ask for it.",
    [["Pre-A1", "I need a bank account."], ["A2", "I'd like to transfer two hundred pounds to this account, please."], ["B1", "My card's been blocked since I used it abroad — can you lift it?"], ["B2", "Neobanks won on UX; incumbents retained trust for a reason."], ["C1", "Banking is becoming invisible infrastructure embedded in other apps."]],

  ),
  t(69, "borrowing-debt", "Borrowing and Debt", "finance", "lesson-14-money-personal-finance",
    "Understand loans: interest, terms, risks, repayment discipline.",
    ["loan / borrow / lend", "interest rate", "monthly repayment", "debt", "credit score", "pay off", "mortgage", "term"],
    ["must/had to for obligations", "second conditional debt traps"],
    ["Explain a loan's true cost including interest.", "Follow a lender's terms read aloud.", "Read loan fine print for traps.", "Write a borrowing decision with maths shown."],
    "Buy-now-pay-later offer at checkout: decide like an adult, show your working.",
    "Borrow = receive; lend = give. 'Can you LEND me...' / 'Can I BORROW...'.",
    [["Pre-A1", "I borrowed ten pounds."], ["A2", "We took out a small loan for the car."], ["B1", "If you only pay the minimum, the interest snowballs for years."], ["B2", "Cheap credit feels free until it structures your entire salary."], ["C1", "Debt instruments increasingly exploit optimism bias by design."]],

  ),
  t(70, "financial-goals", "Financial Goals", "finance", "lesson-14-money-personal-finance",
    "Set money goals with deadlines: house deposit, education, retirement basics.",
    ["goal / target", "deposit", "afford", "invest (basic)", "by next year", "reach my target", "priority spend", "net (after tax)"],
    ["future perfect basics (I'll have saved...)", "time-bound conditionals"],
    ["State a SMART financial goal and its monthly maths.", "Follow a planner-client conversation.", "Read a savings-growth chart description.", "Write your 12-month money plan."],
    "Two-year plan: deposit for a flat versus masters degree — pick, justify, compute.",
    "'Afford' includes time and risk, not just price.",
    [["Pre-A1", "I need money for school."], ["A2", "By December I'll have saved two thousand pounds."], ["B1", "If nothing goes wrong, I'll afford the deposit by autumn."], ["B2", "Goals without monthly mechanics are wishes with deadlines."], ["C1", "Financial planning is mostly behaviour management wearing a spreadsheet."]],
  ),
  t(71, "movies-television", "Movies and Television", "media", "lesson-15-media-entertainment",
    "Discuss films and series: genres, plots, opinions without spoilers.",
    ["comedy / thriller / documentary", "plot / ending", "spoiler", "based on a true story", "highly rated", "binge-watch", "season finale", "subtitles"],
    ["opinion language: I found it + adjective", "present simple plot summaries"],
    ["Pitch a film in 60 seconds, spoiler-free.", "Follow a film-club discussion.", "Read streaming synopses and reviews.", "Write a two-line review with a verdict."],
    "Film club: defend a film you loved against two sceptics, no spoilers allowed.",
    "Plot summaries use present simple: 'The hero LOSES everything', even for past stories.",
    [["Pre-A1", "I like funny films."], ["A1", "It's a story about a family in Cairo."], ["A2", "The ending totally surprised me — no spoilers though!"], ["B1", "It's slow to start, but the second episode completely hooks you."], ["B2", "Subtitles improved my Arabic and English simultaneously — underrated method."], ["C1", "Prestige television has quietly inherited literature's cultural role."]],

  ),
  t(72, "music", "Music", "media", "lesson-15-media-entertainment",
    "Talk about music taste, concerts, and how you discover songs.",
    ["genre: rock / jazz / pop", "lyrics", "gig / concert", "on repeat", "playlist", "catchy", "see live", "album"],
    ["like/love/prefer + gerund", "superlatives for favourites"],
    ["Describe your taste and one concert memory.", "Follow friends arguing about artists.", "Read a gig listing and review.", "Write why one song matters to you."],
    "Playlist swap: explain why three specific songs define different parts of your life.",
    "'See someone live' = watch a performance, not just existence.",
    [["Pre-A1", "I like pop music."], ["A1", "This song is very catchy."], ["A2", "I saw them live last year — best night of the year."], ["B1", "Lyrics hit differently once you've lived what they describe."], ["B2", "Streaming flattened albums into playlists; something was lost."], ["C1", "Musical taste functions as identity shorthand long after hearing declines."]],

  ),
  t(73, "books-reading", "Books and Reading", "education", "lesson-15-media-entertainment",
    "Discuss books: genres, formats, recommendations and reading habits.",
    ["novel / biography", "fiction / non-fiction", "audiobook", "page-turner", "chapter", "recommend", "e-book", "couldn't put it down"],
    ["present perfect progress (I've been reading...)", "recommendation structures"],
    ["Recommend a book with reasons, no spoilers.", "Follow a bookshop conversation.", "Read a blurb and judge the hook.", "Write a three-sentence book pitch."],
    "Bookshop recommendation roulette: pitch a favourite to a stranger in ninety seconds.",
    "Blurb ≠ review: one sells, the other judges.",
    [["Pre-A1", "I read every night."], ["A1", "This book is about a young detective."], ["A2", "I couldn't put it down — I finished it in two days."], ["B1", "I've been reading more non-fiction lately, mostly history."], ["B2", "Audiobooks rescued reading from my destroyed attention span."], ["C1", "Reading tastes map intellectual insecurity surprisingly precisely."]],

  ),
  t(74, "news", "News", "media", "lesson-15-media-entertainment",
    "Follow and discuss news: sources, headlines, bias awareness.",
    ["headline", "breaking news", "source", "report / coverage", "biased", "current affairs", "fact-check", "outlet"],
    ["reported speech basics (They said...)", "passive voice headlines"],
    ["Summarise one news story neutrally.", "Distinguish fact from opinion in audio news.", "Compare two outlets' headlines on one event.", "Write a neutral five-line news summary."],
    "Same event, three headlines: identify slant, then state what's actually known.",
    "Headlines drop articles and verbs: 'PM resigns amid scandal' = compressed passive world.",
    [["Pre-A1", "Bad news today."], ["A1", "I read the news on my phone."], ["A2", "They said the bridge would reopen next month."], ["B1", "The headline implies blame the article never substantiates."], ["B2", "Following one story across outlets reveals how framing manufactures reality."], ["C1", "News literacy is now inseparable from civic competence."]],

  ),
  t(75, "online-content-influencers", "Online Content and Influencers", "media", "lesson-15-media-entertainment",
    "Analyse creator culture: sponsorship, authenticity, parasocial dynamics.",
    ["content creator", "sponsor / ad deal", "authentic", "parasocial", "algorithm", "engagement", "sell out", "niche"],
    ["discourse markers in casual speech", "speculation about motives"],
    ["Evaluate one creator's content honestly.", "Follow a podcast segment on creator burnout.", "Read sponsored content and spot disclosure.", "Write a critical comment worth posting."],
    "Your favourite creator just went full sponsored: assess authenticity loss rationally.",
    "#ad exists for legal reasons — absence of disclosure is itself information.",
    [["Pre-A1", "She makes videos."], ["A2", "Half his reviews are just paid promotions now."], ["B1", "I follow her for recipes, though the ads have doubled recently."], ["B2", "Parasocial bonds explain why audiences forgive creators almost anything."], ["C1", "Authenticity became a performance metric the moment it became monetisable."]],
  ),
];
