/** 150-topic master library, part 5 of 6 (topics 101–125 · Lessons 21–25): science, psychology, leadership, global issues, abstract ideas. */
import type { Topic150 } from "./topics150-a";

const t = (
  n: number, id: string, title: string, category: string, lessonId: string, purpose: string,
  vocab: string[], grammar: string[],
  skills: [string, string, string, string],
  scenario: string, pitfall: string,
  ladder: Array<[string, string]>,
): Topic150 => ({
  n, id, title, category, lessonId, purpose,
  vocab, grammar,
  skills: { speaking: skills[0], listening: skills[1], reading: skills[2], writing: skills[3] },
  scenario, pitfall,
  ladder: ladder.map(([level, example]) => ({ level, example })),
});

export const TOPICS_150_E: Topic150[] = [
  t(101, "science-everyday-life", "Science in Everyday Life", "global", "lesson-21-science-natural-world",
    "Spot science operating daily: cooking, weather, medicine, machines.",
    ["reaction", "energy", "gravity / friction", "experiment", "evidence-based", "hypothesis", "physics of", "trial"],
    ["explanatory sequencing", "causal verbs (causes, enables)"],
    ["Explain the science behind one kitchen process.", "Follow an explainer podcast segment.", "Read a popular-science paragraph.", "Write a science explainer for a child."],
    "Cooking as chemistry class: explain why bread rises, meat browns, water boils differently at altitude.",
    "Science communication trades precision for comprehension — know which you're doing.",
    [["Pre-A1", "Ice is cold water."], ["A2", "Bread rises because the yeast produces gas."], ["B1", "Microwaves heat food by exciting water molecules, essentially."], ["B2", "Everyday intuition fails constantly at quantum and cosmic scales."], ["C1", "Scientific literacy means knowing how knowledge earns confidence, not memorising facts."]],

  ),
  t(102, "climate-change", "Climate Change", "global", "lesson-21-science-natural-world",
    "Discuss climate change accurately: causes, evidence, impacts, responses.",
    ["climate change", "emissions", "carbon footprint", "global warming", "extreme weather", "mitigation", "adaptation", "net zero"],
    ["trend description over time", "attributive caution (linked to, consistent with)"],
    ["Summarise climate evidence without exaggeration.", "Follow a scientist communicating uncertainty.", "Compare coverage of one climate report.", "Write a local-impact assessment."],
    "Sceptical relative at dinner: present the evidence chain calmly, concede unknowns precisely.",
    "Weather ≠ climate — single events prove neither presence nor absence of trends.",
    [["Pre-A1", "The Earth is getting hotter."], ["A2", "Scientists say emissions must fall quickly to limit warming."], ["B1", "The link between emissions and temperature rise is settled physics."], ["B2", "Adaptation debates increasingly matter as much as mitigation ones."], ["C1", "Climate communication struggles between accuracy and agency — doom paralyses, sugar-coating misleads."]],

  ),
  t(103, "environmental-problems", "Environmental Problems", "global", "lesson-21-science-natural-world",
    "Address pollution, waste and biodiversity loss with specificity.",
    ["pollution", "single-use plastic", "landfill", "recycling", "biodiversity", "ecosystem", "conservation", "contamination"],
    ["quantifiers with environmental nouns", "problem-solution structures"],
    ["Propose realistic waste reduction for one household.", "Follow an activist's concrete argument.", "Read recycling guidance for your area.", "Write a waste-audit action list."],
    "Household waste audit: weigh, categorise, identify the two biggest reducible streams.",
    "'Biodegradable' needs conditions to be true — landfill often denies them.",
    [["Pre-A1", "Rubbish is bad for nature."], ["A2", "Our building finally introduced separate food-waste collection."], ["B1", "Most recycling contamination comes from wishful sorting rather than apathy."], ["B2", "Individual action matters symbolically; systemic change matters materially."], ["C1", "Environmental problems share a signature: diffuse costs, concentrated benefits."]],

  ),
  t(104, "energy-sustainability", "Energy and Sustainability", "future", "lesson-21-science-natural-world",
    "Evaluate energy choices: renewables, grids, storage, transition costs.",
    ["renewable energy", "solar / wind power", "grid", "battery storage", "fossil fuels", "efficiency", "transition", "baseload"],
    ["comparative evaluation across systems", "conditional energy futures"],
    ["Argue an energy mix for your country.", "Follow an engineer debunking energy myths.", "Compare two countries' energy strategies.", "Write an energy recommendation with trade-offs named."],
    "National energy debate: advocate a 2050 mix acknowledging intermittency honestly.",
    "Renewables ≠ automatically green everywhere — manufacturing and land use count.",
    [["Pre-A1", "Solar power comes from the sun."], ["A2", "Wind turbines now produce cheaper electricity than coal in many places."], ["B1", "Storage remains the bottleneck once renewables dominate generation."], ["B2", "Transition speed is constrained by infrastructure, not technology readiness."], ["C1", "Energy politics is geography politics wearing engineering clothes."]],

  ),
  t(105, "scientific-discoveries", "Scientific Discoveries", "global", "lesson-21-science-natural-world",
    "Discuss discoveries historically: how knowledge advances and self-corrects.",
    ["discovery / breakthrough", "peer review", "replicate", "paradigm shift", "nobel prize", "clinical trial", "publish", "revise understanding"],
    ["narrative past for discovery stories", "epistemic language (suggests, indicates)"],
    ["Tell one discovery story with its setbacks.", "Follow a history-of-science narrative.", "Read how one finding got overturned.", "Write why one discovery mattered beyond labs."],
    "Story time: penicillin, CRISPR or gravitational waves — tell the human version with failures included.",
    "Single studies suggest; fields confirm. Language precision prevents misinformation.",
    [["Pre-A1", "Scientists found something new!"], ["A2", "Penicillin was discovered by accident in 1928."], ["B1", "Replication failures have cleaned up psychology's shakier findings."], ["B2", "Discovery narratives hide decades of unglamorous groundwork."], ["C1", "Science advances less by certainty than by disciplined self-doubt."]],

  ),
  t(106, "emotions-intelligence", "Emotions and Emotional Intelligence", "psychology", "lesson-22-psychology-human-mind",
    "Develop EQ vocabulary: name, regulate and read emotions precisely.",
    ["self-awareness", "regulate emotions", "triggered", "empathy vs sympathy", "emotional labour", "de-escalate", "granular", "name it to tame it"],
    ["emotion gradation vocabulary", "speculation about internal states"],
    ["Describe an emotional episode with granularity.", "Follow an emotional-intelligence coaching session.", "Read an EQ framework critique.", "Write an emotion log entry analytically."],
    "Conflict post-mortem: separate what happened from what you felt from what you made it mean.",
    "Precision deflates intensity: 'frustrated' enables solutions that 'angry' forecloses.",
    [["Pre-A1", "I feel bad today."], ["A2", "I get anxious before presentations, but breathing helps."], ["B1", "Naming the specific feeling took half its charge away."], ["B2", "Empathy means understanding someone's model, not absorbing their mood."], ["C1", "Emotional granularity correlates with regulation capacity — language shapes affect."]],

  ),
  t(107, "motivation", "Motivation", "psychology", "lesson-22-psychology-human-mind",
    "Engineer motivation: intrinsic vs extrinsic, friction design, momentum.",
    ["motivation / drive", "intrinsic / extrinsic", "procrastinate", "momentum", "reward system", "burnout", "discipline vs motivation", "why-power"],
    ["gerund subjects (Starting beats planning)", "cause-effect motivation analysis"],
    ["Analyse what actually drives one of your habits.", "Follow two coaches debating discipline.", "Compare motivation theories briefly.", "Write your motivation system, not your goals."],
    "Procrastination intervention: diagnose avoidance root (fear? ambiguity? boredom?) then redesign the task.",
    "Motivation follows action more than precedes it — start smaller than feels meaningful.",
    [["Pre-A1", "I don't want to study today."], ["A2", "I motivate myself by tracking streaks on a calendar."], ["B1", "Discipline carried me further than enthusiasm ever did."], ["B2", "Systems outperform willpower because they survive bad days."], ["C1", "Sustainable motivation is architecture, not arousal."]],

  ),
  t(108, "habits-behaviour", "Habits and Behaviour", "psychology", "lesson-22-psychology-human-mind",
    "Reshape habits: cues, routines, rewards, environment design.",
    ["habit loop", "cue / trigger", "routine", "reward", "stacking", "break a habit", "environment design", "default options"],
    ["present simple habitual mechanisms", "conditionals for behaviour change"],
    ["Map one habit's full cue-routine-reward loop.", "Follow behavioural-change case discussion.", "Read habit-formation research summaries.", "Write a habit redesign plan."],
    "Phone-checking loop dissected: identify trigger, interruption cost, replacement behaviour.",
    "Habits live in environments more than intentions — change rooms, not resolutions.",
    [["Pre-A1", "I check my phone first thing."], ["A2", "Putting my book on the pillow replaced the phone habit."], ["B1", "The habit stuck once I tied it to making morning coffee."], ["B2", "Behavioural defaults decide outcomes before deliberation wakes up."], ["C1", "Identity-level change outlasts outcome-level attempts every time."]],

  ),
  t(109, "stress-pressure", "Stress and Pressure", "health", "lesson-22-psychology-human-mind",
    "Manage stress: load, recovery, boundaries, physiological basics.",
    ["stress / pressure", "overwhelmed", "cope with", "recovery", "boundaries", "chronic stress", "cortisol (basic)", "switch off"],
    ["stress collocation range", "advice modality graded by intimacy"],
    ["Assess your current stress load honestly.", "Follow a therapist-style exploration.", "Read burnout research implications.", "Write your non-negotiable recovery practices."],
    "Overload triage: list stressors, split controllable/uncontrollable, act on one, release one.",
    "Recovery isn't laziness — un-recovered stress compounds like debt.",
    [["Pre-A1", "I am stressed."], ["A2", "Walking home without podcasts is when I actually decompress."], ["B1", "I had to learn that saying no protects my ability to say yes properly."], ["B2", "Chronic stress narrows attention exactly when breadth is needed."], ["C1", "Pressure performance depends less on intensity than on interpretation."]],

  ),
  t(110, "decision-psychology", "Decision-Making Psychology", "thinking", "lesson-22-psychology-human-mind",
    "Know your biases: anchoring, loss aversion, confirmation, sunk cost.",
    ["bias", "anchoring", "loss aversion", "confirmation bias", "sunk cost", "heuristics", "overconfidence", "pre-mortem"],
    ["abstract psychological description", "counterfactual conditionals"],
    ["Identify biases in one real past decision.", "Follow bias-explainer examples.", "Read a decision-science summary.", "Write a pre-mortem for an upcoming choice."],
    "Sunk-cost audit: name one commitment you maintain only because you already invested.",
    "Bias awareness doesn't immunise — it just enables catching yourself sooner.",
    [["Pre-A1", "People make mistakes."], ["A2", "We kept going because we'd already spent so much — classic sunk cost."], ["B1", "First numbers anchor every negotiation more than anyone admits."], ["B2", "Confirmation bias curates our information diets invisibly."], ["C1", "De-biasing requires institutional friction, not individual resolve alone."]],

  ),
  t(111, "leadership", "Leadership", "workplace", "lesson-23-leadership-personal-development",
    "Lead effectively: vision, delegation, feedback culture, trust-building.",
    ["lead / leadership", "delegate", "vision", "empower", "accountability", "lead by example", "psychological safety", "servant leadership"],
    ["leadership discourse patterns", "diplomatic directive forms"],
    ["Articulate your leadership philosophy with examples.", "Follow contrasting leader interviews.", "Compare management frameworks critically.", "Write your team's operating principles draft."],
    "New-team-lead scenario: inherit a demoralised group — diagnose before prescribing.",
    "Authority gets compliance; trust gets commitment. Confusing them caps careers.",
    [["Pre-A1", "She is the boss."], ["A2", "Good managers explain why, not just what."], ["B1", "Delegation failed until I started sharing context, not just tasks."], ["B2", "Psychological safety predicts team performance better than talent density."], ["C1", "Leadership legitimacy is granted bottom-up regardless of org charts."]],

  ),
  t(112, "teamwork", "Teamwork", "workplace", "lesson-23-leadership-personal-development",
    "Collaborate well: roles, communication norms, conflict use, remote dynamics.",
    ["collaborate", "role clarity", "stand-up", "handoff", "cross-functional", "groupthink", "async updates", "collective ownership"],
    ["team-process language", "diplomatic disagreement in groups"],
    ["Analyse what made one team succeed/fail.", "Follow a project retrospective.", "Read team charter documents.", "Write working-agreement proposals."],
    "Retrospective facilitation: surface what silently frustrated everyone without blame theatre.",
    "Conflict about work is fuel; conflict about people is solvent. Keep the first, drain the second.",
    [["Pre-A1", "We work together."], ["A2", "Everyone knew their role, so nothing fell through gaps."], ["B1", "Our best decisions came from disagreement handled with respect."], ["B2", "Async-first teams document thinking that meeting cultures leave verbal."], ["C1", "Team cohesion without dissent breeds confident wrong answers."]],

  ),
  t(113, "time-management", "Time Management", "workplace", "lesson-23-leadership-personal-development",
    "Allocate time deliberately: priorities, calendars, protection of deep work.",
    ["prioritise", "deep work", "time-box", "context switching", "calendar blocking", "to-do list", "deadline-driven", "say no strategically"],
    ["schedule descriptions", "priority justification structures"],
    ["Design tomorrow's calendar around one priority.", "Follow productivity-method comparisons.", "Evaluate a time-audit's findings.", "Write your ideal-week template."],
    "Calendar surgery: defend two hours of deep work against five reasonable interruptions.",
    "Busy ≠ productive: measure outputs shipped, not inputs endured.",
    [["Pre-A1", "I don't have enough time."], ["A2", "I plan my day the night before — it changes everything."], ["B1", "Blocking mornings for focused work doubled my output within weeks."], ["B2", "Every yes spends hours you haven't audited yet."], ["C1", "Time management is really attention management wearing clocks."]],

  ),
  t(114, "productivity", "Productivity", "workplace", "lesson-23-leadership-personal-development",
    "Increase output sustainably: systems, tools, measurement, rest integration.",
    ["productive / productivity", "workflow", "automation", "batch similar tasks", "output metrics", "diminishing returns", "sustainable pace", "tool sprawl"],
    ["process description language", "measurement discourse"],
    ["Audit one workflow and propose improvements.", "Follow a systems-thinking discussion.", "Read productivity research critically.", "Write a personal productivity manifesto."],
    "Weekly review implementation: capture, clarify, decide — build the ritual live.",
    "Productivity porn optimises systems while avoiding the uncomfortable priority question.",
    [["Pre-A1", "I finished my work fast."], ["A2", "Batching emails twice daily saved me an hour a day."], ["B1", "Automating the report freed time for analysis nobody else could do."], ["B2", "Optimisation without direction accelerates travel toward wrong destinations."], ["C1", "Rest is a productivity input, not its reward — physiology insists."]],

  ),
  t(115, "personal-growth-discipline", "Personal Growth and Self-Discipline", "thinking", "lesson-23-leadership-personal-development",
    "Grow deliberately: identity, standards, discomfort tolerance, review rituals.",
    ["self-discipline", "growth mindset", "comfort zone", "hold yourself accountable", "standard", "review / reflect", "compound (growth)", "identity-based habits"],
    ["reflective discourse", "identity language (I'm becoming...)"],
    ["Present one growth edge you're actively working.", "Follow mentoring conversations on standards.", "Read development-plan frameworks.", "Write your quarterly self-review honestly."],
    "Quarterly self-review: one win, one miss, one standard raised, one system adjusted.",
    "Discipline serves identity: 'I'm a runner' survives bad days that 'I'm trying to run' doesn't.",
    [["Pre-A1", "I want to be better."], ["A2", "I hold myself accountable by writing weekly goals."], ["B1", "Discomfort turned out to be the sensation of growth, not damage."], ["B2", "Standards slip quietly unless reviews make drift visible."], ["C1", "Growth compounds through consistency that motivation never sustains alone."]],

  ),
  t(116, "governments-citizens", "Governments and Citizens", "society", "lesson-24-society-politics-global",
    "Understand civic basics: branches, elections, participation beyond voting.",
    ["government", "election / vote", "policy", "constitution", "citizen", "petition", "campaign", "local council"],
    ["political process description", "opinion + concession structures"],
    ["Explain how a law gets made simply.", "Follow political news analysis.", "Compare party manifestos on one issue.", "Write to a representative about one issue."],
    "Local council consultation: argue for/against a policy affecting your street with civic literacy.",
    "Politics talk benefits from steelmanning: state others' views better than they do.",
    [["Pre-A1", "People vote for leaders."], ["A2", "Local councils decide things like bins, roads and planning permission."], ["B1", "Democracy requires participation between elections, not just during them."], ["B2", "Institutional literacy has declined while political passion increased."], ["C1", "Citizenship functions as practice, not status."]],

  ),
  t(117, "laws-rules", "Laws and Rules", "society", "lesson-24-society-politics-global",
    "Navigate legal basics: contracts, rights, obligations, when to get help.",
    ["law / legal", "contract terms", "rights", "liability", "small claims", "regulation", "breach", "legal advice"],
    ["legal obligation modality", "formal register comprehension"],
    ["Explain one everyday legal right clearly.", "Follow a consumer-rights explanation.", "Read tenancy contract clauses.", "Write a formal dispute letter."],
    "Landlord withholds deposit unfairly: know rights, gather evidence, escalate formally.",
    "Contracts bind through signatures not comprehension — read before signing anyway.",
    [["Pre-A1", "Rules are important."], ["A2", "My landlord must protect my deposit in a government scheme."], ["B1", "Verbal agreements are binding too, but proving them is harder."], ["B2", "Most legal problems stem from documentation gaps, not legal complexity."], ["C1", "Law encodes power balances while claiming neutrality — read both layers."]],

  ),
  t(118, "freedom-responsibility", "Freedom and Responsibility", "philosophy", "lesson-24-society-politics-global",
    "Balance liberty and obligation: speech, harm, autonomy, social contracts.",
    ["freedom of speech", "responsibility", "autonomy", "harm principle", "social contract", "consequence", "entitled", "civic duty"],
    ["abstract ethical argumentation", "balanced-position discourse"],
    ["Argue a freedom-vs-safety case both ways.", "Follow philosophical panel discussion.", "Read opposing essays on one dilemma.", "Write your position acknowledging strongest counterargument."],
    "Speech-policy debate: draw your own line between offence and harm, defend it under pressure.",
    "Freedom discussions collapse without specifying whose freedom, costing whom what.",
    [["Pre-A1", "I am free to choose."], ["A2", "Freedom comes with responsibility for consequences."], ["B1", "Your right to swing your arm ends where my nose begins."], ["B2", "Absolute positions simplify debates by removing the actual dilemmas."], ["C1", "Liberty and obligation aren't opposites but co-dependents in functional societies."]],

  ),
  t(119, "social-inequality", "Social Inequality", "society", "lesson-24-society-politics-global",
    "Discuss inequality precisely: wealth gaps, opportunity, mobility, structural factors.",
    ["inequality / gap", "wealth distribution", "opportunity", "social mobility", "privilege", "structural", "redistribution", "meritocracy myth"],
    ["statistical discourse", "structural vs individual causation language"],
    ["Distinguish luck from merit in success stories.", "Follow socioeconomic debate respectfully.", "Compare inequality data presentations.", "Write a nuanced position on one policy."],
    "Meritocracy debate: examine your own advantages honestly, then discuss policy implications.",
    "Individual effort and structural advantage interact — denying either distorts analysis.",
    [["Pre-A1", "Some people are rich, some poor."], ["A2", "Where you're born still shapes where you end up."], ["B1", "Equal opportunity sounds fair until you define the starting line."], ["B2", "Mobility statistics reveal how sticky advantage remains across generations."], ["C1", "Inequality debates founder on contested baselines rather than disputed facts."]],

  ),
  t(120, "global-challenges", "Global Challenges", "global", "lesson-24-society-politics-global",
    "Survey global issues: pandemics, migration, conflict, coordination failures.",
    ["global challenge", "pandemic", "refugee crisis", "humanitarian aid", "international cooperation", "conflict zone", "food security", "collective action problem"],
    ["global-scale description", "interconnection language"],
    ["Connect two global challenges causally.", "Follow international-affairs discussion.", "Compare coverage of one humanitarian crisis.", "Write an issue brief with stakeholder map."],
    "Model UN lite: represent one country's interest in a pandemic-response negotiation.",
    "Global problems lack global government — coordination, not solution, is usually the ask.",
    [["Pre-A1", "Countries must work together."], ["A2", "The pandemic showed how connected everything is."], ["B1", "Refugee flows follow conflicts that follow resource pressures."], ["B2", "Collective-action problems explain most stalled global responses."], ["C1", "Interdependence raised stakes faster than institutions evolved."]],

  ),
  t(121, "ethics-moral-choices", "Ethics and Moral Choices", "philosophy", "lesson-25-advanced-ideas",
    "Reason ethically: frameworks, dilemmas, principles under pressure.",
    ["ethics / moral", "dilemma", "principle", "consequentialism (basic)", "duty", "integrity test", "lesser evil", "moral compass"],
    ["ethical reasoning structures", "hypothetical dilemma language"],
    ["Resolve an ethical dilemma defending your framework.", "Follow ethicists disagreeing productively.", "Compare two philosophical treatments.", "Write a personal code with three principles."],
    "Trolleyology plus reality: workplace whistle-blowing dilemma reasoned aloud.",
    "Ethical confidence should track reasoning quality, not conclusion comfort.",
    [["Pre-A1", "Helping people is good."], ["A2", "Sometimes there's no perfect option — only better and worse."], ["B1", "Consequences matter, but so does what the act makes of us."], ["B2", "Integrity shows in decisions that cost you privately and benefit nobody visibly."], ["C1", "Moral maturity tolerates genuine dilemmas without premature resolution."]],

  ),
  t(122, "success-failure", "Success and Failure", "philosophy", "lesson-25-advanced-ideas",
    "Redefine success: metrics, failure's role, survivorship illusions.",
    ["success criteria", "failure", "survivorship bias", "resilience", "redefine", "measure up", "setback", "post-mortem"],
    ["redefinition discourse", "counterfactual reflection"],
    ["Interrogate your own definition of success.", "Follow failure-storytelling sessions.", "Read biographies' edited-out failures.", "Write a failure CV entry with lessons."],
    "Failure résumé exercise: list rejections and flops, extract what each taught or cost.",
    "Survivorship bias hides graveyard data — visible winners overrepresent luck.",
    [["Pre-A1", "Winning is nice."], ["A2", "Failure teaches things success never could."], ["B1", "Most overnight successes were decade-long obscurities first."], ["B2", "Failure post-mortems beat success celebrations for transferable insight."], ["C1", "Success definitions imported uncritically guarantee chronic inadequacy."]],

  ),
  t(123, "happiness-meaning", "Happiness and Meaning", "philosophy", "lesson-25-advanced-ideas",
    "Explore wellbeing: hedonia vs eudaimonia, meaning-making, comparison traps.",
    ["wellbeing", "meaning / purpose", "hedonic treadmill", "fulfilment", "contentment", "gratitude", "flourish", "life satisfaction"],
    ["abstract wellbeing discourse", "contrastive philosophical framing"],
    ["Articulate what makes life meaningful for you.", "Follow wellbeing-science discussion.", "Compare happiness philosophies.", "Write your meaning inventory."],
    "Deathbed perspective exercise: reverse-engineer today's priorities from final regrets.",
    "Pursuing happiness directly backfires; pursuing meaning delivers it obliquely.",
    [["Pre-A1", "Family makes me happy."], ["A2", "New things excite me briefly, then become normal — every time."], ["B1", "Purpose survived even when happiness didn't, which told me something."], ["B2", "Comparison steals contentment through invisible reference groups."], ["C1", "Meaning tolerates suffering; pleasure cannot — the distinction organises lives."]],

  ),
  t(124, "freedom-choice", "Freedom and Choice", "philosophy", "lesson-25-advanced-ideas",
    "Examine choice: abundance paradoxes, constraints enabling, deciding frameworks.",
    ["choice overload", "constraint", "optionality", "commitment device", "FOMO", "agency", "default", "close doors deliberately"],
    ["paradox explanation structures", "meta-cognitive discourse"],
    ["Analyse one decision paralysis you've experienced.", "Follow choice-architecture discussion.", "Read choice-overload research nuance.", "Write what you'll deliberately stop choosing."],
    "Option audit: which open loops drain attention? Close three deliberately this week.",
    "Keeping options open has carrying costs; commitment purchases focus.",
    [["Pre-A1", "Too many choices!"], ["A2", "Having options felt good until choosing became exhausting."], ["B1", "Constraints sped up my decisions once I stopped resenting them."], ["B2", "Abundance shifted scarcity from goods to attention."], ["C1", "Agency expresses itself as much in renunciation as acquisition."]],

  ),
  t(125, "human-values", "Human Values", "philosophy", "lesson-25-advanced-ideas",
    "Clarify values: hierarchies, conflicts, living alignment, cultural variance.",
    ["values", "principle-driven", "value conflict", "integrity gap", "prioritise values", "universal vs relative", "authenticity", "compromise values"],
    ["value-hierarchy discourse", "alignment analysis language"],
    ["Rank your top five values and test recent decisions against them.", "Follow cross-cultural values dialogue.", "Compare values frameworks.", "Write where your stated values diverge from revealed ones."],
    "Values archaeology: examine calendar and bank statement — what do they say you value?",
    "Stated values aspirate; revealed values spend. Audit the second.",
    [["Pre-A1", "Honesty is important."], ["A2", "My top values are family, learning and health."], ["B1", "Value conflicts reveal themselves when two good things compete."], ["B2", "Alignment between values and actions predicts life satisfaction reliably."], ["C1", "Values function as decision heuristics precisely where analysis exhausts itself."]],
  ),
];
