/** 150-topic master library, part 2 of 6 (topics 26–50 · Lessons 6–10): social life, past, future, education, work. */
import type { Topic150 } from "./topics150-a";

const t = (
  n: number, id: string, title: string, category: string, lessonId: string, purpose: string,
  vocab: string[], grammar: string[],
  skills: [string, string, string, string],
  scenario: string, pitfall: string,
  ladder: Array<[string, string]>,
): Topic150 => ({
  n, id, title, category, lessonId, purpose,
  vocab, grammar,
  skills: { speaking: skills[0], listening: skills[1], reading: skills[2], writing: skills[3] },
  scenario, pitfall,
  ladder: ladder.map(([level, example]) => ({ level, example })),
});

export const TOPICS_150_B: Topic150[] = [
  t(26, "friends-friendship", "Friends and Friendship", "social", "lesson-06-people-social-life",
    "Describe friends, how you met, and what makes a good friendship.",
    ["close friend / best friend", "We met at...", "get on well", "have a lot in common", "keep in touch", "trustworthy", "flatmate", "childhood friend"],
    ["past simple for how you met", "present simple for habits together"],
    ["Describe your closest friend and one memory.", "Follow a story about a friendship that changed.", "Read a message between friends.", "Write an invitation to an old friend."],
    "You bump into a school friend after ten years on the metro — rebuild contact in five minutes.",
    "'Get on well WITH someone' — don't drop the preposition.",
    [["Pre-A1", "He is my best friend."], ["A2", "We met at university and got on straight away."], ["B1", "We don't see each other much, but whenever we meet it's like no time has passed."], ["B2", "Adult friendships survive on intention rather than proximity."], ["C1", "The friendships that endure are rarely the most intense ones."]],
  ),
  t(27, "personality-character", "Personality and Character", "personal", "lesson-06-people-social-life",
    "Describe what people are like: character adjectives with examples.",
    ["kind / generous", "shy / confident", "funny / serious", "hard-working / lazy", "honest", "stubborn", "She's the kind of person who...", "a bit + adjective"],
    ["adjective + preposition (afraid of, good at)", "comparatives for people"],
    ["Describe three people you know with proof, not just adjectives.", "Identify personalities from voice tone.", "Read two short character sketches.", "Write your own character in six lines."],
    "Blind-description game: describe a mutual friend until the other guesses who.",
    "Back up adjectives: 'She's generous — she paid for my course.'",
    [["Pre-A1", "My mother is kind."], ["A2", "My brother is quite shy, but very funny once you know him."], ["B1", "He's stubborn to the point of self-sabotage sometimes."], ["B2", "She's the sort of manager who remembers details about everyone's lives."], ["C1", "Confidence and arrogance differ mostly in how they treat being wrong."]],
  ),
  t(28, "social-invitations", "Social Invitations", "social", "lesson-06-people-social-life",
    "Invite, accept and decline politely; fix times and places.",
    ["Would you like to...?", "Do you fancy...?", "I'd love to", "I'm afraid I can't", "How about Saturday?", "Let me check my diary", "count me in", "maybe next time"],
    ["would like + to-infinitive", "present continuous for arrangements"],
    ["Invite someone and handle yes/no/maybe.", "Catch the actual time/place inside friendly chat.", "Read an event invite with RSVP.", "Write a short invitation message."],
    "You're invited to a birthday dinner but already have plans — decline warmly and propose an alternative.",
    "Soften refusals: 'I'm afraid I can't' sounds far kinder than 'No'.",
    [["Pre-A1", "Come to my house!"], ["A1", "Do you want to come for coffee?"], ["A2", "Would you like to join us on Saturday? We're meeting at seven."], ["B1", "I'd love to, but I've already promised to help my sister move."], ["B2", "Count me in — just send me the address closer to the day."], ["C1", "I'll take a rain check if I may — this week has quietly fallen apart."]],
  ),
  t(29, "celebrations-special-occasions", "Celebrations and Special Occasions", "culture", "lesson-06-people-social-life",
    "Talk about birthdays, weddings and holidays, and give good wishes.",
    ["Happy birthday!", "Congratulations!", "wedding / anniversary", "guest", "present / gift", "cake / candles", "make a toast", "Well done!"],
    ["past simple celebration stories", "future plans for upcoming events"],
    ["Congratulate someone and ask follow-up questions.", "Follow wedding/celebration small talk.", "Read an invitation card.", "Write a birthday message to someone."],
    "At a colleague's engagement party, congratulate, chat and ask about plans.",
    "Congratulations is always plural. Good luck vs congratulations — context matters.",
    [["Pre-A1", "Happy birthday!"], ["A1", "Congratulations! I'm so happy for you."], ["A2", "We're having a party next Friday — it's her 30th."], ["B1", "The wedding was lovely, though the speeches went on a bit."], ["B2", "We kept the celebration deliberately small — family, close friends, no fuss."], ["C1", "Rituals matter less for their form than for marking that something changed."]],

  ),
  t(30, "social-rules-manners", "Social Rules and Good Manners", "culture", "lesson-06-people-social-life",
    "Be politely direct: excuse me, sorry, asking permission, polite requests.",
    ["Excuse me", "Sorry / I'm so sorry", "After you", "May I...?", "Could you possibly...?", "Never mind", "That's very kind of you", "No worries"],
    ["could/would for politeness", "mind + -ing (Do you mind if...?)"],
    ["Handle four classic awkward moments politely (bump, interrupt, refuse, thank).", "Hear how tone changes a polite phrase into sarcasm.", "Match polite phrases to situations.", "Write a polite complaint opener."],
    "You spill coffee near a stranger's laptop: full polite recovery sequence required.",
    "'Do you mind if I...?' — answer 'Not at all' means YES you may. Tricky!",
    [["Pre-A1", "Excuse me! Sorry!"], ["A1", "May I open the window?"], ["A2", "Would you mind moving your chair slightly?"], ["B1", "Terribly sorry to interrupt — could I borrow you for a second?"], ["B2", "I hate to be that person, but would it be possible to keep the noise down after eleven?"], ["C1", "British indirectness isn't vagueness — it's precision dressed as courtesy."]],

  ),
  t(31, "yesterday-recent-activities", "Yesterday and Recent Activities", "daily", "lesson-07-past-experiences",
    "Tell what you did recently using past simple regular and irregular verbs.",
    ["yesterday / last night", "this morning", "went / did / saw / had", "got up / came home", "What did you do?", "first / then / after that", "ago", "last weekend"],
    ["past simple: regular -ed and key irregulars", "question/negative with did"],
    ["Narrate yesterday in order with six verbs.", "Spot the lie in two versions of a story.", "Read a short diary entry.", "Write five sentences about last night."],
    "Monday catch-up: colleagues compare weekends; yours was unusual — tell it well.",
    "Negative past uses 'didn't go', not 'didn't went'.",
    [["Pre-A1", "I played football yesterday."], ["A1", "I went to the park and saw Ahmed."], ["A2", "I didn't do much — just cooked and watched two films."], ["B1", "I'd planned a quiet weekend, then everything changed on Saturday morning."], ["B2", "Looking back, that trip quietly reset half my routines."], ["C1", "Memory edits our recent past more aggressively than we admit."]],
  ),
  t(32, "childhood-memories", "Childhood Memories", "personal", "lesson-07-past-experiences",
    "Describe childhood: where you lived, what you did, how life differed.",
    ["when I was a child", "used to play", "primary school", "grandparents' house", "cartoons / games", "I remember...", "back then", "grow up"],
    ["used to + infinitive", "past continuous for background (was living, was playing)"],
    ["Tell a two-minute childhood memory with feeling.", "Understand nostalgia-heavy speech at natural speed.", "Read a memoir extract.", "Write 'my earliest memory' in eight lines."],
    "Grandmother shows you a photo album: narrate the stories behind three photos.",
    "Used to = past habit. Don't say 'I am used to play' for childhood.",
    [["Pre-A1", "I played with my friends."], ["A1", "I lived in a small house with my grandparents."], ["A2", "We used to cycle everywhere — helmets weren't even a thing."], ["B1", "I was convinced our street was the centre of the universe back then."], ["B2", "Childhood summers felt endless precisely because we had nothing to measure them against."], ["C1", "Nostalgia flatters the past mainly by erasing its boredom."]],

  ),
  t(33, "holidays-travel-experiences", "Holidays and Travel Experiences", "social", "lesson-07-past-experiences",
    "Recount trips: where, when, who, what happened — the good and the bad.",
    ["trip / holiday / vacation", "sightseeing", "It was amazing / awful", "we stayed in...", "the food was...", "getting there", "souvenir", "unforgettable"],
    ["past simple narrative", "past perfect basics (had never seen)"],
    ["Tell a 90-second holiday story with a twist.", "Follow a travel anecdote with interruptions.", "Read a hotel review.", "Write a postcard-style summary of a trip."],
    "Dinner party: someone asks about your worst trip ever. Tell it with a proper ending.",
    "Sequence past events clearly: first we landed, THEN the problems started.",
    [["Pre-A1", "I went to the beach."], ["A1", "Last summer we visited Alexandria. It was hot."], ["A2", "The hotel was awful, but the food almost made up for it."], ["B1", "Our flight got cancelled, so we ended up discovering a town none of us knew."], ["B2", "The trip taught us that plans are suggestions; everything else is improvisation."], ["C1", "The best journeys are the ones your itinerary never survives."]],

  ),
  t(34, "memorable-events", "Memorable Events", "personal", "lesson-07-past-experiences",
    "Describe life-changing or unforgettable moments and why they mattered.",
    ["the day I...", "I'll never forget...", "it changed everything", "suddenly", "in the end", "proud / shocked", "turning point", "at the time"],
    ["past continuous interrupted by past simple", "so/such for emphasis"],
    ["Tell one memorable event with build-up and payoff.", "Detect which moment mattered most to a speaker.", "Read a news human-interest story.", "Write the story of your proudest day."],
    "An interview asks: 'Tell us about a moment that changed direction in your life.'",
    "Set the scene with past continuous: 'I WAS WAITING for the bus when...'",
    [["Pre-A1", "It was a happy day."], ["A1", "I passed my exam. I was very proud."], ["A2", "I'll never forget the day we arrived — everything was new."], ["B1", "I was waiting for the results when my phone rang unexpectedly."], ["B2", "That rejection turned out to be the most useful thing that year did for me."], ["C1", "Defining moments rarely announce themselves; they only reveal themselves later."]],

  ),
  t(35, "telling-personal-stories", "Telling Personal Stories", "social", "lesson-07-past-experiences",
    "Structure a spoken story: setting, problem, twist, ending, reaction.",
    ["Guess what happened!", "You'll never believe this", "So anyway...", "to make a long story short", "And then — get this —", "luckily / unfortunately", "in the end", "true story"],
    ["narrative tenses mix", "exclamations and reactions"],
    ["Tell a 60-second story that lands an ending.", "React appropriately to someone else's story beats.", "Read a short anecdote and find its punchline.", "Rewrite a boring story with suspense."],
    "Story night with friends: tell one real story that gets a reaction at the end.",
    "Stories need endings — don't trail off with 'and yeah'.",
    [["Pre-A1", "Then... we laughed!"], ["A1", "Guess what! I found my keys in the fridge."], ["A2", "To cut a long story short, we missed the train but caught a better one."], ["B1", "Unfortunately, the punchline arrived before the joke had finished building."], ["B2", "Every good anecdote hides one detail until exactly the right second."], ["C1", "Storytelling is really the art of withholding — timing over information."]],

  ),
  t(36, "weekend-plans", "Weekend Plans", "social", "lesson-08-future-plans",
    "Arrange weekend activities: suggest, agree, confirm times and places.",
    ["What are you doing at the weekend?", "I'm seeing my cousins", "Shall we...?", "fancy coming?", "meet up", "book / reserve", "if the weather's nice", "confirm"],
    ["present continuous for future arrangements", "shall we / let's suggestions"],
    ["Make a plan with a friend and lock in details.", "Catch arrangements changing mid-chat.", "Read a group chat thread about logistics.", "Write a confirmation message with time+place."],
    "Group chat chaos: five people, one cinema trip — get time, place and tickets sorted.",
    "Arrangements use present continuous: 'I'M MEETING Sara', not 'I will meet'.",
    [["Pre-A1", "Football on Sunday?"], ["A1", "I'm going to the market tomorrow morning."], ["A2", "Are you doing anything on Saturday? A few of us are meeting at the park."], ["B1", "Let's say ten at the main entrance, and I'll book tickets tonight."], ["B2", "Weather permitting, we'll do the coastal walk — otherwise pub lunch it is."], ["C1", "My weekends have become a negotiation between ambition and recovery."]],

  ),
  t(37, "future-dreams", "Future Dreams", "personal", "lesson-08-future-plans",
    "Talk about hopes and dreams: travel, home, family, achievements.",
    ["dream / hope", "one day", "I hope to...", "I'd love to...", "travel the world", "start a family", "achieve", "someday"],
    ["want/hope/plan + to-infinitive", "will vs going to for dreams vs plans"],
    ["Share three dreams and why they matter.", "Follow two friends comparing futures.", "Read a profile of someone who chased a dream.", "Write your top three life goals."],
    "Late-night conversation after a wedding: everyone shares what they actually want from life.",
    "'I'd love to visit Japan' — the 'd is would; don't write 'I will loving'.",
    [["Pre-A1", "I want a big house."], ["A1", "I hope to get a good job."], ["A2", "One day I'd love to open a small café by the sea."], ["B1", "I'm saving up because I intend to take a proper career break next year."], ["B2", "Most of my dreams have become quieter but far more specific."], ["C1", "Dreams evolve from destinations into ways of wanting to live."]],

  ),
  t(38, "education-goals", "Education Goals", "education", "lesson-08-future-plans",
    "Set learning goals: courses, certificates, study plans and motivation.",
    ["course / certificate", "apply for", "pass / fail", "improve my English", "study abroad", "scholarship", "deadline", "make progress"],
    ["plan/intend + to-infinitive", "future time clauses: when I finish..."],
    ["State a study goal with deadline and steps.", "Follow advice about choosing a course.", "Read a course description and entry requirements.", "Write your study plan for this month."],
    "Advising session: pick your next course and justify it against time and money.",
    "'Take an exam' / 'sit an exam' — not 'do an exam'.",
    [["Pre-A1", "I study English every day."], ["A1", "I want to pass the B1 exam."], ["A2", "I'm planning to take an intensive course this summer."], ["B1", "Once I've got the certificate, I'll apply for the masters programme."], ["B2", "Formal qualifications matter less than demonstrable skill — but try telling HR that."], ["C1", "Education goals are increasingly portfolio-shaped rather than degree-shaped."]],

  ),
  t(39, "career-ambitions", "Career Ambitions", "career", "lesson-08-future-plans",
    "Talk about the job you want and the steps to get there.",
    ["career", "promotion", "qualify as", "gain experience", "in five years", "my goal is to...", "work my way up", "change careers"],
    ["going to vs will for career intentions", "first conditional: If I get..., I will..."],
    ["Present a realistic 5-year career picture.", "Follow a career-change story.", "Read a job profile and requirements.", "Write your career sentence: where, what, why."],
    "Mentoring session: describe your ambition honestly, including what scares you about it.",
    "Ambition needs structure: goal → step → deadline, not just 'success'.",
    [["Pre-A1", "I want to be a doctor."], ["A1", "I'm going to study nursing."], ["A2", "In five years I want to manage my own small team."], ["B1", "If I pass the professional exam, I'll finally qualify here."], ["B2", "I'd rather build depth in one field than collect shallow job titles."], ["C1", "Careers now resemble portfolios more than ladders."]],

  ),
  t(40, "life-plans-priorities", "Life Plans and Priorities", "thinking", "lesson-08-future-plans",
    "Prioritise what matters: balance work, money, family, health and time.",
    ["priority", "settle down", "work-life balance", "save up for", "make time for", "trade-off", "long-term", "what really matters"],
    ["future continuous (this time next year I'll be...)", "comparatives for priorities"],
    ["Explain your current #1 priority and why.", "Follow a debate about city vs hometown life.", "Read contrasting life-plan essays briefly.", "Write your priorities ranked with reasons."],
    "New Year conversation: rank your top three priorities and defend the order.",
    "'Priority' — one thing comes first; saying everything is a priority means nothing is.",
    [["Pre-A1", "Family is number one."], ["A1", "First I need a job, then a flat."], ["A2", "Right now my priority is passing the exam, not travelling."], ["B1", "I'm trying to make more time for my parents while I still can."], ["B2", "Every priority costs something else — that's the part nobody budgets for."], ["C1", "Priorities are revealed by calendars, never by mission statements."]],

  ),
  t(41, "school-university-life", "School and University Life", "education", "lesson-09-education-learning",
    "Navigate school/university: subjects, teachers, timetables, campus services.",
    ["term / semester", "timetable / schedule", "lecture / seminar", "campus", "enrol / register", "major / subject", "tutor", "library card"],
    ["present simple for timetables", "obligation: must / have to"],
    ["Describe your weekly timetable.", "Follow orientation-day instructions.", "Read course regulations quickly.", "Write a question email to the registrar."],
    "First week on campus: find your rooms, understand the timetable, register for modules.",
    "Subjects are capitalised in English: Biology, History.",
    [["Pre-A1", "This is my school."], ["A1", "My favourite subject is science."], ["A2", "I have lectures on Mondays and seminars on Wednesdays."], ["B1", "Registration closes Friday, so you'll have to decide about electives today."], ["B2", "Contact hours shrank while independent workload quietly tripled."], ["C1", "Universities increasingly sell belonging as much as knowledge."]],

  ),
  t(42, "subjects-study-skills", "Subjects and Study Skills", "education", "lesson-09-education-learning",
    "Study effectively: note-taking, memorising, planning revision sessions.",
    ["revise / review", "take notes", "summarise", "flashcards", "memorise", "focus / concentrate", "break it down", "study plan"],
    ["advice structures: should, why don't you", "by + gerund (by testing yourself)"],
    ["Give a classmate three study tips.", "Follow a teacher explaining a revision method.", "Read a how-to-study guide.", "Write tomorrow's focused study block."],
    "Exam in ten days: design a revision plan live with a study partner.",
    "'Revise' (UK) = review (US) for exams — same action.",
    [["Pre-A1", "I read my book."], ["A1", "I do my homework every evening."], ["A2", "I make flashcards and test myself on the bus."], ["B1", "Summarising each lecture in five bullet points changed how I retain things."], ["B2", "Active recall beats re-reading — yet everyone still just re-reads."], ["C1", "Study techniques are less magic than honest scheduling."]],

  ),
  t(43, "exams-assessment", "Exams and Assessment", "education", "lesson-09-education-learning",
    "Prepare for and talk about exams: formats, stress tactics, results language.",
    ["exam / test / mock exam", "marks / grades", "multiple choice", "essay question", "retake", "pass mark", "results come out", "cheat"],
    ["modality: might/may for outcomes", "regret: I should have studied earlier"],
    ["Explain how you'll prepare for one specific exam.", "Catch instructions read aloud in an exam hall.", "Read exam rules and rubric notes.", "Write a results-day plan for best and worst cases."],
    "Mock-exam debrief: analyse what went wrong and design the fix before the real one.",
    "Results are 'out', not 'open'. You 'pass' an exam, you don't 'success' it.",
    [["Pre-A1", "Test today. I am nervous."], ["A1", "I passed my English test!"], ["A2", "If I don't pass, I can retake it in June."], ["B1", "I ran out of time on the essay — I should have planned it first."], ["B2", "Mocks exist to expose weaknesses cheaply; treating them as verdicts wastes them."], ["C1", "Assessment shapes learning more than teaching does — for better and worse."]],

  ),
  t(44, "learning-languages", "Learning Languages", "education", "lesson-09-education-learning",
    "Discuss language learning itself: methods, struggles, breakthroughs.",
    ["fluent / beginner level", "accent", "practise speaking", "make mistakes", "pick up (a language)", "language exchange", "vocabulary", "get better at"],
    ["gerunds as subjects (Speaking daily helps)", "comparatives of methods"],
    ["Describe your method and one breakthrough moment.", "Follow a polyglot interview's key points.", "Read app-store reviews of a learning app.", "Write your own language-learning manifesto."],
    "Language-exchange meetup: swap methods, failures and one trick that actually works.",
    "'Practise' (verb, UK) vs 'practice' (noun) — spelling matters.",
    [["Pre-A1", "English is hard."], ["A1", "I learn ten new words every day."], ["A2", "Speaking is harder than reading for me, but it's improving."], ["B1", "Watching series without subtitles forced my listening to level up."], ["B2", "Perfectionism is the biggest obstacle — fluency tolerates error, perfection doesn't."], ["C1", "Languages are learned socially; apps merely schedule the exposure."]],

  ),
  t(45, "online-learning", "Online Learning", "technology", "lesson-09-education-learning",
    "Learn digitally: platforms, video lessons, forums, MOOCs and discipline.",
    ["online course / platform", "log in / sign up", "download / upload", "due date", "discussion forum", "stream / replay", "certificate of completion", "self-paced"],
    ["present perfect experience (I've completed three courses)", "zero conditional for platform rules"],
    ["Explain how online learning suits or doesn't suit you.", "Follow a tech-support style exchange about a course platform.", "Read a course landing page critically.", "Write a two-line review of a course you took."],
    "Platform won't load your certificate: troubleshoot with support in writing and live chat.",
    "'Log in' (verb) vs 'login' (noun) — spelling shifts with grammar.",
    [["Pre-A1", "Class is online today."], ["A1", "I watch English videos on my phone."], ["A2", "I've signed up for two free courses this month."], ["B1", "Self-paced sounds ideal until deadlines stop existing entirely."], ["B2", "Completion rates under 15% say more about course design than learner motivation."], ["C1", "Online learning democratised access while quietly outsourcing accountability to willpower."]],

  ),
  t(46, "jobs-occupations", "Jobs and Occupations", "career", "lesson-10-work-careers",
    "Name common jobs and say what people do in them.",
    ["doctor / nurse", "engineer / architect", "teacher / driver", "salesperson", "works for / works in", "full-time / part-time", "shift", "colleague"],
    ["works as / in / for", "third person -s in job descriptions"],
    ["Describe what five workers do all day.", "Identify jobs from task descriptions.", "Read a company team page.", "Write what your ideal colleague does."],
    "Career day at a school: explain your job to teenagers in plain words.",
    "'Work' is uncountable — 'a work' doesn't exist; use 'a job'.",
    [["Pre-A1", "She is a teacher."], ["A1", "My father works in a hospital."], ["A2", "He works for a construction company as a site engineer."], ["B1", "It's shift-based, which takes adjustment but frees up weekdays."], ["B2", "Job titles inflate faster than responsibilities — read the tasks, not the label."], ["C1", "Occupations increasingly hybridise; nobody's week matches their contract."]],

  ),
  t(47, "the-workplace", "The Workplace", "workplace", "lesson-10-work-careers",
    "Know workplace basics: hours, breaks, dress code, facilities, rules.",
    ["office / site / factory", "clock in / clock out", "dress code", "break room", "HR department", "probation period", "overtime", "notice board"],
    ["have to / must for workplace rules", "allowed to / can't for permissions"],
    ["Ask a colleague three induction questions correctly.", "Follow an office tour explanation.", "Read an employee handbook extract.", "Write your first-week questions list."],
    "First day: absorb the unwritten rules — where people eat, when meetings actually start.",
    "'Staff' is plural: 'The staff ARE friendly', not 'is'.",
    [["Pre-A1", "This is my office."], ["A1", "Lunch break starts at one o'clock."], ["A2", "Do we have to wear a shirt, or is it casual on Fridays?"], ["B1", "Probation lasts three months — after that the benefits kick in."], ["B2", "Hybrid policies quietly renegotiate whose home doubles as an office."], ["C1", "Office culture transmits through micro-signals no handbook captures."]],

  ),
  t(48, "job-interviews", "Job Interviews", "career", "lesson-10-work-careers",
    "Perform in interviews: strengths, experience stories, salary basics.",
    ["strengths / weaknesses", "experience", "I worked on...", "responsible for", "achievement", "Why do you want this job?", "team player", "notice period"],
    ["present perfect for experience (I have led...)", "past simple for specific projects"],
    ["Answer the five universal interview questions.", "Follow an interviewer's follow-up probes.", "Read a job advert against your CV.", "Write answers to two hard questions."],
    "Interview for a junior analyst role: third round, senior interviewer, curveball question included.",
    "Interviews reward stories with numbers: 'cut delivery time by 30%'.",
    [["Pre-A1", "I want this job."], ["A1", "I worked in a shop for two years."], ["A2", "My main strength is staying calm when things go wrong."], ["B1", "I led a small team during our busiest quarter and we hit every target."], ["B2", "I'm looking for scope rather than title — room to own outcomes end-to-end."], ["C1", "The honest answer to 'greatest weakness' is usually a strength unmanaged."]],

  ),
  t(49, "cvs-applications", "CVs, Applications and Professional Introductions", "career", "lesson-10-work-careers",
    "Build CV language and write applications that match a role.",
    ["CV / resume", "cover letter", "references available", "key skills", "work history", "apply for a position", "enclosed / attached", "I look forward to hearing from you"],
    ["action verb past forms (managed, delivered, reduced)", "formal letter conventions"],
    ["Summarise your CV aloud in 45 seconds.", "Follow recruiter screening-call questions.", "Scan a job spec for must-have criteria.", "Write a four-sentence cover letter opening."],
    "Application sprint: tailor your CV summary and cover line to one specific advert in 20 minutes.",
    "CVs use past-tense action verbs without 'I': 'Managed...', not 'I managed...'.",
    [["Pre-A1", "This is my CV."], ["A1", "I can send my CV by email."], ["A2", "Please find my CV attached. I look forward to hearing from you."], ["B1", "I tailored my cover letter to their focus on customer retention."], ["B2", "Recruiters spend seconds per CV — structure carries more weight than prose."], ["C1", "Applications are marketing documents; modesty belongs in interviews, not summaries."]],

  ),
  t(50, "workplace-communication", "Workplace Communication", "workplace", "lesson-10-work-careers",
    "Communicate at work: requests, updates, clarifications across channels.",
    ["Could you get back to me...?", "just checking in", "as discussed", "keep me posted", "circle back", "quick update", "copy me in", "EOD"],
    ["polite request forms", "present continuous for ongoing work"],
    ["Chase a late reply without sounding angry.", "Follow a fast stand-up update round.", "Read a project thread and extract actions.", "Write a two-line status update."],
    "Project slipping silently: raise it constructively in a channel message before it escalates.",
    "Email tone: 'Just circling back' = polite 'you haven't replied'. Learn the code.",
    [["Pre-A1", "Meeting at two o'clock."], ["A1", "Can you send me the file, please?"], ["A2", "Just checking in — any update on the delivery date?"], ["B1", "As discussed, I'll draft the summary and share it by EOD Thursday."], ["B2", "Flagging early so we can adjust scope rather than apologise later."], ["C1", "Workplace friction is usually information asymmetry wearing a bad mood."]],
  ),
];
