/** 150-topic master library, part 6 of 6 (topics 126–150 · Lessons 26–28): argumentation, academic/professional mastery, real-world capstone. */
import type { Topic150 } from "./topics150-a";

const t = (
  n: number, id: string, title: string, category: string, lessonId: string, purpose: string,
  vocab: string[], grammar: string[],
  skills: [string, string, string, string],
  scenario: string, pitfall: string,
  ladder: Array<[string, string]>,
): Topic150 => ({
  n, id, title, category, lessonId, purpose,
  vocab, grammar,
  skills: { speaking: skills[0], listening: skills[1], reading: skills[2], writing: skills[3] },
  scenario, pitfall,
  ladder: ladder.map(([level, example]) => ({ level, example })),
});

export const TOPICS_150_F: Topic150[] = [
  t(126, "argument-structure", "Building an Argument", "argumentation", "lesson-26-advanced-argumentation",
    "Construct rigorous arguments: claim, grounds, warrant, qualification.",
    ["claim", "premise", "evidence", "warrant", "counterclaim", "rebuttal", "qualify a claim", "line of reasoning"],
    ["concessive structures", "formal argument connectives"],
    ["Build a complete Toulmin-style argument aloud.", "Follow structured debate exchanges.", "Analyse one opinion piece's skeleton.", "Write a position with named warrants."],
    "Debate prep room: build your case for a motion, then attack your own weakest link before opponents do.",
    "Arguments fail at unstated warrants — surface the assumption connecting evidence to claim.",
    [["Pre-A1", "I think this because that."], ["A2", "My main point is X; for example, Y proves it."], ["B1", "While some disagree, the evidence favours my position."], ["B2", "Granting the strongest counterexample actually sharpens the central claim."], ["C1", "The warrant here rests on contested definitions of fairness itself."]],

  ),
  t(127, "persuasion-rhetoric", "Persuasion and Rhetoric", "argumentation", "lesson-26-advanced-argumentation",
    "Persuade deliberately: ethos, pathos, logos, framing, rhetorical devices.",
    ["persuade / persuasion", "credibility (ethos)", "emotional appeal (pathos)", "logic appeal (logos)", "framing", "rhetorical question", "tricolon", "call to action"],
    ["rhetorical device recognition and use", "audience-register calibration"],
    ["Deliver a two-minute persuasive pitch.", "Identify appeals in political speech.", "Compare two framings of one issue.", "Write a persuasive op-ed opening."],
    "Pitch panel: sell an idea to three sceptical stakeholders using all three appeals deliberately.",
    "Rhetoric without substance is detectable and corrosive — layer appeals on solid grounds.",
    [["Pre-A1", "Please buy this!"], ["A2", "This product will save you time every day."], ["B1", "As someone who's tested this myself, I can vouch for it."], ["B2", "The question isn't whether we act but when — and delay has costs too."], ["C1", "Whoever frames the debate usually wins it before arguments begin."]],

  ),
  t(128, "debate-counterarguments", "Debate and Counterarguments", "argumentation", "lesson-26-advanced-argumentation",
    "Debate skilfully: steelman, rebut precisely, concede strategically, stay composed.",
    ["debate", "motion", "steelman", "straw man", "concede a point", "turn the argument", "point of information", "closing statement"],
    ["refutation language patterns", "concession + counter pivots"],
    ["Debate both sides of one motion.", "Follow competitive-debate exchanges.", "Transcribe and critique rebuttals.", "Write a rebuttal paragraph under time pressure."],
    "Formal debate: argue against your actual belief credibly — the ultimate flexibility test.",
    "Strawmanning wins rounds and loses credibility; steelman before you strike.",
    [["Pre-A1", "I don't agree."], ["A2", "You make a fair point, but consider this instead."], ["B1", "Conceding the minor case strengthened our major claim."], ["B2", "Their strongest version of the argument still fails on scope."], ["C1", "The rebuttal mischaracterised the premise, attacking a position nobody held."]],

  ),
  t(129, "logical-fallacies", "Logical Fallacies", "thinking", "lesson-26-advanced-argumentation",
    "Spot reasoning traps: ad hominem, false dilemma, slippery slope, appeal to authority.",
    ["fallacy", "ad hominem", "false dilemma", "slippery slope", "appeal to authority", "correlation ≠ causation", "hasty generalisation", "red herring"],
    ["fallacy identification discourse", "precise diagnostic language"],
    ["Name the fallacy in prepared examples.", "Detect fallacies in live discussion.", "Label fallacies in an article.", "Write a fallacy-spotting guide."],
    "Fallacy bingo during a televised debate — then discuss which fallacies actually moved voters.",
    "Fallacy-naming can itself become a red herring — address the argument, not just its label.",
    [["Pre-A1", "That doesn't make sense."], ["A2", "Attacking the person instead of the argument is unfair."], ["B1", "'Either we ban this or society collapses' is a false dilemma."], ["B2", "Just because two trends correlate doesn't mean one causes the other."], ["C1", "Fallacy-spotting sharpens thinking only when it clarifies rather than dismisses."]],

  ),
  t(130, "negotiation-mastery", "Negotiation Mastery", "workplace", "lesson-26-advanced-argumentation",
    "Negotiate at expert level: interests vs positions, BATNA, trades, anchoring.",
    ["negotiate", "interests vs positions", "BATNA", "anchor", "trade-off", "win-win", "walk-away point", "concession pattern"],
    ["conditional bargaining language", "diplomatic hedging under pressure"],
    ["Run a full negotiation with trades not concessions.", "Follow high-stakes negotiation debriefs.", "Study one famous deal analysis.", "Write a negotiation prep sheet."],
    "Salary-plus-scope negotiation: expand the pie (training, remote days, review dates) before dividing it.",
    "Anchoring on positions invites stalemate; negotiating interests reveals trades neither side saw.",
    [["Pre-A1", "Can you give me a better price?"], ["A2", "If you can include delivery, we have a deal."], ["B1", "What matters most to me is predictability, not the headline number."], ["B2", "Our alternative is credible, so let's find value on terms other than price."], ["C1", "Skilled negotiators spend more time diagnosing interests than arguing offers."]],

  ),
  t(131, "academic-writing", "Academic Writing", "academic", "lesson-27-academic-professional-mastery",
    "Write academically: thesis, structure, citation logic, hedging, formal register.",
    ["thesis statement", "literature review", "cite / reference", "hedging language", "cohesion devices", "paraphrase", "abstract", "peer-reviewed"],
    ["nominalisation", "hedged claims (suggests, appears)"],
    ["Draft a thesis-driven paragraph with citations.", "Follow lecture signposting exactly.", "Evaluate an abstract's promises.", "Write a literature-review section."],
    "Journal submission simulation: respond to reviewer comments without capitulating or stonewalling.",
    "Hedging isn't weakness — unhedged certainty in academic prose signals amateur status.",
    [["Pre-A1", "My essay says..."], ["A2", "This paper examines how remote work changed collaboration."], ["B1", "The findings suggest, though do not prove, a causal pathway."], ["B2", "Synthesising across studies reveals a more qualified picture than any single trial."], ["C1", "The literature converges tentatively, pending better-powered replication."]],

  ),
  t(132, "presentations-public-speaking", "Presentations and Public Speaking", "professional", "lesson-27-academic-professional-mastery",
    "Present powerfully: narrative arc, slides discipline, delivery, Q&A control.",
    ["presentation outline", "key message", "signpost", "visual aid", "delivery / pacing", "engage the audience", "handle questions", "call-back"],
    ["presentation signposting phrases", "rhetorical emphasis structures"],
    ["Deliver a five-minute talk with clean structure.", "Follow conference keynotes analytically.", "Study one great transcript's techniques.", "Write speaker notes, not scripts."],
    "Conference presentation: deliver, get a hostile question, handle it without defensiveness.",
    "Slides are support, not teleprompter — text-dense decks split audience attention fatally.",
    [["Pre-A1", "Today I will talk about..."], ["A2", "First I'll cover background, then results."], ["B1", "To put those numbers in context, consider what happened last year."], ["B2", "Let me anticipate the obvious objection before someone raises it."], ["C1", "Great talks restructure how audiences see a problem, not just what they know."]],

  ),
  t(133, "technical-communication", "Technical Communication", "professional", "lesson-27-academic-professional-mastery",
    "Explain complexity clearly: docs, specs, instructions, audience calibration.",
    ["documentation", "specification", "step-by-step instructions", "plain-language summary", "prerequisite knowledge", "worked example", "troubleshooting", "version note"],
    ["imperative instruction forms", "precision vocabulary"],
    ["Document one process so a novice succeeds.", "Follow technical walkthrough audio.", "Test-read documentation for gaps.", "Write a README others can follow."],
    "Rubber-duck documentation: explain a system to an imaginary junior until steps stop hiding.",
    "Expert blind spot makes steps invisible — test instructions on someone who lacks context.",
    [["Pre-A1", "Press this button first."], ["A2", "Before installing, check you have enough storage space."], ["B1", "If step three fails, verify your permissions before retrying."], ["B2", "This guide assumes working knowledge of APIs; newcomers should read Appendix B."], ["C1", "Documentation quality predicts adoption more reliably than feature lists."]],

  ),
  t(134, "professional-networking", "Professional Networking", "professional", "lesson-27-academic-professional-mastery",
    "Network authentically: follow-up systems, reciprocity, weak ties, visibility.",
    ["networking", "reach out", "follow-up message", "mutual connection", "add value first", "weak ties", "visibility", "maintain relationships"],
    ["outreach message conventions", "warm-professional register"],
    ["Write a cold outreach that gets replies.", "Follow networking-conversation flow.", "Read successful outreach post-mortems.", "Write your relationship-maintenance cadence."],
    "Conference hallway practice: open three conversations, extract one follow-up each, send messages same-day.",
    "Networking fails when transactional — give value before asking, always have a reason to reconnect.",
    [["Pre-A1", "Hello, nice to meet you."], ["A2", "We met at the workshop — I really enjoyed your question."], ["B1", "I came across your work on supply chains and wanted to reach out directly."], ["B2", "No ask today — just thought this report might be useful for your team."], ["C1", "Careers compound through weak ties maintained long before they're needed."]],

  ),
  t(135, "meetings-chairs", "Chairing Meetings and Facilitation", "professional", "lesson-27-academic-professional-mastery",
    "Run excellent meetings: agendas, airtime balance, decisions, action capture.",
    ["chair / facilitate", "agenda item", "timebox", "summarise consensus", "parked item", "action items", "decision log", "round-robin"],
    ["facilitation management phrases", "summary and closure discourse"],
    ["Chair a meeting end-to-end including a difficult participant.", "Facilitate from listening comprehension of overlapping speech.", "Evaluate meeting minutes for completeness.", "Write minutes that drive action."],
    "Meeting-from-hell rescue: two dominators, one silent expert, fifteen minutes, one decision needed.",
    "Meetings without captured decisions are expensive conversations — write down who does what by when.",
    [["Pre-A1", "Let's start the meeting."], ["A2", "Thanks everyone — let's keep to the agenda times."], ["B1", "To summarise: we've agreed the timeline; Sam owns the budget check."], ["B2", "Let's park that and return if time allows — decision first."], ["C1", "Airtime asymmetry silently destroys meeting intelligence unless actively countered."]],
  ),
  t(136, "capstone-interview-mastery", "Capstone: Interview Mastery", "career", "lesson-28-real-world-mastery",
    "Integrate everything into interviews: stories, fit signals, questions, follow-through.",
    ["STAR story", "behavioural question", "culture fit", "strengths evidence", "compensation talk", "questions for them", "follow-up note", "offer evaluation"],
    ["narrative past for achievement stories", "confident yet hedged self-presentation"],
    ["Deliver three polished STAR stories on demand.", "Handle a rapid-fire mock interview.", "Decode a job ad's real requirements.", "Write post-interview reflection and follow-up."],
    "Final-round gauntlet: panel interview mixing behavioural, technical, curveball and reverse-question phases.",
    "Generic answers read as rehearsed; specificity about THIS role is the differentiator.",
    [["Pre-A1", "I want this job."], ["A2", "In my last role, I solved this exact problem — let me tell you how."], ["B1", "The project failed initially, which taught me to scope before committing."], ["B2", "What I'd bring specifically here is the bridge between design and data your ad mentions twice."], ["C1", "Interviews are mutual diagnosis, not performance — evaluate them as hard as they evaluate you."]],

  ),
  t(137, "cross-cultural-fluency", "Cross-Cultural Fluency", "global", "lesson-28-real-world-mastery",
    "Work across cultures: directness scales, context levels, repair strategies.",
    ["high-context / low-context", "direct vs indirect feedback", "hierarchy expectations", "face-saving", "cultural baseline", "misread signals", "adapt style", "repair misunderstanding"],
    ["diplomatic recalibration language", "contrastive cultural discourse"],
    ["Adapt one message for two cultures live.", "Diagnose a cross-cultural misfire.", "Compare business-communication guides.", "Write your own cultural-defaults map."],
    "Multinational video call: Japanese indirectness meets Dutch directness — broker understanding without stereotyping.",
    "Culture maps describe averages, not individuals — adapt to the person in front of you.",
    [["Pre-A1", "Different countries, different customs."], ["A2", "In some cultures saying 'no' directly sounds rude, so people say 'maybe'."], ["B1", "My German colleague heard my British hedge as uncertainty rather than politeness."], ["B2", "Silence reads as respect, disagreement or incompetence depending entirely where you are."], ["C1", "Cultural fluency is pattern literacy plus humility — frameworks fail gracefully or not at all."]],

  ),
  t(138, "crisis-communication", "Crisis Communication", "professional", "lesson-28-real-world-mastery",
    "Communicate under pressure: bad news delivery, transparency, holding statements.",
    ["crisis response", "holding statement", "stakeholder update", "take responsibility", "contain the damage", "transparent communication", "reputation management", "post-mortem communication"],
    ["calm-under-pressure register", "responsible-but-not-liable phrasing"],
    ["Deliver bad news with clarity and care.", "Follow crisis press conferences.", "Analyse good vs disastrous crisis statements.", "Draft a first-response statement."],
    "Product-failure crisis: draft the customer email, internal memo and public statement in twenty minutes.",
    "Speed beats polish early — silence breeds narrative vacuum others will fill.",
    [["Pre-A1", "There is a problem. We are fixing it."], ["A2", "We're aware of the outage and working on a fix now."], ["B1", "We take full responsibility for the error and will publish findings once known."], ["B2", "Here's what we know, what we don't, and when you'll hear from us next."], ["C1", "Crisis credibility is built before crises through candour habits, not during them."]],

  ),
  t(139, "influence-without-authority", "Influence Without Authority", "workplace", "lesson-28-real-world-mastery",
    "Move people you can't command: coalitions, framing, reciprocity, timing.",
    ["influence", "build a coalition", "frame the issue", "reciprocity", "social proof", "pick your moment", "make the ask", "champion"],
    ["indirect persuasion structures", "coalition-building discourse"],
    ["Plan an influence campaign for a real blocked goal.", "Follow organisational-politics case studies.", "Read influence literature critically.", "Write a stakeholder-by-stakeholder strategy."],
    "No-budget initiative pitch: get cross-department buy-in using allies, framing and patience.",
    "Influence attempts leak intent — genuine curiosity about others' interests persuades better than technique.",
    [["Pre-A1", "I need help from other teams."], ["A2", "I asked what mattered to them before proposing anything."], ["B1", "Getting the operations lead onboard early made the meeting almost unnecessary."], ["B2", "Reframed as their problem-solver rather than my agenda-pusher, doors opened."], ["C1", "Organisational change runs on informal networks org charts pretend don't exist."]],

  ),
  t(140, "complex-negotiation-disputes", "Complex Negotiations and Disputes", "argumentation", "lesson-28-real-world-mastery",
    "Resolve entrenched disputes: de-escalation, mediation stance, face-saving exits.",
    ["dispute resolution", "de-escalate", "mediation", "common ground", "face-saving exit", "escalation path", "settlement", "relationship preservation"],
    ["de-escalation language patterns", "formal settlement discourse"],
    ["Mediate a dispute between two parties.", "De-escalate one hostile exchange.", "Study a settled conflict's turning points.", "Write a settlement proposal preserving dignity."],
    "Neighbour/contractor dispute mediation: both sides lose face-win options unless you engineer them.",
    "Winning the argument while losing the relationship is expensive long-term — price it in.",
    [["Pre-A1", "Let's calm down and talk."], ["A2", "I understand why you're angry — let's find something fair for both of us."], ["B1", "Neither side needs to lose face for this to end well."], ["B2", "Escalation was the right threat only because we'd exhausted every softer path."], ["C1", "Durable settlements address the grievance beneath the position."]],

  ),
  t(141, "media-literacy-misinformation", "Media Literacy and Misinformation", "thinking", "lesson-28-real-world-mastery",
    "Resist manipulation: source triangulation, deepfakes, motivated reasoning, epistemic hygiene.",
    ["misinformation / disinformation", "verify sources", "lateral reading", "deepfake", "echo chamber", "prebunking", "manipulation technique", "epistemic hygiene"],
    ["source-evaluation discourse", "calibrated confidence language"],
    ["Fact-check one viral claim end-to-end.", "Detect manipulation techniques in clips.", "Trace one rumour's origin and spread.", "Write a verification checklist you'd actually use."],
    "Viral-claim investigation: trace sourcing laterally, identify emotional hook, rate verifiability honestly.",
    "Smart people spread misinformation too — intelligence doesn't immunise against motivated reasoning.",
    [["Pre-A1", "Is this news true?"], ["A2", "Check who first reported it before sharing anything."], ["B1", "The screenshot had no original source — classic manipulation signal."], ["B2", "Feeling certain isn't evidence; verify especially what confirms your views."], ["C1", "Epistemic security now requires active defence, not passive consumption."]],

  ),
  t(142, "digital-identity-brand", "Digital Identity and Personal Brand", "future", "lesson-28-real-world-mastery",
    "Manage digital presence: footprint, positioning, content strategy, privacy trade-offs.",
    ["digital footprint", "personal brand", "positioning", "thought leadership", "privacy settings", "online reputation", "content consistency", "audience"],
    ["self-positioning discourse", "public-facing register control"],
    ["Audit your searchable self and fix gaps.", "Analyse strong professional profiles.", "Compare personal-brand approaches.", "Write a bio that positions precisely."],
    "Reputation audit: search yourself as a hiring manager would, remediate what surfaces.",
    "Brands built on projection crack; brands built on demonstrated work compound quietly.",
    [["Pre-A1", "Be careful what you post online."], ["A2", "My profile clearly says what I do and who I help."], ["B1", "Consistent sharing about my field brought opportunities I never applied for."], ["B2", "Privacy and visibility trade off differently at every career stage."], ["C1", "Your brand is the residue of behaviour observed over time, not the bio you write."]],

  ),
  t(143, "financial-independence-planning", "Financial Independence and Life Planning", "money", "lesson-28-real-world-mastery",
    "Plan decades ahead: FI math, lifestyle design, risk horizons, optionality purchases.",
    ["financial independence", "passive income", "runway", "lifestyle inflation", "risk horizon", "diversification", "savings rate", "optionality"],
    ["long-horizon conditionals", "planning and projection language"],
    ["Model your own independence number roughly.", "Follow financial-plan critiques.", "Compare FI-path case studies.", "Write a ten-year financial outline."],
    "Life-design session: cost your ideal ordinary Tuesday — that number drives every big decision.",
    "FI planning fails when it optimises money while ignoring what the money is FOR.",
    [["Pre-A1", "I'm saving for the future."], ["A2", "Spending rises to match income unless you decide otherwise."], ["B1", "Twenty-five times annual expenses is the rough independence threshold people cite."], ["B2", "Every purchase is also a decision about future freedom."], ["C1", "Financial planning is really values clarification with spreadsheets attached."]],

  ),
  t(144, "health-longevity-habits", "Health and Longevity", "health", "lesson-28-real-world-mastery",
    "Sustain health across life: sleep, movement, nutrition basics, screening, stress physiology.",
    ["longevity", "sleep quality", "sedentary", "processed food", "screening check-up", "chronic condition prevention", "mobility", "consistency over intensity"],
    ["health-advice modality calibration", "cause-correlation caution"],
    ["Design one sustainable health upgrade.", "Evaluate health claims sceptically.", "Compare longevity research headlines.", "Write a realistic weekly health protocol."],
    "Lifestyle prescription: build a protocol surviving travel, deadlines and motivation crashes.",
    "Health optimisation culture overshoots marginal gains while skipping boring fundamentals.",
    [["Pre-A1", "Sleep and walking are good for you."], ["A2", "I stopped eating late and my sleep improved immediately."], ["B1", "Small consistent habits beat dramatic short-lived regimes every time."], ["B2", "Most longevity benefits come from not doing obvious harms consistently."], ["C1", "Health advice cycles through fashions while the boring consensus holds."]],

  ),
  t(145, "teaching-mentoring-others", "Teaching and Mentoring Others", "education", "lesson-28-real-world-mastery",
    "Transfer knowledge: explain simply, scaffold, give growth-oriented feedback.",
    ["mentor / mentoring", "explain simply", "scaffold learning", "constructive feedback", "ask guiding questions", "model a task", "psychological safety", "delegate with support"],
    ["explanatory simplification", "feedback framing language"],
    ["Teach one skill to a beginner successfully.", "Follow mentoring-conversation models.", "Compare teaching frameworks.", "Write a mentee development plan."],
    "Mentoring simulation: diagnose why a junior is stuck, then unstick without doing it for them.",
    "Explaining clearly requires forgetting what's obvious — expertise actively obstructs teaching.",
    [["Pre-A1", "I can show you."], ["A2", "Let me demonstrate first, then you try with me watching."], ["B1", "Good questions helped her find the answer she already half-knew."], ["B2", "Feedback lands when it targets the work, protects the person."], ["C1", "Teaching reveals the gaps in your own mastery faster than any test."]],

  ),
  t(146, "adaptability-uncertainty", "Adaptability and Uncertainty", "thinking", "lesson-28-real-world-mastery",
    "Thrive amid ambiguity: scenario thinking, reversible decisions, identity flexibility.",
    ["uncertainty", "scenario planning", "reversible decision", "pivot", "ambiguity tolerance", "optionality", "resilience", "learn fast, adjust faster"],
    ["probabilistic language", "decision-under-ignorance discourse"],
    ["Apply reversibility test to one stuck decision.", "Follow founders discussing pivots.", "Read scenario-planning cases.", "Write contingencies for your biggest current risk."],
    "Ambiguity drill: plan with three critical facts missing — decide anyway, define tripwires.",
    "Waiting for certainty is itself a decision — usually the most expensive one.",
    [["Pre-A1", "Things change. That's OK."], ["A2", "If this doesn't work, I'll try the other option next month."], ["B1", "Reversible decisions deserve speed; irreversible ones deserve delay."], ["B2", "Rigid plans break on contact with reality; flexible intentions bend usefully."], ["C1", "Comfort with ambiguity increasingly separates those who move from those who wait."]],

  ),
  t(147, "ethics-professional-integrity", "Professional Integrity Under Pressure", "philosophy", "lesson-28-real-world-mastery",
    "Hold ethical lines: pressure analysis, escalation, exit calculus, whistle-blowing reality.",
    ["integrity under pressure", "ethical line", "raise concerns", "whistle-blowing", "compliance vs ethics", "cover-up dynamics", "exit options", "document everything"],
    ["assertive refusal structures", "protective documentation language"],
    ["Rehearse refusing an unethical request.", "Assess an escalating-pressure scenario.", "Study a real integrity failure case.", "Write your personal red lines in advance."],
    "Pressure spiral: small compromise requested, then larger — practise the early no that prevents late disasters.",
    "Ethical failures start tiny — deciding boundaries beforehand beats improvising under pressure.",
    [["Pre-A1", "That is wrong. I won't do it."], ["A2", "I'm not comfortable signing this without checking the numbers."], ["B1", "Putting my concerns in writing protected everyone, including me."], ["B2", "Normalisation begins with exceptions nobody challenges."], ["C1", "Integrity costs exactly what you didn't plan to pay — so plan."]],

  ),
  t(148, "legacy-contribution", "Legacy and Contribution", "philosophy", "lesson-28-real-world-mastery",
    "Think beyond self: mentorship chains, knowledge transfer, community building, mortality salience.",
    ["legacy", "contribution", "give back", "knowledge transfer", "succession", "community builder", "generativity", "memento mori"],
    ["reflective legacy discourse", "long-view temporal language"],
    ["Articulate the contribution you want to make.", "Discuss legacy across cultures respectfully.", "Read end-of-life reflection essays.", "Write the obituary you'd want, work backwards."],
    "Legacy mapping: name whose growth you've caused, then design the next decade's contribution.",
    "Legacy anxiety can paralyse present contribution — most legacies are accumulated small acts.",
    [["Pre-A1", "I want to help people after me."], ["A2", "Teaching others what I know feels like the point of learning it."], ["B1", "My best manager's influence still shapes how I lead today."], ["B2", "Succession planning is legacy thinking applied before it's urgent."], ["C1", "Generativity — investing in those who outlast you — organises a meaningful second half of life."]],

  ),
  t(149, "lifelong-learning-system", "Lifelong Learning System", "education", "lesson-28-real-world-mastery",
    "Build a permanent learning system: curriculum design for self, spaced practice, transfer.",
    ["lifelong learning", "self-directed learning", "spaced repetition", "deliberate practice", "learning portfolio", "transfer skills", "meta-learning", "curiosity-driven"],
    ["learning-process description", "self-assessment discourse"],
    ["Design your next-year learning curriculum.", "Diagnose a stalled learning effort.", "Compare self-taught experts' methods.", "Write your personal syllabus."],
    "Meta-learning audit: what did you learn last year, what systems produced it, what will compound next?",
    "Consuming content ≠ learning — retrieval, spacing and application do the actual work.",
    [["Pre-A1", "I love learning new things."], ["A2", "I review new words after one day, one week, then one month."], ["B1", "Projects taught me more than courses ever did — forcing application matters."], ["B2", "Learning how to learn compounds faster than any individual subject."], ["C1", "Sustained learners treat curiosity as infrastructure, maintained deliberately like fitness."]],

  ),
  t(150, "english-as-life-tool", "English as a Life Tool", "personal", "lesson-28-real-world-mastery",
    "Consolidate identity as English user: maintenance systems, register switching, community, ownership.",
    ["maintain fluency", "code-switch registers", "immersion habits", "language community", "think in English", "own your accent", "use it or lose it", "English for specific purposes"],
    ["metalinguistic reflection", "register-flexible production"],
    ["Switch registers smoothly within one conversation.", "Sustain ten minutes of spontaneous speech on any topic.", "Consume native media extracting value independently.", "Write a letter to your future English-speaking self."],
    "Full-circle capstone: handle one day simulated entirely in English — morning to night, every domain, no fallback.",
    "Perfectionism is the final plateau — fluent users prioritise connection over error-free performance.",
    [["Pre-A1", "English helps me connect."], ["A2", "I watch shows in English now without subtitles catching every word perfectly."], ["B1", "My accent is mine — people understand me and that's the metric."], ["B2", "Thinking directly in English removed translation lag and opened fluency."], ["C1", "Language mastery ends where it began: not in grammar books but in lives actually lived through it."]],
  ),
];
