/** 150-topic master library, part 4 of 6 (topics 76–100 · Lessons 16–20): culture, business, professional skills, decisions, technology. */
import type { Topic150 } from "./topics150-a";

const t = (
  n: number, id: string, title: string, category: string, lessonId: string, purpose: string,
  vocab: string[], grammar: string[],
  skills: [string, string, string, string],
  scenario: string, pitfall: string,
  ladder: Array<[string, string]>,
): Topic150 => ({
  n, id, title, category, lessonId, purpose,
  vocab, grammar,
  skills: { speaking: skills[0], listening: skills[1], reading: skills[2], writing: skills[3] },
  scenario, pitfall,
  ladder: ladder.map(([level, example]) => ({ level, example })),
});

export const TOPICS_150_D: Topic150[] = [
  t(76, "traditions-customs", "Traditions and Customs", "culture", "lesson-16-society-culture",
    "Explain traditions from your culture and ask about others' respectfully.",
    ["tradition / custom", "pass down", "generation", "ritual", "celebrate", "It's traditional to...", "heritage", "symbolise"],
    ["passive voice for origins (it is celebrated...)", "relative clauses for explaining customs"],
    ["Explain one tradition so an outsider truly gets it.", "Follow a documentary-style explanation.", "Read about another culture's custom.", "Write your tradition in outsider-friendly terms."],
    "International evening at work: explain one custom from home without clichés.",
    "Avoid 'we always do' — traditions vary within cultures too.",
    [["Pre-A1", "We eat together on Eid."], ["A2", "This dish is traditionally served at weddings."], ["B1", "The tradition has been passed down for four generations now."], ["B2", "Traditions persist partly because they encode practical wisdom."], ["C1", "Customs are answers to questions their originators no longer remember asking."]],
  ),
  t(77, "festivals-around-world", "Festivals and Celebrations Around the World", "culture", "lesson-16-society-culture",
    "Describe world festivals and compare celebration styles.",
    ["festival / carnival", "parade / fireworks", "public holiday", "religious significance", "costume", "street food", "procession", "attract millions"],
    ["present simple for recurring festivals", "numbers and scale language"],
    ["Present one world festival to the class.", "Follow a festival-experience anecdote.", "Read a festival travel guide.", "Write an invitation-style description of your festival."],
    "Travel podcast asks you to sell your hometown's biggest festival in sixty seconds.",
    "Festival names capitalise: Ramadan, Carnival, Diwali.",
    [["Pre-A1", "I like fireworks."], ["A2", "During Carnival, the whole city stops working."], ["B1", "What strikes visitors most is how family-centred everything remains."], ["B2", "Globalised festivals risk becoming backdrops for photos rather than rituals."], ["C1", "Festivals function as social pressure valves societies schedule deliberately."]],

  ),
  t(78, "food-culture", "Food Culture", "culture", "lesson-16-society-culture",
    "Discuss food identity: cuisine, hospitality norms, food as belonging.",
    ["cuisine", "hospitality", "signature dish", "street food culture", "family recipe", "dietary norm", "food heritage", "share a meal"],
    ["used to for food memory", "emphasis structures (what matters is...)"],
    ["Defend why one dish represents your culture.", "Follow chefs debating authenticity.", "Read a restaurant review of a diaspora kitchen.", "Write the story behind a family recipe."],
    "Potluck day: bring a dish and tell its story — who cooked it, when it's eaten, why it matters.",
    "Food talk is identity talk — criticism of cuisine lands as criticism of people.",
    [["Pre-A1", "This food is from my country."], ["A2", "Guests are never allowed to leave hungry — that's the rule."], ["B1", "Every family guards its version of this recipe like a state secret."], ["B2", "Migration rewrote national cuisines while everyone argued about authenticity."], ["C1", "Food is the last cultural artifact migrants keep when everything else assimilates."]],

  ),
  t(79, "cultural-identity", "Cultural Identity", "society", "lesson-16-society-culture",
    "Explore identity: belonging, hybridity, language and self-definition.",
    ["identity", "roots / background", "dual nationality", "belong (to)", "assimilate", "second-generation", "hybrid", "define yourself"],
    ["complex relative clauses", "reflexives (identify as)"],
    ["Articulate what culturally defines you.", "Follow hyphenated-identity interviews.", "Read a personal essay on belonging.", "Write your identity paragraph without clichés."],
    "Second-generation panel: where are you 'really' from? Answer with nuance, not defensiveness.",
    "'Where are you really from?' can be curiosity or microaggression — tone and context decide.",
    [["Pre-A1", "I am Egyptian."], ["A2", "My parents came here, but I grew up between two worlds."], ["B1", "I feel most myself switching between languages mid-sentence."], ["B2", "Identity stopped being a box the moment I stopped needing one."], ["C1", "Belonging is less about geography than about being understood unasked."]],

  ),
  t(80, "multicultural-society", "Living in a Multicultural Society", "society", "lesson-16-society-culture",
    "Navigate diversity: inclusion, friction, integration debates, daily reality.",
    ["diverse / diversity", "integrate", "community", "discrimination", "mutual respect", "common ground", "enrich", "coexist"],
    ["abstract argument structures", "concession clauses (while/although)"],
    ["Argue both benefits and frictions of multicultural cities.", "Follow a nuanced panel disagreement.", "Compare two op-eds on integration.", "Write a balanced view with one clear position."],
    "Neighbourhood meeting about a new community centre: voices conflict; find common ground.",
    "Balanced writing still needs a conclusion — weighing isn't dodging.",
    [["Pre-A1", "Many people live here."], ["A2", "Our street has families from ten different countries."], ["B1", "Integration works both ways, though nobody budgets patience for that."], ["B2", "Diversity generates friction precisely because it generates value."], ["C1", "Successful multiculturalism is infrastructure policy wearing a values badge."]],

  ),
  t(81, "businesses-companies", "Businesses and Companies", "business", "lesson-17-business-economy",
    "Understand company basics: types, departments, structure, lifecycle.",
    ["company / startup", "department", "headquarters", "founder / CEO", "revenue", "scale up", "market share", "go under"],
    ["business present tenses", "passive descriptions of process"],
    ["Describe a company you know end-to-end.", "Follow a company-history pitch.", "Read an About Us page critically.", "Write a two-line company summary."],
    "Investor coffee: explain a small company's model clearly enough to interest a stranger.",
    "'Turnover' (UK) = revenue (US); 'going under' means bankruptcy, not diving.",
    [["Pre-A1", "This is a big company."], ["A2", "She founded the company in her garage in 2019."], ["B1", "Revenue tripled after they shifted to subscriptions."], ["B2", "Startups die from distribution problems more often than product flaws."], ["C1", "Company culture ossifies the moment it gets written down."]],

  ),
  t(82, "customers-customer-service", "Customers and Customer Service", "workplace", "lesson-17-business-economy",
    "Deliver and receive service: complaints, refunds, de-escalation, loyalty.",
    ["refund / exchange", "warranty", "loyal customer", "complaint", "escalate", "on hold", "goodwill gesture", "retention"],
    ["polite complaint frames", "future forms for resolutions"],
    ["Resolve an angry customer scenario calmly.", "Handle a fast-talking complainer by phone.", "Read a returns policy for loopholes.", "Write a service-recovery email."],
    "Front line: customer wants a refund outside policy — find the yes without breaking rules.",
    "Service recovery paradox: well-fixed problems create MORE loyalty than none occurring.",
    [["Pre-A1", "I want my money back."], ["A2", "The product stopped working after a week. What can you do?"], ["B1", "I understand it's outside policy, but surely we can find a middle ground."], ["B2", "Retention costs a fraction of acquisition — yet budgets say otherwise."], ["C1", "Complaints are free consulting if organisations can stomach hearing them."]],

  ),
  t(83, "sales-marketing", "Sales and Marketing", "business", "lesson-17-business-economy",
    "Grasp selling: features vs benefits, funnels, persuasion ethics.",
    ["sell / pitch", "target audience", "benefits vs features", "discount / offer", "conversion", "brand loyalty", "upsell", "call to action"],
    ["persuasion conditionals", "comparative advantage language"],
    ["Pitch a product in 45 seconds honestly.", "Decode a salesperson's techniques live.", "Analyse one advert's persuasion stack.", "Write product copy without clichés."],
    "Market stall economics: sell one item to three different customer types authentically.",
    "Features describe products; benefits describe customers' lives. Sell the second.",
    [["Pre-A1", "Buy two, get one free!"], ["A2", "This model saves you money long-term because it lasts longer."], ["B1", "Our conversion doubled once we simplified the checkout flow."], ["B2", "Discounting trains customers to wait for discounts."], ["C1", "Marketing increasingly manufactures the anxiety it then sells relief from."]],

  ),
  t(84, "business-meetings", "Business Meetings", "workplace", "lesson-17-business-economy",
    "Run and survive meetings: agendas, interruptions, action points, follow-ups.",
    ["agenda / minutes", "action point", "table it", "circle back", "to summarise", "does anyone object?", "time-box", "follow up by email"],
    ["meeting modality: shall we / could we", "reported speech for minutes"],
    ["Chair a five-minute meeting to decision.", "Track actions through overlapping speakers.", "Read minutes and extract your tasks.", "Write crisp minutes with owners and dates."],
    "Standing meeting turned rambling: take the chair, timebox, force one decision before close.",
    "Meetings without written actions didn't happen — capture owner + date or lose the outcome.",
    [["Pre-A1", "Meeting starts now."], ["A2", "Let's look at the agenda — first item is the budget."], ["B1", "Can we table that and come back once legal have reviewed?"], ["B2", "To summarise: pricing holds, launch moves to May, Sara owns comms."], ["C1", "Meeting proliferation is usually decision avoidance wearing calendar invites."]],

  ),
  t(85, "basic-economics", "Basic Economics", "finance", "lesson-17-business-economy",
    "Understand economic literacy: inflation, supply/demand, rates in daily life.",
    ["inflation", "interest rate", "supply and demand", "recession", "purchasing power", "wage growth", "GDP (basic)", "cost of living"],
    ["causal language (leads to, results in)", "trend verbs (rise, fall, stabilise)"],
    ["Explain one economic force affecting your life.", "Follow news analysis on interest rates.", "Read a simple economic explainer.", "Write how inflation hit your budget specifically."],
    "Family group chat argues about prices: inject actual mechanism into the debate.",
    "Correlation ≠ causation — ice cream doesn't cause drowning.",
    [["Pre-A1", "Prices go up."], ["A2", "Everything costs more than last year, but my salary didn't move."], ["B1", "Rate rises cool spending by making borrowing expensive — by design."], ["B2", "Inflation quietly redistributes from savers to borrowers."], ["C1", "Economic literacy is civic self-defence in policy debates."]],

  ),
  t(86, "professional-emails", "Professional Emails", "workplace", "lesson-18-professional-communication",
    "Master workplace email register: requests, refusals, updates, apologies.",
    ["I'm reaching out regarding...", "as per", "at your earliest convenience", "apologies for", "could you clarify", "kind regards", "action required", "follow-up"],
    ["hedged requests (would it be possible...)", "formal negative structures (regrettably)"],
    ["Rewrite a blunt email into professional register.", "Extract deadlines buried in prose.", "Compare formal vs direct styles appropriately.", "Write an apology email that fixes trust."],
    "Client email landed angry and vague: reply de-escalating while protecting scope.",
    "Emails read colder than intended — add warmth deliberately, edit ruthlessly.",
    [["Pre-A1", "Dear Sir,"], ["A2", "Just following up on my previous email below."], ["B1", "Apologies for chasing — could you confirm whether Friday still works?"], ["B2", "Regrettably, this falls outside current scope; happy to discuss alternatives."], ["C1", "Executive email is compression engineering: maximum signal, minimum offence."]],

  ),
  t(87, "presentations", "Presentations", "workplace", "lesson-18-professional-communication",
    "Structure and deliver presentations: openings, signposting, handling questions.",
    ["outline / agenda slide", "signpost (Moving on...)", "key takeaway", "demo", "Q&A", "handout", "rehearse", "visual aid"],
    ["signposting discourse markers", "rhetorical questions"],
    ["Deliver a 90-second structured mini-presentation.", "Follow a talk and note its structure.", "Identify weak presentation abstracts.", "Write speaker notes for three slides."],
    "Five slides, five minutes, real audience: pitch quarterly results without reading slides.",
    "Slides are visual aids, not teleprompters — never read them verbatim.",
    [["Pre-A1", "Today I talk about sales."], ["A2", "First I'll cover the background, then our three recommendations."], ["B1", "Moving on to the risks — and there are three worth flagging."], ["B2", "If you remember one number from today, make it forty percent."], ["C1", "Great presenting is editing performed live."]],

  ),
  t(88, "negotiation", "Negotiation", "workplace", "lesson-18-professional-communication",
    "Negotiate outcomes: interests vs positions, trades, walk-away points.",
    ["negotiate / deal", "compromise", "bottom line", "win-win", "concession", "That doesn't work for us", "meet halfway", "terms"],
    ["conditionals for trades (if you..., we can...)", "diplomatic refusal forms"],
    ["Negotiate a realistic trade to mutual gain.", "Track counterpart's real interests beneath positions.", "Read contract clauses for traps.", "Write your walk-away point plus rationale."],
    "Supplier renewal at +30%: negotiate using volume commitments against rate stability.",
    "Never negotiate against yourself — counter, don't bid up unprompted.",
    [["Pre-A1", "Lower price, please."], ["A2", "If I buy three, can you do a better price?"], ["B1", "We could meet halfway on delivery dates if you hold the rate."], ["B2", "Positions harden; interests stay flexible — negotiate the second."], ["C1", "The best deals leave both sides slightly uncomfortable and fully committed."]],

  ),
  t(89, "persuasion", "Persuasion", "thinking", "lesson-18-professional-communication",
    "Persuade ethically: evidence, framing, credibility, emotional resonance.",
    ["convince / persuade", "evidence", "frame", "credibility", "appeal to", "trade-off", "counterargument", "land the point"],
    ["persuasive structures (not only... but also)", "concessive argumentation"],
    ["Persuade someone to change a concrete behaviour.", "Spot manipulation vs legitimate persuasion.", "Analyse persuasive techniques in an article.", "Write a one-paragraph persuasive case."],
    "Convince your landlord to allow a cat: anticipate objections, offer safeguards, close.",
    "Ethical persuasion survives scrutiny; manipulation dies under one clarifying question.",
    [["Pre-A1", "Please! It's good!"], ["A2", "Studies show employees with flexible hours perform better."], ["B1", "You raise a fair concern about mess — here's how we'd manage it."], ["B2", "Frame it as risk reduction rather than benefit addition for this audience."], ["C1", "Persuasion is alignment engineering, not verbal force."]],

  ),
  t(90, "conflict-resolution-workplace", "Workplace Conflict Resolution", "workplace", "lesson-18-professional-communication",
    "Resolve professional conflicts: mediation, documentation, escalation paths.",
    ["mediation", "grievance", "de-escalate", "common ground", "document / log", "HR involvement", "burning bridge", "professional boundary"],
    ["past modals for blame-free review (should have flagged earlier)", "neutral report language"],
    ["Mediate a dispute between two colleagues fairly.", "Follow an HR-mediated conversation.", "Read a grievance procedure.", "Write a neutral incident summary."],
    "Two team members, one credit dispute: mediate toward documented agreement.",
    "Document contemporaneously — memory rewrites itself to flatter the author.",
    [["Pre-A1", "They argue every day."], ["A2", "Can we talk about what happened yesterday? I don't want tension."], ["B1", "Let's focus on the workflow issue rather than who said what."], ["B2", "Unresolved low-grade conflict taxes teams more than open disputes."], ["C1", "Escalation exists to protect fairness, not to punish honesty."]],

  ),
  t(91, "everyday-problems", "Everyday Problems", "daily", "lesson-19-problem-solving-decisions",
    "Solve daily-life failures: leaks, breakdowns, admin errors, lost items.",
    ["break down / stop working", "deal with", "get it fixed", "customer support", "workaround", "temporary solution", "make do", "sort out"],
    ["problem-narrative past tenses", "sequencing solutions"],
    ["Narrate a problem and its fix concisely.", "Follow troubleshooting instructions by phone.", "Scan FAQ pages for your exact case.", "Write a problem report others can act on."],
    "Washing machine flooding at 11 p.m.: triage, contain, contact, document.",
    "Report problems with symptoms first, theories second — helps helpers help.",
    [["Pre-A1", "It doesn't work."], ["A2", "The internet keeps cutting out — I've tried restarting twice."], ["B1", "Long story short, we contained the leak, then called emergency plumbing."], ["B2", "Most household crises reward the boring checklist over improvisation."], ["C1", "Daily resilience is systems design applied to ordinary chaos."]],

  ),
  t(92, "difficult-decisions", "Making Difficult Decisions", "thinking", "lesson-19-problem-solving-decisions",
    "Decide well under uncertainty: criteria, reversibility, regret minimisation.",
    ["weigh up", "pros and cons", "reversible", "risk", "gut feeling", "sleep on it", "commit to", "second-guess"],
    ["decision frameworks language", "mixed conditionals for reflection"],
    ["Talk through a real decision using explicit criteria.", "Follow a coaching conversation on choice.", "Read decision-framework summaries.", "Write a decision memo: options, criteria, call."],
    "Two job offers, one week: build the comparison framework live and commit aloud.",
    "Reversibility beats optimisation — prefer choices you can undo cheaply.",
    [["Pre-A1", "Hard choice."], ["A2", "I weighed the pros and cons, but I'm still torn."], ["B1", "If I take the London offer, reversing later gets expensive."], ["B2", "Most decisions matter less than how quickly you commit afterwards."], ["C1", "Decision quality separates process from outcome — luck contaminates both."]],

  ),
  t(93, "comparing-options", "Comparing Options", "thinking", "lesson-19-problem-solving-decisions",
    "Compare systematically: criteria tables, weighted trade-offs, honest verdicts.",
    ["compare / contrast", "criteria", "advantage / drawback", "whereas", "on balance", "better value", "trade-off", "deal-breaker"],
    ["comparative and superlative precision", "whereas/while contrasts"],
    ["Compare three options on named criteria aloud.", "Follow a structured product comparison.", "Read comparison tables critically.", "Write a comparison verdict with reasoning."],
    "Flat-hunting matrix: rent vs commute vs light vs neighbours — score and defend.",
    "Comparisons need explicit criteria; otherwise they're vibes with adjectives.",
    [["Pre-A1", "This one is better."], ["A2", "The blue one costs less, whereas the black lasts longer."], ["B1", "On balance, the extra commute outweighs the cheaper rent."], ["B2", "Comparison shopping collapses once you name your deal-breakers honestly."], ["C1", "Options multiply faster than criteria — selection discipline is the skill."]],

  ),
  t(94, "risk-consequences", "Risk and Consequences", "thinking", "lesson-19-problem-solving-decisions",
    "Assess risk: likelihood, impact, mitigation and honest uncertainty.",
    ["risk / risky", "likelihood", "worst-case scenario", "mitigate", "insurance", "downside", "play it safe", "exposure"],
    ["probability language (likely, unlikely, bound to)", "conditional chains"],
    ["Break one personal risk into likelihood × impact.", "Follow an insurance-explainer conversation.", "Read risk disclosures for plain meaning.", "Write a mini risk assessment for a plan."],
    "Freelance leap planning: income volatility, safety net, exit ramp — quantify all three.",
    "Risk ≠ danger: risk is measurable exposure; danger ignores probability.",
    [["Pre-A1", "Is it safe?"], ["A2", "There's a small chance of delays, but the downside is manageable."], ["B1", "Worst case, I burn savings for three months and return employed."], ["B2", "People systematically overrate dramatic risks and underrate chronic ones."], ["C1", "Risk management is mostly about surviving variance, not predicting it."]],

  ),
  t(95, "problem-solving-strategies", "Problem-Solving Strategies", "thinking", "lesson-19-problem-solving-decisions",
    "Apply frameworks: define, decompose, generate options, test, iterate.",
    ["define the problem", "root cause", "brainstorm", "trial and error", "iterate", "constraint", "hypothesis", "evaluate options"],
    ["purpose clauses (so that / in order to)", "process sequencing"],
    ["Solve an unfamiliar problem using a named framework.", "Follow a strategy consultant's thinking aloud.", "Read a case-study solution section.", "Write your five-step plan for a stuck problem."],
    "Team stuck on falling retention: run a root-cause session to hypotheses worth testing.",
    "Solutions premised before problems get defined solve elegant wrong things.",
    [["Pre-A1", "Let's try again."], ["A2", "First we need to understand why users leave."], ["B1", "Breaking it into smaller questions made it suddenly solvable."], ["B2", "Fast iteration beats perfect planning whenever feedback loops are short."], ["C1", "Problem definition is half the solution; most effort skips it."]],

  ),
  t(96, "artificial-intelligence", "Artificial Intelligence", "technology", "lesson-20-technology-digital-future",
    "Use and question AI tools: capabilities, limits, prompting, verification.",
    ["AI / chatbot", "prompt", "hallucinate (AI)", "automate", "training data", "generate", "verify outputs", "machine learning"],
    ["capability comparisons", "speculation about futures"],
    ["Demonstrate one AI task done well and verified.", "Follow an AI-capability discussion.", "Read an AI tool's limitations doc.", "Write a prompt that actually works."],
    "AI drafted your report — verify claims, fix hallucinated citations, own the result.",
    "AI output sounds confident regardless of accuracy — verification stays human work.",
    [["Pre-A1", "Computers can talk now!"], ["A2", "I use AI to draft emails, but I check everything it says."], ["B1", "It's impressive until you catch it inventing sources confidently."], ["B2", "Prompt quality sets the ceiling on output quality — garbage prompts, garbage out."], ["C1", "AI shifts premium value toward judgment precisely because generation got cheap."]],

  ),
  t(97, "automation-jobs", "Automation and Jobs", "workplace", "lesson-20-technology-digital-future",
    "Debate automation: displacement, new roles, transition pain, reskilling.",
    ["automation", "displacement", "reskill / retrain", "entry-level roles", "productivity gains", "universal basic income (UBI)", "transition", "obsolescence"],
    ["future forms for prediction ranges", "argument concession structures"],
    ["Argue a position on automation with evidence.", "Follow an economist-layperson dialogue.", "Compare two automation studies' claims.", "Write a balanced brief on one industry's future."],
    "Your sector automates 40% of tasks: map which parts of YOUR role survive and why.",
    "Automation history rhymes: tasks automate, jobs transform, transitions hurt unevenly.",
    [["Pre-A1", "Robots do some jobs now."], ["A2", "Machines replaced many factory jobs, but created others."], ["B1", "The transition hurts specific people even when statistics improve overall."], ["B2", "Predictions keep missing that augmentation, not replacement, dominates near-term."], ["C1", "Automation debates are distribution debates wearing technology costumes."]],

  ),
  t(98, "cybersecurity-online-safety", "Cybersecurity and Online Safety", "technology", "lesson-20-technology-digital-future",
    "Stay safe online: passwords, phishing, scams, two-factor habits.",
    ["phishing", "scam", "two-factor authentication", "data breach", "suspicious link", "password manager", "verify the sender", "malware"],
    ["warning imperatives", "modality of suspicion (could/might be fake)"],
    ["Spot three red flags in a suspicious message.", "Follow security-training scenarios.", "Read a breach notification properly.", "Write scam-report steps for a relative."],
    "Urgent email from 'your bank': identify the phish, verify independently, report it.",
    "Urgency + authority + unusual payment = classic scam triangle. Slow down deliberately.",
    [["Pre-A1", "Don't click strange links!"], ["A2", "The email looked real, but the address was slightly wrong."], ["B1", "Enable two-factor before you become the cautionary tale."], ["B2", "Humans remain the exploit of choice — technical walls, social doors."], ["C1", "Security UX fails users by designing for compliance rather than comprehension."]],

  ),
  t(99, "digital-privacy", "Digital Privacy", "technology", "lesson-20-technology-digital-future",
    "Control your data: permissions, tracking, consent, data rights.",
    ["personal data", "track / tracking", "consent", "opt out", "privacy policy", "data broker", "incognito mode", "right to deletion"],
    ["permission language for data", "passive voice for data flows (data is collected)"],
    ["Audit and reduce one app's data access.", "Follow privacy-settings walkthroughs.", "Skim a privacy policy for key rights.", "Write a data-deletion request."],
    "New app demands contacts, location and microphone: decide what's justified, configure rest off.",
    "'Accept all cookies' trains consent reflexes that extend far beyond cookies.",
    [["Pre-A1", "Apps collect information."], ["A2", "Why does a torch app need my location?"], ["B1", "I opted out of targeted ads, though enforcement feels theatrical."], ["B2", "Privacy policies exist legally, not functionally — nobody reads 8,000 words per app."], ["C1", "Privacy eroded through convenience trades each individually defensible."]],

  ),
  t(100, "future-of-technology", "The Future of Technology", "future", "lesson-20-technology-digital-future",
    "Speculate responsibly: emerging tech, timelines, hype cycles, preparedness.",
    ["emerging technology", "hype cycle", "breakthrough", "mainstream adoption", "regulate", "science fiction becomes science", "disrupt", "roadmap"],
    ["future perfect and future continuous", "measured speculation language"],
    ["Make calibrated predictions with explicit uncertainty.", "Follow a futurist interview sceptically.", "Compare prediction articles across years.", "Write one prediction with confidence level stated."],
    "2035 scenario workshop: pick one tech shift, defend timeline AND confidence level.",
    "Prediction credibility requires stating failure conditions, not just visions.",
    [["Pre-A1", "Future cars will fly!"], ["A2", "Self-driving taxis already operate in some cities."], ["B1", "Adoption always takes longer than demos suggest, then arrives suddenly."], ["B2", "Hype cycles obscure genuine signals underneath funding noise."], ["C1", "Forecasting credibility belongs to those publishing their error bars."]],
  ),
];
