/** 150-topic master library, part 1 of 6 (topics 1–25 · Lessons 1–5): identity, home, food, places, health. */

export interface TopicSkillSet { speaking: string; listening: string; reading: string; writing: string }

export interface Topic150 {
  n: number;
  id: string;
  title: string;
  category: string;
  lessonId: string;
  purpose: string;
  vocab: string[];
  grammar: string[];
  skills: TopicSkillSet;
  scenario: string;
  pitfall: string;
  ladder: Array<{ level: string; example: string }>;
}

const t = (
  n: number, id: string, title: string, category: string, lessonId: string, purpose: string,
  vocab: string[], grammar: string[],
  skills: [string, string, string, string],
  scenario: string, pitfall: string,
  ladder: Array<[string, string]>,
): Topic150 => ({
  n, id, title, category, lessonId, purpose,
  vocab, grammar,
  skills: { speaking: skills[0], listening: skills[1], reading: skills[2], writing: skills[3] },
  scenario, pitfall,
  ladder: ladder.map(([level, example]) => ({ level, example })),
});

export const TOPICS_150_A: Topic150[] = [
  t(1, "greetings-introductions", "Greetings and Introductions", "social", "lesson-01-me-my-world",
    "Open any interaction confidently with hello/goodbye, please/thank you, and simple self-introduction chunks.",
    ["Hello!", "Good morning", "Nice to meet you", "How are you?", "I'm fine, thanks", "See you later", "Please", "Thank you"],
    ["verb be (I am / you are)", "question forms: How...?"],
    ["Introduce yourself to two new people in under a minute.", "Catch greetings vs farewells in fast exchanges.", "Recognise greeting words on signs and cards.", "Write your name and one greeting line."],
    "Your first day at a language school in London: the receptionist greets you, and a student introduces herself.",
    "Translating word-for-word instead of learning 'Nice to meet you' as one fixed chunk.",
    [["Pre-A1", "Hello! I'm Sara. Nice to meet you."], ["A2", "Let me introduce you to my colleague Kareem."], ["B1", "How do you two know each other, exactly?"], ["C1", "We were formally introduced at a conference, but we'd never actually worked together."]],
  ),
  t(2, "name-age-personal-info", "My Name, Age and Personal Information", "personal", "lesson-01-me-my-world",
    "State and ask for names, ages, countries, jobs and contact details accurately.",
    ["My name is...", "I'm from...", "I'm ... years old", "I live in...", "I work as a...", "What's your name?", "Where are you from?", "my / your / his / her"],
    ["possessive adjectives", "be: statements and questions"],
    ["Answer a five-question personal profile aloud.", "Catch names and countries in a slow introduction.", "Fill a simple registration form.", "Complete an ID-card style profile."],
    "Filling in a gym membership form while the clerk asks you the same questions out loud.",
    "Mixing his/her and confusing 'I'm 25' with 'I have 25'.",
    [["Pre-A1", "My name is Omar. I am from Cairo."], ["A1", "She's my sister. Her name is Layla."], ["A2", "Could I just check how you spell your surname?"], ["B1", "Sorry, I didn't catch your name — could you say it again more slowly?"]],
  ),
  t(3, "numbers-dates-time", "Numbers, Dates and Time", "daily", "lesson-01-me-my-world",
    "Understand and say numbers, prices, phone numbers, dates and clock times.",
    ["one, two, three...", "thirteen / thirty", "What time is it?", "It's half past nine", "on Monday", "in May", "in 2026", "today / tomorrow"],
    ["prepositions of time: at / on / in", "plural numbers"],
    ["Say your phone number and birthday clearly.", "Understand gate numbers and times in an announcement.", "Read opening hours and dates on a ticket.", "Write three important dates in your week."],
    "A receptionist gives you an appointment time over a bad phone line — you must catch the day, date and hour.",
    "Confusing thirteen/thirty and mishearing times like 'seven forty-five'.",
    [["Pre-A1", "The class is at nine o'clock."], ["A1", "My birthday is on 14 March."], ["A2", "Can we move our meeting to Thursday afternoon?"], ["B1", "I'll need to check my calendar — I might be double-booked."], ["B2", "Could we find a slot that works across time zones?"]],
  ),
  t(4, "family-people-around-me", "Family and People Around Me", "personal", "lesson-01-me-my-world",
    "Name family members and close people, and describe who they are simply.",
    ["mother / father", "brother / sister", "wife / husband", "son / daughter", "friend", "This is my...", "He is a doctor", "She is six"],
    ["verb be + he/she/it", "possessive 's (Sara's brother)"],
    ["Show a photo and describe three family members.", "Identify family words in a short description.", "Match names to roles in a simple text.", "Draw your family tree and label it."],
    "You show your phone gallery to a classmate and introduce everyone in three photos.",
    "Saying 'He is teacher' instead of 'He is a teacher'.",
    [["Pre-A1", "This is my brother. He is six."], ["A2", "My cousin is getting married next month."], ["B1", "I take after my mother — we're both quite stubborn."], ["B2", "Extended families often end up sharing childcare responsibilities."], ["C1", "Family expectations can quietly shape career choices long after childhood."]],
  ),
  t(5, "basic-feelings-emotions", "Basic Feelings and Emotions", "personal", "lesson-01-me-my-world",
    "Say how you feel and ask others, using the core emotion words.",
    ["happy / sad", "tired", "hungry / thirsty", "hot / cold", "angry", "scared", "I'm (not) okay", "Are you okay?"],
    ["I feel + adjective", "you are / he is + feeling"],
    ["Say how you feel today and why in one sentence.", "Hear which feeling someone names.", "Match faces and emoji to feeling words.", "Write one line about today's mood."],
    "A friend looks upset after class; you gently ask how she feels and she explains.",
    "Using 'I am boring' instead of 'I am bored'.",
    [["Pre-A1", "I'm tired. I want to sleep."], ["A2", "I was really nervous before the exam."], ["B1", "Honestly, I felt a bit let down when they cancelled."], ["B2", "He seemed oddly detached, given what had happened."], ["C1", "There's a quiet frustration running beneath her cheerfulness."]],
  ),

  t(6, "my-home", "My Home", "daily", "lesson-02-home-everyday-life",
    "Describe where you live: house or flat, size, location, what you like.",
    ["house / flat / apartment", "room", "kitchen / bathroom / bedroom", "small / big", "I live in...", "near the station", "upstairs / downstairs", "rent"],
    ["there is / there are", "prepositions of place: in / on / under / next to"],
    ["Describe your home in five sentences.", "Follow a tour of a flat.", "Read a rental advert's basics.", "Write three lines about where you live."],
    "A landlord shows you a small flat; you ask what things are and say what you like.",
    "Saying 'the life in third floor' instead of 'I live on the third floor'.",
    [["Pre-A1", "My house is small. I like it."], ["A1", "My flat has two rooms and a small kitchen."], ["A2", "I live in a flat on the third floor, near the station."], ["B1", "We're thinking of moving somewhere with more natural light."], ["C1", "There's a real trade-off between space, commute and affordability."]],
  ),
  t(7, "rooms-household-objects", "Rooms and Household Objects", "daily", "lesson-02-home-everyday-life",
    "Name furniture and everyday objects and say where they are.",
    ["table / chair", "bed / sofa", "fridge / cooker", "key / lamp", "window / door", "Where is the...?", "It's on the table", "in the cupboard"],
    ["where-questions", "in / on / under / behind"],
    ["Say where five objects are in your kitchen.", "Find objects from audio instructions ('Put the cup on the table').", "Label a room picture from memory.", "Write where three things are right now."],
    "A flatmate asks where the scissors, charger and mugs are — direct them precisely.",
    "Dropping articles: 'key is on table' instead of 'The key is on the table'.",
    [["Pre-A1", "The cat is under the table."], ["A1", "The mugs are in the cupboard next to the sink."], ["A2", "Could you plug the lamp in behind the sofa?"], ["B1", "We need somewhere to store the vacuum — the hallway cupboard's overflowing."], ["B2", "The layout works, provided the desk doesn't block the radiator."]],
  ),
  t(8, "daily-routines", "Daily Routines", "daily", "lesson-02-home-everyday-life",
    "Describe a normal day from waking to sleeping with times and sequence words.",
    ["wake up / get up", "have breakfast / lunch / dinner", "go to work / school", "watch TV", "go to bed", "then / after that", "always / usually / sometimes / never", "at seven o'clock"],
    ["present simple (I / you / we / they)", "adverbs of frequency"],
    ["Describe your whole day in order.", "Compare two speakers' routines and spot differences.", "Read a daily timetable.", "Write your typical morning in four sentences."],
    "You explain your morning routine to a new flatmate who keeps different hours.",
    "Forgetting the -s: 'she get up at seven' instead of 'gets up'.",
    [["Pre-A1", "I wake up at seven every day."], ["A1", "I usually have breakfast at eight."], ["A2", "I usually check my phone before I even get out of bed."], ["B1", "I've started walking to work instead of taking the bus."], ["B2", "My evenings tend to disappear into admin unless I plan around it."], ["C1", "Routines quietly decide outcomes long before motivation enters the picture."]],
  ),
  t(9, "personal-belongings", "Personal Belongings", "daily", "lesson-02-home-everyday-life",
    "Talk about the things you own: phone, bag, clothes, devices — and whose they are.",
    ["bag / wallet", "phone / laptop", "keys / glasses", "mine / yours / hers", "Whose is this?", "It's mine", "new / old", "I have..."],
    ["have got / has got", "possessive pronouns"],
    ["List what's in your bag right now.", "Identify items described by touch clues in audio.", "Read lost-property notices.", "Write a 'lost item' note with description."],
    "At a hostel, three identical black rucksacks appear — sort out whose is whose.",
    "Swapping mine/my: 'Is this my?' instead of 'Is this mine?'.",
    [["Pre-A1", "This is my phone."], ["A1", "I've got two keys and a wallet."], ["A2", "Whose charger is this? It isn't mine."], ["B1", "Everything valuable was in the side pocket, thankfully."], ["B2", "I tend to carry far more gadgets than any trip justifies."]],
  ),
  t(10, "household-responsibilities", "Basic Household Responsibilities", "daily", "lesson-02-home-everyday-life",
    "Discuss simple chores and agree who does what at home.",
    ["wash the dishes", "do the cleaning", "cook dinner", "take the rubbish out", "do the washing", "Can you...?", "I'll do it", "every day / twice a week"],
    ["can for requests", "present simple with he/she chores"],
    ["Ask a flatmate politely to swap a chore.", "Catch which days tasks happen in a shared-flat chat.", "Read a chore rota.", "Write two house rules."],
    "Chore rota night in a shared flat: dishes, bins and bathroom duty get negotiated.",
    "'Wash up' means dishes in UK English — don't confuse it with washing clothes.",
    [["Pre-A1", "I wash the dishes."], ["A1", "He cooks dinner on Fridays."], ["A2", "Could you take the rubbish out when you leave?"], ["B1", "If you handle the bins, I'll sort the bathroom this week."], ["B2", "We've settled into an unofficial system that somehow works for everyone."]],

  ),
  t(11, "food-and-drinks", "Food and Drinks", "daily", "lesson-03-food-shopping-services",
    "Name common foods and drinks and say what you like and don't like.",
    ["bread / rice / eggs", "chicken / fish", "milk / tea / coffee", "apple / banana", "I like... / I don't like...", "Do you like...?", "delicious", "water"],
    ["like + noun / -ing", "countable vs uncountable (some rice, two eggs)"],
    ["Say what you eat on a normal day.", "Catch food words in a market conversation.", "Read a simple menu.", "Write your three favourite foods."],
    "At a busy market stall you ask what things are and taste something completely new.",
    "Saying 'a rice' — some foods (rice, water, bread) are uncountable.",
    [["Pre-A1", "I like rice. I don't like fish."], ["A1", "Do you want some tea?"], ["A2", "I'm trying to eat less sugar these days."], ["B1", "We mostly cook at home during the week and eat out on Fridays."], ["B2", "There's growing awareness about where our food actually comes from."], ["C1", "Our eating habits are shaped as much by schedules as by taste."]],
  ),
  t(12, "meals-eating-habits", "Meals and Eating Habits", "daily", "lesson-03-food-shopping-services",
    "Talk about breakfast, lunch and dinner and compare meal customs.",
    ["breakfast / lunch / dinner", "starter / main course / dessert", "vegetarian", "takeaway", "eat out", "What do you usually have...?", "for breakfast", "snack"],
    ["present simple questions (Do you...? What...?)", "frequency expressions: once a week"],
    ["Describe yesterday's meals.", "Follow two friends comparing food habits.", "Read café opening times and menu sections.", "Write about a typical dinner at home."],
    "Two colleagues compare lunch habits — one cooks everything, one lives on takeaways.",
    "Meals differ by culture: 'dinner' can be midday or evening depending on the country.",
    [["Pre-A1", "I have breakfast at home."], ["A1", "We have dinner at seven o'clock."], ["A2", "I usually grab a quick sandwich at lunchtime."], ["B1", "Sunday lunch is the one meal we never skip as a family."], ["B2", "Convenience has quietly rewritten how an entire generation eats."], ["C1", "Meal patterns reveal more about working culture than most surveys capture."]],
  ),
  t(13, "shopping-everyday-items", "Shopping for Everyday Items", "daily", "lesson-03-food-shopping-services",
    "Buy everyday things: ask for items, sizes, quantities and pay simply.",
    ["How much is it?", "I'd like..., please", "Have you got...?", "a kilo of", "a bottle of", "cheap / expensive", "the bill, please", "receipt"],
    ["I'd like / Can I have", "some / any"],
    ["Buy five items at a shop politely.", "Catch prices said quickly.", "Read price labels and offers.", "Write a three-item shopping list."],
    "In a corner shop before closing time, buy what you need and pay in cash.",
    "Prices: £4.50 is 'four pounds fifty', not 'four comma five'.",
    [["Pre-A1", "How much is it?"], ["A1", "I'd like a kilo of apples, please."], ["A2", "Excuse me, have you got this in a bigger size?"], ["B1", "It's a bit pricey, but it lasts much longer."], ["B2", "I compared three supermarkets and the difference was negligible."], ["C1", "Own-brand products have quietly closed the quality gap in most categories."]],
  ),
  t(14, "prices-money-payment", "Prices, Money and Payment", "finance", "lesson-03-food-shopping-services",
    "Handle money: understand prices, notes and coins, card and cash payments.",
    ["pound / dollar / euro", "change", "cash / card", "Can I pay by card?", "Here you are", "fifty pence", "banknote", "It comes to..."],
    ["How much...? with is/are", "numbers for money"],
    ["Pay for something and check your change.", "Follow a checkout total spoken quickly.", "Read a receipt.", "Write the cost of three things you bought."],
    "Self-checkout refuses your card; sort out payment with the assistant without panic.",
    "'Change' means both coins and the money returned — context decides.",
    [["Pre-A1", "How much?"], ["A1", "Can I pay by card, please?"], ["A2", "I think you've given me the wrong change."], ["B1", "Could I get a receipt? I need it for expenses."], ["B2", "Contactless quietly replaced cash in most of my spending."], ["C1", "Payment habits are a surprisingly reliable window into financial stress."]],
  ),
  t(15, "restaurants-ordering", "Restaurants, Cafés and Ordering", "social", "lesson-03-food-shopping-services",
    "Order food and drinks in a café or restaurant and ask about the menu.",
    ["A table for two", "Can I see the menu?", "I'll have the chicken", "Anything to drink?", "Still or sparkling?", "How would you like it?", "The bill, please", "tip"],
    ["will for instant decisions (I'll have...)", "would like for polite offers"],
    ["Order a full meal including drinks.", "Catch a waiter's questions and specials.", "Read a menu with descriptions.", "Write a short review of a café."],
    "Busy Friday evening, a waiter asks rapid-fire questions — order calmly and completely.",
    "'I'll have...' not 'I will having' — decisions use plain will.",
    [["Pre-A1", "A coffee, please."], ["A1", "Can I have the menu, please?"], ["A2", "I'll have the pasta and a sparkling water, please."], ["B1", "Is the curry very spicy? I'm not great with chilli."], ["B2", "We're in no rush — could you give us a few minutes with the wine list?"], ["C1", "The tasting menu is tempting, though the vegetarian alternative decides it for me."]],

  ),
  t(16, "places-in-town", "Places in Town", "daily", "lesson-04-places-getting-around",
    "Name key places in a town and say what you can do there.",
    ["bank / post office", "supermarket / chemist", "bus stop / station", "hospital / school", "library", "Where is the bank?", "next to / opposite", "town centre"],
    ["there is / are in town descriptions", "imperatives: Turn left"],
    ["Say where five places are from your point.", "Follow someone describing their street.", "Read shop signs and opening hours.", "Write what you can do at three places."],
    "A tourist asks you to point out the essentials on a town map.",
    "'Chemist' (UK) = pharmacy (US) — same place, different name.",
    [["Pre-A1", "The bank is there."], ["A1", "The supermarket is next to the bus stop."], ["A2", "Is there a chemist open near here at this hour?"], ["B1", "The post office moved — it's inside the station now."], ["B2", "High streets have changed beyond recognition in a decade."], ["C1", "Town centres are being reinvented around experience rather than retail."]],
  ),
  t(17, "asking-giving-directions", "Asking for and Giving Directions", "social", "lesson-04-places-getting-around",
    "Ask for directions and guide someone clearly with left/right and landmarks.",
    ["Excuse me, how do I get to...?", "Turn left / right", "Go straight on", "It's on your left", "crossroads / traffic lights", "Is it far?", "five minutes' walk", "Take the second turning"],
    ["imperatives", "prepositions of movement: along / past / through"],
    ["Guide someone from the station to your meeting point.", "Repeat back directions to confirm you understood.", "Read a simple street map.", "Write directions from your home to the nearest shop."],
    "Phone lost signal, no map: a stranger guides you to the embassy on foot.",
    "Reacting too fast — repeat the directions back before you walk off.",
    [["Pre-A1", "Left here."], ["A1", "Go straight on, then turn left."], ["A2", "Take the second right, opposite the church."], ["B1", "Keep going until you hit the crossroads — it's tucked behind the bakery."], ["B2", "Honestly, sat-nav has made giving directions a dying skill."], ["C1", "Directions reveal how differently people mentally map the same city."]],
  ),
  t(18, "public-transportation", "Public Transportation", "daily", "lesson-04-places-getting-around",
    "Use buses, metro and trains: tickets, platforms, times and delays.",
    ["ticket / single / return", "platform / stop", "next train / bus", "Does this bus go to...?", "get on / get off", "monthly pass", "delayed", "change at..."],
    ["present simple timetables (The train leaves at...)", "have to for rules"],
    ["Buy a return ticket and find your platform.", "Catch platform changes in an announcement.", "Read a metro map and timetable.", "Write how you get to work each day."],
    "Announcements say your train is delayed and moved to another platform — re-plan fast.",
    "Timetables use present simple: 'The train LEAVES at 6', not 'is leaving'.",
    [["Pre-A1", "One ticket, please."], ["A1", "Does this bus go to the centre?"], ["A2", "Which platform does the Manchester train leave from?"], ["B1", "You'll need to change at Clapham — the direct service stops running early."], ["B2", "Season tickets only pay off if you commute at least three days a week."], ["C1", "Underinvestment shows: reliability has quietly become the network's biggest luxury."]],
  ),
  t(19, "streets-buildings-neighbourhoods", "Streets, Buildings and Neighbourhoods", "daily", "lesson-04-places-getting-around",
    "Describe your street and neighbourhood: what's there and what it's like.",
    ["quiet / noisy", "safe", "park / playground", "corner shop", "block of flats", "I live near...", "friendly", "neighbour"],
    ["there is/are + quantifiers (lots of, a few)", "adjective order basics"],
    ["Describe your street in six sentences.", "Compare two neighbourhoods from a conversation.", "Read a neighbourhood guide blurb.", "Write what you like about your area."],
    "You recommend your neighbourhood to a friend who might move there — honestly.",
    "'Neighbourhood' = the area; 'neighbour' = the person next door.",
    [["Pre-A1", "My street is quiet."], ["A1", "There is a park near my house."], ["A2", "It's a friendly area, but parking is impossible."], ["B1", "It's got worse traffic lately, but the new cycle lane helps."], ["B2", "House prices have pushed half our generation to the outskirts."], ["C1", "Neighbourhoods are defined less by geography than by whoever still runs the corner shop."]],
  ),
  t(20, "travel-basics", "Travel Basics", "social", "lesson-04-places-getting-around",
    "Handle first travel moments: passports, simple bookings and basic questions abroad.",
    ["passport / visa", "booking / reservation", "one-way / round trip", "Where are you flying?", "How long are you staying?", "tourist", "luggage / suitcase", "board"],
    ["present continuous for arrangements (I'm flying on Monday)", "how long / how often questions"],
    ["Answer five immigration-style questions simply.", "Catch flight details in a slow announcement.", "Read a basic booking confirmation.", "Write a packing list with reasons."],
    "Border control at your first international arrival: answer the officer's standard questions.",
    "Present continuous for future plans: 'I'm staying for two weeks', not 'I stay'.",
    [["Pre-A1", "This is my passport."], ["A1", "I'm here for one week."], ["A2", "I'm visiting my cousin, and I'm flying back on the 12th."], ["B1", "It's a work trip mostly, though I'm staying the weekend to look around."], ["B2", "The visa process has become noticeably stricter since last year."], ["C1", "Queue management tells you more about a country than its airports ever could."]],

  ),
  t(21, "human-body", "The Human Body", "health", "lesson-05-health-body",
    "Name parts of the body and describe simple physical states.",
    ["head / hand / arm", "leg / foot / knee", "back / stomach", "tooth (teeth)", "eye / ear", "My ... hurts", "ache", "skin / bone"],
    ["have + ache (I have a headache)", "hurts vs is painful"],
    ["Point and name ten body parts quickly.", "Understand a nurse's 'where does it hurt?' exchange.", "Read medicine packet warnings.", "Label a body diagram in words."],
    "At a pharmacy, describe exactly where it hurts and since when.",
    "'My leg hurts' (verb) vs 'I have a pain in my leg' — both fine, don't mix structures.",
    [["Pre-A1", "My head hurts."], ["A1", "I have a pain in my stomach."], ["A2", "I've got a sore throat and a temperature."], ["B1", "It's a dull ache rather than a sharp pain, if that makes sense."], ["B2", "The physio identified a weakness in my left knee from years of poor posture."], ["C1", "Chronic pain reshapes behaviour so gradually that patients often normalise it."]],
  ),
  t(22, "illnesses-symptoms", "Common Illnesses and Symptoms", "health", "lesson-05-health-body",
    "Describe being ill: colds, flu, allergies and how long symptoms last.",
    ["cold / flu", "fever / temperature", "cough / sneeze", "headache", "sore throat", "I feel ill", "since yesterday", "getting better / worse"],
    ["present perfect with for/since (I've been ill since Monday)", "feel + adjective"],
    ["Describe symptoms and their timeline.", "Catch a doctor's follow-up questions.", "Read a symptom leaflet.", "Text a friend that you're sick and can't come."],
    "Monday morning: flu symptoms since the weekend — call in sick with enough detail.",
    "For/since: 'since Monday' (point) vs 'for three days' (duration).",
    [["Pre-A1", "I am sick."], ["A1", "I have a cold and a cough."], ["A2", "I've had this headache since Sunday."], ["B1", "It started as a sore throat, then turned into proper flu."], ["B2", "The antibiotics cleared the infection, though recovery dragged on for weeks."], ["C1", "Symptom timelines matter more than intensity when GPs triage cases."]],
  ),
  t(23, "visiting-the-doctor", "Visiting the Doctor", "health", "lesson-05-health-body",
    "Book and attend a medical appointment; understand advice and prescriptions.",
    ["appointment / surgery", "prescription / pharmacy", "symptoms", "twice a day", "How long have you felt like this?", "insurance card", "follow-up", "blood test"],
    ["present perfect questions (How long have you...?)", "should / shouldn't for advice"],
    ["Role-play booking and attending an appointment.", "Understand dosage instructions first time.", "Read a prescription label.", "Write down the doctor's advice as bullet points."],
    "Doctor's appointment for a persistent cough: describe it, answer questions, get a prescription.",
    "Dosages: 'twice daily' = two times a day, not every two hours.",
    [["Pre-A1", "I need a doctor."], ["A1", "Can I make an appointment, please?"], ["A2", "I've had a cough for two weeks and it's getting worse."], ["B1", "Should I come back if it hasn't cleared up by Friday?"], ["B2", "The GP referred me for tests mostly to rule anything serious out."], ["C1", "Over-prescription worries have made GPs noticeably more conservative lately."]],

  ),
  t(24, "healthy-habits", "Healthy Habits", "health", "lesson-05-health-body",
    "Discuss sleep, diet, water and screen habits — and suggest improvements.",
    ["enough sleep", "drink water", "junk food", "stay healthy", "give up smoking", "It's good/bad for you", "in moderation", "routine"],
    ["should / shouldn't", "too much / not enough + noun"],
    ["Give a friend two pieces of health advice.", "Catch healthy/unhealthy habits in a radio item.", "Read a wellbeing checklist.", "Write your three healthiest habits."],
    "A wellness app onboards you: rate your sleep, water, steps and screens honestly.",
    "'Advise' vs 'advice' — verb vs noun spelling trap.",
    [["Pre-A1", "Water is good for you."], ["A1", "You shouldn't eat too much sugar."], ["A2", "I try to sleep eight hours, but it doesn't always happen."], ["B1", "Cutting caffeine after four o'clock genuinely improved my sleep."], ["B2", "Wellbeing advice tends to ignore how demanding people's jobs actually are."], ["C1", "Health habits are less about discipline than about designing better defaults."]],
  ),
  t(25, "exercise-physical-activity", "Exercise and Physical Activity", "health", "lesson-05-health-body",
    "Talk about sport, exercise routines and moving your body regularly.",
    ["go running / swimming", "work out / gym", "fit / unfit", "warm up", "stretch", "How often do you exercise?", "team sport", "steps"],
    ["go + -ing for sports", "how often + frequency answers"],
    ["Describe your weekly activity truthfully.", "Follow a gym induction's key instructions.", "Read a class timetable.", "Write tomorrow's realistic exercise plan."],
    "A friend invites you to a 6 a.m. run — negotiate frequency, time and honest fitness levels.",
    "'Play football' but 'go swimming' and 'do yoga' — collocation, not logic.",
    [["Pre-A1", "I play football."], ["A1", "I go swimming on Saturdays."], ["A2", "I try to work out twice a week, mostly cardio."], ["B1", "I've signed up for a 5k, which seemed wiser three months ago."], ["B2", "Consistency beats intensity — I finally believe it after years of injuries."], ["C1", "Fitness culture sells transformation while quietly ignoring maintenance."]],
  ),
];
