// Vocabulary page expansion — bands B1–C2 (task 28-b).
// Companion to the BANK in app/(app)/vocabulary/page.tsx: no word overlaps with the
// existing A1/B1/B2/A2 entries. One compact line per entry; UK spelling throughout.

export interface VocabPageWord {
  word: string;
  type: string; // "noun" | "verb" | "adjective" | "adverb" | "phrase" | "idiom" etc.
  meaning: string; // clear English definition appropriate to the band
  ar: string; // accurate natural Arabic translation (MSA, short)
  example: string; // natural UK-English example sentence
}

export const VOCAB_PAGE_EXPANSION_B: Record<string, VocabPageWord[]> = {
  "B1": [
    { word: "opinion", type: "noun", meaning: "what you think or believe about something", ar: "رأي", example: "In my opinion, the film was better than the book." },
    { word: "opportunity", type: "noun", meaning: "a time or situation that lets you do something you want", ar: "فرصة", example: "If I had the opportunity, I would study abroad." },
    { word: "background", type: "noun", meaning: "a person's education, family and past work", ar: "خلفية", example: "She has a background in graphic design." },
    { word: "progress", type: "noun", meaning: "movement forward towards a better state or result", ar: "تقدم", example: "You've made brilliant progress since January." },
    { word: "talent", type: "noun", meaning: "a natural ability to do something well", ar: "موهبة", example: "He has a real talent for languages." },
    { word: "knowledge", type: "noun", meaning: "the information and understanding you have gained", ar: "معرفة", example: "Her knowledge of the subject impressed the tutor." },
    { word: "assignment", type: "noun", meaning: "a piece of work given as part of a job or course", ar: "واجب دراسي", example: "I've just finished my history assignment." },
    { word: "qualification", type: "noun", meaning: "an official record showing you have finished training or study", ar: "مؤهل", example: "You'll need a teaching qualification for that role." },
    { word: "employer", type: "noun", meaning: "a person or company that pays people to work", ar: "صاحب العمل", example: "My employer has agreed to fund the course." },
    { word: "employee", type: "noun", meaning: "a person who is paid to work for a company", ar: "موظف", example: "Each employee receives twenty days of holiday." },
    { word: "salary", type: "noun", meaning: "fixed money paid regularly for a job", ar: "راتب", example: "The salary is reviewed every April." },
    { word: "promotion", type: "noun", meaning: "a move to a higher, more important position at work", ar: "ترقية", example: "He's hoping for a promotion this year." },
    { word: "industry", type: "noun", meaning: "the production of goods or services in a particular area of business", ar: "صناعة / قطاع", example: "She's worked in the travel industry for five years." },
    { word: "career", type: "noun", meaning: "the series of jobs you have during your working life", ar: "مسار مهني", example: "A career in engineering suits curious people." },
    { word: "interview", type: "noun", meaning: "a formal meeting to discuss whether someone suits a job", ar: "مقابلة", example: "I've got a job interview on Thursday morning." },
    { word: "colleague", type: "noun", meaning: "a person you work with", ar: "زميل عمل", example: "My colleagues have been very supportive lately." },
    { word: "contract", type: "noun", meaning: "a written agreement between people or companies", ar: "عقد", example: "Read the contract carefully before you sign it." },
    { word: "internship", type: "noun", meaning: "a period of work experience, often for students", ar: "تدريب عملي", example: "He's doing a summer internship at a law firm." },
    { word: "responsibility", type: "noun", meaning: "a duty to deal with something or take care of someone", ar: "مسؤولية", example: "Taking responsibility for mistakes builds trust." },
    { word: "challenge", type: "noun", meaning: "something new and difficult that needs effort", ar: "تحدٍّ", example: "Starting a business was a huge challenge for them." },
    { word: "success", type: "noun", meaning: "the achievement of what you planned or wanted", ar: "نجاح", example: "Their success surprised everyone." },
    { word: "failure", type: "noun", meaning: "the lack of success in doing something", ar: "فشل", example: "Failure is part of learning anything new." },
    { word: "effect", type: "noun", meaning: "the change that something causes in something else", ar: "تأثير", example: "The new timetable has had a positive effect on attendance." },
    { word: "solution", type: "noun", meaning: "a way to fix a problem", ar: "حل", example: "If we pool our ideas, we'll find a solution." },
    { word: "advantage", type: "noun", meaning: "something that helps you be better or more successful", ar: "ميزة", example: "The main advantage of the flat is its location." },
    { word: "benefit", type: "noun", meaning: "a good or helpful result", ar: "فائدة", example: "Cycling to work has real health benefits." },
    { word: "purpose", type: "noun", meaning: "the reason for doing something", ar: "غرض", example: "The purpose of this meeting is to agree the budget." },
    { word: "decision", type: "noun", meaning: "a choice made after thinking", ar: "قرار", example: "We've made a final decision about the venue." },
    { word: "risk", type: "noun", meaning: "the possibility that something bad may happen", ar: "مخاطرة", example: "If you don't back up your files, you risk losing everything." },
    { word: "effort", type: "noun", meaning: "physical or mental energy used to do something", ar: "جهد", example: "She put a lot of effort into the presentation." },
    { word: "suggest", type: "verb", meaning: "to put forward an idea or plan for others to consider", ar: "يقترح", example: "I suggest we take a short break." },
    { word: "claim", type: "verb", meaning: "to state something is true without offering proof", ar: "يزعم / يدّعي", example: "He claims he finished the report, but I haven't seen it." },
    { word: "outline", type: "verb", meaning: "to give the main points of a plan or idea", ar: "يوجز", example: "Let me outline the plan before we vote." },
    { word: "mention", type: "verb", meaning: "to speak or write about something briefly", ar: "يذكر", example: "She mentioned that the prices have gone up." },
    { word: "realise", type: "verb", meaning: "to become aware of or understand something", ar: "يدرك", example: "I didn't realise how late it was." },
    { word: "insist", type: "verb", meaning: "to demand something firmly, refusing to change", ar: "يصرّ", example: "He insisted on paying for the meal." },
    { word: "remind", type: "verb", meaning: "to make someone remember something they must do", ar: "يذكّر", example: "Please remind me to post this letter." },
    { word: "convince", type: "verb", meaning: "to make someone believe something is true", ar: "يقنع", example: "If you show the data, you'll convince the board." },
    { word: "manage", type: "verb", meaning: "to succeed in doing something difficult", ar: "يتمكّن من", example: "I managed to finish the essay before midnight." },
    { word: "intend", type: "verb", meaning: "to plan or mean to do something", ar: "ينوي", example: "We intend to extend the shop next spring." },
    { word: "attend", type: "verb", meaning: "to be present at an event or class", ar: "يحضر", example: "All staff must attend the fire training." },
    { word: "revise", type: "verb", meaning: "to study work again before an exam", ar: "يراجع", example: "If you revise a little each night, you'll remember more." },
    { word: "apply", type: "verb", meaning: "to make a formal request for a job or place", ar: "يتقدم بطلب", example: "I've applied for three jobs this week." },
    { word: "accept", type: "verb", meaning: "to agree to take something offered", ar: "يقبل", example: "They accepted our offer within a day." },
    { word: "refuse", type: "verb", meaning: "to say you will not do or accept something", ar: "يرفض", example: "She refused to discuss it over email." },
    { word: "apologise", type: "verb", meaning: "to say sorry for having done something wrong", ar: "يعتذر", example: "He apologised for arriving so late." },
    { word: "promise", type: "verb", meaning: "to tell someone you will certainly do something", ar: "يعد", example: "I promise I'll send it by Friday." },
    { word: "admit", type: "verb", meaning: "to agree, perhaps unwillingly, that something is true", ar: "يعترف", example: "Nobody has admitted breaking the window." },
    { word: "deny", type: "verb", meaning: "to say that something is not true", ar: "ينكر", example: "The company denies that safety rules were broken." },
    { word: "blame", type: "verb", meaning: "to say someone is responsible for something bad", ar: "يلوم", example: "Don't blame the team for the delay." },
    { word: "warn", type: "verb", meaning: "to tell someone about possible danger or trouble", ar: "يحذر", example: "The forecast warns of heavy rain tonight." },
    { word: "criticise", type: "verb", meaning: "to point out the faults of something or someone", ar: "ينتقد", example: "Parents criticised the school's new parking rules." },
    { word: "find out", type: "phrasal verb", meaning: "to discover a fact or piece of information", ar: "يكتشف", example: "I'll find out what time the museum opens." },
    { word: "give up", type: "phrasal verb", meaning: "to stop trying or stop doing something", ar: "يستسلم / يقلع عن", example: "He's given up sugar for a month." },
    { word: "carry on", type: "phrasal verb", meaning: "to continue doing something", ar: "يواصل", example: "Carry on with your notes while I fetch the handouts." },
    { word: "come up with", type: "phrasal verb", meaning: "to think of an idea, plan or answer", ar: "يتوصل إلى", example: "She came up with a great idea for the campaign." },
    { word: "deal with", type: "phrasal verb", meaning: "to take action about a problem or task", ar: "يتعامل مع", example: "Could you deal with this complaint, please?" },
    { word: "sort out", type: "phrasal verb", meaning: "to organise or solve a confusing situation", ar: "يحلّ / يرتّب", example: "We'll sort out the timetable once the dates are fixed." },
    { word: "set up", type: "phrasal verb", meaning: "to create or arrange a business, system or meeting", ar: "يؤسّس", example: "They've set up a small studio in the garage." },
    { word: "put off", type: "phrasal verb", meaning: "to delay doing something to a later time", ar: "يؤجّل", example: "Don't put off booking the tickets; prices rise." },
    { word: "turn down", type: "phrasal verb", meaning: "to say no to an offer or request", ar: "يرفض عرضًا", example: "She turned down the job because of the commute." },
    { word: "look forward to", type: "phrasal verb", meaning: "to feel pleased and excited about something to come", ar: "يتشوّق إلى", example: "I look forward to hearing from you." },
    { word: "get used to", type: "phrasal verb", meaning: "to become familiar with something so it feels normal", ar: "يعتاد على", example: "You'll soon get used to the early starts." },
    { word: "work out", type: "phrasal verb", meaning: "to find the answer by thinking or calculating", ar: "يستنتج الحل", example: "I can't work out how the new printer functions." },
    { word: "ambitious", type: "adjective", meaning: "having a strong wish to be successful", ar: "طموح", example: "He's ambitious, so he'll chase that role." },
    { word: "organised", type: "adjective", meaning: "able to plan things carefully and keep order", ar: "منظّم", example: "She's very organised; her notes are colour-coded." },
    { word: "punctual", type: "adjective", meaning: "arriving or happening at the exact agreed time", ar: "دقيق في المواعيد", example: "Please be punctual; the tour leaves at nine." },
    { word: "easy-going", type: "adjective", meaning: "relaxed and not easily worried or annoyed", ar: "سهل العشرة", example: "Our manager is easy-going about start times." },
    { word: "keen", type: "adjective", meaning: "very interested in and enthusiastic about something", ar: "متحمس", example: "If you're keen to join, let me know today." },
    { word: "worthwhile", type: "adjective", meaning: "useful or enjoyable enough to justify the time spent", ar: "يستحق العناء", example: "Volunteering turned out to be really worthwhile." },
    { word: "worth", type: "adjective", meaning: "good, useful or enjoyable enough for the money or time given", ar: "يستحق", example: "The museum is well worth a visit." },
    { word: "unemployed", type: "adjective", meaning: "without a job although willing to work", ar: "عاطل عن العمل", example: "He's been unemployed since the factory closed." },
    { word: "full-time", type: "adjective", meaning: "working or studying the whole working week", ar: "بدوام كامل", example: "She works full-time and studies at weekends." },
    { word: "annoyed", type: "adjective", meaning: "slightly angry about something", ar: "منزعج", example: "I was annoyed that the shop closed early." },
    { word: "apparently", type: "adverb", meaning: "used to report something you have heard but not confirmed", ar: "يبدو أن", example: "Apparently, the exam dates have changed." },
    { word: "mainly", type: "adverb", meaning: "most importantly or most of the time", ar: "بشكل رئيسي", example: "The delay was mainly caused by bad weather." },
    { word: "personally", type: "adverb", meaning: "used to give your own opinion", ar: "بشكل شخصي", example: "Personally, I'd rather walk than take the bus." },
    { word: "however", type: "connector", meaning: "used to introduce a point that contrasts with what came before", ar: "بيد أن", example: "The plan is cheap; however, it takes longer." },
    { word: "although", type: "connector", meaning: "despite the fact that", ar: "رغم أن", example: "Although it rained, we enjoyed the match." },
    { word: "therefore", type: "connector", meaning: "for that reason", ar: "لذلك", example: "The bridge is closed; therefore, we'll take the ferry." },
    { word: "whereas", type: "connector", meaning: "used to compare two things that differ", ar: "في حين أن", example: "I prefer tea, whereas my sister only drinks coffee." },
    { word: "meanwhile", type: "connector", meaning: "during the time between two events", ar: "في هذه الأثناء", example: "The kettle boiled; meanwhile, I laid the table." },
    { word: "for instance", type: "phrase", meaning: "for example", ar: "على سبيل المثال", example: "Try local transport; for instance, the tram is excellent." },
    { word: "in my view", type: "phrase", meaning: "used to state an opinion plainly", ar: "في رأيي", example: "In my view, homework helps discipline." },
    { word: "on the other hand", type: "phrase", meaning: "used to give the opposite side of an argument", ar: "من ناحية أخرى", example: "The rent is low; on the other hand, the flat is tiny." },
    { word: "to be honest", type: "phrase", meaning: "used before admitting something frankly", ar: "بصراحة", example: "To be honest, I haven't started yet." },
    { word: "in general", type: "phrase", meaning: "usually or mostly true", ar: "عمومًا", example: "In general, our customers pay by card." },
    { word: "after all", type: "phrase", meaning: "despite what was expected or planned", ar: "بعد كل شيء", example: "Let's take the map after all; the streets look confusing." },
  ],
  "B2": [
    { word: "outcome", type: "noun", meaning: "the final result of an activity or process", ar: "النتيجة النهائية", example: "The outcome of the review will be announced on Friday." },
    { word: "implication", type: "noun", meaning: "a likely consequence of an action or decision", ar: "تبعات", example: "She warned that the delay had serious implications." },
    { word: "criterion", type: "noun", meaning: "a standard on which a judgement is based (plural: criteria)", ar: "معيار", example: "Applicants are assessed against one criterion: reliability." },
    { word: "stakeholder", type: "noun", meaning: "anyone with an interest in how a project or company performs", ar: "طرف معني", example: "All stakeholders were consulted before the merger." },
    { word: "workload", type: "noun", meaning: "the amount of work a person is expected to do", ar: "عبء العمل", example: "If the workload grew any heavier, staff would resign." },
    { word: "workforce", type: "noun", meaning: "all the people employed by an organisation", ar: "القوى العاملة", example: "Half the workforce was transferred to the new site." },
    { word: "turnover", type: "noun", meaning: "the total value of sales a company makes in a period", ar: "حجم مبيعات الشركة", example: "The branch doubled its turnover within a year." },
    { word: "revenue", type: "noun", meaning: "money a business receives from its activities", ar: "إيرادات", example: "Extra revenue was generated through online sales." },
    { word: "expenditure", type: "noun", meaning: "the total amount of money spent", ar: "نفقات", example: "Marketing expenditure was capped at ten per cent." },
    { word: "incentive", type: "noun", meaning: "something that encourages a person to act", ar: "حافز", example: "A bonus scheme was introduced as an incentive." },
    { word: "redundancy", type: "noun", meaning: "the loss of a job because it is no longer needed", ar: "تسريح من العمل", example: "He was made redundant when the depot closed." },
    { word: "infrastructure", type: "noun", meaning: "the basic structures a country needs, such as roads and power", ar: "بنية تحتية", example: "The bridges were repaired with infrastructure funding." },
    { word: "legislation", type: "noun", meaning: "a law or set of laws made by a government", ar: "تشريع", example: "Stricter legislation was passed last year." },
    { word: "regulation", type: "noun", meaning: "an official rule controlling an activity", ar: "لائحة", example: "Under the new regulation, helmets are compulsory." },
    { word: "guideline", type: "noun", meaning: "official advice on how something should be done", ar: "إرشادات", example: "The guidelines were updated in response to complaints." },
    { word: "framework", type: "noun", meaning: "a basic structure of ideas or rules that supports something", ar: "إطار عمل", example: "The project fits within the agreed framework." },
    { word: "obstacle", type: "noun", meaning: "something that blocks progress towards a goal", ar: "عقبة", example: "Poor transport remains the main obstacle to growth." },
    { word: "setback", type: "noun", meaning: "a problem that delays or reverses progress", ar: "انتكاسة", example: "The trial suffered a setback, but work continued." },
    { word: "breakthrough", type: "noun", meaning: "an important discovery or sudden advance", ar: "اختراق", example: "A breakthrough was achieved after months of testing." },
    { word: "consensus", type: "noun", meaning: "general agreement reached by a group", ar: "توافق", example: "A consensus was finally reached on the budget." },
    { word: "controversy", type: "noun", meaning: "strong public disagreement about something", ar: "جدل", example: "The decision sparked controversy across the sector." },
    { word: "bias", type: "noun", meaning: "an unfair preference for or against something", ar: "تحيّز", example: "The survey was criticised for hidden bias." },
    { word: "evidence", type: "noun", meaning: "facts or signs that help prove something", ar: "أدلة", example: "Little evidence was found to support the claim." },
    { word: "trend", type: "noun", meaning: "the general direction in which something is changing", ar: "اتجاه", example: "A clear trend towards remote work was observed." },
    { word: "forecast", type: "noun", meaning: "a statement of what is expected to happen", ar: "تنبؤ", example: "Sales were forecast to rise by five per cent." },
    { word: "trade-off", type: "noun", meaning: "giving up one advantage in order to gain another", ar: "مقايضة", example: "There is a trade-off between speed and accuracy." },
    { word: "standpoint", type: "noun", meaning: "the position from which a matter is viewed", ar: "وجهة نظر", example: "From a legal standpoint, the contract is sound." },
    { word: "objection", type: "noun", meaning: "a reason for disagreeing with a plan or statement", ar: "اعتراض", example: "The only objection raised was about cost." },
    { word: "assess", type: "verb", meaning: "to judge the quality or value of something", ar: "يقيّم", example: "Each proposal will be assessed by two panels." },
    { word: "evaluate", type: "verb", meaning: "to consider carefully in order to judge worth", ar: "يقيّم / يحكم على", example: "The trial results are being evaluated now." },
    { word: "justify", type: "verb", meaning: "to show that something is right or reasonable", ar: "يبرّر", example: "How can such spending be justified?" },
    { word: "clarify", type: "verb", meaning: "to make something easier to understand", ar: "يوضّح", example: "The office clarified that no jobs were at risk." },
    { word: "emphasise", type: "verb", meaning: "to give special weight or attention to something", ar: "يؤكد", example: "The coach emphasised that discipline comes first." },
    { word: "highlight", type: "verb", meaning: "to draw attention to the most important part", ar: "يبرز", example: "The report highlighted several safety failures." },
    { word: "undermine", type: "verb", meaning: "to weaken something gradually or secretly", ar: "يقوّض", example: "Leaked emails undermined the minister's position." },
    { word: "enforce", type: "verb", meaning: "to make sure a rule is obeyed", ar: "يفرض", example: "The rules are strictly enforced on site." },
    { word: "comply", type: "verb", meaning: "to act in the way a rule or law demands", ar: "يمتثل", example: "If the firm didn't comply, it would be fined." },
    { word: "allocate", type: "verb", meaning: "to give money, time or resources to a purpose", ar: "يخصّص", example: "More funds were allocated to rural schools." },
    { word: "appoint", type: "verb", meaning: "to choose someone officially for a position", ar: "يعيّن", example: "A new director was appointed last week." },
    { word: "delegate", type: "verb", meaning: "to pass tasks or authority to someone else", ar: "يفوّض", example: "Good managers delegate routine tasks." },
    { word: "implement", type: "verb", meaning: "to put a plan or decision into effect", ar: "ينفّذ", example: "The changes will be implemented in stages." },
    { word: "streamline", type: "verb", meaning: "to make a process simpler and more efficient", ar: "يبسّط الإجراءات", example: "Booking was streamlined, so queues shortened." },
    { word: "prioritise", type: "verb", meaning: "to deal with things in order of importance", ar: "يعطي أولوية", example: "Safety concerns were prioritised over speed." },
    { word: "escalate", type: "verb", meaning: "to make a problem more serious or refer it upward", ar: "يصعّد", example: "If the dispute escalated, deliveries would stop." },
    { word: "outsource", type: "verb", meaning: "to pay another company to do work for you", ar: "يعهد به لجهة خارجية", example: "Cleaning has been outsourced to a local firm." },
    { word: "suspend", type: "verb", meaning: "to stop something temporarily", ar: "يعلّق مؤقتًا", example: "The service was suspended during the storm." },
    { word: "terminate", type: "verb", meaning: "to end something, such as a contract or employment", ar: "يفسخ / ينهي", example: "His contract was terminated with immediate effect." },
    { word: "reimburse", type: "verb", meaning: "to pay someone back for money they have spent", ar: "يعوّض النفقات", example: "Staff will be reimbursed for travel costs." },
    { word: "monitor", type: "verb", meaning: "to watch and check something regularly", ar: "يراقب", example: "Air quality is monitored every hour." },
    { word: "acquire", type: "verb", meaning: "to obtain or take over something, often a company", ar: "يستحوذ على", example: "The start-up was acquired by a larger rival." },
    { word: "attribute", type: "verb", meaning: "to say that something is caused by something else", ar: "ينسب إلى", example: "The dip was attributed to rising fuel prices." },
    { word: "object", type: "verb", meaning: "to express disagreement with or disapproval of something", ar: "يعترض", example: "Several councillors objected to the plan." },
    { word: "feasible", type: "adjective", meaning: "possible to do easily or conveniently", ar: "قابل للتحقيق", example: "Is the timeline feasible if we hire help?" },
    { word: "viable", type: "adjective", meaning: "able to work successfully, especially commercially", ar: "مجدٍ", example: "Without subsidy, the route isn't viable." },
    { word: "unprecedented", type: "adjective", meaning: "never having happened before", ar: "غير مسبوق", example: "Demand was unprecedented, so the site crashed." },
    { word: "substantial", type: "adjective", meaning: "large in amount, size or importance", ar: "كبير", example: "A substantial discount was offered to early buyers." },
    { word: "widespread", type: "adjective", meaning: "existing in many places or among many people", ar: "واسع الانتشار", example: "The practice is widespread in the industry." },
    { word: "stringent", type: "adjective", meaning: "strict and demanding full obedience", ar: "صارم", example: "Stringent checks are carried out before export." },
    { word: "mandatory", type: "adjective", meaning: "required by a rule or law", ar: "إلزامي", example: "The briefing is mandatory for all new staff." },
    { word: "ambiguous", type: "adjective", meaning: "having more than one possible meaning", ar: "غامض", example: "The clause was criticised as ambiguous." },
    { word: "controversial", type: "adjective", meaning: "causing a lot of public disagreement", ar: "مثير للجدل", example: "It was argued that the ban was too controversial." },
    { word: "drastic", type: "adjective", meaning: "extreme and having a major effect", ar: "جذري", example: "He warned that drastic cuts would follow." },
    { word: "bring about", type: "phrasal verb", meaning: "to make something happen", ar: "يُحدث", example: "The reform brought about real change." },
    { word: "carry out", type: "phrasal verb", meaning: "to perform or complete a task or promise", ar: "ينفّذ", example: "Repairs were carried out overnight." },
    { word: "cut down on", type: "phrasal verb", meaning: "to reduce the amount of something", ar: "يقلل من", example: "If I cut down on coffee, I'd sleep better." },
    { word: "keep up with", type: "phrasal verb", meaning: "to move or progress as fast as someone or something", ar: "يواكب", example: "He struggled to keep up with the syllabus." },
    { word: "look into", type: "phrasal verb", meaning: "to investigate a matter", ar: "يدرس / يحقق في", example: "The complaint is being looked into." },
    { word: "put forward", type: "phrasal verb", meaning: "to offer an idea or proposal for discussion", ar: "يطرح", example: "A compromise was put forward on Monday." },
    { word: "rule out", type: "phrasal verb", meaning: "to decide that something is impossible or unsuitable", ar: "يستبعد", example: "A strike hasn't been ruled out." },
    { word: "stand out", type: "phrasal verb", meaning: "to be clearly better or more noticeable than others", ar: "يتميّز", example: "Her application stood out from hundreds." },
    { word: "take on", type: "phrasal verb", meaning: "to accept a task, responsibility or extra staff", ar: "يتولى", example: "Extra staff were taken on for the season." },
    { word: "account for", type: "phrasal verb", meaning: "to explain the cause or share of something", ar: "يفسّر", example: "Fuel accounts for a third of our costs." },
    { word: "call off", type: "phrasal verb", meaning: "to cancel a planned event", ar: "يلغي", example: "The match was called off because of fog." },
    { word: "follow up", type: "phrasal verb", meaning: "to check or act again on something earlier", ar: "يتابع", example: "He promised to follow up with a written summary." },
    { word: "raise awareness", type: "collocation", meaning: "to increase public knowledge of an issue", ar: "يرفع الوعي", example: "A campaign was launched to raise awareness of dementia." },
    { word: "heavy investment", type: "collocation", meaning: "a very large amount of money put into something", ar: "استثمار ضخم", example: "Heavy investment in rail was promised before the election." },
    { word: "take measures", type: "collocation", meaning: "to act in order to deal with a problem", ar: "يتخذ إجراءات", example: "Firm measures were taken against spam callers." },
    { word: "strike a balance", type: "collocation", meaning: "to find a fair middle point between two demands", ar: "يحقق توازنًا", example: "A balance was struck between cost and quality." },
    { word: "to some extent", type: "phrase", meaning: "partly, but not completely", ar: "إلى حد ما", example: "To some extent, the critics were proved right." },
    { word: "arguably", type: "adverb", meaning: "used when stating an opinion that can be defended", ar: "يمكن القول إن", example: "It is arguably the best café in Leeds." },
    { word: "on the whole", type: "phrase", meaning: "taking everything into account", ar: "على العموم", example: "On the whole, the feedback was positive." },
    { word: "broadly speaking", type: "phrase", meaning: "in a general, not exact, sense", ar: "بصفة عامة", example: "Broadly speaking, costs are rising faster than wages." },
    { word: "in the long run", type: "phrase", meaning: "over a long period of time", ar: "على المدى الطويل", example: "In the long run, training saves money." },
    { word: "it remains to be seen", type: "phrase", meaning: "used to say a result is still unknown", ar: "يبقى أن نرى", example: "It remains to be seen whether the merger succeeds." },
    { word: "provided that", type: "connector", meaning: "only if; on the condition that", ar: "بشرط أن", example: "We'll proceed, provided that the board approves the budget." },
    { word: "in terms of", type: "phrase", meaning: "with regard to a particular aspect", ar: "من حيث", example: "In terms of value, the second option wins." },
    { word: "as long as", type: "connector", meaning: "on the condition that; if", ar: "ما دام", example: "As long as demand holds, no jobs will be cut." },
    { word: "by and large", type: "adverb", meaning: "in general, with small exceptions", ar: "إجمالًا", example: "By and large, the rollout went smoothly." },
  ],
  "C1": [
    { word: "underpin", type: "verb", meaning: "to support or form the basis of something", ar: "يشكّل الأساس", example: "It is trust that underpins every long partnership." },
    { word: "underscore", type: "verb", meaning: "to stress the importance of something by drawing attention to it", ar: "يشدد على", example: "Not once did he underscore his own role in the rescue." },
    { word: "bolster", type: "verb", meaning: "to strengthen or prop up something", ar: "يقوّي", example: "Rarely has a budget so clearly bolstered small firms." },
    { word: "curtail", type: "verb", meaning: "to cut something short or reduce it", ar: "يقلّص", example: "Were the grant cut, tours would be curtailed." },
    { word: "deter", type: "verb", meaning: "to discourage someone from acting by making them fear consequences", ar: "يردع", example: "Nothing would deter her from appealing the verdict." },
    { word: "exacerbate", type: "verb", meaning: "to make a problem or feeling worse", ar: "يفاقم", example: "Not only did the strike delay freight; it exacerbated fuel shortages." },
    { word: "impede", type: "verb", meaning: "to slow or block the progress of something", ar: "يعيق", example: "Such rules, however well-meant, impede innovation." },
    { word: "preclude", type: "verb", meaning: "to make something impossible in advance", ar: "يحول دون", example: "A signed waiver precludes any further claims." },
    { word: "rebut", type: "verb", meaning: "to counter a claim with argument or evidence", ar: "يفنّد", example: "It was the data, not rhetoric, that rebutted the claim." },
    { word: "concede", type: "verb", meaning: "to accept, often grudgingly, that something is true", ar: "يُقرّ", example: "Concede the point gracefully, and the room will warm to you." },
    { word: "stipulate", type: "verb", meaning: "to state a condition clearly as a requirement", ar: "ينصّ على", example: "The contract stipulates that notice be given in writing." },
    { word: "redress", type: "verb", meaning: "to put right a wrong or imbalance", ar: "يعالج / يصحّح", example: "Only an independent review can redress this injustice." },
    { word: "spearhead", type: "verb", meaning: "to lead an attack, campaign or initiative", ar: "يقود (مبادرة)", example: "It was Dr Okafor who spearheaded the vaccine trial." },
    { word: "overhaul", type: "verb", meaning: "to examine and repair something thoroughly, changing it greatly", ar: "يعيد هيكلته", example: "Had the system been overhauled sooner, the backlog would be smaller." },
    { word: "curb", type: "verb", meaning: "to restrain or keep something within limits", ar: "يكبح", example: "Only by capping emissions can cities curb warming." },
    { word: "spur", type: "verb", meaning: "to prompt or incite action", ar: "يحفّز", example: "What spurred the reform was public outrage." },
    { word: "harness", type: "verb", meaning: "to put a resource or force to productive use", ar: "يوظّف (قوة)", example: "The scheme harnesses tidal power without harming birds." },
    { word: "entail", type: "verb", meaning: "to involve necessarily as a consequence", ar: "يستلزم", example: "Such autonomy entails accountability, however unwelcome." },
    { word: "jeopardise", type: "verb", meaning: "to put at risk of harm or failure", ar: "يعرّض للخطر", example: "Not a single clause should be allowed to jeopardise the deal." },
    { word: "oblige", type: "verb", meaning: "to bind someone by law, duty or circumstance", ar: "يُلزم", example: "Members are obliged to declare any conflict of interest." },
    { word: "waive", type: "verb", meaning: "to give up a right or requirement voluntarily", ar: "يتنازل عن", example: "The fee was waived for students from partner universities." },
    { word: "withstand", type: "verb", meaning: "to endure force or criticism without yielding", ar: "يصمد أمام", example: "Few start-ups could withstand such pressure." },
    { word: "attain", type: "verb", meaning: "to reach or achieve after effort", ar: "يبلغ / يحقق", example: "Only with sustained practice is fluency attained." },
    { word: "envisage", type: "verb", meaning: "to picture or expect something in the future", ar: "يتصوّر", example: "Little did they envisage how popular the scheme would prove." },
    { word: "elicit", type: "verb", meaning: "to draw out a response, fact or reaction", ar: "يستخلص", example: "It was the open question that elicited the richest answers." },
    { word: "allude", type: "verb", meaning: "to mention something indirectly", ar: "يلمّح إلى", example: "She alluded to earlier failures without naming anyone." },
    { word: "comprise", type: "verb", meaning: "to consist of or contain the listed parts", ar: "يضمّ", example: "The panel comprises academics and practitioners." },
    { word: "denote", type: "verb", meaning: "to be the sign or symbol of something", ar: "يدلّ على", example: "In the chart, a dotted line denotes projected figures." },
    { word: "encompass", type: "verb", meaning: "to cover or include a wide range", ar: "يشمل", example: "The remit encompasses training, audit and outreach." },
    { word: "exemplify", type: "verb", meaning: "to serve as a typical example of", ar: "يجسّد", example: "Few firms exemplify ethical trading as this one does." },
    { word: "conducive", type: "adjective", meaning: "making a result more likely to happen", ar: "مواتٍ", example: "Quiet corners are conducive to deep reading." },
    { word: "salient", type: "adjective", meaning: "most noticeable and important", ar: "بارز", example: "The most salient point, though, went unmentioned." },
    { word: "pertinent", type: "adjective", meaning: "directly relevant to the matter at hand", ar: "وثيق الصلة", example: "Her remarks were pertinent, if somewhat blunt." },
    { word: "tangible", type: "adjective", meaning: "real and able to be measured or touched", ar: "ملموس", example: "Not until autumn did we see tangible results." },
    { word: "disparate", type: "adjective", meaning: "very different from each other in kind", ar: "متباين", example: "The anthology weaves together disparate voices." },
    { word: "tentative", type: "adjective", meaning: "not certain or fixed; cautious", ar: "مبدئي", example: "The findings remain tentative until replication." },
    { word: "provisional", type: "adjective", meaning: "arranged for now, likely to change later", ar: "مؤقت", example: "The date is provisional, subject to board approval." },
    { word: "impartial", type: "adjective", meaning: "treating all sides equally and fairly", ar: "محايد", example: "Only an impartial panel could command public trust." },
    { word: "empirical", type: "adjective", meaning: "based on observation and experiment rather than theory", ar: "تجريبي", example: "It is empirical evidence, not intuition, that settled the debate." },
    { word: "anecdotal", type: "adjective", meaning: "based on personal stories rather than systematic data", ar: "قائم على روايات فردية", example: "Much of the praise, however, is anecdotal." },
    { word: "cogent", type: "adjective", meaning: "clear, logical and convincing", ar: "محكم ومقنع", example: "The brief was cogent; the rebuttal even more so." },
    { word: "lucid", type: "adjective", meaning: "expressed clearly and easy to understand", ar: "جليّ", example: "Never has a textbook explained tenses so lucidly." },
    { word: "astute", type: "adjective", meaning: "quick to notice and understand things", ar: "فطن", example: "An astute observer would spot the flaw at once." },
    { word: "prudent", type: "adjective", meaning: "acting with care and thought for the future", ar: "حصيف", example: "It would be prudent to hedge the currency exposure." },
    { word: "innocuous", type: "adjective", meaning: "completely harmless", ar: "غير ضار", example: "The remark seemed innocuous, yet tempers flared." },
    { word: "adverse", type: "adjective", meaning: "unfavourable and likely to cause harm", ar: "غير مؤاتٍ", example: "Were the reaction adverse, we would revisit the wording." },
    { word: "detrimental", type: "adjective", meaning: "causing damage or harm", ar: "ضار", example: "The ruling is detrimental to smaller publishers." },
    { word: "paramount", type: "adjective", meaning: "more important than anything else", ar: "في غاية الأهمية", example: "What is paramount is that no data be lost." },
    { word: "intrinsic", type: "adjective", meaning: "belonging naturally to the essential nature of something", ar: "جوهري", example: "Risk, she argued, is intrinsic to research." },
    { word: "implicit", type: "adjective", meaning: "suggested without being stated directly", ar: "ضمني", example: "Implicit in the proposal is a cut to overtime." },
    { word: "ramification", type: "noun", meaning: "a complicated consequence spreading from an action or decision", ar: "تداعيات", example: "Not everyone had grasped the ramifications of the ruling." },
    { word: "constraint", type: "noun", meaning: "a limit that restricts what is possible", ar: "قيد", example: "Budget constraints, however tight, rarely excuse poor design." },
    { word: "paradigm", type: "noun", meaning: "a standard model or framework of thinking", ar: "نموذج فكري", example: "The discovery forced a paradigm shift in cosmology." },
    { word: "attainment", type: "noun", meaning: "the act of reaching a level, or something achieved", ar: "إنجاز", example: "Reading attainment rose markedly across the cohort." },
    { word: "cohort", type: "noun", meaning: "a group sharing a defining characteristic, such as age", ar: "فئة متشابهة", example: "The 2020 cohort graduated under exceptional conditions." },
    { word: "surge", type: "noun", meaning: "a sudden powerful increase", ar: "ارتفاع مفاجئ", example: "Scarcely had the doors opened when a surge of visitors arrived." },
    { word: "momentum", type: "noun", meaning: "the force that keeps progress building", ar: "زخم", example: "The campaign is gaining momentum, thanks largely to volunteers." },
    { word: "threshold", type: "noun", meaning: "the point at which something begins or changes", ar: "عتبة", example: "Once the noise crosses a threshold, complaints follow." },
    { word: "expertise", type: "noun", meaning: "specialist skill or knowledge in a field", ar: "خبرة متخصصة", example: "It was her legal expertise that carried the negotiation." },
    { word: "integrity", type: "noun", meaning: "steadfast honesty and soundness of principle", ar: "نزاهة", example: "Seldom does ambition sit so comfortably with integrity." },
    { word: "credibility", type: "noun", meaning: "the quality of being believed or trusted", ar: "مصداقية", example: "The leak cost the ministry much of its credibility." },
    { word: "shortfall", type: "noun", meaning: "the amount by which something falls short", ar: "عجز", example: "Were the shortfall left unaddressed, services would suffer." },
    { word: "surplus", type: "noun", meaning: "the amount left over beyond what is needed", ar: "فائض", example: "The surplus was quietly redirected to reserves." },
    { word: "benchmark", type: "noun", meaning: "a reference point against which things are measured", ar: "مرجع للمقارنة", example: "The scheme set a benchmark that others now follow." },
    { word: "milestone", type: "noun", meaning: "a significant stage in progress or development", ar: "إنجاز مرحلي", example: "Little noticed was the milestone buried in the report." },
    { word: "backdrop", type: "noun", meaning: "the setting or background conditions for events", ar: "خلفية", example: "Against a backdrop of strikes, the pay deal emerged." },
    { word: "pitfall", type: "noun", meaning: "a hidden danger or difficulty", ar: "فخ خفي", example: "The seminar steers founders around common pitfalls." },
    { word: "bottleneck", type: "noun", meaning: "a point of congestion that slows a whole process", ar: "عنق زجاجة", example: "It is customs, not ports, that creates the bottleneck." },
    { word: "upheaval", type: "noun", meaning: "violent or disruptive change", ar: "اضطراب كبير", example: "Whatever the upheaval, service to patients never stopped." },
    { word: "advent", type: "noun", meaning: "the arrival or introduction of something important", ar: "ظهور", example: "With the advent of streaming, schedules lost their grip." },
    { word: "notably", type: "adverb", meaning: "especially or most significantly", ar: "بصفة خاصة", example: "The draft improved, notably in its treatment of consent." },
    { word: "markedly", type: "adverb", meaning: "to a noticeable degree", ar: "بدرجة ملحوظة", example: "Attendance fell markedly after the fee change." },
    { word: "presumably", type: "adverb", meaning: "used when concluding from what is known", ar: "على الأغلب", example: "Presumably, the figures exclude overtime." },
    { word: "ostensibly", type: "adverb", meaning: "apparently, but perhaps not in reality", ar: "ظاهريًا", example: "The trip was ostensibly a holiday; really it was research." },
    { word: "conversely", type: "connector", meaning: "introducing the opposite of what was said", ar: "في المقابل", example: "Demand is robust; conversely, supply is fragile." },
    { word: "accordingly", type: "connector", meaning: "in a way that suits what has been said or done", ar: "وفقًا لذلك", example: "The verdict was overturned, and the sentence amended accordingly." },
    { word: "subsequently", type: "connector", meaning: "afterwards, following something in time", ar: "لاحقًا", example: "He resigned, and was subsequently charged." },
    { word: "hence", type: "connector", meaning: "for this reason", ar: "ومن ثمّ", example: "The runway floods; hence the diverted flights." },
    { word: "thereby", type: "connector", meaning: "by that action or means", ar: "وبذلك", example: "Prices rose, thereby eroding the discount." },
    { word: "whereby", type: "connector", meaning: "by which, referring to an agreement or system", ar: "بموجبه", example: "They signed a deal whereby royalties would be shared." },
    { word: "nonetheless", type: "connector", meaning: "in spite of that", ar: "ومع هذا", example: "The odds were poor; they pressed on nonetheless." },
    { word: "albeit", type: "connector", meaning: "although; even if", ar: "وإن كان", example: "The plan succeeded, albeit narrowly." },
    { word: "that said", type: "phrase", meaning: "used to admit a contrasting point after a statement", ar: "مع كل ذلك", example: "The results are promising; that said, the sample is small." },
    { word: "be that as it may", type: "phrase", meaning: "used to accept a point, then insist on yours", ar: "مهما يكن من أمر", example: "Be that as it may, the deadline stands." },
    { word: "in light of", type: "phrase", meaning: "considering new information or events", ar: "في ضوء", example: "In light of the audit, two clauses were rewritten." },
    { word: "with regard to", type: "phrase", meaning: "concerning or about a particular matter", ar: "بشأن", example: "With regard to refunds, the policy is unchanged." },
    { word: "at the expense of", type: "phrase", meaning: "causing harm or loss to something else", ar: "على حساب", example: "Speed was won, but at the expense of accuracy." },
    { word: "in tandem with", type: "phrase", meaning: "together with, at the same pace as", ar: "بالتوازي مع", example: "The app was launched in tandem with the handbook." },
    { word: "by virtue of", type: "phrase", meaning: "because of, by reason of", ar: "بحكم", example: "By virtue of seniority, she chairs the committee." },
    { word: "for the sake of", type: "phrase", meaning: "for the benefit or purpose of", ar: "من أجل", example: "For the sake of clarity, the jargon was dropped." },
    { word: "at the outset", type: "phrase", meaning: "at the very beginning", ar: "في البداية", example: "At the outset, let me declare an interest." },
    { word: "not least", type: "phrase", meaning: "used to add an especially important reason", ar: "ولا سيما", example: "The trial matters, not least because it is reproducible." },
    { word: "give rise to", type: "phrase", meaning: "to cause something to appear or happen", ar: "يُولّد", example: "It was the merger that gave rise to the complaint." },
    { word: "get to grips with", type: "phrase", meaning: "to begin to deal seriously with something hard", ar: "يتصدى له بجدية", example: "Only now is the industry getting to grips with AI ethics." },
    { word: "single out", type: "phrase", meaning: "to choose one person or thing for special attention", ar: "ينتقي", example: "No single author was singled out for blame." },
    { word: "dwell on", type: "phrase", meaning: "to spend too long thinking or talking about something", ar: "يطيل الحديث عن", example: "Dwell on failures too long, and momentum drains." },
    { word: "touch on", type: "phrase", meaning: "to mention a subject briefly", ar: "يتطرق بإيجاز", example: "The lecture touched on ethics, though briefly." },
    { word: "pave the way for", type: "phrase", meaning: "to create conditions that make something possible", ar: "يمهّد الطريق لـ", example: "The pilot paved the way for national rollout." },
    { word: "take issue with", type: "phrase", meaning: "to disagree strongly with something said", ar: "يعترض على", example: "It was the sample size that reviewers took issue with." },
    { word: "align with", type: "phrase", meaning: "to bring into agreement or line with", ar: "يتوافق مع", example: "Were prices aligned with costs, margins would improve." },
  ],
  "C2": [
    { word: "a blessing in disguise", type: "idiom", meaning: "something that seems bad at first but proves beneficial", ar: "نعمة مقنّعة", example: "Losing that contract was a blessing in disguise, as it turned out." },
    { word: "the elephant in the room", type: "idiom", meaning: "an obvious problem everyone avoids mentioning", ar: "مشكلة واضحة يتجاهلها الجميع", example: "Nobody mentioned pay — the elephant in the room, of course." },
    { word: "bite the bullet", type: "idiom", meaning: "to force yourself to do something very unpleasant", ar: "يتحمّل أمرًا مؤلمًا بشجاعة", example: "She bit the bullet and apologised, though it galled her." },
    { word: "cut corners", type: "idiom", meaning: "to do something poorly in order to save time or money", ar: "يختصر الطريق على حساب الجودة", example: "They cut corners on training, and the audits, unsurprisingly, caught up with them." },
    { word: "hit the nail on the head", type: "idiom", meaning: "to describe a situation or problem exactly", ar: "يصيب الهدف تمامًا", example: "Her review hit the nail on the head; the novel sags in the middle." },
    { word: "let sleeping dogs lie", type: "idiom", meaning: "to avoid restarting an old quarrel", ar: "يترك الأمر هادئًا ولا يفتح الخلاف القديم", example: "I would let sleeping dogs lie if I were you; the file is closed." },
    { word: "make ends meet", type: "idiom", meaning: "to have just enough money for basic living", ar: "يعادل بين دخله ومصروفاته", example: "Even on two salaries, they barely make ends meet — such is London." },
    { word: "once in a blue moon", type: "idiom", meaning: "very rarely; almost never", ar: "نادرًا جدًا", example: "He answers emails once in a blue moon, and only under duress." },
    { word: "spill the beans", type: "idiom", meaning: "to reveal a secret carelessly or suddenly", ar: "يفشي السر", example: "Hardly had the toast ended when someone spilled the beans." },
    { word: "take something with a pinch of salt", type: "idiom", meaning: "to doubt how true a statement is", ar: "يتعامل به مع تحفظ", example: "Take his forecasts with a pinch of salt; he said that last year, too." },
    { word: "the last straw", type: "idiom", meaning: "the final small burden that makes patience collapse", ar: "القشة التي قصمت ظهر البعير", example: "The delayed refund was the last straw, and she closed the account." },
    { word: "throw in the towel", type: "idiom", meaning: "to admit defeat and stop trying", ar: "يستسلم", example: "Most editors would have thrown in the towel; she merely grinned." },
    { word: "a storm in a teacup", type: "idiom", meaning: "great fuss about something trivial", ar: "ضجة لا أساس لها", example: "The crisis proved a storm in a teacup, as sensible people had predicted." },
    { word: "burn the midnight oil", type: "idiom", meaning: "to work or study late into the night", ar: "يسهر ليلًا في العمل", example: "By the time we were burning the midnight oil, the deadline had already passed." },
    { word: "on the back foot", type: "idiom", meaning: "in a defensive, losing position", ar: "في موقف دفاعي", example: "Put on the back foot by the evidence, the spokesman changed tack." },
    { word: "off the beaten track", type: "idiom", meaning: "far from the places most people go", ar: "في مكان نائي", example: "The inn, tucked well off the beaten track, was all the better for it." },
    { word: "strike a chord", type: "idiom", meaning: "to sound true or touch people emotionally", ar: "يجد صدى", example: "Her speech struck a chord, though she claimed it was improvised." },
    { word: "the lion's share", type: "idiom", meaning: "by far the largest part of something", ar: "النصيب الأكبر", example: "The lion's share, as ever, went to the consultants." },
    { word: "turn a blind eye", type: "idiom", meaning: "to pretend not to see something wrong", ar: "يغض الطرف", example: "The regulator knew, or claimed to; either way, it turned a blind eye." },
    { word: "read between the lines", type: "idiom", meaning: "to find the meaning hidden in the actual words", ar: "يقرأ ما بين السطور", example: "Read between the lines of the memo, and the merger is already decided." },
    { word: "add fuel to the fire", type: "idiom", meaning: "to make a quarrel or crisis worse", ar: "يزيد النار اشتعالًا", example: "Rather than calm things, his reply merely added fuel to the fire." },
    { word: "back to square one", type: "idiom", meaning: "forced to start again from the beginning", ar: "العودة إلى نقطة الصفر", example: "With the licence revoked, we were back to square one, just as the sceptics foresaw." },
    { word: "beat about the bush", type: "idiom", meaning: "to avoid the point with extra words", ar: "يلفّ ويدور", example: "Stop beating about the bush; tell me whether the offer stands." },
    { word: "open a can of worms", type: "idiom", meaning: "to start a problem that breeds many more", ar: "يفتح قضية معقدة", example: "Ask about the pension scheme, and you open a can of worms." },
    { word: "ephemeral", type: "adjective", meaning: "lasting a very short time", ar: "زائل", example: "Fame, as the poet had it, is ephemeral; print is less forgiving." },
    { word: "ubiquitous", type: "adjective", meaning: "seeming to be present everywhere at once", ar: "منتشر في كل مكان", example: "So ubiquitous has the phrase become that it now means nothing." },
    { word: "quintessential", type: "adjective", meaning: "being the most perfect, typical example of its kind", ar: "نموذجي بامتياز", example: "The cottage is the quintessential English retreat, roses and rain included." },
    { word: "esoteric", type: "adjective", meaning: "intended for or understood by only a small, learned circle", ar: "يقتصر على الخواص", example: "The footnote was so esoteric that only the examiner appreciated it." },
    { word: "opaque", type: "adjective", meaning: "impossible to see through, literally or figuratively", ar: "غير شفاف", example: "The clause was deliberately opaque, which told its own story." },
    { word: "pernicious", type: "adjective", meaning: "harmful in a gradual, insidious way", ar: "خبيث", example: "More pernicious than outright censorship is the quiet trimming of budgets." },
    { word: "surreptitious", type: "adjective", meaning: "done secretly so as to avoid notice", ar: "بخلسة", example: "He took one surreptitious glance at his notes, believing nobody had noticed." },
    { word: "clandestine", type: "adjective", meaning: "done in secret, usually for illicit reasons", ar: "سري", example: "The negotiations, ostensibly about trade, had a clandestine second agenda." },
    { word: "flagrant", type: "adjective", meaning: "shockingly obvious and deliberate", ar: "صارخ", example: "The breach was flagrant; even the firm's own lawyers winced." },
    { word: "egregious", type: "adjective", meaning: "outstandingly bad, beyond ordinary faults", ar: "فادح", example: "Of all the errors, that was the most egregious, and the least acknowledged." },
    { word: "mercurial", type: "adjective", meaning: "changing mood or behaviour unpredictably", ar: "متقلّب المزاج", example: "The conductor, mercurial as ever, stormed out mid-rehearsal, then sent flowers." },
    { word: "effusive", type: "adjective", meaning: "expressing feelings in a gushing, unrestrained way", ar: "مفيض بالمشاعر", example: "Her review was so effusive that we suspected a family connection." },
    { word: "laconic", type: "adjective", meaning: "using very few words", ar: "قليل الكلام", example: "Could be worse, came the laconic verdict — high praise, by his standards." },
    { word: "reticent", type: "adjective", meaning: "unwilling to reveal thoughts or feelings", ar: "متحفّظ في الكلام", example: "Ever reticent about money, he simply called the sum adequate." },
    { word: "imperious", type: "adjective", meaning: "arrogantly commanding, expecting obedience", ar: "متغطرس", example: "One imperious wave of her hand, and the debate was over." },
    { word: "obsequious", type: "adjective", meaning: "servilely eager to please or flatter", ar: "متملق متذلّل", example: "The obsequious applause only sharpened her suspicion of him." },
    { word: "voracious", type: "adjective", meaning: "devouring great amounts, of food or information", ar: "نهم", example: "A voracious reader, she devoured the archive in a fortnight." },
    { word: "insatiable", type: "adjective", meaning: "impossible to satisfy", ar: "لا يُشبع", example: "The public's insatiable appetite for scandal doomed the reform." },
    { word: "inexorable", type: "adjective", meaning: "impossible to stop or prevent once under way", ar: "لا هوادة فيه", example: "The tide, inexorable as ever, undid the sandcastle in minutes." },
    { word: "rampant", type: "adjective", meaning: "spreading unchecked, usually something unwelcome", ar: "منتشر بلا ضبط", example: "Rumour ran rampant, as rumour will, until the statement quelled it." },
    { word: "rife", type: "adjective", meaning: "abundant in a place, especially something undesirable", ar: "سائد على نحو سيئ", example: "Speculation was rife that the ship had already been sold." },
    { word: "poignant", type: "adjective", meaning: "touchingly sad or moving", ar: "موجع ومؤثر", example: "The final chapter, all the more poignant for its restraint, ends mid-sentence." },
    { word: "serendipity", type: "noun", meaning: "the luck of finding something good by accident", ar: "مصادفة سعيدة", example: "By pure serendipity, the misplaced letter solved the case." },
    { word: "debacle", type: "noun", meaning: "a sudden, humiliating collapse or failure", ar: "انهيار فاضح", example: "The launch was a debacle of the first order; even rivals were embarrassed for them." },
    { word: "quagmire", type: "noun", meaning: "a complicated situation with no easy way out", ar: "وضع عالق معقد", example: "One compromise led to another, and soon we were in a quagmire of our own digging." },
    { word: "equanimity", type: "noun", meaning: "evenness of temper under pressure", ar: "رباطة جأش", example: "She received the rejection with equanimity, having expected worse." },
    { word: "sycophant", type: "noun", meaning: "a flatterer who serves the powerful for gain", ar: "مُداهن متملق", example: "Surrounded by sycophants, the chairman mistook flattery for consensus." },
    { word: "charlatan", type: "noun", meaning: "a fraud who falsely claims skill or knowledge", ar: "نصّاب يدّعي العلم", example: "The charlatan, wisely, vanished before the results were published." },
    { word: "demagogue", type: "noun", meaning: "a leader who whips up crowds with reckless appeals", ar: "زعيم شعوذي", example: "The demagogue offered simple answers, and the queue of believers grew." },
    { word: "pundit", type: "noun", meaning: "an expert who offers opinions in the media", ar: "محلل إعلامي", example: "Every pundit predicted a landslide; the electorate disagreed." },
    { word: "polemic", type: "noun", meaning: "a forceful written attack on an opinion or practice", ar: "جدال حاد انحيازي", example: "His polemic against the museum went further than its target deserved." },
    { word: "diatribe", type: "noun", meaning: "a long, bitter outburst of criticism", ar: "هجوم لفظي عنيف", example: "The review read less like criticism than a diatribe, entertaining if unfair." },
    { word: "panacea", type: "noun", meaning: "an imagined remedy for every ill", ar: "دواء لكل داء", example: "Technology is no panacea, whatever the brochure implies." },
    { word: "dearth", type: "noun", meaning: "a severe shortage", ar: "شحّ", example: "The dearth of tenants told the landlord more than any survey." },
    { word: "surfeit", type: "noun", meaning: "an excessive oversupply of something", ar: "إفراط مبالغ", example: "A surfeit of options, paradoxically, left the committee paralysed." },
    { word: "plethora", type: "noun", meaning: "a very large number, more than needed", ar: "كثرة مفرطة", example: "The report offered a plethora of reasons, none of them the real one." },
    { word: "implore", type: "verb", meaning: "to beg someone earnestly and desperately", ar: "يتوسّل", example: "She implored the board to reconsider, if only for appearances' sake." },
    { word: "cajole", type: "verb", meaning: "to persuade with flattery and gentle pressure", ar: "يستمال بالتملق", example: "He cajoled the creditor into a fortnight's grace, charm being his sole asset." },
    { word: "placate", type: "verb", meaning: "to soothe someone's anger by yielding", ar: "يهدّئ غضب", example: "The refund placated nobody, least of all the woman at the counter." },
    { word: "assuage", type: "verb", meaning: "to ease a pain, worry or hunger", ar: "يخفّف حدة", example: "No apology could assuage a loss like that." },
    { word: "exasperate", type: "verb", meaning: "to irritate someone beyond patience", ar: "يستفز غضبه", example: "Nothing, perhaps, exasperates an editor like a confident typo." },
    { word: "castigate", type: "verb", meaning: "to reprimand severely in public", ar: "يوبّخ بعنف", example: "The judge castigated the bank, whose lawyers nodded along." },
    { word: "reprimand", type: "verb", meaning: "to rebuke officially and formally", ar: "يؤدّب رسميًا", example: "He was reprimanded quietly, of course; the board disliked scenes." },
    { word: "admonish", type: "verb", meaning: "to warn or scold mildly but firmly", ar: "ينبه بنصح واعتاب", example: "She admonished the intern gently, which somehow stung more." },
    { word: "lament", type: "verb", meaning: "to mourn or express deep regret for", ar: "يندّب", example: "Old players lament the passing of the long format, as old players will." },
    { word: "bemoan", type: "verb", meaning: "to complain repeatedly about something", ar: "يتذمّر من", example: "Critics bemoan the sequel, then queue for it." },
    { word: "squander", type: "verb", meaning: "to waste money, time or chances recklessly", ar: "يبذّر", example: "Having squandered the advance, he wrote the sequel out of necessity." },
    { word: "glean", type: "verb", meaning: "to gather facts slowly from scattered sources", ar: "يجمع خلاصات متفرقة", example: "From three overheard sentences, the journalist gleaned the whole story." },
    { word: "wield", type: "verb", meaning: "to hold and exercise power or influence", ar: "يمسك بزمام", example: "Whoever wields the proxy votes wields the company." },
    { word: "flout", type: "verb", meaning: "to defy a rule openly and contemptuously", ar: "يتجاهل علنًا", example: "The firm flouted the ban openly, daring anyone to act." },
    { word: "hitherto", type: "adverb", meaning: "until this point in time", ar: "حتى الآن", example: "The hitherto unmarked grave was identified by the ring alone." },
    { word: "henceforth", type: "adverb", meaning: "from this moment on", ar: "من الآن فصاعدًا", example: "Henceforth, all complaints were to be logged and, presumably, ignored." },
    { word: "erstwhile", type: "adverb", meaning: "belonging to an earlier time; former", ar: "سابقًا", example: "His erstwhile ally now led the opposition against him." },
    { word: "inadvertently", type: "adverb", meaning: "without meaning to; by accident", ar: "دون قصد", example: "The email, sent inadvertently to the whole firm, ended the secrecy." },
    { word: "understatement", type: "noun", meaning: "deliberately making something seem less than it is", ar: "تقليل مقصود من أهمية الأمر", example: "Calling the storm brisk was understatement of a very British order." },
    { word: "hyperbole", type: "noun", meaning: "deliberate exaggeration for effect", ar: "مبالغة", example: "The trailer promised a masterpiece; hyperbole, as ever, came free." },
    { word: "euphemism", type: "noun", meaning: "a mild term standing in for a blunt or unpleasant one", ar: "تلطيف التسمية", example: "Streamlining proved a chilling euphemism for dismissal." },
    { word: "satire", type: "noun", meaning: "wit used to ridicule folly and vice", ar: "سخرية هجائية", example: "The satire cut deeper precisely because it smiled." },
    { word: "parody", type: "noun", meaning: "a comic imitation that exaggerates a style or work", ar: "تقليد ساخر", example: "So exact was the parody that the minister reportedly enjoyed it." },
    { word: "allegory", type: "noun", meaning: "a story carrying a hidden moral or political meaning", ar: "حكاية رمزية", example: "Read as allegory, the farmyard fable indicts every revolution." },
    { word: "juxtaposition", type: "noun", meaning: "placing contrasting elements side by side for effect", ar: "تقابل مقصود", example: "The juxtaposition of marble and corrugated iron is the exhibition's sharpest argument." },
    { word: "dichotomy", type: "noun", meaning: "a sharp division into two opposing parts", ar: "انقسام ثنائي", example: "The dichotomy between craft and art, she argued, is largely invented." },
    { word: "paradox", type: "noun", meaning: "a statement that defies logic yet proves true", ar: "مفارقة", example: "The paradox, of course, is that the shortcut costs more time than it saves." },
    { word: "cliché", type: "noun", meaning: "a phrase worn flat by overuse", ar: "عبارة مستهلكة", example: "Every speech leaned on some cliché about the journey, usually the same one." },
    { word: "to put it bluntly", type: "phrase", meaning: "said before an uncomfortably frank remark", ar: "بصراحة قاسية", example: "To put it bluntly, the prototype doesn't work." },
    { word: "so to speak", type: "phrase", meaning: "used to mark a phrase as figurative", ar: "إن صحّ التعبير", example: "The report opened doors, so to speak — mainly to the exit." },
    { word: "in no uncertain terms", type: "phrase", meaning: "in language leaving no room for doubt", ar: "بوضوح لا لبس فيه", example: "She made the deadline clear in no uncertain terms." },
    { word: "at the drop of a hat", type: "phrase", meaning: "instantly and without needing persuading", ar: "دون أدنى تردد", example: "He will argue syntax at the drop of a hat, even at weddings." },
    { word: "for good measure", type: "phrase", meaning: "as an extra beyond what is required", ar: "وزيادة عليه", example: "She checked the figures twice, and for good measure a third time." },
    { word: "needless to say", type: "phrase", meaning: "obviously; as any listener would expect", ar: "لا داعي للقول إن", example: "Needless to say, the projector failed during the demo." },
    { word: "when all is said and done", type: "phrase", meaning: "in the final analysis", ar: "في نهاية المطاف", example: "When all is said and done, the book sold, whatever the critics hoped." },
    { word: "par for the course", type: "phrase", meaning: "about as good or bad as usual, no surprise", ar: "أمر متوقع لا غرابة فيه", example: "Two leaks in the first week was par for the course with that roof." },
    { word: "curry favour", type: "idiom", meaning: "to court approval through flattery", ar: "يتملق كسبًا لمنفعة", example: "He flattered everyone senior, currying favour with a thoroughness that repelled." },
    { word: "get wind of", type: "idiom", meaning: "to hear news of something indirectly or before it is public", ar: "يطّلن على خبر ما", example: "The press got wind of the merger before the board had finished lunch." },
    { word: "bear fruit", type: "idiom", meaning: "to yield the desired result", ar: "يثمر", example: "The slow negotiations finally bore fruit, a week after the money ran out." },
    { word: "hold sway", type: "idiom", meaning: "to dominate opinion or events", ar: "يحوز النفوذ", example: "Even now, the old families hold sway over the county's quieter decisions." },
  ],
};
