/**
 * Vocabulary page band expansion (wave 28-a): Pre-A1 / A1 / A2 top-ups.
 * Additive bank for app/(app)/vocabulary — no existing page word is duplicated.
 * UK spelling throughout; ar = short MSA gloss for Arabic-speaking learners.
 */

export interface VocabPageWord {
  word: string;
  type: string; // "noun" | "verb" | "adjective" | "adverb" | "phrase" | "question word" | "number" etc.
  meaning: string; // clear simple English definition
  ar: string; // accurate natural Arabic translation (MSA, short)
  example: string; // natural UK-English example sentence
}

export const VOCAB_PAGE_EXPANSION_A: Record<string, VocabPageWord[]> = {
  "Pre-A1": [
    { word: "yes", type: "adverb", meaning: "a word you say to agree", ar: "نعم", example: "Yes, it is my book." },
    { word: "no", type: "adverb", meaning: "a word you say to refuse or disagree", ar: "لا", example: "No, thank you very much." },
    { word: "please", type: "adverb", meaning: "a polite word added when you ask for something", ar: "من فضلك", example: "Please open the door." },
    { word: "thank you", type: "phrase", meaning: "words you say to show you are grateful", ar: "شكراً", example: "Thank you for the gift." },
    { word: "sorry", type: "adjective", meaning: "a word you say when you make a mistake", ar: "آسف", example: "Sorry, I am late." },
    { word: "hello", type: "phrase", meaning: "a word you say when you meet someone", ar: "مرحباً", example: "Hello, my name is Omar." },
    { word: "goodbye", type: "phrase", meaning: "what you say when you leave someone", ar: "إلى اللقاء", example: "Goodbye, see you tomorrow." },
    { word: "help", type: "verb", meaning: "to give a person what they need to make something easier", ar: "يساعد", example: "Help me, please." },
    { word: "toilet", type: "noun", meaning: "a room where people pass body waste", ar: "مرحاض", example: "Where is the toilet, please?" },
    { word: "water", type: "noun", meaning: "the clear liquid that we drink", ar: "ماء", example: "I drink water every day." },
    { word: "one", type: "number", meaning: "the number 1", ar: "واحد", example: "I have one brother." },
    { word: "two", type: "number", meaning: "the number 2", ar: "اثنان", example: "I have two hands." },
    { word: "three", type: "number", meaning: "the number 3", ar: "ثلاثة", example: "The class starts at three." },
    { word: "four", type: "number", meaning: "the number 4", ar: "أربعة", example: "A table has four legs." },
    { word: "five", type: "number", meaning: "the number 5", ar: "خمسة", example: "My hand has five fingers." },
    { word: "six", type: "number", meaning: "the number 6", ar: "ستة", example: "There are six chairs." },
    { word: "seven", type: "number", meaning: "the number 7", ar: "سبعة", example: "A week has seven days." },
    { word: "eight", type: "number", meaning: "the number 8", ar: "ثمانية", example: "The shop opens at eight." },
    { word: "nine", type: "number", meaning: "the number 9", ar: "تسعة", example: "I have nine books." },
    { word: "ten", type: "number", meaning: "the number 10", ar: "عشرة", example: "I read ten pages." },
    { word: "red", type: "adjective", meaning: "the colour of blood or fire", ar: "أحمر", example: "The apple is red." },
    { word: "blue", type: "adjective", meaning: "the colour of a clear sky", ar: "أزرق", example: "The sky is blue." },
    { word: "green", type: "adjective", meaning: "the colour of grass and leaves", ar: "أخضر", example: "The grass is green." },
    { word: "yellow", type: "adjective", meaning: "the colour of lemons and the sun", ar: "أصفر", example: "The sun looks yellow." },
    { word: "black", type: "adjective", meaning: "the darkest colour, like night", ar: "أسود", example: "My bag is black." },
    { word: "white", type: "adjective", meaning: "the colour of snow and milk", ar: "أبيض", example: "The walls are white." },
    { word: "brown", type: "adjective", meaning: "the colour of earth or chocolate", ar: "بني", example: "The table is brown." },
    { word: "pink", type: "adjective", meaning: "a pale red colour", ar: "وردي", example: "Her dress is pink." },
    { word: "mother", type: "noun", meaning: "your female parent", ar: "أم", example: "My mother cooks dinner." },
    { word: "father", type: "noun", meaning: "your male parent", ar: "أب", example: "My father drives a car." },
    { word: "brother", type: "noun", meaning: "a boy or man with the same parents as you", ar: "أخ", example: "My brother is six." },
    { word: "sister", type: "noun", meaning: "a girl or woman with the same parents as you", ar: "أخت", example: "My sister is at home." },
    { word: "baby", type: "noun", meaning: "a very young child who cannot yet talk or walk", ar: "رضيع", example: "The baby is sleeping." },
    { word: "family", type: "noun", meaning: "parents and children together as a group", ar: "عائلة", example: "My family is big." },
    { word: "friend", type: "noun", meaning: "a person you like and enjoy spending time with", ar: "صديق", example: "Ali is my friend." },
    { word: "boy", type: "noun", meaning: "a young male person", ar: "ولد", example: "The boy likes football." },
    { word: "girl", type: "noun", meaning: "a young female person", ar: "بنت", example: "The girl sings a song." },
    { word: "name", type: "noun", meaning: "the word that a person or thing is called", ar: "اسم", example: "My name is Sara." },
    { word: "day", type: "noun", meaning: "a period of twenty-four hours", ar: "يوم", example: "I study every day." },
    { word: "Monday", type: "noun", meaning: "the first working day of the week", ar: "الاثنين", example: "We start school on Monday." },
    { word: "Tuesday", type: "noun", meaning: "the day after Monday", ar: "الثلاثاء", example: "I play football on Tuesday." },
    { word: "Wednesday", type: "noun", meaning: "the day after Tuesday", ar: "الأربعاء", example: "My birthday is on Wednesday." },
    { word: "Thursday", type: "noun", meaning: "the day after Wednesday", ar: "الخميس", example: "We visit Grandma on Thursday." },
    { word: "Friday", type: "noun", meaning: "the last working day of the week", ar: "الجمعة", example: "We rest on Friday." },
    { word: "Saturday", type: "noun", meaning: "the day after Friday", ar: "السبت", example: "I play on Saturday." },
    { word: "Sunday", type: "noun", meaning: "the day of rest at the end of the week", ar: "الأحد", example: "The family eats together on Sunday." },
    { word: "bread", type: "noun", meaning: "food made from flour and baked in an oven", ar: "خبز", example: "I eat bread and cheese." },
    { word: "rice", type: "noun", meaning: "small white or brown grains cooked in water", ar: "أرز", example: "We eat rice for lunch." },
    { word: "milk", type: "noun", meaning: "the white drink that comes from cows", ar: "حليب", example: "The baby drinks milk." },
    { word: "egg", type: "noun", meaning: "a round food with a shell, from a bird", ar: "بيضة", example: "I eat an egg for breakfast." },
    { word: "apple", type: "noun", meaning: "a round fruit with red or green skin", ar: "تفاحة", example: "I eat an apple every day." },
    { word: "banana", type: "noun", meaning: "a long curved yellow fruit", ar: "موزة", example: "The banana is yellow." },
    { word: "cheese", type: "noun", meaning: "a yellow or white food made from milk", ar: "جبن", example: "I put cheese on bread." },
    { word: "chicken", type: "noun", meaning: "a farm bird kept for its meat and eggs", ar: "دجاج", example: "We eat chicken on Friday." },
    { word: "orange", type: "noun", meaning: "a round sweet fruit with a thick skin", ar: "برتقال", example: "The orange is sweet." },
    { word: "tea", type: "noun", meaning: "a hot drink made from dried leaves", ar: "شاي", example: "My father drinks tea." },
    { word: "meat", type: "noun", meaning: "food from animals, such as beef or lamb", ar: "لحم", example: "We cook meat for lunch." },
    { word: "sugar", type: "noun", meaning: "sweet white grains added to drinks and cakes", ar: "سكر", example: "I put sugar in my tea." },
    { word: "juice", type: "noun", meaning: "a drink made from fruit", ar: "عصير", example: "I drink orange juice." },
    { word: "head", type: "noun", meaning: "the part of the body above the neck", ar: "رأس", example: "Touch your head, please." },
    { word: "hand", type: "noun", meaning: "the body part with five fingers", ar: "يد", example: "Raise your hand, please." },
    { word: "eye", type: "noun", meaning: "the body part you see with", ar: "عين", example: "I see with my eyes." },
    { word: "ear", type: "noun", meaning: "the body part you hear with", ar: "أذن", example: "I listen with my ears." },
    { word: "nose", type: "noun", meaning: "the body part you smell with", ar: "أنف", example: "The dog has a black nose." },
    { word: "mouth", type: "noun", meaning: "the body part you eat and speak with", ar: "فم", example: "Open your mouth, please." },
    { word: "foot", type: "noun", meaning: "the body part you stand and walk on", ar: "قدم", example: "I stand on one foot." },
    { word: "hair", type: "noun", meaning: "the soft threads that grow on your head", ar: "شعر", example: "Her hair is long and black." },
    { word: "book", type: "noun", meaning: "pages with words and pictures, fastened together to read", ar: "كتاب", example: "This is my book." },
    { word: "pen", type: "noun", meaning: "a tool for writing with ink", ar: "قلم", example: "The pen is on the desk." },
    { word: "pencil", type: "noun", meaning: "a wooden tool for writing or drawing", ar: "قلم رصاص", example: "I write with a pencil." },
    { word: "bag", type: "noun", meaning: "a container you carry things in", ar: "حقيبة", example: "This is my school bag." },
    { word: "desk", type: "noun", meaning: "a small table for one person to work or study at", ar: "مكتب", example: "My desk is clean." },
    { word: "chair", type: "noun", meaning: "a seat with a back and four legs", ar: "كرسي", example: "Sit on the chair, please." },
    { word: "door", type: "noun", meaning: "the part of a room that opens to let people in", ar: "باب", example: "Please close the door." },
    { word: "window", type: "noun", meaning: "glass in a wall that lets light and air inside", ar: "نافذة", example: "Open the window, please." },
    { word: "board", type: "noun", meaning: "a flat surface the teacher writes on", ar: "سبورة", example: "The teacher writes on the board." },
    { word: "ruler", type: "noun", meaning: "a flat tool for drawing straight lines", ar: "مسطرة", example: "I draw lines with a ruler." },
    { word: "eat", type: "verb", meaning: "to put food in your mouth and swallow it", ar: "يأكل", example: "We eat lunch at home." },
    { word: "drink", type: "verb", meaning: "to take liquid into your mouth and swallow it", ar: "يشرب", example: "Cats drink milk." },
    { word: "go", type: "verb", meaning: "to move or travel to another place", ar: "يذهب", example: "We go to school." },
    { word: "come", type: "verb", meaning: "to move towards the person speaking", ar: "يأتي", example: "Come here, please." },
    { word: "sit", type: "verb", meaning: "to lower your body onto a seat", ar: "يجلس", example: "Sit down, please." },
    { word: "stand", type: "verb", meaning: "to be upright on your feet", ar: "يقف", example: "Stand up, please." },
    { word: "open", type: "verb", meaning: "to make something no longer closed", ar: "يفتح", example: "Open your book, please." },
    { word: "close", type: "verb", meaning: "to shut a door, window or bag", ar: "يغلق", example: "Close the window, please." },
    { word: "look", type: "verb", meaning: "to turn your eyes towards something", ar: "ينظر", example: "Look at the board." },
    { word: "listen", type: "verb", meaning: "to pay attention to what you hear", ar: "يستمع", example: "Listen to the teacher." },
    { word: "read", type: "verb", meaning: "to understand written words", ar: "يقرأ", example: "I read at night." },
    { word: "write", type: "verb", meaning: "to make words with a pen or pencil", ar: "يكتب", example: "Write your name, please." },
    { word: "stop", type: "verb", meaning: "to no longer move or do something", ar: "يتوقف", example: "Stop here, please." },
    { word: "teacher", type: "noun", meaning: "a person who works in a school and helps you learn", ar: "معلم", example: "My teacher is very kind." },
    { word: "school", type: "noun", meaning: "a place where children learn", ar: "مدرسة", example: "I go to school by bus." },
    { word: "house", type: "noun", meaning: "a building where people live", ar: "بيت", example: "My house is small." },
    { word: "bed", type: "noun", meaning: "furniture you lie on to sleep", ar: "سرير", example: "I sleep in my bed." },
    { word: "big", type: "adjective", meaning: "large in size", ar: "كبير", example: "An elephant is big." },
    { word: "small", type: "adjective", meaning: "little in size", ar: "صغير", example: "A mouse is small." },
    { word: "hot", type: "adjective", meaning: "with a high temperature", ar: "حار", example: "The tea is hot." },
    { word: "cold", type: "adjective", meaning: "with a low temperature", ar: "بارد", example: "The milk is cold." },
    { word: "good", type: "adjective", meaning: "nice, right or of high quality", ar: "جيد", example: "This cake is very good." },
    { word: "hungry", type: "adjective", meaning: "feeling that you want food", ar: "جائع", example: "I am hungry, Mum." },
  ],
  A1: [
    { word: "park", type: "noun", meaning: "a public green space with trees and seats", ar: "حديقة عامة", example: "The children play in the park." },
    { word: "shop", type: "noun", meaning: "a building where you buy things", ar: "متجر", example: "I buy bread at the shop." },
    { word: "market", type: "noun", meaning: "an open place where people buy and sell food and goods", ar: "سوق", example: "We buy fruit at the market." },
    { word: "hospital", type: "noun", meaning: "a place where sick people get medical care", ar: "مستشفى", example: "The doctor works at the hospital." },
    { word: "bank", type: "noun", meaning: "a place that keeps money safe and lends money", ar: "بنك", example: "My mother works in a bank." },
    { word: "café", type: "noun", meaning: "a small place where you buy coffee and light food", ar: "مقهى", example: "We drink tea at the café." },
    { word: "restaurant", type: "noun", meaning: "a place where you order and eat meals", ar: "مطعم", example: "We eat dinner at a restaurant." },
    { word: "library", type: "noun", meaning: "a quiet place full of books people can read or borrow", ar: "مكتبة", example: "I read books in the library." },
    { word: "classroom", type: "noun", meaning: "a room in a school where lessons happen", ar: "فصل دراسي", example: "Our classroom has big windows." },
    { word: "road", type: "noun", meaning: "a long hard surface for cars and buses", ar: "طريق", example: "Our road is quiet at night." },
    { word: "garden", type: "noun", meaning: "an area with flowers and plants next to a house", ar: "حديقة المنزل", example: "Flowers grow in our garden." },
    { word: "flat", type: "noun", meaning: "a home on one floor of a bigger building", ar: "شقة", example: "Our flat has two bedrooms." },
    { word: "city", type: "noun", meaning: "a very large town", ar: "مدينة", example: "Cairo is a big city." },
    { word: "town", type: "noun", meaning: "a group of houses and shops, smaller than a city", ar: "بلدة", example: "My town is small and quiet." },
    { word: "beach", type: "noun", meaning: "a sandy or stony area by the sea", ar: "شاطئ", example: "We swim at the beach." },
    { word: "mosque", type: "noun", meaning: "a building where Muslims pray", ar: "مسجد", example: "The mosque is near our house." },
    { word: "post office", type: "noun", meaning: "a place where you send letters and parcels", ar: "مكتب بريد", example: "The post office opens at nine." },
    { word: "metro", type: "noun", meaning: "an electric train that runs under a city", ar: "مترو الأنفاق", example: "The metro is fast and cheap." },
    { word: "bus", type: "noun", meaning: "a large road vehicle that carries many people", ar: "أتوبيس", example: "I take the bus to school." },
    { word: "train", type: "noun", meaning: "a vehicle that runs on rails", ar: "قطار", example: "The train leaves at seven." },
    { word: "car", type: "noun", meaning: "a road vehicle with four wheels for a few people", ar: "سيارة", example: "Our car is very old." },
    { word: "taxi", type: "noun", meaning: "a car you pay to take you somewhere", ar: "تاكسي", example: "The taxi is outside." },
    { word: "bike", type: "noun", meaning: "a two-wheeled vehicle you pedal", ar: "دراجة", example: "I ride my bike every day." },
    { word: "plane", type: "noun", meaning: "a flying vehicle with wings and engines", ar: "طائرة", example: "The plane flies to Paris." },
    { word: "boat", type: "noun", meaning: "a small vessel that travels on water", ar: "قارب", example: "The boat sails on the river." },
    { word: "airport", type: "noun", meaning: "a place where planes take off and land", ar: "مطار", example: "The airport is far from here." },
    { word: "ticket", type: "noun", meaning: "a paper or phone pass that lets you travel or enter", ar: "تذكرة", example: "One ticket to the city, please." },
    { word: "walk", type: "verb", meaning: "to move on foot", ar: "يمشي", example: "I walk to the shop." },
    { word: "drive", type: "verb", meaning: "to control a car and make it move", ar: "يقود", example: "He drives a blue car." },
    { word: "sun", type: "noun", meaning: "the star that gives Earth light and heat", ar: "شمس", example: "The sun is very bright today." },
    { word: "rain", type: "noun", meaning: "water that falls from clouds", ar: "مطر", example: "I like the sound of rain." },
    { word: "cloud", type: "noun", meaning: "a white or grey shape floating in the sky", ar: "سحابة", example: "The sky is full of clouds." },
    { word: "wind", type: "noun", meaning: "moving air you can feel but not see", ar: "رياح", example: "The wind moves the leaves." },
    { word: "snow", type: "noun", meaning: "soft white flakes of ice that fall in winter", ar: "ثلج", example: "Snow falls in winter." },
    { word: "sunny", type: "adjective", meaning: "bright with a lot of light from the sun", ar: "مشمس", example: "It is sunny in July." },
    { word: "cloudy", type: "adjective", meaning: "with many clouds in the sky", ar: "غائم", example: "It is cloudy this morning." },
    { word: "windy", type: "adjective", meaning: "with a lot of moving air outside", ar: "عاصف", example: "It is windy at the beach." },
    { word: "warm", type: "adjective", meaning: "a little hot, in a pleasant way", ar: "دافئ", example: "The weather is warm in spring." },
    { word: "grey", type: "adjective", meaning: "the colour between black and white", ar: "رمادي", example: "The sky is grey today." },
    { word: "doctor", type: "noun", meaning: "a person who treats sick people", ar: "طبيب", example: "The doctor helps sick people." },
    { word: "nurse", type: "noun", meaning: "a person trained to care for sick people, often in a hospital", ar: "ممرضة", example: "The nurse works in a hospital." },
    { word: "driver", type: "noun", meaning: "a person whose job is to drive a bus, taxi or lorry", ar: "سائق", example: "The bus driver knows every road." },
    { word: "farmer", type: "noun", meaning: "a person who grows food and keeps animals on a farm", ar: "مزارع", example: "The farmer grows vegetables." },
    { word: "chef", type: "noun", meaning: "a person who cooks in a restaurant", ar: "طاهي", example: "The chef cooks special meals." },
    { word: "waiter", type: "noun", meaning: "a man who brings food and drinks to your table", ar: "نادل", example: "The waiter brings the menu." },
    { word: "engineer", type: "noun", meaning: "a person who designs and builds machines or structures", ar: "مهندس", example: "My brother is an engineer." },
    { word: "police", type: "noun", meaning: "the officers who keep people safe and stop crime", ar: "شرطة", example: "We call the police for help." },
    { word: "manager", type: "noun", meaning: "the person who is in charge of a shop or office", ar: "مدير", example: "The manager opens the shop." },
    { word: "shop assistant", type: "noun", meaning: "a person who serves customers in a shop", ar: "بائع", example: "The shop assistant helps me choose." },
    { word: "job", type: "noun", meaning: "the work you do regularly for money", ar: "وظيفة", example: "My mother has a new job." },
    { word: "wake up", type: "verb", meaning: "to stop sleeping and open your eyes", ar: "يستيقظ", example: "I wake up at six." },
    { word: "morning", type: "noun", meaning: "the time from sunrise until midday", ar: "صباح", example: "I read in the morning." },
    { word: "afternoon", type: "noun", meaning: "the time between midday and the evening", ar: "بعد الظهر", example: "We play football in the afternoon." },
    { word: "evening", type: "noun", meaning: "the time after the afternoon, before bed", ar: "مساء", example: "I watch TV in the evening." },
    { word: "night", type: "noun", meaning: "the dark time when people usually sleep", ar: "ليل", example: "The city is quiet at night." },
    { word: "breakfast", type: "noun", meaning: "the first meal of the day", ar: "فطور", example: "I eat breakfast at seven." },
    { word: "lunch", type: "noun", meaning: "the meal you eat around the middle of the day", ar: "غداء", example: "We have lunch at one." },
    { word: "dinner", type: "noun", meaning: "the main meal of the evening", ar: "عشاء", example: "We eat dinner at home." },
    { word: "sleep", type: "verb", meaning: "to rest with your eyes closed and mind quiet", ar: "ينام", example: "I sleep at ten o'clock." },
    { word: "wash", type: "verb", meaning: "to clean something with water and usually soap", ar: "يغسل", example: "I wash my hands before lunch." },
    { word: "brush", type: "verb", meaning: "to clean your teeth, usually in the morning and at night", ar: "ينظف أسنانه", example: "I brush my teeth every morning." },
    { word: "shower", type: "noun", meaning: "a device that sprays water over your body", ar: "دش", example: "She takes a quick shower." },
    { word: "favourite", type: "adjective", meaning: "the person or thing you like more than all others", ar: "مفضل", example: "Blue is my favourite colour." },
    { word: "free time", type: "phrase", meaning: "time when you have no work or lessons", ar: "وقت فراغ", example: "I read in my free time." },
    { word: "always", type: "adverb", meaning: "every time; all the time", ar: "دائماً", example: "I always say please." },
    { word: "never", type: "adverb", meaning: "at no time; not ever", ar: "أبداً", example: "He never eats meat." },
    { word: "today", type: "adverb", meaning: "this day", ar: "اليوم", example: "Today is my birthday." },
    { word: "tomorrow", type: "adverb", meaning: "the day after today", ar: "غداً", example: "I start school tomorrow." },
    { word: "weekend", type: "noun", meaning: "Saturday and Sunday, when most people do not work", ar: "عطلة نهاية الأسبوع", example: "We visit family at the weekend." },
    { word: "like", type: "verb", meaning: "to enjoy something or find it nice", ar: "يحب", example: "I like music very much." },
    { word: "love", type: "verb", meaning: "to like someone or something very much", ar: "يعشق", example: "I love my family." },
    { word: "enjoy", type: "verb", meaning: "to get pleasure from something", ar: "يستمتع", example: "We enjoy the weekend together." },
    { word: "want", type: "verb", meaning: "to wish to have or do something", ar: "يريد", example: "I want a glass of water." },
    { word: "need", type: "verb", meaning: "to have to have something", ar: "يحتاج", example: "I need a new school bag." },
    { word: "play", type: "verb", meaning: "to do things for fun, like games and sport", ar: "يلعب", example: "We play games after school." },
    { word: "watch", type: "verb", meaning: "to look at something for some time, like TV or a match", ar: "يشاهد", example: "I watch cartoons on Friday." },
    { word: "music", type: "noun", meaning: "sounds made by voices or instruments", ar: "موسيقى", example: "This music makes me happy." },
    { word: "happy", type: "adjective", meaning: "feeling pleased and glad", ar: "سعيد", example: "My friend is happy today." },
    { word: "sad", type: "adjective", meaning: "feeling unhappy", ar: "حزين", example: "Why is the boy sad?" },
    { word: "where", type: "question word", meaning: "used to ask about a place", ar: "أين", example: "Where do you live?" },
    { word: "when", type: "question word", meaning: "used to ask about a time", ar: "متى", example: "When does the shop open?" },
    { word: "how much", type: "question word", meaning: "used to ask about price or amount", ar: "بكم", example: "How much is this bag?" },
    { word: "live", type: "verb", meaning: "to have your home in a place", ar: "يسكن", example: "I live near the park." },
    { word: "buy", type: "verb", meaning: "to get something by paying money for it", ar: "يشتري", example: "I buy fruit every week." },
    { word: "sell", type: "verb", meaning: "to give something to someone for money", ar: "يبيع", example: "They sell fresh bread here." },
    { word: "pay", type: "verb", meaning: "to give money for something", ar: "يدفع", example: "I pay with my card." },
    { word: "cheap", type: "adjective", meaning: "costing little money", ar: "رخيص", example: "This bag is very cheap." },
    { word: "expensive", type: "adjective", meaning: "costing a lot of money", ar: "غالي", example: "That car is too expensive." },
  ],
  A2: [
    { word: "customer", type: "noun", meaning: "a person who buys from a shop or business", ar: "زبون", example: "The customer paid by card." },
    { word: "price", type: "noun", meaning: "how much money something costs", ar: "سعر", example: "The price was lower last week." },
    { word: "discount", type: "noun", meaning: "a lower price than usual", ar: "خصم", example: "They gave me a discount yesterday." },
    { word: "sale", type: "noun", meaning: "a time when shops sell things at lower prices", ar: "تخفيضات", example: "I bought these shoes in the sale." },
    { word: "change", type: "noun", meaning: "the money you get back after paying more than the cost", ar: "الباقي", example: "The assistant gave me the wrong change." },
    { word: "size", type: "noun", meaning: "how big or small something is", ar: "مقاس", example: "They didn't have my size." },
    { word: "fit", type: "verb", meaning: "to be the right size for your body", ar: "يناسب", example: "The jacket didn't fit me." },
    { word: "try on", type: "verb", meaning: "to put clothes on to see if they suit you", ar: "يقيس الملابس", example: "I tried on three jackets." },
    { word: "refund", type: "noun", meaning: "money given back when you return something to a shop", ar: "استرداد", example: "I asked for a full refund." },
    { word: "brand", type: "noun", meaning: "a company's name for its products", ar: "ماركة", example: "She bought a famous brand of perfume." },
    { word: "trolley", type: "noun", meaning: "a large wheeled basket you push in a supermarket", ar: "عربة تسوق", example: "I pushed a full trolley around the supermarket." },
    { word: "checkout", type: "noun", meaning: "the place in a shop where you pay", ar: "الكاشير", example: "The queue at the checkout was long." },
    { word: "queue", type: "noun", meaning: "a line of people waiting for something", ar: "طابور", example: "I waited in a long queue." },
    { word: "cash", type: "noun", meaning: "money in coins and notes", ar: "نقد", example: "I paid in cash, not by card." },
    { word: "bargain", type: "noun", meaning: "something bought for much less than usual", ar: "صفقة", example: "I got a real bargain in the January sales." },
    { word: "return", type: "verb", meaning: "to give something back to a shop", ar: "يعيد", example: "I returned the broken kettle to the shop." },
    { word: "luggage", type: "noun", meaning: "the bags and cases you take when travelling", ar: "أمتعة", example: "My luggage didn't arrive with my flight." },
    { word: "suitcase", type: "noun", meaning: "a case with a handle for clothes when you travel", ar: "حقيبة سفر", example: "My suitcase was too heavy." },
    { word: "passport", type: "noun", meaning: "an official document you need to travel abroad", ar: "جواز سفر", example: "He lost his passport in Rome." },
    { word: "visa", type: "noun", meaning: "an official mark in your passport that lets you enter a country", ar: "تأشيرة", example: "She applied for a visa online." },
    { word: "flight", type: "noun", meaning: "a journey by plane", ar: "رحلة جوية", example: "Our flight was delayed by two hours." },
    { word: "delay", type: "verb", meaning: "to make something happen later than planned", ar: "يؤخر", example: "The storm delayed all the trains." },
    { word: "journey", type: "noun", meaning: "the act of travelling from one place to another", ar: "رحلة", example: "The journey took five hours." },
    { word: "guidebook", type: "noun", meaning: "a book of advice and facts for visitors to a place", ar: "دليل سياحي", example: "We followed a guidebook around the city." },
    { word: "reserve", type: "verb", meaning: "to keep a table, room or seat for someone in advance", ar: "يحجز", example: "We reserved a table for Saturday." },
    { word: "abroad", type: "adverb", meaning: "in or to a foreign country", ar: "في الخارج", example: "She travelled abroad for the first time." },
    { word: "sightseeing", type: "noun", meaning: "visiting the famous places of a city", ar: "زيارة المعالم", example: "We went sightseeing all morning." },
    { word: "tour", type: "noun", meaning: "a short trip around a place to see it", ar: "جولة", example: "The tour lasted three hours." },
    { word: "border", type: "noun", meaning: "the line that separates two countries", ar: "حدود", example: "We crossed the border before midnight." },
    { word: "map", type: "noun", meaning: "a drawing that shows streets, towns and countries", ar: "خريطة", example: "I bought a paper map of Cairo." },
    { word: "hotel", type: "noun", meaning: "a building with rooms that guests pay to sleep in", ar: "فندق", example: "Our hotel was near the beach." },
    { word: "medicine", type: "noun", meaning: "a substance you take to treat an illness", ar: "دواء", example: "The doctor gave me strong medicine." },
    { word: "headache", type: "noun", meaning: "a pain inside your head", ar: "صداع", example: "I had a terrible headache yesterday." },
    { word: "fever", type: "noun", meaning: "a body temperature higher than normal", ar: "حمى", example: "The baby had a high fever." },
    { word: "cough", type: "noun", meaning: "a sudden loud push of air from the throat when you are ill", ar: "سعال", example: "A dry cough kept me awake." },
    { word: "pain", type: "noun", meaning: "the bad feeling you have when a part of your body hurts", ar: "ألم", example: "She felt a sharp pain in her back." },
    { word: "hurt", type: "verb", meaning: "to cause pain in a body part", ar: "يؤلم", example: "My knee hurt after the match." },
    { word: "healthy", type: "adjective", meaning: "strong and well, not ill", ar: "صحي", example: "We ate healthy food on holiday." },
    { word: "illness", type: "noun", meaning: "a sickness of the body or mind", ar: "مرض", example: "The illness spread quickly at school." },
    { word: "injured", type: "adjective", meaning: "with a wound or damage after an accident", ar: "مصاب", example: "Two players were injured in the game." },
    { word: "rest", type: "verb", meaning: "to relax by sitting or lying down", ar: "يرتاح", example: "The doctor told me to rest." },
    { word: "tablet", type: "noun", meaning: "a small round piece of medicine you swallow", ar: "حبة دواء", example: "I took a tablet after lunch." },
    { word: "pharmacy", type: "noun", meaning: "a shop that sells medicines and health products", ar: "صيدلية", example: "The pharmacy was closed on Sunday." },
    { word: "dentist", type: "noun", meaning: "a person who checks and treats your teeth", ar: "طبيب أسنان", example: "I visited the dentist twice last year." },
    { word: "ambulance", type: "noun", meaning: "a van that takes sick or injured people to hospital fast", ar: "سيارة إسعاف", example: "Someone called an ambulance immediately." },
    { word: "emergency", type: "noun", meaning: "a sudden dangerous situation that needs action fast", ar: "طوارئ", example: "In an emergency, we dialled 999." },
    { word: "well", type: "adjective", meaning: "healthy and not ill", ar: "بخير", example: "I didn't feel well yesterday." },
    { word: "sick", type: "adjective", meaning: "ill and not feeling healthy", ar: "مريض", example: "I stayed at home because I was sick." },
    { word: "nervous", type: "adjective", meaning: "worried and a little afraid before something important", ar: "متوتر", example: "I felt nervous before the interview." },
    { word: "excited", type: "adjective", meaning: "very happy and interested about something coming", ar: "متحمس", example: "The children were excited about the trip." },
    { word: "worried", type: "adjective", meaning: "unhappy and afraid because of a problem", ar: "قلق", example: "Mum was worried when I came home late." },
    { word: "lonely", type: "adjective", meaning: "sad because you are alone or lack company", ar: "وحيد", example: "He felt lonely in the new city." },
    { word: "proud", type: "adjective", meaning: "pleased about something you or someone close did", ar: "فخور", example: "They were proud of my results." },
    { word: "embarrassed", type: "adjective", meaning: "feeling silly or ashamed in front of people", ar: "محرج", example: "I was so embarrassed in class." },
    { word: "angry", type: "adjective", meaning: "feeling very annoyed because something bad happened", ar: "غاضب", example: "The coach was angry after the match." },
    { word: "calm", type: "adjective", meaning: "quiet and relaxed, not worried or angry", ar: "هادئ", example: "She stayed calm during the storm." },
    { word: "surprised", type: "adjective", meaning: "feeling that something unexpected happened", ar: "مندهش", example: "We were surprised by the news." },
    { word: "mood", type: "noun", meaning: "the way you feel at a particular time", ar: "مزاج", example: "He was in a good mood yesterday." },
    { word: "shy", type: "adjective", meaning: "nervous with people you do not know", ar: "خجول", example: "I was shy as a child." },
    { word: "relaxed", type: "adjective", meaning: "calm and without worry", ar: "مسترخي", example: "I felt relaxed after the holiday." },
    { word: "jealous", type: "adjective", meaning: "unhappy because someone has what you want", ar: "غيور", example: "He was jealous of his brother's success." },
    { word: "upset", type: "adjective", meaning: "sad or worried because something bad happened", ar: "منزعج", example: "She was upset about the lost keys." },
    { word: "brave", type: "adjective", meaning: "not afraid when things are difficult or dangerous", ar: "شجاع", example: "She was brave at the dentist's." },
    { word: "post", type: "verb", meaning: "to send a letter or parcel to someone", ar: "يرسل بالبريد", example: "I posted the letter this morning." },
    { word: "parcel", type: "noun", meaning: "a package wrapped for sending", ar: "طرد", example: "A parcel arrived for you yesterday." },
    { word: "delivery", type: "noun", meaning: "the act of bringing goods to someone's door", ar: "توصيل", example: "The delivery came an hour late." },
    { word: "plumber", type: "noun", meaning: "a person who repairs water pipes", ar: "سباك", example: "The plumber fixed the leaking pipe." },
    { word: "electrician", type: "noun", meaning: "a person who fits and repairs electrical wiring", ar: "كهربائي", example: "We called an electrician last week." },
    { word: "mechanic", type: "noun", meaning: "a person who repairs cars and machines", ar: "ميكانيكي", example: "The mechanic repaired our car quickly." },
    { word: "repair", type: "verb", meaning: "to fix something that is broken", ar: "يصلح", example: "They repaired the broken window." },
    { word: "lend", type: "verb", meaning: "to give something to someone for a short time", ar: "يعير", example: "He lent me his umbrella." },
    { word: "rent", type: "verb", meaning: "to pay to use a flat, house or car for a time", ar: "يستأجر", example: "We rented a small flat by the sea." },
    { word: "booking", type: "noun", meaning: "an arrangement that keeps a room, table or seat for you", ar: "حجز", example: "They confirmed our booking by email." },
    { word: "customer service", type: "noun", meaning: "the team that helps people who bought something", ar: "خدمة العملاء", example: "I phoned customer service twice." },
    { word: "complaint", type: "noun", meaning: "a statement that you are not happy about something", ar: "شكوى", example: "The hotel received a formal complaint." },
    { word: "bill", type: "noun", meaning: "a paper that shows how much to pay in a restaurant", ar: "فاتورة", example: "The waiter brought the bill quickly." },
    { word: "fee", type: "noun", meaning: "money you pay for a service", ar: "رسوم", example: "The bank charged me a fee." },
    { word: "signature", type: "noun", meaning: "your name written in your own special way", ar: "توقيع", example: "The form needed my signature." },
    { word: "form", type: "noun", meaning: "a paper with empty spaces where you write your details", ar: "استمارة", example: "I filled in the form carefully." },
    { word: "childhood", type: "noun", meaning: "the time when you were a child", ar: "الطفولة", example: "I spent my childhood in Alexandria." },
    { word: "used to", type: "phrase", meaning: "a phrase for past habits that have now stopped", ar: "كان معتاداً على", example: "We used to play outside every day." },
    { word: "collect", type: "verb", meaning: "to gather similar things over time because you enjoy them", ar: "يجمع", example: "I collected stamps as a child." },
    { word: "guitar", type: "noun", meaning: "a musical instrument with six strings", ar: "جيتار", example: "I played the guitar at school." },
    { word: "chess", type: "noun", meaning: "a game for two players with pieces on a board", ar: "شطرنج", example: "We played chess every evening." },
    { word: "picnic", type: "noun", meaning: "a meal you eat outside, often sitting on the ground", ar: "نزهة", example: "We had a picnic by the river." },
    { word: "trip", type: "noun", meaning: "a short journey to a place and back", ar: "رحلة قصيرة", example: "Our trip to Luxor was amazing." },
    { word: "memory", type: "noun", meaning: "something you remember from the past", ar: "ذكرى", example: "We made happy memories that summer." },
    { word: "swimming", type: "noun", meaning: "the activity of moving through water", ar: "سباحة", example: "I went swimming every weekend last summer." },
  ],
};
