"use client";
import { useEffect,useMemo,useState } from "react";
interface LearnerState{currentLessonId:string|null;completedLessonIds:string[];nextAction:{type:string;id:string;reason?:string;priority?:string}|null}
interface Lesson{id:string;title:string;mission:string;objectiveId:string;level:string;skill:string}
interface AdaptiveLesson{title?:string;objective?:string;explanation?:string;examples?:string[];guidedPractice?:Array<{prompt:string;answer:string}>;productionTask?:string;successCriteria?:string[];reviewTip?:string}
interface LoopState{phase:string;failedAttempts:number;successfulAttempts:number;transferPassed:boolean;assessedScore:number|null}
export default function LearnPage(){
 const[state,setState]=useState<LearnerState|null>(null);const[lesson,setLesson]=useState<Lesson|null>(null);const[loop,setLoop]=useState<LoopState|null>(null);const[busy,setBusy]=useState(false);const[aiBusy,setAiBusy]=useState(false);const[aiLesson,setAiLesson]=useState<AdaptiveLesson|null>(null);const[production,setProduction]=useState("");const[error,setError]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;Promise.all([fetch("/api/learner-state",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error??"Unable to load learner state.");return p.state as LearnerState}),fetch("/api/curriculum",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error??"Unable to load curriculum.");return p.lessons as Lesson[]}),fetch("/api/learning-loop",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error??"Unable to load learning loop.");return p.loop as LoopState})]).then(([nextState,lessons,nextLoop])=>{if(cancelled)return;setState(nextState);setLesson(lessons.find(i=>i.id===nextState.currentLessonId)??null);setLoop(nextLoop)}).catch((reason:unknown)=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Unable to load the lesson.")});return()=>{cancelled=true}},[]);
 const productionTask=aiLesson?.productionTask??lesson?.mission??"Complete the lesson mission in your own words.";
 const performanceScore=useMemo(()=>{const words=production.trim().split(/\s+/).filter(Boolean).length;const sentences=production.split(/[.!?]+/).filter(Boolean).length;return Math.min(100,Math.round(Math.min(words/25,1)*70+Math.min(sentences/3,1)*30));},[production]);
 async function completeCurrentLesson(){if(!lesson)return;const answer=production.trim();if(answer.length<20){setError("Complete the production task in at least 20 characters before finishing the lesson.");return}setBusy(true);setError(null);try{const evidenceId=`production-${lesson.id}-${crypto.randomUUID()}`;const practice=await fetch("/api/practice/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({skill:lesson.skill,objectiveId:lesson.objectiveId,correct:performanceScore>=70,lessonId:lesson.id,evidenceId,prompt:productionTask,answer})});const practicePayload=await practice.json();if(!practice.ok)throw new Error(practicePayload.error??"Unable to save your practice evidence.");const loopResponse=await fetch("/api/learning-loop",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phase:"PRODUCE",evidenceId,passed:performanceScore>=70,score:performanceScore})});const loopPayload=await loopResponse.json();if(!loopResponse.ok)throw new Error(loopPayload.error??"Unable to update the learning loop.");setLoop(loopPayload.loop);const response=await fetch("/api/lesson/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({lessonId:lesson.id,evidenceIds:[evidenceId],performanceScore})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to complete the lesson.");setState(payload.state);setProduction("");setAiLesson(null);const curriculum=await fetch("/api/curriculum",{cache:"no-store"}).then(r=>r.json());setLesson(curriculum.lessons.find((item:Lesson)=>item.id===payload.state.currentLessonId)??null)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to complete the lesson.")}finally{setBusy(false)}}
 async function generateAdaptiveLesson(){if(!lesson)return;setAiBusy(true);setError(null);try{const response=await fetch("/api/ai/lesson",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal:lesson.mission,skill:lesson.skill,lessonId:lesson.id})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Unable to generate adaptive lesson.");setAiLesson(payload.lesson)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to generate adaptive lesson.")}finally{setAiBusy(false)}}
 if(error&&!state)return <main style={{maxWidth:900,margin:"0 auto",padding:"56px 24px"}}><p role="alert">{error}</p></main>;if(!state)return <main style={{maxWidth:900,margin:"0 auto",padding:"56px 24px"}}><p>Loading your learner state…</p></main>;if(!lesson)return <main style={{maxWidth:900,margin:"0 auto",padding:"56px 24px"}}><h1>Learning path complete</h1><p>There is no unfinished lesson in the current curriculum.</p><a href="/dashboard">Back to dashboard</a></main>;
 return <main style={{maxWidth:900,margin:"0 auto",padding:"56px 24px"}}><p style={{fontWeight:700,textTransform:"uppercase",letterSpacing:".08em"}}>Today</p><h1>{lesson.title}</h1><p style={{fontSize:20,lineHeight:1.6}}>{lesson.mission}</p><section style={{marginTop:32,padding:24,background:"white",borderRadius:18,border:"1px solid #e4e8f0"}}><h2>Lesson objective</h2><p><strong>Objective:</strong> {lesson.objectiveId}</p><p><strong>Level:</strong> {lesson.level}</p><p><strong>Skill:</strong> {lesson.skill}</p><p><strong>Learning loop:</strong> {loop?.phase??"TEACH"}</p><p><strong>Completed:</strong> {state.completedLessonIds.length} lesson(s)</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:18}}><button disabled={busy} onClick={completeCurrentLesson} style={{padding:"13px 18px",border:0,borderRadius:10,background:"#6840d6",color:"white",fontWeight:800,cursor:busy?"wait":"pointer"}}>{busy?"Saving your real evidence…":"Submit production & complete →"}</button><button disabled={aiBusy} onClick={generateAdaptiveLesson} style={{padding:"13px 18px",border:"1px solid #dfe3ec",borderRadius:10,background:"white",fontWeight:800,cursor:aiBusy?"wait":"pointer"}}>{aiBusy?"Building your custom lesson…":"Teach me this with AI →"}</button></div><label style={{display:"grid",gap:8,marginTop:18}}><span><strong>Your production</strong> — {productionTask}</span><textarea aria-label="Your production response" value={production} onChange={e=>setProduction(e.target.value.slice(0,5000))} rows={7} placeholder="Write or say your answer here. Your response becomes learning evidence."/><small>Evidence strength: {performanceScore}%</small></label>{error&&<p role="alert" style={{marginTop:14,color:"#a53b3b"}}>{error}</p>}</section>{aiLesson&&<section style={{marginTop:20,padding:24,background:"#fbfaff",borderRadius:18,border:"1px solid #e7defc"}}><p style={{fontWeight:700,textTransform:"uppercase",letterSpacing:".08em"}}>Adaptive AI Teacher</p><h2>{aiLesson.title}</h2><p>{aiLesson.objective}</p><h3>Explanation</h3><p>{aiLesson.explanation}</p>{aiLesson.examples?.length&&<><h3>Examples</h3><ul>{aiLesson.examples.map((x,i)=><li key={i}>{x}</li>)}</ul></>}{aiLesson.guidedPractice?.length&&<><h3>Guided practice</h3>{aiLesson.guidedPractice.map((x,i)=><div key={i} style={{padding:12,background:"white",borderRadius:10,marginTop:8}}><strong>{i+1}.</strong> {x.prompt}<p style={{marginBottom:0}}><strong>Model answer:</strong> {x.answer}</p></div>)}</>}{aiLesson.productionTask&&<><h3>Production</h3><p>{aiLesson.productionTask}</p></>}{aiLesson.reviewTip&&<p><strong>Review tip:</strong> {aiLesson.reviewTip}</p>}</section>}<a href="/dashboard" style={{display:"inline-block",marginTop:24}}>Back to dashboard</a></main>;
}
